/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0021
 * Generated: 3/6/2026 7:25:18 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	SetVar 0x400A 250
	PlayCry 0x400A 0
	Message 4
	WaitCry
	CloseMessage
	CheckVersion 0x800C
	CompareVarValue 0x800C 7
	JumpIf DIFFERENT Function#1
	SetVar 0x8004 45
Jump Function#2

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckFlag 264
	JumpIf EQUAL Function#3
	Message 1
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 3:
	CheckFlag 164
	JumpIf EQUAL Function#4
End

Script 4:
	SetVar 0x4003 111
	SetFlag 261
End

Script 5:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckFlag 264
	JumpIf EQUAL Function#5
	Message 1
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 6:
	CompareVarValue 0x400B 123
	JumpIf DIFFERENT Function#6
	StopFanfare SEQ_SE_GS_KYOUHUU
	SetVar 0x400B 0
	CheckFlag 264
	JumpIf EQUAL Function#7
	CheckFlag 266
	JumpIf LESS Function#7
	CompareVarValue 0x4003 111
	JumpIf DIFFERENT Function#8
	SetOWPosition Overworld.0 16 1 18 Up
	SetOWPosition Overworld.1 12 1 18 Up
	SetOWPosition Overworld.2 12 1 12 Down
	SetOWPosition Overworld.3 18 1 18 Up
	SetOWPosition Overworld.4 18 1 12 Down
	SetVar 0x4003 0
End

Script 7:
	MecScript
	LockAll
	CMD_805
	Movement Overworld.0 Action#1
	WaitMovement
	Message 0
	CloseMessage
	StopFanfare SEQ_SE_GS_KYOUHUU
	FadeScreen 4 4 0 0x7FFF
	WaitFadeScreen
	CMD_755
	CMD_757
	PlayFanfare SEQ_SE_GS_SUZUSYUTUGEN_HO
	FadeScreen 4 4 1 0x7FFF
	WaitFadeScreen
	WaitFanfare SEQ_SE_GS_SUZUSYUTUGEN_HO
	Movement Overworld.0 Action#2
	Movement Overworld.1 Action#3
	Movement Overworld.2 Action#4
	Movement Overworld.3 Action#5
	Movement Overworld.4 Action#6
	WaitMovement
	WaitTime 16 0x800C
	Movement Overworld.0 Action#1
	Movement Overworld.1 Action#1
	Movement Overworld.2 Action#1
	Movement Overworld.3 Action#1
	Movement Overworld.4 Action#1
	WaitMovement
	WaitTime 16 0x800C
	StopMusic 0
	TempMusic SEQ_GS_E_MAIKO_MAI
	WaitTime 18 0x800C
	Movement Overworld.0 Action#7
	Movement Overworld.1 Action#7
	Movement Overworld.2 Action#7
	Movement Overworld.3 Action#7
	Movement Overworld.4 Action#7
	WaitTime 12 0x800C
	CMD_758 1
	PlayFanfare SEQ_SE_GS_SUZUNOONPA_RU
	WaitMovement
	WaitTime 67 0x800C
	Movement Overworld.0 Action#7
	Movement Overworld.1 Action#7
	Movement Overworld.2 Action#7
	Movement Overworld.3 Action#7
	Movement Overworld.4 Action#7
	WaitTime 12 0x800C
	CMD_758 1
	PlayFanfare SEQ_SE_GS_SUZUNOONPA_RU
	WaitMovement
	FadeScreen 4 6 1 0x7FFF
	CMD_765
	WaitFadeScreen
	WaitTime 4 0x800C
	Movement Overworld.0 Action#8
	Movement Overworld.1 Action#9
	Movement Overworld.2 Action#10
	Movement Overworld.3 Action#8
	Movement Overworld.4 Action#11
	WaitMovement
	Movement Overworld.0 Action#12
	Movement Overworld.1 Action#13
	Movement Overworld.2 Action#14
	Movement Overworld.3 Action#12
	Movement Overworld.4 Action#15
	WaitTime 12 0x800C
	CMD_758 1
	PlayFanfare SEQ_SE_GS_SUZUNOONPA_RU
	WaitMovement
	WaitTime 32 0x800C
	Movement Overworld.0 Action#9
	Movement Overworld.1 Action#9
	Movement Overworld.2 Action#10
	Movement Overworld.3 Action#8
	Movement Overworld.4 Action#11
	WaitMovement
	Movement Overworld.0 Action#13
	Movement Overworld.1 Action#13
	Movement Overworld.2 Action#14
	Movement Overworld.3 Action#12
	Movement Overworld.4 Action#15
	WaitTime 12 0x800C
	CMD_758 1
	PlayFanfare SEQ_SE_GS_SUZUNOONPA_RU
	WaitMovement
	WaitTime 33 0x800C
	Movement Overworld.0 Action#9
	Movement Overworld.1 Action#9
	Movement Overworld.2 Action#10
	Movement Overworld.3 Action#8
	Movement Overworld.4 Action#11
	WaitMovement
	Movement Overworld.0 Action#13
	Movement Overworld.1 Action#16
	Movement Overworld.2 Action#17
	Movement Overworld.3 Action#18
	Movement Overworld.4 Action#19
	WaitTime 12 0x800C
	CMD_758 1
	PlayFanfare SEQ_SE_GS_SUZUNOONPA_RU
	WaitMovement
	WaitTime 32 0x800C
	Movement Overworld.0 Action#10
	Movement Overworld.1 Action#10
	Movement Overworld.2 Action#11
	Movement Overworld.3 Action#9
	Movement Overworld.4 Action#8
	WaitMovement
	Movement Overworld.0 Action#14
	Movement Overworld.1 Action#14
	Movement Overworld.2 Action#15
	Movement Overworld.3 Action#13
	Movement Overworld.4 Action#12
	WaitTime 12 0x800C
	CMD_758 1
	PlayFanfare SEQ_SE_GS_SUZUNOONPA_RU
	WaitMovement
	CMD_766
	CMD_762 0
	WaitTime 32 0x800C
	Movement Overworld.0 Action#10
	Movement Overworld.1 Action#10
	Movement Overworld.2 Action#11
	Movement Overworld.3 Action#9
	Movement Overworld.4 Action#8
	WaitMovement
	Movement Overworld.0 Action#14
	Movement Overworld.1 Action#14
	Movement Overworld.2 Action#15
	Movement Overworld.3 Action#13
	Movement Overworld.4 Action#12
	WaitTime 12 0x800C
	CMD_758 0
	PlayFanfare SEQ_SE_GS_SUZUNOONPA2
	WaitMovement
	WaitTime 32 0x800C
	Movement Overworld.0 Action#11
	Movement Overworld.1 Action#10
	Movement Overworld.2 Action#11
	Movement Overworld.3 Action#9
	Movement Overworld.4 Action#8
	WaitMovement
	Movement Overworld.0 Action#15
	Movement Overworld.1 Action#14
	Movement Overworld.2 Action#15
	Movement Overworld.3 Action#13
	Movement Overworld.4 Action#12
	WaitTime 12 0x800C
	CMD_758 0
	PlayFanfare SEQ_SE_GS_SUZUNOONPA2
	WaitMovement
	WaitTime 41 0x800C
	CMD_763
	WaitTime 8 0x800C
	FadeScreen 6 1 0 0
	WaitFadeScreen
	CMD_761 1
	FadeScreen 6 1 1 0
	WaitFadeScreen
	WaitTime 20 0x800C
	CMD_758 0
	PlayFanfare SEQ_SE_GS_SUZUNOONPA2
	Release Overworld.0
	Release Overworld.1
	Release Overworld.2
	Release Overworld.3
	Release Overworld.4
	SetOWPosition Overworld.0 15 1 18 Up
	SetOWPosition Overworld.1 12 1 18 Up
	SetOWPosition Overworld.2 12 1 12 Down
	SetOWPosition Overworld.3 18 1 18 Up
	SetOWPosition Overworld.4 18 1 12 Down
	WaitTime 86 0x800C
	CMD_758 0
	PlayFanfare SEQ_SE_GS_SUZUNOONPA2
	WaitTime 32 0x800C
	FadeScreen 6 1 0 0
	WaitFadeScreen
	CMD_761 2
	FadeScreen 6 1 1 0
	WaitFadeScreen
	WaitTime 22 0x800C
	Movement Overworld.0 Action#13
	Movement Overworld.1 Action#13
	Movement Overworld.2 Action#15
	Movement Overworld.3 Action#13
	Movement Overworld.4 Action#15
	WaitTime 12 0x800C
	CMD_758 0
	PlayFanfare SEQ_SE_GS_SUZUNOONPA2
	WaitMovement
	WaitTime 32 0x800C
	WaitTime 34 0x800C
	Movement Overworld.0 Action#13
	Movement Overworld.1 Action#13
	Movement Overworld.2 Action#15
	Movement Overworld.3 Action#13
	Movement Overworld.4 Action#15
	WaitTime 12 0x800C
	CMD_758 0
	PlayFanfare SEQ_SE_GS_SUZUNOONPA2
	WaitMovement
	WaitTime 60 0x800C
	CMD_762 1
	CMD_763
	StopMusic 0
	CMD_756
	SetVar 0x400B 123
	FadeScreen 6 1 0 0x7FFF
	WaitFadeScreen
	RenderCutscene 0
	ClearFlag 578
	AddOW Overworld.5
	VanishOverworld Overworld.5
	WaitTime 6 0x800C
	FadeScreen 6 1 1 0x7FFF
	WaitFadeScreen
	WaitTime 20 0x800C
	CMD_764
	StopMusic 30
	Movement Overworld.0 Action#20
	WaitMovement
	CMD_726
	TextPlayerName 0
	Message 2
	CloseMessage
	Movement Overworld.0 Action#1
	WaitMovement
	TextPlayerName 0
	Message 3
	CloseMessage
	Movement Overworld.0 Action#21
	WaitMovement
	ReleaseAll
	SetFlag 266
	SetVar 0x40FA 2
End

//===== FUNCTIONS =====//
Function 1:
	SetVar 0x8004 70
	SetFlag 164
	WildBattleSp 0x400A 0x8004 0
	ClearFlag 164
	GetBattleOutcome 0x4005
	CompareVarValue 0x4005 2
	JumpIf EQUAL Function#9
	CompareVarValue 0x4005 3
	JumpIf EQUAL Function#9
	CompareVarValue 0x4005 4
	CallIf EQUAL Function#10
	ReleaseAll
	SetFlag 264
	SetVar 0x4081 3
	SetFlag 418
	SetFlag 417
	SetFlag 744
	ClearFlag 741
	SetFlag 580
	ClearFlag 572
	ClearFlag 577
End

Function 2:
	SetFlag 164
	WildBattleSp 0x400A 0x8004 0
	ClearFlag 164
	GetBattleOutcome 0x4005
	CompareVarValue 0x4005 2
	JumpIf EQUAL Function#9
	CompareVarValue 0x4005 3
	JumpIf EQUAL Function#9
	CompareVarValue 0x4005 4
	CallIf EQUAL Function#10
	ReleaseAll
	SetFlag 264
	SetVar 0x4081 3
	SetFlag 418
	SetFlag 417
	SetFlag 744
	ClearFlag 741
	SetFlag 580
	ClearFlag 572
	ClearFlag 577
End

Function 3:
	CompareVarValue 0x4005 5
	JumpIf DIFFERENT Function#11
	Message 8
Jump Function#12

Function 4:
	SetFlag 578
	RemoveOW Overworld.5
	ClearFlag 164
End

Function 5:
	Message 5
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 6:
	CheckFlag 264
	JumpIf EQUAL Function#7
	CheckFlag 266
	JumpIf LESS Function#7
	CompareVarValue 0x4003 111
	JumpIf DIFFERENT Function#8
	SetOWPosition Overworld.0 16 1 18 Up
	SetOWPosition Overworld.1 12 1 18 Up
	SetOWPosition Overworld.2 12 1 12 Down
	SetOWPosition Overworld.3 18 1 18 Up
	SetOWPosition Overworld.4 18 1 12 Down
	SetVar 0x4003 0
End

Function 7:
End

Function 8:
	SetVar 0x4003 0
End

Function 9:
	ClearFlag 578
	LostBattle
	ReleaseAll
End

Function 10:
	SetFlag 278
Return

Function 11:
	CompareVarValue 0x4005 6
	JumpIf DIFFERENT Function#13
	Message 8
Jump Function#12

Function 12:
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 13:
	CompareVarValue 0x4005 4
	JumpIf DIFFERENT Function#14
	Message 6
Jump Function#12

Function 14:
	Message 7
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== ACTIONS =====//
Action 1:
	WalkOnSpotSouth8 0x1
End

Action 2:
	Delay8 0x6
	WalkNorth8 0x1
End

Action 3:
	Delay8 0x5
	WalkWest8 0x2
End

Action 4:
	WalkWest8 0x1
	WalkNorth8 0x6
End

Action 5:
	Delay8 0x5
	WalkEast8 0x2
End

Action 6:
	WalkEast8 0x1
	WalkNorth8 0x6
End

Action 7:
	FaceWest 0x1
	Delay2 0x1
	FaceNorth 0x1
	Delay2 0x1
	FaceEast 0x1
	Delay2 0x1
	FaceSouth 0x1
	Delay2 0x1
End

Action 8:
	WalkWest16 0x2
End

Action 9:
	WalkNorth16 0x2
End

Action 10:
	WalkEast16 0x2
End

Action 11:
	WalkSouth16 0x2
End

Action 12:
	FaceNorth 0x1
	Delay2 0x1
	FaceEast 0x1
	Delay2 0x1
	FaceSouth 0x1
	Delay2 0x1
	FaceWest 0x1
	Delay2 0x1
End

Action 13:
	FaceEast 0x1
	Delay2 0x1
	FaceSouth 0x1
	Delay2 0x1
	FaceWest 0x1
	Delay2 0x1
	FaceNorth 0x1
	Delay2 0x1
End

Action 14:
	FaceSouth 0x1
	Delay2 0x1
	FaceWest 0x1
	Delay2 0x1
	FaceNorth 0x1
	Delay2 0x1
	FaceEast 0x1
	Delay2 0x1
End

Action 15:
	FaceWest 0x1
	Delay2 0x1
	FaceNorth 0x1
	Delay2 0x1
	FaceEast 0x1
	Delay2 0x1
	FaceSouth 0x1
	Delay2 0x1
End

Action 16:
	FaceEast 0x1
	Delay2 0x1
	FaceSouth 0x1
	Delay2 0x1
	FaceWest 0x1
	Delay2 0x1
	FaceNorth 0x1
	Delay2 0x1
	FaceEast 0x1
	Delay2 0x1
End

Action 17:
	FaceSouth 0x1
	Delay2 0x1
	FaceWest 0x1
	Delay2 0x1
	FaceNorth 0x1
	Delay2 0x1
	FaceEast 0x1
	Delay2 0x1
	FaceSouth 0x1
	Delay2 0x1
End

Action 18:
	FaceNorth 0x1
	Delay2 0x1
	FaceEast 0x1
	Delay2 0x1
	FaceSouth 0x1
	Delay2 0x1
	FaceWest 0x1
	Delay2 0x1
	FaceNorth 0x1
	Delay2 0x1
End

Action 19:
	FaceWest 0x1
	Delay2 0x1
	FaceNorth 0x1
	Delay2 0x1
	FaceEast 0x1
	Delay2 0x1
	FaceSouth 0x1
	Delay2 0x1
	FaceWest 0x1
	Delay2 0x1
End

Action 20:
	WalkOnSpotNorth8 0x1
End

Action 21:
	FaceWest 0x1
	LockDir 0x1
	WalkEast16 0x1
	ReleaseDir 0x1
End

