/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0030
 * Generated: 3/6/2026 7:25:18 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 6
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 7
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 3:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 8
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 4:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	PlayCry SPECIES_JIGGLYPUFF 0
	Message 3
	WaitCry
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 5:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CompareVarValue 0x4077 4
	JumpIf DIFFERENT Function#1
	Message 2
Jump Function#2

Script 6:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 0
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 7:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CompareVarValue 0x4077 5
	JumpIf DIFFERENT Function#3
	Message 5
Jump Function#4

Script 8:
	SetFlag 439
	SetFlag 440
	CompareVarValue 0x4077 4
	JumpIf DIFFERENT Function#5
	ClearFlag 439
Jump Function#6

Script 9:
	CompareVarValue 0x4077 5
	JumpIf DIFFERENT Function#7
	SetOWPosition Overworld.3 2 1 7 Right
End

Script 10:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CompareVarValue 0x4077 4
	JumpIf DIFFERENT Function#8
	Message 9
Jump Function#9

Script 11:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CompareVarValue 0x4077 4
	JumpIf EQUAL Function#10
	CheckItem ITEM_BLUE_CARD 1 0x800C
	CompareVarValue 0x800C 1
	JumpIf GREATER/EQUAL Function#11
	Message 33
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== FUNCTIONS =====//
Function 1:
	Message 1
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 2:
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 3:
	Message 4
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 4:
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 5:
	CompareVarValue 0x4077 2
	JumpIf GREATER/EQUAL Function#12
	ClearFlag 440
Jump Function#6

Function 6:
End

Function 7:
End

Function 8:
Jump Function#13

Function 9:
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 10:
	Message 39
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 11:
	TextNumber 0 0x413A
	Message 34
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 12:
	ClearFlag 440
End

Function 13:
	CheckItem ITEM_BLUE_CARD 1 0x800C
	CompareVarValue 0x800C 1
	JumpIf GREATER/EQUAL Function#14
	Message 10
	CloseMessage
	SetVar 0x8004 472
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#15
	CommonScript 2033
	CloseMessage
	IncrementVar 0x4115 1
	ReleaseAll
End

Function 14:
	CompareVarValue 0x4115 2
	JumpIf LESS Function#16
	TextPlayerName 0
	GenderMessage 12 13
Jump Function#17

Function 15:
	CommonScript 2009
	CloseMessage
Jump Function#18

Function 16:
	Message 11
	CloseMessage
	CheckFlag 2742
	JumpIf EQUAL Function#19
	Message 28
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 17:
	CloseMessage
	CheckFlag 2742
	JumpIf EQUAL Function#19
	Message 28
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 18:
	CompareVarValue 0x413A 30
	JumpIf LESS Function#20
	Message 36
	CloseMessage
	PlaySound SEQ_ME_KEYITEM
	Message 37
	WaitSound
	CloseMessage
	CompareVarValue 0x4115 255
	JumpIf GREATER/EQUAL Function#21
	IncrementVar 0x4115 1
	SetVar 0x413A 0
	Message 38
	CloseMessage
	Movement Overworld.8 Action#1
	WaitMovement
	ReleaseAll
End

Function 19:
	CheckFlag 2723
	JumpIf EQUAL Function#22
	Message 14
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#23
	TextPlayerName 0
	CompareVarValue 0x4115 2
	JumpIf LESS Function#24
	GenderMessage 17 18
Jump Function#25

Function 20:
	Message 38
	CloseMessage
	Movement Overworld.8 Action#1
	WaitMovement
	ReleaseAll
End

Function 21:
	SetVar 0x413A 0
	Message 38
	CloseMessage
	Movement Overworld.8 Action#1
	WaitMovement
	ReleaseAll
End

Function 22:
	Message 29
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 23:
	Message 19
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 24:
	GenderMessage 15 16
	CloseMessage
	Movement Overworld.9 Action#2
	WaitMovement
	GenderMessage 20 21
	CloseMessage
	GetPlayerDirection 0x4000
	CheckPokemonAlive 0x4002
	CompareVarValue 0x4002 0
	JumpIf EQUAL Function#26
	Release Following
	CompareVarValue 0x4000 2
	JumpIf DIFFERENT Function#27
	Movement Player Action#3
	Movement Following Action#4
Jump Function#28

Function 25:
	CloseMessage
	Movement Overworld.9 Action#2
	WaitMovement
	GenderMessage 20 21
	CloseMessage
	GetPlayerDirection 0x4000
	CheckPokemonAlive 0x4002
	CompareVarValue 0x4002 0
	JumpIf EQUAL Function#26
	Release Following
	CompareVarValue 0x4000 2
	JumpIf DIFFERENT Function#27
	Movement Player Action#3
	Movement Following Action#4
Jump Function#28

Function 26:
	CompareVarValue 0x4000 2
	JumpIf DIFFERENT Function#29
	Movement Player Action#3
Jump Function#30

Function 27:
	Movement Player Action#5
	Movement Following Action#6
	WaitMovement
	Lock Following
Jump Function#31

Function 28:
	WaitMovement
	Lock Following
Jump Function#31

Function 29:
	Movement Player Action#5
	WaitMovement
	GetBuenasPassword 0x8000 0x8001
	OpenTouchScreen
	MultiTouchLocalText 1 1 0 0 0x800C
	CreateMultiTouchBox 0x8000 255 0
	IncrementVar 0x8000 1
	CreateMultiTouchBox 0x8000 255 1
	IncrementVar 0x8000 1
	CreateMultiTouchBox 0x8000 255 2
	CloseMultiTouch
	CloseTouchScreen
	SetFlag 258
	SetFlag 2723
	Movement Overworld.9 Action#7
	WaitMovement
	CompareVars 0x800C 0x8001
	JumpIf DIFFERENT Function#32
	Message 22
	Movement Overworld.9 Action#8
	WaitMovement
	Movement Player Action#9
	WaitMovement
	PlayFanfare SEQ_SE_GS_OKOZUKAI
	CompareVarValue 0x413A 30
	JumpIf GREATER/EQUAL Function#33
	IncrementVar 0x413A 1
	CompareVarValue 0x413A 30
	JumpIf LESS Function#34
	CompareVarValue 0x4115 2
	JumpIf GREATER/EQUAL Function#34
	Movement Overworld.9 Action#7
	WaitMovement
	GenderMessage 24 25
	CloseMessage
	RecordPokegearNumber 8
	Message 26
	PlaySound SEQ_ME_POKEGEAR_REGIST
	WaitSound
	CloseMessage
	Movement Overworld.9 Action#7
	WaitMovement
	Message 27
	CloseMessage
	CompareVarValue 0x413A 1
	JumpIf EQUAL Function#35
	CompareVarValue 0x413A 3
	JumpIf EQUAL Function#36
	CompareVarValue 0x413A 5
	JumpIf EQUAL Function#37
	CompareVarValue 0x413A 10
	JumpIf EQUAL Function#38
	CompareVarValue 0x413A 15
	JumpIf EQUAL Function#39
	CompareVarValue 0x413A 20
	JumpIf EQUAL Function#40
	CompareVarValue 0x413A 25
	JumpIf EQUAL Function#41
	CompareVarValue 0x413A 30
	JumpIf EQUAL Function#42
Jump Function#43

Function 30:
	WaitMovement
	GetBuenasPassword 0x8000 0x8001
	OpenTouchScreen
	MultiTouchLocalText 1 1 0 0 0x800C
	CreateMultiTouchBox 0x8000 255 0
	IncrementVar 0x8000 1
	CreateMultiTouchBox 0x8000 255 1
	IncrementVar 0x8000 1
	CreateMultiTouchBox 0x8000 255 2
	CloseMultiTouch
	CloseTouchScreen
	SetFlag 258
	SetFlag 2723
	Movement Overworld.9 Action#7
	WaitMovement
	CompareVars 0x800C 0x8001
	JumpIf DIFFERENT Function#32
	Message 22
	Movement Overworld.9 Action#8
	WaitMovement
	Movement Player Action#9
	WaitMovement
	PlayFanfare SEQ_SE_GS_OKOZUKAI
	CompareVarValue 0x413A 30
	JumpIf GREATER/EQUAL Function#33
	IncrementVar 0x413A 1
	CompareVarValue 0x413A 30
	JumpIf LESS Function#34
	CompareVarValue 0x4115 2
	JumpIf GREATER/EQUAL Function#34
	Movement Overworld.9 Action#7
	WaitMovement
	GenderMessage 24 25
	CloseMessage
	RecordPokegearNumber 8
	Message 26
	PlaySound SEQ_ME_POKEGEAR_REGIST
	WaitSound
	CloseMessage
	Movement Overworld.9 Action#7
	WaitMovement
	Message 27
	CloseMessage
	CompareVarValue 0x413A 1
	JumpIf EQUAL Function#35
	CompareVarValue 0x413A 3
	JumpIf EQUAL Function#36
	CompareVarValue 0x413A 5
	JumpIf EQUAL Function#37
	CompareVarValue 0x413A 10
	JumpIf EQUAL Function#38
	CompareVarValue 0x413A 15
	JumpIf EQUAL Function#39
	CompareVarValue 0x413A 20
	JumpIf EQUAL Function#40
	CompareVarValue 0x413A 25
	JumpIf EQUAL Function#41
	CompareVarValue 0x413A 30
	JumpIf EQUAL Function#42
Jump Function#43

Function 31:
	GetBuenasPassword 0x8000 0x8001
	OpenTouchScreen
	MultiTouchLocalText 1 1 0 0 0x800C
	CreateMultiTouchBox 0x8000 255 0
	IncrementVar 0x8000 1
	CreateMultiTouchBox 0x8000 255 1
	IncrementVar 0x8000 1
	CreateMultiTouchBox 0x8000 255 2
	CloseMultiTouch
	CloseTouchScreen
	SetFlag 258
	SetFlag 2723
	Movement Overworld.9 Action#7
	WaitMovement
	CompareVars 0x800C 0x8001
	JumpIf DIFFERENT Function#32
	Message 22
	Movement Overworld.9 Action#8
	WaitMovement
	Movement Player Action#9
	WaitMovement
	PlayFanfare SEQ_SE_GS_OKOZUKAI
	CompareVarValue 0x413A 30
	JumpIf GREATER/EQUAL Function#33
	IncrementVar 0x413A 1
	CompareVarValue 0x413A 30
	JumpIf LESS Function#34
	CompareVarValue 0x4115 2
	JumpIf GREATER/EQUAL Function#34
	Movement Overworld.9 Action#7
	WaitMovement
	GenderMessage 24 25
	CloseMessage
	RecordPokegearNumber 8
	Message 26
	PlaySound SEQ_ME_POKEGEAR_REGIST
	WaitSound
	CloseMessage
	Movement Overworld.9 Action#7
	WaitMovement
	Message 27
	CloseMessage
	CompareVarValue 0x413A 1
	JumpIf EQUAL Function#35
	CompareVarValue 0x413A 3
	JumpIf EQUAL Function#36
	CompareVarValue 0x413A 5
	JumpIf EQUAL Function#37
	CompareVarValue 0x413A 10
	JumpIf EQUAL Function#38
	CompareVarValue 0x413A 15
	JumpIf EQUAL Function#39
	CompareVarValue 0x413A 20
	JumpIf EQUAL Function#40
	CompareVarValue 0x413A 25
	JumpIf EQUAL Function#41
	CompareVarValue 0x413A 30
	JumpIf EQUAL Function#42
Jump Function#43

Function 32:
	Message 23
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 33:
	CompareVarValue 0x413A 30
	JumpIf LESS Function#34
	CompareVarValue 0x4115 2
	JumpIf GREATER/EQUAL Function#34
	Movement Overworld.9 Action#7
	WaitMovement
	GenderMessage 24 25
	CloseMessage
	RecordPokegearNumber 8
	Message 26
	PlaySound SEQ_ME_POKEGEAR_REGIST
	WaitSound
	CloseMessage
	Movement Overworld.9 Action#7
	WaitMovement
	Message 27
	CloseMessage
	CompareVarValue 0x413A 1
	JumpIf EQUAL Function#35
	CompareVarValue 0x413A 3
	JumpIf EQUAL Function#36
	CompareVarValue 0x413A 5
	JumpIf EQUAL Function#37
	CompareVarValue 0x413A 10
	JumpIf EQUAL Function#38
	CompareVarValue 0x413A 15
	JumpIf EQUAL Function#39
	CompareVarValue 0x413A 20
	JumpIf EQUAL Function#40
	CompareVarValue 0x413A 25
	JumpIf EQUAL Function#41
	CompareVarValue 0x413A 30
	JumpIf EQUAL Function#42
Jump Function#43

Function 34:
	CompareVarValue 0x413A 1
	JumpIf EQUAL Function#35
	CompareVarValue 0x413A 3
	JumpIf EQUAL Function#36
	CompareVarValue 0x413A 5
	JumpIf EQUAL Function#37
	CompareVarValue 0x413A 10
	JumpIf EQUAL Function#38
	CompareVarValue 0x413A 15
	JumpIf EQUAL Function#39
	CompareVarValue 0x413A 20
	JumpIf EQUAL Function#40
	CompareVarValue 0x413A 25
	JumpIf EQUAL Function#41
	CompareVarValue 0x413A 30
	JumpIf EQUAL Function#42
Jump Function#43

Function 35:
	SetVar 0x8004 4
	SetVar 0x8005 1
Jump Function#44

Function 36:
	SetVar 0x8004 23
	SetVar 0x8005 1
Jump Function#44

Function 37:
	SetVar 0x8004 46
	SetVar 0x8005 1
Jump Function#44

Function 38:
	SetVar 0x8004 47
	SetVar 0x8005 1
Jump Function#44

Function 39:
	SetVar 0x8004 48
	SetVar 0x8005 1
Jump Function#44

Function 40:
	SetVar 0x8004 92
	SetVar 0x8005 1
Jump Function#44

Function 41:
	SetVar 0x8004 50
	SetVar 0x8005 1
Jump Function#44

Function 42:
	SetVar 0x8004 45
	SetVar 0x8005 1
Jump Function#44

Function 43:
	Message 32
	CloseMessage
	Movement Overworld.9 Action#10
	WaitMovement
	ReleaseAll
End

Function 44:
	Message 32
	CloseMessage
	Movement Overworld.9 Action#10
	WaitMovement
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	Movement Overworld.8 Action#11
	Movement Player Action#12
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	TextNumber 0 0x413A
	TextItem 1 0x8004
	Message 35
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#15
	CommonScript 2033
	CompareVarValue 0x413A 30
	JumpIf LESS Function#20
	Message 36
	CloseMessage
	PlaySound SEQ_ME_KEYITEM
	Message 37
	WaitSound
	CloseMessage
	CompareVarValue 0x4115 255
	JumpIf GREATER/EQUAL Function#21
	IncrementVar 0x4115 1
	SetVar 0x413A 0
	Message 38
	CloseMessage
	Movement Overworld.8 Action#1
	WaitMovement
	ReleaseAll
End

//===== ACTIONS =====//
Action 1:
	WalkWest8 0x3
	WalkNorth8 0x2
	WalkOnSpotSouth8 0x1
End

Action 2:
	WalkOnSpotWest8 0x1
End

Action 3:
	FaceSouth 0x1
	WalkSouth8 0x2
	WalkWest8 0x1
	WalkOnSpotWest8 0x1
End

Action 4:
	WalkSouth8 0x2
	WalkWest8 0x1
	WalkOnSpotNorth8 0x1
End

Action 5:
	FaceSouth 0x1
	WalkSouth8 0x1
	WalkOnSpotWest8 0x1
End

Action 6:
	WalkSouth8 0x1
	WalkOnSpotNorth8 0x1
End

Action 7:
	WalkOnSpotSouth8 0x1
End

Action 8:
	WalkSouth8 0x1
End

Action 9:
	WalkOnSpotNorth8 0x1
End

Action 10:
	FaceNorth 0x1
	WalkNorth8 0x1
	WalkOnSpotWest8 0x1
End

Action 11:
	WalkSouth8 0x2
	WalkEast8 0x3
End

Action 12:
	WalkSouth8 0x1
	WalkWest8 0x2
End

