/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0045
 * Generated: 3/6/2026 7:25:18 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	FadeScreen 6 1 0 0
	WaitFadeScreen
	OpenAlphaPuzzle 3
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	CheckFlag 2426
	JumpIf EQUAL Function#1
	ReleaseAll
End

Script 2:
	MecScript
	LockAll
	OpenRuinsofAlphHiddenRoom 3
	CheckBornPokemonInParty 0x800C SPECIES_HO_OH
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#2
Jump Function#3

Script 3:
	MecScript
	LockAll
	CheckPokemonAlive 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#4
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#5
End

//===== FUNCTIONS =====//
Function 1:
	WaitTime 2 0x8004
	ShakeCamera 0 2 10 6
	WaitTime 10 0x8004
	Movement Player Action#1
	WaitMovement
	RemoveOW Overworld.1
	PlayFanfare SEQ_SE_DP_KI_GASYAN
	ClearFlag 273
	SetFlag 546
	ClearFlag 565
	CheckPokemonAlive 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#6
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#7
End

Function 2:
	ReleaseAll
End

Function 3:
	WaitTime 2 0x8004
	ShakeCamera 0 2 10 6
	WaitTime 10 0x8004
	Movement Player Action#1
	WaitMovement
	RemoveOW Overworld.0
	SetFlag 545
	PlayFanfare SEQ_SE_DP_UG_008
	ReleaseAll
End

Function 4:
	Movement Player Action#2
	WaitMovement
Jump Function#8

Function 5:
	Movement Player Action#2
	Movement Following Action#3
	WaitMovement
	SetVar 0x40CE 1
	PlayFanfare SEQ_SE_GS_RAKKA01
	CompareVarValue 0x403E 7
	JumpIf GREATER/EQUAL Function#9
	CompareVarValue 0x403E 6
	JumpIf EQUAL Function#10
	FadeScreen 6 1 0 0
	WaitFadeScreen
	Warp 315 0 5 24 Up
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Function 6:
	Movement Player Action#2
	WaitMovement
Jump Function#11

Function 7:
	Movement Player Action#2
	Movement Following Action#3
	WaitMovement
	SetVar 0x40CE 1
	CompareVarValue 0x40EC 1
	JumpIf GREATER/EQUAL Function#12
	PlayFanfare SEQ_SE_GS_RAKKA01
	FadeScreen 6 1 0 0
	WaitFadeScreen
	Warp 315 0 5 24 Up
	FadeScreen 6 1 1 0
	WaitFadeScreen
	SetVar 0x40E0 1
	IncrementVar 0x40EC 1
	ReleaseAll
End

Function 8:
	SetVar 0x40CE 1
	PlayFanfare SEQ_SE_GS_RAKKA01
	CompareVarValue 0x403E 7
	JumpIf GREATER/EQUAL Function#9
	CompareVarValue 0x403E 6
	JumpIf EQUAL Function#10
	FadeScreen 6 1 0 0
	WaitFadeScreen
	Warp 315 0 5 24 Up
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Function 9:
	FadeScreen 6 1 0 0
	WaitFadeScreen
	Warp 492 0 5 24 Up
	FadeScreen 6 1 1 0
	WaitFadeScreen
Jump Function#13

Function 10:
	FadeScreen 6 1 0 0
	WaitFadeScreen
	Warp 490 0 5 24 Up
	FadeScreen 6 1 1 0
	WaitFadeScreen
Jump Function#13

Function 11:
	SetVar 0x40CE 1
	CompareVarValue 0x40EC 1
	JumpIf GREATER/EQUAL Function#12
	PlayFanfare SEQ_SE_GS_RAKKA01
	FadeScreen 6 1 0 0
	WaitFadeScreen
	Warp 315 0 5 24 Up
	FadeScreen 6 1 1 0
	WaitFadeScreen
	SetVar 0x40E0 1
	IncrementVar 0x40EC 1
	ReleaseAll
End

Function 12:
	SetFlag 565
	PlayFanfare SEQ_SE_GS_RAKKA01
	FadeScreen 6 1 0 0
	WaitFadeScreen
	Warp 315 0 5 24 Up
	FadeScreen 6 1 1 0
	WaitFadeScreen
	SetVar 0x40E0 1
	IncrementVar 0x40EC 1
	ReleaseAll
End

Function 13:
	ReleaseAll
End

//===== ACTIONS =====//
Action 1:
	EmoteExclamation 0x1
End

Action 2:
	WalkOnSpotNorth2 0x4
	SetInvisible 0x1
End

Action 3:
	Delay4 0x3
	WalkNorth2 0x1
	SetInvisible 0x1
End

