/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0060
 * Generated: 3/6/2026 7:25:18 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 5
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 3
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#1
	CloseMessage
	ReleaseAll
End

Script 3:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 1
	CloseMessage
	TrainerBattle TRAINER_PROTON_486 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#2
	Message 2
	CloseMessage
	FadeScreen 6 1 0 0
	WaitFadeScreen
	RemoveOW Overworld.1
	RemoveOW Overworld.2
	RemoveOW Overworld.3
	RemoveOW Overworld.4
	SetFlag 425
	WaitTime 20 0x8004
	PlayFanfare SEQ_SE_DP_KAIDAN2
	WaitFanfare SEQ_SE_DP_KAIDAN2
	FadeScreen 6 1 1 0
	WaitFadeScreen
	SetOWPosition Overworld.7 36 0 7 Left
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	GetPlayerDirection 0x800C
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#3
	Movement Overworld.7 Action#1
	Movement Player Action#2
Jump Function#4

//===== FUNCTIONS =====//
Function 1:
	TextPlayerName 0
	Message 4
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 2:
	LostBattle
	ReleaseAll
End

Function 3:
	Movement Overworld.7 Action#1
	Movement Player Action#3
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	TextPlayerName 0
	Message 0
	CloseMessage
	ClearFlag 414
	ClearFlag 427
	SetFlag 123
	SetVar 0x4075 1
	SetVar 0x4080 2
	SetVar 0x4099 1
	SetVar 0x409B 1
	SetVar 0x409E 1
	PlayFanfare SEQ_SE_DP_KAIDAN2
	WaitFanfare SEQ_SE_DP_KAIDAN2
	FadeScreen 6 1 0 0
	WaitFadeScreen
	Warp 164 0 4 5 Up
	FadeScreen 6 1 1 0
	WaitFadeScreen
	SetFlag 426
	SetFlag 469
	SetFlag 428
	ClearFlag 429
	ClearFlag 423
	ClearFlag 424
	SetVar 0x40F4 1
	ReleaseAll
End

Function 4:
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	TextPlayerName 0
	Message 0
	CloseMessage
	ClearFlag 414
	ClearFlag 427
	SetFlag 123
	SetVar 0x4075 1
	SetVar 0x4080 2
	SetVar 0x4099 1
	SetVar 0x409B 1
	SetVar 0x409E 1
	PlayFanfare SEQ_SE_DP_KAIDAN2
	WaitFanfare SEQ_SE_DP_KAIDAN2
	FadeScreen 6 1 0 0
	WaitFadeScreen
	Warp 164 0 4 5 Up
	FadeScreen 6 1 1 0
	WaitFadeScreen
	SetFlag 426
	SetFlag 469
	SetFlag 428
	ClearFlag 429
	ClearFlag 423
	ClearFlag 424
	SetVar 0x40F4 1
	ReleaseAll
End

//===== ACTIONS =====//
Action 1:
	WalkWest8 0x2
	WalkSouth8 0x2
	WalkWest8 0x3
	WalkNorth8 0x2
	Delay4 0x4
	WalkWest8 0x1
	WalkNorth8 0x3
	FaceWest 0x1
End

Action 2:
	WalkEast8 0x2
	FaceNorth 0x1
	Delay8 0x6
	FaceSouth 0x1
	Delay8 0x5
	FaceEast 0x1
End

Action 3:
	WalkSouth8 0x1
	WalkEast8 0x1
	FaceNorth 0x1
	Delay8 0x6
	FaceSouth 0x1
	Delay8 0x5
	FaceEast 0x1
End

