/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0070
 * Generated: 3/6/2026 7:25:18 PM
 */

//===== SCRIPTS =====//
Script 1:
	CompareVarValue 0x414D 0
	CallIf DIFFERENT Function#1
	CMD_412 43 0 0x400A
	Call Function#2
	CompareVarValue 0x400A 2
	CallIf EQUAL Function#3
	CompareVarValue 0x400A 3
	CallIf EQUAL Function#3
	CompareVarValue 0x400A 0
	CallIf EQUAL Function#2
	CompareVarValue 0x400A 1
	CallIf EQUAL Function#2
	CompareVarValue 0x400A 4
	CallIf EQUAL Function#4
	CompareVarValue 0x400A 5
	CallIf EQUAL Function#4
	CompareVarValue 0x400A 6
	CallIf EQUAL Function#4
End

Script 2:
	MecScript
	LockAll
	SetVar 0x4000 0
	Call Function#5
Jump Function#6

Script 3:
	MecScript
	LockAll
	SetVar 0x4000 0
	Call Function#5
Jump Function#7

Script 4:
	MecScript
	LockAll
	SetVar 0x4000 1
	Call Function#5
Jump Function#8

//===== FUNCTIONS =====//
Function 1:
	CMD_520
Return

Function 2:
	SetVar 0x402A 282
Return

Function 3:
	SetVar 0x402A 283
Return

Function 4:
	SetVar 0x402A 286
Return

Function 5:
	Call Function#9
	ElevatorAnimation Up 3
	Call Function#10
Return

Function 6:
	FadeScreen 6 1 0 0
	WaitFadeScreen
	CMD_412 43 0 0x800C
	CompareVarValue 0x800C 4
	JumpIf EQUAL Function#11
	CompareVarValue 0x800C 5
	JumpIf EQUAL Function#11
	FinishOverworldScreen
	CMD_627 5
	ReturnScreen
	Warp 265 0 15 6 Up
End

Function 7:
	FadeScreen 6 1 0 0
	WaitFadeScreen
	FinishOverworldScreen
	CMD_627 6
	ReturnScreen
	Warp 265 0 11 6 Up
End

Function 8:
	FadeScreen 6 1 0 0
	WaitFadeScreen
	Warp 271 0 8 2 Down
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Function 9:
	Movement Player Action#1
	WaitMovement
Return

Function 10:
	Movement Overworld.0 Action#2
	Movement Player Action#3
	WaitMovement
Return

Function 11:
	FinishOverworldScreen
	CMD_627 5
	ReturnScreen
	Warp 265 0 19 6 Up
End

//===== ACTIONS =====//
Action 1:
	WalkNorth8 0x2
	FaceSouth 0x1
End

Action 2:
	WalkSouth8 0x1
	FaceWest 0x1
	WalkWest8 0x1
	FaceSouth 0x1
	WalkSouth8 0x1
	SetInvisible 0x1
End

Action 3:
	Delay8 0x2
	Delay2 0x1
	WalkSouth8 0x2
	SetInvisible 0x1
End

