/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0119
 * Generated: 3/6/2026 7:25:18 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CompareVarValue 0x4057 6
	JumpIf LESS Function#1
	Message 15
Jump Function#2

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CompareVarValue 0x4057 7
	JumpIf EQUAL Function#3
	CompareVarValue 0x4057 6
	JumpIf LESS Function#4
	SetVar 0x800C 500
	TextNumber 1 0x800C
	Message 1
Jump Function#5

Script 3:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CompareVarValue 0x4057 0
	JumpIf EQUAL Function#6
	CompareVarValue 0x4057 1
	JumpIf EQUAL Function#6
	CompareVarValue 0x4057 2
	JumpIf EQUAL Function#6
	CompareVarValue 0x4057 3
	JumpIf EQUAL Function#6
	Message 19
	OpenTouchScreen
	MultiTouchStandardText 1 1 0 1 0x800C
	CreateMultiTouchBox 457 255 0
	CreateMultiTouchBox 458 255 1
	CreateMultiTouchBox 459 255 2
	CreateMultiTouchBox 460 255 3
	CreateMultiTouchBox 461 255 4
	CreateMultiTouchBox 462 255 5
	CloseMultiTouch
	SetVarFromVariable 0x8008 0x800C
	CompareVarValue 0x8008 0
	JumpIf EQUAL Function#7
	CompareVarValue 0x8008 1
	JumpIf EQUAL Function#8
	CompareVarValue 0x8008 2
	JumpIf EQUAL Function#9
	CompareVarValue 0x8008 3
	JumpIf EQUAL Function#10
	CompareVarValue 0x8008 4
	JumpIf EQUAL Function#11
Jump Function#12

Script 4:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CompareVarValue 0x4057 7
	JumpIf EQUAL Function#13
	DummyNationalDexCheck
	NationalDex 2 0x4000
	CompareVarValue 0x4000 0
	JumpIf EQUAL Function#14
	CompareVarValue 0x4057 6
	JumpIf LESS Function#15
	Message 65
Jump Function#16

Script 5:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CompareVarValue 0x4057 7
	JumpIf EQUAL Function#17
	DummyNationalDexCheck
	NationalDex 2 0x4000
	CompareVarValue 0x4000 0
	JumpIf EQUAL Function#14
	CMD_824 0x4000
	CompareVarValue 0x4000 0
	JumpIf EQUAL Function#18
	SetVar 0x4000 0
	CMD_823 0x4000
	Message 54
Jump Function#19

Script 6:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CompareVarValue 0x4057 0
	JumpIf EQUAL Function#20
	CompareVarValue 0x4057 1
	JumpIf EQUAL Function#20
	CompareVarValue 0x4057 2
	JumpIf EQUAL Function#20
	CompareVarValue 0x4057 3
	JumpIf EQUAL Function#20
	TextPlayerName 0
	Message 27
	CloseMessage
	ClearFlag 2461
	FadeScreen 6 1 0 0
	WaitFadeScreen
	CMD_716
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	CheckFlag 2461
	JumpIf EQUAL Function#21
	ReleaseAll
End

Script 7:
	MecScript
	LockAll
	Movement Overworld.2 Action#1
	Movement Overworld.4 Action#1
	WaitMovement
	Message 7
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#22
	SetSafariFlag 1 0
	CloseTouchScreen
	CloseMessage
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#23
	Movement Player Action#2
	WaitMovement
	PlayFanfare SEQ_SE_DP_KAIDAN2
	FadeScreen 6 1 0 0
	WaitFadeScreen
	Warp 357 0 79 100 Up
	FadeScreen 6 1 1 0
	WaitFadeScreen
	Lock Following
	BallResetFollowingPoke
	Movement Following Action#3
	WaitMovement
	Release Following
	ReleaseAll
End

Script 8:
	MecScript
	LockAll
	Movement Player Action#4
	WaitMovement
	GetPlayerPosition 0x4000 0x4001
	CompareVarValue 0x4000 5
	JumpIf DIFFERENT Function#24
	SetVar 0x4002 5
	SetVar 0x4003 5
Jump Function#25

Script 9:
	MecScript
	LockAll
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	Movement Overworld.5 Action#5
	Movement Player Action#6
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	Message 29
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#26
	Message 30
	WaitButton
	CloseMessage
	SetVar 0x4057 2
	ReleaseAll
End

Script 10:
	MecScript
	LockAll
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	Movement Overworld.5 Action#5
	Movement Player Action#6
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	Message 34
	CloseMessage
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	Movement Overworld.5 Action#7
	Movement Player Action#8
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	Message 35
	CloseMessage
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	Movement Overworld.5 Action#9
	Movement Player Action#10
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	Message 36
	WaitButton
	CloseMessage
	SetVar 0x4057 5
	ClearFlag 793
	ReleaseAll
End

Script 11:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckFlag 387
	JumpIf EQUAL Function#27
	CompareVarValue 0x4057 2
	JumpIf EQUAL Function#28
	CompareVarValue 0x4057 3
	JumpIf EQUAL Function#29
	CompareVarValue 0x4057 5
	JumpIf EQUAL Function#30
	CompareVarValue 0x4057 6
	JumpIf EQUAL Function#31
	CompareVarValue 0x4057 7
	JumpIf EQUAL Function#32
	Message 42
Jump Function#33

Script 12:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	DummyNationalDexCheck
	NationalDex 2 0x4000
	CompareVarValue 0x4000 0
	JumpIf EQUAL Function#34
	CompareVarValue 0x4057 6
	JumpIf LESS Function#35
	Message 93
Jump Function#36

//===== FUNCTIONS =====//
Function 1:
	Message 14
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#37
	SetVar 0x8004 30
	TextNumber 1 0x8004
	SetVar 0x8005 1000
	TextNumber 2 0x8005
	Message 16
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 2:
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#37
	SetVar 0x8004 30
	TextNumber 1 0x8004
	SetVar 0x8005 1000
	TextNumber 2 0x8005
	Message 16
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 3:
	CheckFlag 387
	JumpIf EQUAL Function#38
	Message 18
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 4:
	SetVar 0x800C 500
	TextNumber 1 0x800C
	Message 0
	ShowMoney 20 2
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#39
	CountPCFreeSpace 0x800C
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#40
	GetPartyCount 0x8004
	CompareVarValue 0x8004 6
	JumpIf EQUAL Function#41
	CompareMoney 0x800C 500
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#42
	SetVar 0x800C 500
	TextNumber 1 0x800C
	Message 2
	PlayFanfare SEQ_SE_DP_REGI
	TakeMoney 500
	UpdateMoney
	Message 4
	TextPlayerName 0
	SetVar 0x800C 30
	TextNumber 1 0x800C
	Message 5
	PlaySound SEQ_ME_ITEM
	WaitSound
	Message 6
	CloseMessage
	HideMoney
	SendBackFollowingPoke
	Movement Player Action#11
	WaitMovement
	DoorAnimation 0 0 5 5 77
	Call Function#43
	Movement Player Action#12
	WaitMovement
	Call Function#44
	SetVar 0x40E3 1
	SetSafariFlag 0 0
	SetElevatorWarp 173 1 5 2 1
	PlayFanfare SEQ_SE_DP_KAIDAN2
	FadeScreen 6 1 0 0
	WaitFadeScreen
	Warp 357 0 79 100 Up
	FadeScreen 6 1 1 0
	WaitFadeScreen
	Lock Following
	BallResetFollowingPoke
	Movement Following Action#3
	WaitMovement
	Release Following
	ReleaseAll
End

Function 5:
	ShowMoney 20 2
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#39
	CountPCFreeSpace 0x800C
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#40
	GetPartyCount 0x8004
	CompareVarValue 0x8004 6
	JumpIf EQUAL Function#41
	CompareMoney 0x800C 500
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#42
	SetVar 0x800C 500
	TextNumber 1 0x800C
	Message 2
	PlayFanfare SEQ_SE_DP_REGI
	TakeMoney 500
	UpdateMoney
	Message 4
	TextPlayerName 0
	SetVar 0x800C 30
	TextNumber 1 0x800C
	Message 5
	PlaySound SEQ_ME_ITEM
	WaitSound
	Message 6
	CloseMessage
	HideMoney
	SendBackFollowingPoke
	Movement Player Action#11
	WaitMovement
	DoorAnimation 0 0 5 5 77
	Call Function#43
	Movement Player Action#12
	WaitMovement
	Call Function#44
	SetVar 0x40E3 1
	SetSafariFlag 0 0
	SetElevatorWarp 173 1 5 2 1
	PlayFanfare SEQ_SE_DP_KAIDAN2
	FadeScreen 6 1 0 0
	WaitFadeScreen
	Warp 357 0 79 100 Up
	FadeScreen 6 1 1 0
	WaitFadeScreen
	Lock Following
	BallResetFollowingPoke
	Movement Following Action#3
	WaitMovement
	Release Following
	ReleaseAll
End

Function 6:
	Message 25
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 7:
	Message 20
Jump Function#45

Function 8:
	Message 21
Jump Function#45

Function 9:
	Message 22
Jump Function#45

Function 10:
	Message 23
Jump Function#45

Function 11:
	Message 24
Jump Function#45

Function 12:
	CloseTouchScreen
	Message 26
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 13:
	CheckFlag 387
	JumpIf EQUAL Function#46
	Message 18
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 14:
	Message 84
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 15:
	Message 66
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseMessage
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#47
	CommonScript 2006
	SetVarFromVariable 0x800C 0x4000
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#48
Jump Function#49

Function 16:
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseMessage
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#47
	CommonScript 2006
	SetVarFromVariable 0x800C 0x4000
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#48
Jump Function#49

Function 17:
	CheckFlag 387
	JumpIf EQUAL Function#50
	Message 18
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 18:
	Message 60
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 19:
	ShowMoney 20 2
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#51
	CountPCFreeSpace 0x800C
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#52
	GetPartyCount 0x8004
	CompareVarValue 0x8004 6
	JumpIf EQUAL Function#53
	CompareMoney 0x800C 500
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#54
	SetVar 0x800C 500
	TextNumber 1 0x800C
	Message 55
	PlayFanfare SEQ_SE_DP_REGI
	TakeMoney 500
	UpdateMoney
	Message 57
	TextPlayerName 0
	SetVar 0x800C 30
	TextNumber 1 0x800C
	Message 58
	PlaySound SEQ_ME_ITEM
	WaitSound
	Message 59
	CloseMessage
	HideMoney
	SendBackFollowingPoke
	Movement Player Action#11
	WaitMovement
	DoorAnimation 0 0 19 5 77
	Call Function#43
	Movement Player Action#12
	WaitMovement
	Call Function#44
	SetVar 0x40E3 3
	SetSafariFlag 0 1
	SetElevatorWarp 173 2 19 2 1
	PlayFanfare SEQ_SE_DP_KAIDAN2
	FadeScreen 6 1 0 0
	WaitFadeScreen
	Warp 357 0 79 100 Up
	FadeScreen 6 1 1 0
	WaitFadeScreen
	Lock Following
	BallResetFollowingPoke
	Movement Following Action#3
	WaitMovement
	Release Following
	ReleaseAll
End

Function 20:
	Message 28
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 21:
	ShakeCamera 0 2 10 6
	PlayFanfare SEQ_SE_DP_KI_GASYAN
	Message 91
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 22:
	CloseTouchScreen
	CloseMessage
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#23
	Movement Player Action#2
	WaitMovement
	PlayFanfare SEQ_SE_DP_KAIDAN2
	FadeScreen 6 1 0 0
	WaitFadeScreen
	Warp 357 0 79 100 Up
	FadeScreen 6 1 1 0
	WaitFadeScreen
	Lock Following
	BallResetFollowingPoke
	Movement Following Action#3
	WaitMovement
	Release Following
	ReleaseAll
End

Function 23:
	GetPlayerPosition 0x4000 0x4001
	CompareVarValue 0x4000 5
	JumpIf DIFFERENT Function#55
	SetVar 0x4002 5
	SetVar 0x4003 5
Jump Function#56

Function 24:
	SetVar 0x4002 19
	SetVar 0x4003 5
	DoorAnimation 0 0 0x4002 0x4003 77
	Call Function#43
	Movement Player Action#13
	WaitMovement
	Call Function#44
	SetVar 0x40E3 0
	Message 9
	WaitButton
	CloseMessage
	BallResetFollowingPoke
	ReleaseAll
End

Function 25:
	DoorAnimation 0 0 0x4002 0x4003 77
	Call Function#43
	Movement Player Action#13
	WaitMovement
	Call Function#44
	SetVar 0x40E3 0
	Message 9
	WaitButton
	CloseMessage
	BallResetFollowingPoke
	ReleaseAll
End

Function 26:
	Message 31
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#26
Jump Function#57

Function 27:
	Message 45
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#58
	MultiTouchStandardText 1 1 0 1 0x800C
	CreateMultiTouchBox 463 255 0
	CreateMultiTouchBox 464 255 1
	CreateMultiTouchBox 465 255 2
	CreateMultiTouchBox 466 255 3
	CreateMultiTouchBox 467 255 4
	CreateMultiTouchBox 468 255 5
	CreateMultiTouchBox 469 255 6
	CloseMultiTouch
	SetVarFromVariable 0x8008 0x800C
	CompareVarValue 0x8008 0
	JumpIf EQUAL Function#59
	CompareVarValue 0x8008 1
	JumpIf EQUAL Function#60
	CompareVarValue 0x8008 2
	JumpIf EQUAL Function#61
	CompareVarValue 0x8008 3
	JumpIf EQUAL Function#62
	CompareVarValue 0x8008 4
	JumpIf EQUAL Function#63
	CompareVarValue 0x8008 5
	JumpIf EQUAL Function#64
Jump Function#58

Function 28:
	CMD_791 0 0x800C
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#65
	Message 33
Jump Function#66

Function 29:
	Message 42
Jump Function#33

Function 30:
	CMD_791 1 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#67
	Message 37
	CloseMessage
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	GetPlayerDirection 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#68
	Movement Overworld.5 Action#14
	Movement Player Action#15
	WaitMovement
Jump Function#69

Function 31:
	Message 40
Jump Function#33

Function 32:
	SetFlag 387
	Message 43
	Message 44
	Message 45
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#58
	MultiTouchStandardText 1 1 0 1 0x800C
	CreateMultiTouchBox 463 255 0
	CreateMultiTouchBox 464 255 1
	CreateMultiTouchBox 465 255 2
	CreateMultiTouchBox 466 255 3
	CreateMultiTouchBox 467 255 4
	CreateMultiTouchBox 468 255 5
	CreateMultiTouchBox 469 255 6
	CloseMultiTouch
	SetVarFromVariable 0x8008 0x800C
	CompareVarValue 0x8008 0
	JumpIf EQUAL Function#59
	CompareVarValue 0x8008 1
	JumpIf EQUAL Function#60
	CompareVarValue 0x8008 2
	JumpIf EQUAL Function#61
	CompareVarValue 0x8008 3
	JumpIf EQUAL Function#62
	CompareVarValue 0x8008 4
	JumpIf EQUAL Function#63
	CompareVarValue 0x8008 5
	JumpIf EQUAL Function#64
Jump Function#58

Function 33:
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 34:
	Message 92
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 35:
	Message 94
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#70
	Message 95
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 36:
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#70
	Message 95
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 37:
	Message 17
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 38:
	CompareVarValue 0x4057 6
	JumpIf LESS Function#4
	SetVar 0x800C 500
	TextNumber 1 0x800C
	Message 1
Jump Function#5

Function 39:
	HideMoney
	Message 3
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 40:
	CompareMoney 0x800C 500
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#42
	SetVar 0x800C 500
	TextNumber 1 0x800C
	Message 2
	PlayFanfare SEQ_SE_DP_REGI
	TakeMoney 500
	UpdateMoney
	Message 4
	TextPlayerName 0
	SetVar 0x800C 30
	TextNumber 1 0x800C
	Message 5
	PlaySound SEQ_ME_ITEM
	WaitSound
	Message 6
	CloseMessage
	HideMoney
	SendBackFollowingPoke
	Movement Player Action#11
	WaitMovement
	DoorAnimation 0 0 5 5 77
	Call Function#43
	Movement Player Action#12
	WaitMovement
	Call Function#44
	SetVar 0x40E3 1
	SetSafariFlag 0 0
	SetElevatorWarp 173 1 5 2 1
	PlayFanfare SEQ_SE_DP_KAIDAN2
	FadeScreen 6 1 0 0
	WaitFadeScreen
	Warp 357 0 79 100 Up
	FadeScreen 6 1 1 0
	WaitFadeScreen
	Lock Following
	BallResetFollowingPoke
	Movement Following Action#3
	WaitMovement
	Release Following
	ReleaseAll
End

Function 41:
	HideMoney
	CompareVarValue 0x4057 6
	JumpIf LESS Function#71
	Message 13
Jump Function#72

Function 42:
	HideMoney
	CompareVarValue 0x4057 6
	JumpIf LESS Function#73
	Message 11
Jump Function#74

Function 43:
	OpenDoor 77
	WaitDoor 77
Return

Function 44:
	CloseDoor 77
	WaitDoor 77
	FreeDoor 77
Return

Function 45:
	MultiTouchStandardText 1 1 0 1 0x800C
	CreateMultiTouchBox 457 255 0
	CreateMultiTouchBox 458 255 1
	CreateMultiTouchBox 459 255 2
	CreateMultiTouchBox 460 255 3
	CreateMultiTouchBox 461 255 4
	CreateMultiTouchBox 462 255 5
	CloseMultiTouch
	SetVarFromVariable 0x8008 0x800C
	CompareVarValue 0x8008 0
	JumpIf EQUAL Function#7
	CompareVarValue 0x8008 1
	JumpIf EQUAL Function#8
	CompareVarValue 0x8008 2
	JumpIf EQUAL Function#9
	CompareVarValue 0x8008 3
	JumpIf EQUAL Function#10
	CompareVarValue 0x8008 4
	JumpIf EQUAL Function#11
Jump Function#12

Function 46:
	DummyNationalDexCheck
	NationalDex 2 0x4000
	CompareVarValue 0x4000 0
	JumpIf EQUAL Function#14
	CompareVarValue 0x4057 6
	JumpIf LESS Function#15
	Message 65
Jump Function#16

Function 47:
	Message 85
	WaitButton
	CloseMessage
	CloseTouchScreen
	ReleaseAll
End

Function 48:
	OpenTouchScreen
	Message 71
	MultiTouchStandardText 1 1 0 1 0x800C
	CreateMultiTouchBox 14 255 0
	CreateMultiTouchBox 15 255 1
	CreateMultiTouchBox 5 255 2
	CloseMultiTouch
	SetVarFromVariable 0x8008 0x800C
	CompareVarValue 0x8008 0
	JumpIf EQUAL Function#75
	CompareVarValue 0x8008 1
	JumpIf EQUAL Function#76
Jump Function#47

Function 49:
	Message 85
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 50:
	DummyNationalDexCheck
	NationalDex 2 0x4000
	CompareVarValue 0x4000 0
	JumpIf EQUAL Function#14
	CMD_824 0x4000
	CompareVarValue 0x4000 0
	JumpIf EQUAL Function#18
	SetVar 0x4000 0
	CMD_823 0x4000
	Message 54
Jump Function#19

Function 51:
	HideMoney
	Message 3
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 52:
	CompareMoney 0x800C 500
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#54
	SetVar 0x800C 500
	TextNumber 1 0x800C
	Message 55
	PlayFanfare SEQ_SE_DP_REGI
	TakeMoney 500
	UpdateMoney
	Message 57
	TextPlayerName 0
	SetVar 0x800C 30
	TextNumber 1 0x800C
	Message 58
	PlaySound SEQ_ME_ITEM
	WaitSound
	Message 59
	CloseMessage
	HideMoney
	SendBackFollowingPoke
	Movement Player Action#11
	WaitMovement
	DoorAnimation 0 0 19 5 77
	Call Function#43
	Movement Player Action#12
	WaitMovement
	Call Function#44
	SetVar 0x40E3 3
	SetSafariFlag 0 1
	SetElevatorWarp 173 2 19 2 1
	PlayFanfare SEQ_SE_DP_KAIDAN2
	FadeScreen 6 1 0 0
	WaitFadeScreen
	Warp 357 0 79 100 Up
	FadeScreen 6 1 1 0
	WaitFadeScreen
	Lock Following
	BallResetFollowingPoke
	Movement Following Action#3
	WaitMovement
	Release Following
	ReleaseAll
End

Function 53:
	HideMoney
	CompareVarValue 0x4057 6
	JumpIf LESS Function#77
	Message 13
Jump Function#78

Function 54:
	HideMoney
	CompareVarValue 0x4057 6
	JumpIf LESS Function#79
	Message 11
Jump Function#80

Function 55:
	SetVar 0x4002 19
	SetVar 0x4003 5
	Movement Player Action#16
	WaitMovement
	DoorAnimation 0 0 0x4002 0x4003 77
	Call Function#43
	Movement Player Action#13
	Movement Overworld.2 Action#17
	Movement Overworld.4 Action#17
	WaitMovement
	Call Function#44
	SetVar 0x40E3 0
	Message 8
	Message 9
	WaitButton
	CloseMessage
	BallResetFollowingPoke
	ReleaseAll
End

Function 56:
	Movement Player Action#16
	WaitMovement
	DoorAnimation 0 0 0x4002 0x4003 77
	Call Function#43
	Movement Player Action#13
	Movement Overworld.2 Action#17
	Movement Overworld.4 Action#17
	WaitMovement
	Call Function#44
	SetVar 0x40E3 0
	Message 8
	Message 9
	WaitButton
	CloseMessage
	BallResetFollowingPoke
	ReleaseAll
End

Function 57:
	Message 30
	WaitButton
	CloseMessage
	SetVar 0x4057 2
	ReleaseAll
End

Function 58:
	CloseTouchScreen
	Message 53
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 59:
	Message 47
Jump Function#81

Function 60:
	Message 48
Jump Function#81

Function 61:
	Message 49
Jump Function#81

Function 62:
	Message 50
Jump Function#81

Function 63:
	Message 51
Jump Function#81

Function 64:
	Message 52
Jump Function#81

Function 65:
	Message 32
	SetVar 0x4057 3
	CMD_792
Jump Function#33

Function 66:
Jump Function#33

Function 67:
	Message 41
Jump Function#33

Function 68:
	CompareVarValue 0x800C 3
	JumpIf DIFFERENT Function#82
	Movement Overworld.5 Action#18
	Movement Player Action#19
	WaitMovement
Jump Function#69

Function 69:
	Message 38
	CloseMessage
	Movement Overworld.5 Action#20
	Movement Player Action#21
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	Message 39
	SetVar 0x4057 6
	CMD_792
Jump Function#33

Function 70:
	Message 96
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 71:
	Message 12
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 72:
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 73:
	Message 10
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 74:
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 75:
	Message 86
	YesNoTouchScreen 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#48
	SetVar 0x8004 39
	SetVar 0x8005 0
	CMD_226 0x8004 0x8005 0 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#83
	CompareVarValue 0x800C 3
	JumpIf EQUAL Function#84
	CompareVarValue 0x800C 4
	JumpIf EQUAL Function#85
Jump Function#86

Function 76:
	Message 86
	YesNoTouchScreen 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#48
	SetVar 0x8004 39
	SetVar 0x8005 0
	CMD_227 0x8004 0x8005 0 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#87
	CompareVarValue 0x800C 3
	JumpIf EQUAL Function#88
	CompareVarValue 0x800C 4
	JumpIf EQUAL Function#89
Jump Function#86

Function 77:
	Message 12
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 78:
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 79:
	Message 10
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 80:
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 81:
	MultiTouchStandardText 1 1 0 1 0x800C
	CreateMultiTouchBox 463 255 0
	CreateMultiTouchBox 464 255 1
	CreateMultiTouchBox 465 255 2
	CreateMultiTouchBox 466 255 3
	CreateMultiTouchBox 467 255 4
	CreateMultiTouchBox 468 255 5
	CreateMultiTouchBox 469 255 6
	CloseMultiTouch
	SetVarFromVariable 0x8008 0x800C
	CompareVarValue 0x8008 0
	JumpIf EQUAL Function#59
	CompareVarValue 0x8008 1
	JumpIf EQUAL Function#60
	CompareVarValue 0x8008 2
	JumpIf EQUAL Function#61
	CompareVarValue 0x8008 3
	JumpIf EQUAL Function#62
	CompareVarValue 0x8008 4
	JumpIf EQUAL Function#63
	CompareVarValue 0x8008 5
	JumpIf EQUAL Function#64
Jump Function#58

Function 82:
	Movement Overworld.5 Action#18
	Movement Player Action#22
	WaitMovement
	Message 38
	CloseMessage
	Movement Overworld.5 Action#20
	Movement Player Action#21
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	Message 39
	SetVar 0x4057 6
	CMD_792
Jump Function#33

Function 83:
	EndWirelessComms
	OpenTouchScreen
Jump Function#48

Function 84:
	EndWirelessComms
	CloseTouchScreen
	Message 87
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 85:
	EndWirelessComms
	Message 85
	WaitButton
	CloseMessage
	CloseTouchScreen
	ReleaseAll
End

Function 86:
	SetVar 0x4133 1
	Message 81
	CMD_257 96
	CMD_822
	EndWirelessComms
	SetVar 0x4000 0
	CMD_823 0x4000
	OpenTouchScreen
	Message 82
	Message 88
	AddWaitingIcon
	SaveGame 0x800C
	RemoveWaitingIcon
	TextPlayerName 0
	Message 89
	PlayFanfare SEQ_SE_DP_SAVE
	WaitFanfare SEQ_SE_DP_SAVE
	Message 83
	SetVar 0x4133 0
	CloseTouchScreen
	CloseMessage
	ReleaseAll
End

Function 87:
	EndWirelessComms
	OpenTouchScreen
Jump Function#48

Function 88:
	EndWirelessComms
	Message 87
	WaitButton
	CloseMessage
	CloseTouchScreen
	ReleaseAll
End

Function 89:
	EndWirelessComms
	Message 85
	WaitButton
	CloseMessage
	CloseTouchScreen
	ReleaseAll
End

//===== ACTIONS =====//
Action 1:
	FaceEast 0x1
End

Action 2:
	WalkNorth8 0x1
End

Action 3:
	FaceNorth 0x1
End

Action 4:
	WalkSouth8 0x2
End

Action 5:
	FaceSouth 0x1
	EmoteExclamation 0x1
	Delay16 0x1
	WalkWest8 0x1
End

Action 6:
	Delay16 0x1
	WalkNorth8 0x3
	FaceEast 0x1
End

Action 7:
	WalkNorth8 0x2
	WalkEast8 0x3
	WalkNorth8 0x1
End

Action 8:
	WalkNorth8 0x2
	WalkEast8 0x4
	WalkNorth8 0x1
End

Action 9:
	WalkSouth8 0x2
	WalkWest8 0x2
	WalkSouth8 0x1
	EmoteExclamation 0x1
	FaceNorth 0x1
End

Action 10:
	FaceSouth 0x1
End

Action 11:
	WalkEast8 0x1
	FaceNorth 0x1
End

Action 12:
	WalkNorth8 0x4
End

Action 13:
	WalkSouth8 0x2
	WalkWest8 0x1
	WalkOnSpotNorth8 0x1
End

Action 14:
	WalkWest8 0x2
	WalkNorth8 0x4
	WalkEast8 0x4
	FaceSouth 0x1
End

Action 15:
	Delay16 0x1
	FaceNorth 0x1
	Delay16 0x1
	WalkSouth8 0x1
	FaceNorth 0x1
End

Action 16:
	WalkSouth8 0x1
End

Action 17:
	Delay8 0x1
	FaceSouth 0x1
End

Action 18:
	WalkNorth8 0x4
	WalkEast8 0x2
	FaceSouth 0x1
End

Action 19:
	WalkEast8 0x1
	FaceNorth 0x1
End

Action 20:
	WalkSouth8 0x2
	WalkEast8 0x1
	WalkSouth8 0x2
	FaceWest 0x1
End

Action 21:
	Delay16 0x3
	FaceEast 0x1
End

Action 22:
	WalkNorth8 0x1
End

