/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0144
 * Generated: 3/6/2026 7:25:18 PM
 */

//===== SCRIPTS =====//
Script 1:
	MysteryGiftGive 0
	CheckMomGift 0x4000
	CMD_490 0x4000
	CompareVarValue 0x4000 0
	JumpIf DIFFERENT Function#1
	SetFlag 680
Jump Function#2

Script 2:
	MysteryGiftGive 0
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	MysteryGiftGive 1 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#3
	GetTimePeriod 0x800C
	SetVarFromVariable 0x8008 0x800C
	CompareVarValue 0x8008 0
	JumpIf EQUAL Function#4
	CompareVarValue 0x8008 1
	JumpIf EQUAL Function#5
Jump Function#6

Script 3:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckMomGift 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#7
	GetTimePeriod 0x800C
	SetVarFromVariable 0x8008 0x800C
	CompareVarValue 0x8008 0
	JumpIf EQUAL Function#8
	CompareVarValue 0x8008 1
	JumpIf EQUAL Function#9
Jump Function#10

Script 4:
	MysteryGiftGive 0
	CheckMomGift 0x4000
	CMD_490 0x4000
	CompareVarValue 0x4000 0
	JumpIf DIFFERENT Function#11
	SetFlag 680
Jump Function#12

//===== FUNCTIONS =====//
Function 1:
	ClearFlag 680
	MysteryGiftGive 1 0x4138
	CompareVarValue 0x4138 0
	JumpIf DIFFERENT Function#13
	SetFlag 679
Jump Function#14

Function 2:
	MysteryGiftGive 1 0x4138
	CompareVarValue 0x4138 0
	JumpIf DIFFERENT Function#13
	SetFlag 679
Jump Function#14

Function 3:
	Message 3
	WaitButton
Jump Function#15

Function 4:
	TextPlayerName 0
	Message 0
Jump Function#16

Function 5:
	TextPlayerName 0
	Message 1
Jump Function#16

Function 6:
	TextPlayerName 0
	Message 2
Jump Function#16

Function 7:
	Message 30
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 8:
	TextPlayerName 0
	Message 27
Jump Function#17

Function 9:
	TextPlayerName 0
	Message 28
Jump Function#17

Function 10:
	TextPlayerName 0
	Message 29
Jump Function#17

Function 11:
	ClearFlag 680
	MysteryGiftGive 1 0x4138
	CompareVarValue 0x4138 0
	JumpIf DIFFERENT Function#18
	SetFlag 679
Jump Function#19

Function 12:
	MysteryGiftGive 1 0x4138
	CompareVarValue 0x4138 0
	JumpIf DIFFERENT Function#18
	SetFlag 679
Jump Function#19

Function 13:
	ClearFlag 679
	MysteryGiftGive 7
End

Function 14:
	MysteryGiftGive 7
End

Function 15:
	CloseMessage
	ReleaseAll
	MysteryGiftGive 7
End

Function 16:
	MysteryGiftGive 3 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#20
	PlaySound SEQ_ME_ITEM
	MysteryGiftGive 5 0x8005 0x8006
	MessageFromArchive 0x8005 0x8006
	WaitSound
	Message 20
	WaitButton
	MysteryGiftGive 4
Jump Function#21

Function 17:
	CMD_811 0x8004 0x8005
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#22
	CommonScript 2033
	CMD_812
	CMD_149 12
	Message 20
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 18:
	ClearFlag 679
	SetVar 0x40E5 2
	MysteryGiftGive 7
End

Function 19:
	SetVar 0x40E5 2
	MysteryGiftGive 7
End

Function 20:
	MysteryGiftGive 6 0x8005 0x8006
	MessageFromArchive 0x8005 0x8006
	WaitButton
Jump Function#15

Function 21:
	CloseMessage
	ReleaseAll
	MysteryGiftGive 8
End

Function 22:
	TextItem 0 0x8004
	Message 5
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== ACTIONS =====//
