/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0152
 * Generated: 3/6/2026 7:25:18 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckFlag 2404
	JumpIf LESS Function#1
	CompareVarValue 0x4002 1
	JumpIf GREATER/EQUAL Function#2
	GetPlayerDirection 0x4001
	CompareVarValue 0x4001 0
	JumpIf EQUAL Function#3
	CompareVarValue 0x40CB 7
	JumpIf GREATER/EQUAL Function#4
	Message 1
	CloseMessage
	CheckItem ITEM_SS_TICKET 1 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#5
	Movement Player Action#1
	WaitMovement
	TextPlayerName 0
	Message 4
	CloseMessage
	Movement Overworld.0 Action#2
	WaitMovement
	Message 5
	CloseMessage
	Movement Overworld.0 Action#3
	WaitMovement
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	Movement Player Action#4
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	SetVar 0x4002 1
	SetVar 0x40E1 1
	SetVar 0x40DC 0
	ClearFlag 235
	SetFlag 556
	SetFlag 555
	ReleaseAll
End

Script 2:
	GetPreviousHeaderID 0x4000
	CompareVarValue 0x4000 330
	JumpIf EQUAL Function#6
End

Script 3:
	MecScript
	LockAll
	Movement Overworld.1 Action#5
	WaitMovement
	StopMusic 0
	PlayMusic SEQ_GS_OHKIDO
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	Movement Overworld.1 Action#6
	Movement Player Action#7
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	TextPlayerName 0
	GenderMessage 9 10
	CloseMessage
	Movement Overworld.1 Action#8
	WaitMovement
	NationalDex 1 0x800C
	TextPlayerName 0
	PlaySound SEQ_ME_ITEM
	Message 11
	WaitSound
	EnableMassOutbreaks
	Message 12
	CloseMessage
	Movement Overworld.1 Action#9
	WaitMovement
	Message 13
	CloseMessage
	Movement Overworld.1 Action#10
	WaitMovement
	RemoveOW Overworld.1
	SetFlag 593
	SetVar 0x411A 0
	FadeOutMusic 0 30
	StopMusic 0
	PlayDefaultMusic
	ReleaseAll
	CompareVarValue 0x40D3 1
	CallIf EQUAL Function#7
	EnableMassOutbreaks
End

Script 4:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 14
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 5:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 15
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== FUNCTIONS =====//
Function 1:
	Message 0
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 2:
	Message 6
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 3:
	Movement Overworld.0 Action#11
	WaitMovement
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	Movement Player Action#12
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	Movement Overworld.0 Action#13
	WaitMovement
	ReleaseAll
End

Function 4:
	GetDayOfWeek 0x800C
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#8
Jump Function#9

Function 5:
	Movement Player Action#14
	WaitMovement
	TextPlayerName 0
	Message 2
	CloseMessage
	Movement Overworld.0 Action#2
	WaitMovement
	Message 3
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 6:
	SetOWDefaultDirection Overworld.0 Down
End

Function 7:
	ClearFlag 691
Return

Function 8:
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#10
Jump Function#11

Function 9:
	Message 8
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 10:
	CompareVarValue 0x800C 2
	JumpIf DIFFERENT Function#12
Jump Function#9

Function 11:
	Message 7
	CloseMessage
	Movement Overworld.0 Action#3
	WaitMovement
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	Movement Player Action#4
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	SetVar 0x4002 1
	SetVar 0x40E1 1
	SetVar 0x40DC 0
	ClearFlag 235
	SetFlag 554
	ClearFlag 555
	SetFlag 556
	ReleaseAll
End

Function 12:
	CompareVarValue 0x800C 3
	JumpIf DIFFERENT Function#13
Jump Function#9

Function 13:
	CompareVarValue 0x800C 4
	JumpIf DIFFERENT Function#14
Jump Function#9

Function 14:
	CompareVarValue 0x800C 5
	JumpIf DIFFERENT Function#15
Jump Function#11

Function 15:
Jump Function#9

//===== ACTIONS =====//
Action 1:
	WalkOnSpotEast8 0x1
	FaceSouth 0x2
End

Action 2:
	WalkOnSpotNorth8 0x1
End

Action 3:
	LockDir 0x1
	WalkSouth8 0x1
	ReleaseDir 0x1
	FaceWest 0x2
	LockDir 0x1
	WalkEast8 0x1
	ReleaseDir 0x1
End

Action 4:
	WalkSouth8 0x2
End

Action 5:
	EmoteExclamation 0x1
End

Action 6:
	Delay8 0x1
	WalkWest8 0x3
	WalkNorth8 0x1
	WalkOnSpotWest8 0x1
End

Action 7:
	Delay8 0x3
	WalkSouth8 0x3
	WalkOnSpotEast8 0x1
End

Action 8:
	WalkOnSpotWest8 0x1
	Delay8 0x2
	WalkOnSpotWest8 0x1
End

Action 9:
	EmoteExclamation 0x1
End

Action 10:
	WalkNorth8 0x2
	WalkWest8 0x1
	WalkNorth8 0x1
End

Action 11:
	LockDir 0x1
	WalkNorth8 0x1
	ReleaseDir 0x1
	FaceWest 0x2
	LockDir 0x1
	WalkEast8 0x1
	ReleaseDir 0x1
End

Action 12:
	Delay8 0x1
	WalkNorth8 0x4
End

Action 13:
	WalkWest8 0x1
	FaceSouth 0x2
	WalkSouth8 0x1
	WalkOnSpotNorth8 0x1
End

Action 14:
	JumpOnSpotWest8 0x1
	JumpOnSpotEast8 0x1
	FaceSouth 0x2
	EmoteExclamation 0x1
End

