/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0202
 * Generated: 3/6/2026 7:25:18 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 0
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#1
	CheckAlbumPhoto 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#2
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 1
	CloseMessage
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	GetPlayerDirection 0x800C
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#3
	Movement Player Action#1
	Movement Overworld.10 Action#2
Jump Function#4

Script 2:
	CheckFlag 393
	JumpIf LESS Function#5
	ClearFlag 393
End

Script 3:
	MecScript
	LockAll
	ClearFlag 677
	AddOW Overworld.12
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	GetPlayerPosition 0x4000 0x4001
	CompareVarValue 0x4000 1358
	JumpIf DIFFERENT Function#6
	Movement Player Action#3
	WaitMovement
Jump Function#7

Script 4:
	TextPlayerName 0
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 7
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 5:
	TextPlayerName 0
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 7
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 6:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckFlag 348
	JumpIf EQUAL Function#8
	Message 0
	CheckBike 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#9
	GetFirstAlivePokemonSlot 0x4000
	GetPartyPokemonID 0x4000 0x4001
	CompareVarValue 0x4001 113
	JumpIf EQUAL Function#10
	Message 1
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== FUNCTIONS =====//
Function 1:
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 5
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 2:
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 3
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 3:
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#11
	Movement Player Action#4
Jump Function#4

Function 4:
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	CheckPokemonAlive 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#12
	Movement Following Action#5
	WaitMovement
	SetFlag 393
	FadeScreen 6 1 0 0
	WaitFadeScreen
	TakePhoto 60
	LockAll
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ClearFlag 393
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 5:
	GetDayOfWeek 0x4000
	CompareVarValue 0x4000 4
	JumpIf EQUAL Function#13
	CompareVarValue 0x4000 0
	JumpIf EQUAL Function#13
	SetFlag 638
End

Function 6:
Jump Function#14

Function 7:
	PlayCry SPECIES_SUICUNE 0
	Release Overworld.11
	ShakeOverworld Overworld.11 2 90 2 0
	Lock Overworld.11
	WaitCry
	CompareVarValue 0x4000 1358
	JumpIf DIFFERENT Function#15
Jump Function#16

Function 8:
	CheckBike 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#17
	GetFirstAlivePokemonSlot 0x4000
	GetPartyPokemonID 0x4000 0x4001
	CompareVarValue 0x4001 113
	JumpIf EQUAL Function#18
	Message 5
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 9:
	Message 1
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 10:
	Movement Overworld.17 Action#6
	WaitMovement
	Message 2
	SetVar 0x8004 256
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#19
	CommonScript 2033
	SetFlag 348
	Message 3
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 11:
	CompareVarValue 0x800C 3
	JumpIf DIFFERENT Function#20
	Movement Player Action#7
	Movement Overworld.10 Action#2
Jump Function#4

Function 12:
	SetFlag 393
	FadeScreen 6 1 0 0
	WaitFadeScreen
	TakePhoto 60
	LockAll
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ClearFlag 393
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 13:
	ClearFlag 638
End

Function 14:
	CompareVarValue 0x4001 409
	JumpIf DIFFERENT Function#21
	Movement Player Action#3
	WaitMovement
Jump Function#7

Function 15:
	CompareVarValue 0x4000 1359
	JumpIf DIFFERENT Function#22
Jump Function#23

Function 16:
	CompareVarValue 0x4001 409
	JumpIf DIFFERENT Function#24
	Movement Player Action#8
Jump Function#25

Function 17:
	Message 5
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 18:
	Message 4
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 19:
	CommonScript 2009
	CloseMessage
	ReleaseAll
End

Function 20:
	Movement Player Action#9
	Movement Overworld.10 Action#2
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	CheckPokemonAlive 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#12
	Movement Following Action#5
	WaitMovement
	SetFlag 393
	FadeScreen 6 1 0 0
	WaitFadeScreen
	TakePhoto 60
	LockAll
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ClearFlag 393
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 21:
	Movement Player Action#3
	WaitMovement
	PlayCry SPECIES_SUICUNE 0
	Release Overworld.11
	ShakeOverworld Overworld.11 2 90 2 0
	Lock Overworld.11
	WaitCry
	CompareVarValue 0x4000 1358
	JumpIf DIFFERENT Function#15
Jump Function#16

Function 22:
Jump Function#26

Function 23:
	CompareVarValue 0x4001 409
	JumpIf DIFFERENT Function#27
	Movement Player Action#10
Jump Function#28

Function 24:
	CompareVarValue 0x4001 410
	JumpIf DIFFERENT Function#29
	Movement Player Action#11
Jump Function#25

Function 25:
	WaitMovement
Jump Function#30

Function 26:
	CompareVarValue 0x4001 409
	JumpIf DIFFERENT Function#31
	Movement Player Action#12
Jump Function#32

Function 27:
	Movement Player Action#13
	WaitMovement
Jump Function#30

Function 28:
	WaitMovement
Jump Function#30

Function 29:
	CompareVarValue 0x4001 411
	JumpIf DIFFERENT Function#33
	Movement Player Action#14
Jump Function#25

Function 30:
	Movement Overworld.11 Action#15
	Movement Player Action#16
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	CommonScript 2042
	Movement Overworld.12 Action#17
	Movement Player Action#18
	WaitMovement
	TextPlayerName 0
	Message 6
	WaitButton
	CloseMessage
	CommonScript 2043
	RemoveOW Overworld.11
	SetFlag 672
	SetFlag 677
	ClearFlag 684
	SetVar 0x4086 0
	SetFlag 333
	CheckBadge 9 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#34
	ClearFlag 673
	SetVar 0x4089 1
	ReleaseAll
End

Function 31:
	Movement Player Action#19
	WaitMovement
	Movement Overworld.11 Action#15
	Movement Player Action#16
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	CommonScript 2042
	Movement Overworld.12 Action#17
	Movement Player Action#18
	WaitMovement
	TextPlayerName 0
	Message 6
	WaitButton
	CloseMessage
	CommonScript 2043
	RemoveOW Overworld.11
	SetFlag 672
	SetFlag 677
	ClearFlag 684
	SetVar 0x4086 0
	SetFlag 333
	CheckBadge 9 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#34
	ClearFlag 673
	SetVar 0x4089 1
	ReleaseAll
End

Function 32:
	WaitMovement
	Movement Overworld.11 Action#15
	Movement Player Action#16
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	CommonScript 2042
	Movement Overworld.12 Action#17
	Movement Player Action#18
	WaitMovement
	TextPlayerName 0
	Message 6
	WaitButton
	CloseMessage
	CommonScript 2043
	RemoveOW Overworld.11
	SetFlag 672
	SetFlag 677
	ClearFlag 684
	SetVar 0x4086 0
	SetFlag 333
	CheckBadge 9 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#34
	ClearFlag 673
	SetVar 0x4089 1
	ReleaseAll
End

Function 33:
	CompareVarValue 0x4001 412
	JumpIf DIFFERENT Function#35
	Movement Player Action#20
Jump Function#25

Function 34:
	ReleaseAll
End

Function 35:
	CompareVarValue 0x4001 413
	JumpIf DIFFERENT Function#36
	Movement Player Action#21
Jump Function#25

Function 36:
	CompareVarValue 0x4001 414
	JumpIf DIFFERENT Function#37
	Movement Player Action#22
Jump Function#25

Function 37:
	Movement Player Action#23
	WaitMovement
Jump Function#30

//===== ACTIONS =====//
Action 1:
	WalkEast8 0x1
	WalkNorth8 0x2
	WalkWest8 0x1
	WalkNorth8 0x3
	WalkOnSpotSouth8 0x1
End

Action 2:
	Delay8 0x1
	WalkOnSpotNorth8 0x1
End

Action 3:
	EmoteExclamation 0x1
End

Action 4:
	WalkNorth8 0x3
	WalkOnSpotSouth8 0x1
End

Action 5:
	WalkEast8 0x1
	WalkNorth8 0x1
	FaceSouth 0x1
End

Action 6:
	EmoteExclamation 0x1
	Delay4 0x1
End

Action 7:
	WalkNorth8 0x1
	WalkEast8 0x1
	WalkNorth8 0x3
	WalkOnSpotSouth8 0x1
End

Action 8:
	WalkSouth8 0x1
	WalkEast8 0x3
	WalkSouth8 0x2
	FaceEast 0x1
End

Action 9:
	WalkNorth8 0x1
	WalkWest8 0x1
	WalkNorth8 0x3
	WalkOnSpotSouth8 0x1
End

Action 10:
	WalkSouth8 0x1
	WalkEast8 0x2
	WalkSouth8 0x2
	FaceEast 0x1
End

Action 11:
	WalkEast8 0x3
	WalkSouth8 0x2
	FaceEast 0x1
End

Action 12:
	WalkSouth8 0x3
	FaceEast 0x1
End

Action 13:
	WalkNorth8 0x1
	WalkEast8 0x2
	WalkNorth8 0x2
	FaceEast 0x1
End

Action 14:
	WalkEast8 0x3
	WalkSouth8 0x1
	FaceEast 0x1
End

Action 15:
	WalkNorth2 0x2
	JumpNorth8 0x1
	JumpFarNorth 0x1
	WalkNorth2 0x2
	JumpNorth8 0x1
	JumpFarNorth 0x2
	WalkNorth2 0x2
	JumpNorth8 0x1
End

Action 16:
	Delay8 0x1
	FaceNorth 0x1
	WalkNorth8 0x1
End

Action 17:
	WalkNorth4 0xB
	WalkNorth8 0x2
	WalkNorth32 0x1
	Delay8 0x3
	WalkSouth16 0x1
	FaceEast 0x1
End

Action 18:
	Delay16 0x5
	FaceWest 0x1
End

Action 19:
	WalkNorth8 0x3
	FaceEast 0x1
End

Action 20:
	WalkEast8 0x3
End

Action 21:
	WalkEast8 0x3
	WalkNorth8 0x1
	FaceEast 0x1
End

Action 22:
	WalkEast8 0x3
	WalkNorth8 0x2
	FaceEast 0x1
End

Action 23:
	WalkNorth8 0x1
	WalkEast8 0x3
	WalkNorth8 0x2
	FaceEast 0x1
End

