/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0219
 * Generated: 3/6/2026 7:25:18 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 0
	CloseMessage
	FadeScreen 6 1 0 0
	WaitFadeScreen
	PlaySound SEQ_ME_ASA
	WaitSound
	HealPokemon
	FinishOverworldScreen
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	Message 1
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 2
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== FUNCTIONS =====//
//===== ACTIONS =====//
