/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0240
 * Generated: 3/6/2026 7:25:18 PM
 */

//===== SCRIPTS =====//
Script 1:
	SetIconBoard 28 1 4 0x800C
	ShowBoard 3
	WaitBoard
	CloseBoard 0x800C
	CommonScript 2000
End

Script 2:
	CheckFlag 393
	JumpIf LESS Function#1
	ClearFlag 393
End

Script 3:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 21
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 4:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 0
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#2
	CheckAlbumPhoto 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#3
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 1
	CloseMessage
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	GetPlayerDirection 0x800C
	CompareVarValue 0x800C 3
	JumpIf DIFFERENT Function#4
	Movement Player Action#1
	Movement Overworld.12 Action#2
Jump Function#5

Script 5:
	SetIconBoard 29 1 19 0x800C
	ShowBoard 3
	WaitBoard
	CloseBoard 0x800C
	CommonScript 2000
End

//===== FUNCTIONS =====//
Function 1:
	GetDayOfWeek 0x4000
	CompareVarValue 0x4000 1
	JumpIf EQUAL Function#6
	CompareVarValue 0x4000 2
	JumpIf EQUAL Function#6
	CompareVarValue 0x4000 5
	JumpIf EQUAL Function#6
	SetFlag 638
Jump Function#7

Function 2:
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 5
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 3:
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 3
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 4:
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#8
	Movement Player Action#3
Jump Function#5

Function 5:
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	CheckPokemonAlive 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#9
	Movement Following Action#4
	WaitMovement
	SetFlag 393
	FadeScreen 6 1 0 0
	WaitFadeScreen
	TakePhoto 11
	LockAll
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ClearFlag 393
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 6:
	ClearFlag 638
	GetTimePeriod 0x4000
	CompareVarValue 0x4000 3
	JumpIf EQUAL Function#10
	CompareVarValue 0x4000 4
	JumpIf EQUAL Function#10
	ClearFlag 461
	SetFlag 462
End

Function 7:
	GetTimePeriod 0x4000
	CompareVarValue 0x4000 3
	JumpIf EQUAL Function#10
	CompareVarValue 0x4000 4
	JumpIf EQUAL Function#10
	ClearFlag 461
	SetFlag 462
End

Function 8:
	Movement Player Action#5
	Movement Overworld.12 Action#2
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	CheckPokemonAlive 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#9
	Movement Following Action#4
	WaitMovement
	SetFlag 393
	FadeScreen 6 1 0 0
	WaitFadeScreen
	TakePhoto 11
	LockAll
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ClearFlag 393
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 9:
	SetFlag 393
	FadeScreen 6 1 0 0
	WaitFadeScreen
	TakePhoto 11
	LockAll
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ClearFlag 393
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 10:
	ClearFlag 462
	SetFlag 461
End

//===== ACTIONS =====//
Action 1:
	WalkNorth8 0x1
	WalkEast8 0x1
	WalkNorth8 0x3
	WalkOnSpotSouth8 0x1
End

Action 2:
	Delay8 0x1
	WalkOnSpotNorth8 0x1
End

Action 3:
	WalkNorth8 0x3
	WalkOnSpotSouth8 0x1
End

Action 4:
	WalkEast8 0x1
	WalkNorth8 0x1
	FaceSouth 0x1
End

Action 5:
	WalkNorth8 0x1
	WalkWest8 0x1
	WalkNorth8 0x3
	WalkOnSpotSouth8 0x1
End

