/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0242
 * Generated: 3/6/2026 7:25:18 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 9
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CommonScript 0x28A5
	CompareVarValue 0x4118 1
	JumpIf DIFFERENT Function#1
	CheckFlag 452
	JumpIf EQUAL Function#2
	GetPlayerDirection 0x800C
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#3
	Movement Player Action#1
Jump Function#4

Script 3:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 3
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 4:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 5
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 5:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 6
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 6:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 0
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 7:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 7
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 8:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 8
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 9:
	MecScript
	LockAll
	Movement Overworld.2 Action#2
	WaitMovement
	GetPlayerPosition 0x4000 0x4001
	CompareVarValue 0x4001 7
	JumpIf DIFFERENT Function#5
	Movement Overworld.2 Action#3
Jump Function#6

Script 10:
End

Script 11:
	MecScript
	LockAll
	Movement Player Action#4
	Movement Overworld.7 Action#5
	WaitMovement
	CommonScript 0x28A6
	CompareVarValue 0x4118 1
	JumpIf DIFFERENT Function#7
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	Movement Player Action#6
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	PlayFanfare SEQ_SE_DP_KAIDAN2
	FadeScreen 6 1 0 0
	WaitFadeScreen
	Warp 487 0 40 86 Up
	FadeScreen 6 1 1 0
	WaitFadeScreen
	Lock Following
	GetFollowingPokeSize 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#8
	BallResetFollowingPoke
Jump Function#9

Script 12:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 0
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#10
	CheckAlbumPhoto 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#11
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 1
	CloseMessage
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	GetPlayerDirection 0x800C
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#12
	Movement Player Action#7
	Movement Overworld.6 Action#8
Jump Function#13

Script 13:
	GetDayOfWeek 0x4000
	CompareVarValue 0x4118 1
	JumpIf DIFFERENT Function#14
	ClearFlag 452
	SetFlag 451
Jump Function#15

//===== FUNCTIONS =====//
Function 1:
	ReleaseAll
End

Function 2:
	GetPlayerDirection 0x800C
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	Movement Player Action#9
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	PlayFanfare SEQ_SE_DP_KAIDAN2
	FadeScreen 6 1 0 0
	WaitFadeScreen
	Warp 487 0 40 86 Up
	FadeScreen 6 1 1 0
	WaitFadeScreen
	Lock Following
	GetFollowingPokeSize 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#16
	BallResetFollowingPoke
Jump Function#17

Function 3:
	CompareVarValue 0x800C 2
	JumpIf DIFFERENT Function#18
	Movement Player Action#6
Jump Function#4

Function 4:
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
Jump Function#19

Function 5:
	CompareVarValue 0x4001 8
	JumpIf DIFFERENT Function#20
	Movement Overworld.2 Action#10
Jump Function#6

Function 6:
	WaitMovement
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 56
	Movement Overworld.2 Action#11
	Movement Player Action#12
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	Message 10
	CloseMessage
	CompareVarValue 0x4001 7
	JumpIf DIFFERENT Function#21
	Movement Overworld.2 Action#13
Jump Function#22

Function 7:
	ReleaseAll
End

Function 8:
	NoBallResetFollowingPoke
	Movement Following Action#14
	WaitMovement
	Release Following
	ReleaseAll
End

Function 9:
	Movement Following Action#14
	WaitMovement
	Release Following
	ReleaseAll
End

Function 10:
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 5
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 11:
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 3
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 12:
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#23
	Movement Player Action#15
Jump Function#13

Function 13:
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	CheckPokemonAlive 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#24
	Movement Following Action#16
	WaitMovement
	SetFlag 393
	FadeScreen 6 1 0 0
	WaitFadeScreen
	TakePhoto 12
	LockAll
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ClearFlag 393
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 14:
	CompareVarValue 0x4000 2
	JumpIf DIFFERENT Function#25
	ClearFlag 452
	SetFlag 451
Jump Function#15

Function 15:
	CheckFlag 393
	JumpIf LESS Function#26
	ClearFlag 393
End

Function 16:
	NoBallResetFollowingPoke
	Movement Following Action#14
	WaitMovement
	Release Following
	ReleaseAll
End

Function 17:
	Movement Following Action#14
	WaitMovement
	Release Following
	ReleaseAll
End

Function 18:
	Movement Player Action#17
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
Jump Function#19

Function 19:
	PlayFanfare SEQ_SE_DP_KAIDAN2
	FadeScreen 6 1 0 0
	WaitFadeScreen
	Warp 487 0 40 86 Up
	FadeScreen 6 1 1 0
	WaitFadeScreen
	Lock Following
	GetFollowingPokeSize 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#16
	BallResetFollowingPoke
Jump Function#17

Function 20:
	CompareVarValue 0x4001 10
	JumpIf DIFFERENT Function#27
	Movement Overworld.2 Action#18
Jump Function#6

Function 21:
	CompareVarValue 0x4001 8
	JumpIf DIFFERENT Function#28
	Movement Overworld.2 Action#19
Jump Function#22

Function 22:
	WaitMovement
	ReleaseAll
End

Function 23:
	CompareVarValue 0x800C 3
	JumpIf DIFFERENT Function#29
	Movement Player Action#20
	Movement Overworld.6 Action#8
Jump Function#13

Function 24:
	SetFlag 393
	FadeScreen 6 1 0 0
	WaitFadeScreen
	TakePhoto 12
	LockAll
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ClearFlag 393
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 25:
	CompareVarValue 0x4000 4
	JumpIf DIFFERENT Function#30
	ClearFlag 452
	SetFlag 451
Jump Function#15

Function 26:
	GetDayOfWeek 0x4000
	CompareVarValue 0x4000 6
	JumpIf EQUAL Function#31
	CompareVarValue 0x4000 0
	JumpIf EQUAL Function#31
	SetFlag 638
End

Function 27:
	Movement Overworld.2 Action#21
	WaitMovement
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 56
	Movement Overworld.2 Action#11
	Movement Player Action#12
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	Message 10
	CloseMessage
	CompareVarValue 0x4001 7
	JumpIf DIFFERENT Function#21
	Movement Overworld.2 Action#13
Jump Function#22

Function 28:
	CompareVarValue 0x4001 10
	JumpIf DIFFERENT Function#32
	Movement Overworld.2 Action#22
Jump Function#22

Function 29:
	Movement Player Action#23
	Movement Overworld.6 Action#8
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	CheckPokemonAlive 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#24
	Movement Following Action#16
	WaitMovement
	SetFlag 393
	FadeScreen 6 1 0 0
	WaitFadeScreen
	TakePhoto 12
	LockAll
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ClearFlag 393
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 30:
	CompareVarValue 0x4000 6
	JumpIf DIFFERENT Function#33
	ClearFlag 452
	SetFlag 451
Jump Function#15

Function 31:
	ClearFlag 638
End

Function 32:
	Movement Overworld.2 Action#24
	WaitMovement
	ReleaseAll
End

Function 33:
	ClearFlag 451
	SetFlag 452
	CheckFlag 393
	JumpIf LESS Function#26
	ClearFlag 393
End

//===== ACTIONS =====//
Action 1:
	WalkEast8 0x1
	WalkNorth8 0x2
End

Action 2:
	EmoteExclamation 0x1
End

Action 3:
	WalkWest4 0x1
	WalkNorth4 0x2
	WalkOnSpotEast4 0x1
End

Action 4:
	FaceWest 0x1
End

Action 5:
	FaceEast 0x1
End

Action 6:
	WalkNorth8 0x1
End

Action 7:
	WalkEast8 0x1
	WalkNorth8 0x2
	WalkWest8 0x1
	WalkNorth8 0x3
	WalkOnSpotSouth8 0x1
End

Action 8:
	Delay8 0x1
	WalkOnSpotNorth8 0x1
End

Action 9:
	WalkEast8 0x2
	WalkNorth8 0x2
End

Action 10:
	WalkWest4 0x1
	WalkNorth4 0x1
	WalkOnSpotEast4 0x1
End

Action 11:
	WalkEast8 0x1
End

Action 12:
	LockDir 0x1
	WalkEast8 0x1
	ReleaseDir 0x1
End

Action 13:
	WalkSouth8 0x2
	WalkOnSpotEast8 0x1
End

Action 14:
	FaceNorth 0x1
End

Action 15:
	WalkNorth8 0x3
	WalkOnSpotSouth8 0x1
End

Action 16:
	WalkEast8 0x1
	WalkNorth8 0x1
	FaceSouth 0x1
End

Action 17:
	WalkSouth8 0x1
	WalkEast8 0x2
	WalkNorth8 0x2
End

Action 18:
	WalkWest4 0x1
	WalkSouth4 0x1
	WalkOnSpotEast4 0x1
End

Action 19:
	WalkSouth8 0x1
	WalkOnSpotEast8 0x1
End

Action 20:
	WalkNorth8 0x1
	WalkEast8 0x1
	WalkNorth8 0x3
	WalkOnSpotSouth8 0x1
End

Action 21:
	WalkWest4 0x1
	WalkSouth4 0x2
	WalkOnSpotEast4 0x1
End

Action 22:
	WalkNorth8 0x1
	WalkOnSpotEast8 0x1
End

Action 23:
	WalkNorth8 0x1
	WalkWest8 0x1
	WalkNorth8 0x3
	WalkOnSpotSouth8 0x1
End

Action 24:
	WalkNorth8 0x2
	WalkOnSpotEast8 0x1
End

