/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0786
 * Generated: 3/6/2026 7:25:19 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckBadge 11 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#1
	Message 0
	CloseMessage
	TrainerBattle TRAINER_ERIKA_256 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#2
	GiveBadge 11
	IncrementVar 0x4135 1
	AddTrainerScore 22
	SetTrainerFlag TRAINER_JO_AND_ZOE_326
	SetTrainerFlag TRAINER_MICHELLE_356
	SetTrainerFlag TRAINER_TANYA_336
	SetTrainerFlag TRAINER_JULIA_346
	Message 1
	TextPlayerName 0
	Message 2
	PlaySound SEQ_ME_BADGE
	WaitSound
	Message 3
Jump Function#3

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckBadge 11 0x800C
	TextPlayerName 0
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#4
	Message 5
Jump Function#5

Script 3:
	CheckPokeGearRematch 28 0x4001
	CompareVarValue 0x4001 0
	JumpIf DIFFERENT Function#6
	CheckPokegearNumberRegistered 28 0x4001
	CompareVarValue 0x4001 1
	JumpIf EQUAL Function#7
	CheckBadge 15 0x4002
	CompareVarValue 0x4002 1
	JumpIf EQUAL Function#8
Jump Function#9

//===== FUNCTIONS =====//
Function 1:
	CheckFlag 292
	JumpIf LESS Function#3
	Message 4
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 2:
	LostBattle
	ReleaseAll
End

Function 3:
	SetVar 0x8004 346
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#10
	CommonScript 2033
	SetFlag 292
	CheckFlag 292
	JumpIf LESS Function#3
	Message 4
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 4:
	Message 6
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 5:
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 6:
	SetFlag 754
End

Function 7:
	GetDayOfWeek 0x4000
	CompareVarValue 0x4000 1
	JumpIf DIFFERENT Function#11
	SetFlag 754
Jump Function#12

Function 8:
	GetDayOfWeek 0x4000
	CompareVarValue 0x4000 6
	JumpIf DIFFERENT Function#13
Jump Function#14

Function 9:
	ClearFlag 754
End

Function 10:
	CommonScript 2009
	CloseMessage
	ReleaseAll
End

Function 11:
Jump Function#9

Function 12:
End

Function 13:
	CompareVarValue 0x4000 0
	JumpIf DIFFERENT Function#15
Jump Function#14

Function 14:
	GetHour 0x4000
	CompareVarValue 0x4000 14
	JumpIf DIFFERENT Function#16
	SetFlag 754
Jump Function#17

Function 15:
Jump Function#9

Function 16:
	CompareVarValue 0x4000 15
	JumpIf DIFFERENT Function#18
	SetFlag 754
Jump Function#17

Function 17:
End

Function 18:
	CompareVarValue 0x4000 16
	JumpIf DIFFERENT Function#19
	SetFlag 754
Jump Function#17

Function 19:
Jump Function#9

//===== ACTIONS =====//
