/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0885
 * Generated: 3/6/2026 7:25:19 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CompareVarValue 0x40DA 1
	JumpIf DIFFERENT Function#1
	CompareVarValue 0x40DB 0
	JumpIf EQUAL Function#2
	Message 9
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CompareVarValue 0x4077 2
	JumpIf GREATER/EQUAL Function#3
	Message 4
Jump Function#4

Script 3:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckFlag 138
	JumpIf EQUAL Function#5
	Message 6
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 4:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 8
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 5:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckBike 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#6
	Message 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 6:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CompareVarValue 0x40DA 1
	JumpIf DIFFERENT Function#7
	CompareVarValue 0x40DB 0
	JumpIf EQUAL Function#8
	Message 0
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 7:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CompareVarValue 0x40DA 1
	JumpIf DIFFERENT Function#9
	CompareVarValue 0x40DB 0
	JumpIf EQUAL Function#10
	Message 11
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 8:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Message 13
	CloseMessage
	GetPlayerDirection 0x800C
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#11
	Movement Overworld.4 Action#1
	WaitMovement
Jump Function#12

Script 9:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CompareVarValue 0x4077 3
	JumpIf DIFFERENT Function#13
	Message 17
Jump Function#14

Script 10:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CompareVarValue 0x4077 3
	JumpIf DIFFERENT Function#15
	Message 19
Jump Function#16

Script 11:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CompareVarValue 0x4077 3
	JumpIf DIFFERENT Function#17
	Message 21
Jump Function#18

Script 12:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CompareVarValue 0x4077 3
	JumpIf DIFFERENT Function#19
	Message 23
Jump Function#20

Script 13:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CompareVarValue 0x4077 3
	JumpIf DIFFERENT Function#21
	Message 25
Jump Function#22

Script 14:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CompareVarValue 0x4077 3
	JumpIf DIFFERENT Function#23
	Message 30
Jump Function#24

Script 15:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 31
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 16:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 32
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 17:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CompareVarValue 0x4077 3
	JumpIf DIFFERENT Function#25
	Message 34
Jump Function#26

Script 18:
	MecScript
	LockAll
	Movement Overworld.15 Action#2
	WaitMovement
	GetPlayerPosition 0x4000 0x4001
	CompareVarValue 0x4000 354
	JumpIf DIFFERENT Function#27
	Movement Overworld.15 Action#3
Jump Function#28

Script 19:
	SetFlag 441
	SetFlag 442
	SetFlag 439
	SetFlag 443
	SetFlag 440
	CompareVarValue 0x4077 0
	JumpIf DIFFERENT Function#29
	ClearFlag 440
	ClearFlag 441
Jump Function#30

Script 20:
	SetTextBoard 2 0
	ShowBoard 3
	WaitBoard
	BoardMessage 36 0x800C
	CommonScript 2000
End

Script 21:
	SetTextBoard 2 0
	ShowBoard 3
	WaitBoard
	BoardMessage 37 0x800C
	CommonScript 2000
End

Script 22:
	SetTextBoard 2 0
	ShowBoard 3
	WaitBoard
	BoardMessage 38 0x800C
	CommonScript 2000
End

Script 23:
	SetIconBoard 39 0 16 0x800C
	ShowBoard 3
	WaitBoard
	CloseBoard 0x800C
	CommonScript 2000
End

Script 24:
	SetTextBoard 2 0
	ShowBoard 3
	WaitBoard
	BoardMessage 40 0x800C
	CommonScript 2000
End

Script 25:
	SetTextBoard 2 0
	ShowBoard 3
	WaitBoard
	BoardMessage 41 0x800C
	CommonScript 2000
End

Script 26:
	SetTextBoard 2 0
	ShowBoard 3
	WaitBoard
	BoardMessage 42 0x800C
	CommonScript 2000
End

Script 27:
	SetTextBoard 3 0
	ShowBoard 3
	WaitBoard
	BoardMessage 43 0x800C
	CommonScript 2000
End

Script 28:
	SetTextBoard 3 0
	ShowBoard 3
	WaitBoard
	BoardMessage 44 0x800C
	CommonScript 2000
End

Script 29:
	SetTextBoard 2 0
	ShowBoard 3
	WaitBoard
	BoardMessage 45 0x800C
	CommonScript 2000
End

Script 30:
	SetTextBoard 2 0
	ShowBoard 3
	WaitBoard
	BoardMessage 46 0x800C
	CommonScript 2000
End

Script 31:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Message 26
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 32:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Message 27
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 33:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 28
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== FUNCTIONS =====//
Function 1:
	Message 9
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 2:
	Message 10
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 3:
	Message 5
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 4:
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 5:
	Message 7
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 6:
	Message 3
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 7:
	Message 0
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 8:
	Message 1
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 9:
	Message 11
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 10:
	Message 12
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 11:
	CompareVarValue 0x800C 2
	JumpIf DIFFERENT Function#31
	Movement Overworld.4 Action#4
	WaitMovement
Jump Function#12

Function 12:
	CompareVarValue 0x4077 3
	JumpIf DIFFERENT Function#32
	Message 15
Jump Function#33

Function 13:
	Message 16
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 14:
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 15:
	Message 18
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 16:
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 17:
	Message 20
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 18:
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 19:
	Message 22
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 20:
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 21:
	Message 24
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 22:
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 23:
	Message 29
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 24:
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 25:
	Message 33
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 26:
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 27:
	CompareVarValue 0x4000 355
	JumpIf DIFFERENT Function#34
	Movement Overworld.15 Action#5
Jump Function#28

Function 28:
	WaitMovement
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 56
	Movement Overworld.15 Action#6
	Movement Player Action#7
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	Message 35
	CloseMessage
	CompareVarValue 0x4000 354
	JumpIf DIFFERENT Function#35
	Movement Overworld.15 Action#8
Jump Function#36

Function 29:
	CompareVarValue 0x4077 1
	JumpIf DIFFERENT Function#37
	ClearFlag 440
	ClearFlag 441
	ClearFlag 442
Jump Function#30

Function 30:
End

Function 31:
	CompareVarValue 0x800C 3
	JumpIf DIFFERENT Function#12
	Movement Overworld.4 Action#9
	WaitMovement
	CompareVarValue 0x4077 3
	JumpIf DIFFERENT Function#32
	Message 15
Jump Function#33

Function 32:
	Message 14
	CloseMessage
	CompareVarValue 0x4001 350
	JumpIf EQUAL Function#38
	Movement Overworld.4 Action#10
	WaitMovement
	ReleaseAll
End

Function 33:
	CloseMessage
	CompareVarValue 0x4001 350
	JumpIf EQUAL Function#38
	Movement Overworld.4 Action#10
	WaitMovement
	ReleaseAll
End

Function 34:
	CompareVarValue 0x4000 356
	JumpIf DIFFERENT Function#39
	Movement Overworld.15 Action#11
Jump Function#28

Function 35:
	CompareVarValue 0x4000 355
	JumpIf DIFFERENT Function#40
	Movement Overworld.15 Action#12
Jump Function#36

Function 36:
	WaitMovement
	ReleaseAll
End

Function 37:
	CompareVarValue 0x4077 3
	JumpIf DIFFERENT Function#41
	ClearFlag 441
	ClearFlag 442
	ClearFlag 439
	ClearFlag 443
Jump Function#30

Function 38:
	ReleaseAll
End

Function 39:
	CompareVarValue 0x4000 357
	JumpIf DIFFERENT Function#42
	Movement Overworld.15 Action#13
Jump Function#28

Function 40:
	CompareVarValue 0x4000 356
	JumpIf DIFFERENT Function#43
	Movement Overworld.15 Action#14
Jump Function#36

Function 41:
	CompareVarValue 0x4077 5
	JumpIf DIFFERENT Function#44
	ClearFlag 440
Jump Function#30

Function 42:
	CompareVarValue 0x4000 358
	JumpIf DIFFERENT Function#45
	Movement Overworld.15 Action#15
Jump Function#28

Function 43:
	CompareVarValue 0x4000 357
	JumpIf DIFFERENT Function#46
	Movement Overworld.15 Action#16
Jump Function#36

Function 44:
	ClearFlag 441
	ClearFlag 442
	ClearFlag 439
End

Function 45:
	CompareVarValue 0x4000 359
	JumpIf DIFFERENT Function#47
	Movement Overworld.15 Action#17
Jump Function#28

Function 46:
	CompareVarValue 0x4000 358
	JumpIf DIFFERENT Function#48
	Movement Overworld.15 Action#18
Jump Function#36

Function 47:
	CompareVarValue 0x4000 360
	JumpIf DIFFERENT Function#49
	Movement Overworld.15 Action#19
Jump Function#28

Function 48:
	CompareVarValue 0x4000 359
	JumpIf DIFFERENT Function#50
	Movement Overworld.15 Action#20
Jump Function#36

Function 49:
	CompareVarValue 0x4000 361
	JumpIf DIFFERENT Function#51
	Movement Overworld.15 Action#21
Jump Function#28

Function 50:
	CompareVarValue 0x4000 360
	JumpIf DIFFERENT Function#52
	Movement Overworld.15 Action#22
Jump Function#36

Function 51:
	CompareVarValue 0x4000 362
	JumpIf DIFFERENT Function#53
	Movement Overworld.15 Action#23
Jump Function#28

Function 52:
	CompareVarValue 0x4000 361
	JumpIf DIFFERENT Function#54
	Movement Overworld.15 Action#24
Jump Function#36

Function 53:
	CompareVarValue 0x4000 363
	JumpIf DIFFERENT Function#28
	Movement Overworld.15 Action#25
	WaitMovement
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 56
	Movement Overworld.15 Action#6
	Movement Player Action#7
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	Message 35
	CloseMessage
	CompareVarValue 0x4000 354
	JumpIf DIFFERENT Function#35
	Movement Overworld.15 Action#8
Jump Function#36

Function 54:
	CompareVarValue 0x4000 362
	JumpIf DIFFERENT Function#55
	Movement Overworld.15 Action#26
Jump Function#36

Function 55:
	CompareVarValue 0x4000 363
	JumpIf DIFFERENT Function#36
	Movement Overworld.15 Action#27
	WaitMovement
	ReleaseAll
End

//===== ACTIONS =====//
Action 1:
	WalkOnSpotSouth8 0x1
End

Action 2:
	EmoteExclamation 0x1
End

Action 3:
	WalkWest8 0x5
End

Action 4:
	WalkOnSpotEast8 0x1
End

Action 5:
	WalkWest8 0x4
End

Action 6:
	WalkNorth8 0x1
End

Action 7:
	LockDir 0x1
	WalkNorth8 0x1
	ReleaseDir 0x1
End

Action 8:
	WalkSouth8 0x1
	WalkEast8 0x5
	WalkOnSpotNorth8 0x1
End

Action 9:
	WalkOnSpotWest8 0x1
End

Action 10:
	WalkOnSpotNorth8 0x1
End

Action 11:
	WalkWest8 0x3
End

Action 12:
	WalkSouth8 0x1
	WalkEast8 0x4
	WalkOnSpotNorth8 0x1
End

Action 13:
	WalkWest8 0x2
End

Action 14:
	WalkSouth8 0x1
	WalkEast8 0x3
	WalkOnSpotNorth8 0x1
End

Action 15:
	WalkWest8 0x1
End

Action 16:
	WalkSouth8 0x1
	WalkEast8 0x2
	WalkOnSpotNorth8 0x1
End

Action 17:
	Delay1 0x1
End

Action 18:
	WalkSouth8 0x1
	WalkEast8 0x1
	WalkOnSpotNorth8 0x1
End

Action 19:
	WalkEast8 0x1
End

Action 20:
	WalkSouth8 0x1
	WalkOnSpotNorth8 0x1
End

Action 21:
	WalkEast8 0x2
End

Action 22:
	WalkSouth8 0x1
	WalkWest8 0x1
	WalkOnSpotNorth8 0x1
End

Action 23:
	WalkEast8 0x3
End

Action 24:
	WalkSouth8 0x1
	WalkWest8 0x2
	WalkOnSpotNorth8 0x1
End

Action 25:
	WalkEast8 0x4
End

Action 26:
	WalkSouth8 0x1
	WalkWest8 0x3
	WalkOnSpotNorth8 0x1
End

Action 27:
	WalkSouth8 0x1
	WalkWest8 0x4
	WalkOnSpotNorth8 0x1
End

