/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0893
 * Generated: 3/6/2026 7:25:19 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckFlag 280
	JumpIf EQUAL Function#1
	Message 0
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 2:
	MecScript
	LockAll
	Movement Player Action#1
	WaitMovement
	CheckFlag 291
	JumpIf EQUAL Function#2
	Message 1
	CloseMessage
	SetFlag 291
	WaitTime 50 0x8004
	CheckItem ITEM_PASS 1 0x800C
	CompareVarValue 0x800C 1
	JumpIf GREATER/EQUAL Function#3
	Message 2
	CloseMessage
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	Movement Player Action#2
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	ReleaseAll
End

Script 3:
End

Script 4:
End

Script 5:
End

Script 6:
	CheckFlag 280
	JumpIf EQUAL Function#4
End

Script 7:
	CMD_582 76 348 350
	CheckFlag 280
	JumpIf EQUAL Function#5
End

Script 8:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Message 9
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== FUNCTIONS =====//
Function 1:
	GetPlayerDirection 0x800C
	CompareVarValue 0x800C 2
	JumpIf DIFFERENT Function#6
	Message 5
	WaitButton
	CloseMessage
Jump Function#7

Function 2:
	Message 3
	CloseMessage
Jump Function#8

Function 3:
	Message 4
	WaitButton
	CloseMessage
	SetVar 0x410B 1
	SetVar 0x411E 1
	ReleaseAll
End

Function 4:
	SetOWPosition Overworld.0 4 0 6 Right
End

Function 5:
	SetVar 0x410B 0
End

Function 6:
	Message 7
	CloseMessage
	Movement Overworld.0 Action#3
	WaitMovement
	ReleaseAll
End

Function 7:
	ReleaseAll
End

Function 8:
	WaitTime 50 0x8004
	CheckItem ITEM_PASS 1 0x800C
	CompareVarValue 0x800C 1
	JumpIf GREATER/EQUAL Function#3
	Message 2
	CloseMessage
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	Movement Player Action#2
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	ReleaseAll
End

//===== ACTIONS =====//
Action 1:
	WalkOnSpotWest8 0x1
End

Action 2:
	WalkSouth8 0x2
End

Action 3:
	FaceEast 0x1
End

