/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0928
 * Generated: 3/6/2026 7:25:19 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckFlag 162
	JumpIf EQUAL Function#1
	Message 25
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	PlayCry SPECIES_PSYDUCK 0
	Message 30
	WaitCry
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 3:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CompareVarValue 0x400A 10
	JumpIf EQUAL Function#2
	CompareVarValue 0x410C 1
	JumpIf EQUAL Function#3
	Message 31
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 4:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	StopMusic 0
	PlayMusic SEQ_GS_EYE_ROCKET
	Message 5
	CloseMessage
	SetVar 0x4009 222
	TrainerBattle TRAINER_GRUNT_601 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#4
	Message 6
	CloseMessage
	GetPlayerDirection 0x8004
	CompareVarValue 0x8004 0
	JumpIf DIFFERENT Function#5
	Movement Overworld.12 Action#1
Jump Function#6

Script 5:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CompareVarValue 0x410C 1
	JumpIf EQUAL Function#7
	CompareVarValue 0x400A 10
	JumpIf EQUAL Function#8
	Message 10
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 6:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckFlag 264
	JumpIf EQUAL Function#9
	CheckFlag 265
	JumpIf EQUAL Function#9
	Message 19
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 7:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckFlag 264
	JumpIf EQUAL Function#10
	CheckFlag 265
	JumpIf EQUAL Function#10
	Message 19
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 8:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	SetVar 0x8000 77
	CheckFlag 264
	JumpIf EQUAL Function#11
	CheckFlag 265
	JumpIf EQUAL Function#11
	Message 13
	OpenTouchScreen
	YesNoTouchScreen 0x8004
	CloseTouchScreen
	CompareVarValue 0x8004 1
	JumpIf EQUAL Function#12
	CloseMessage
	GetPlayerDirection 0x800C
	CompareVarValue 0x800C 0
	CallIf DIFFERENT Function#13
Jump Function#14

Script 9:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckFlag 264
	JumpIf EQUAL Function#15
	CheckFlag 265
	JumpIf EQUAL Function#15
	Message 19
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 10:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckFlag 264
	JumpIf EQUAL Function#16
	CheckFlag 265
	JumpIf EQUAL Function#16
	Message 19
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 11:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 39
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 12:
	MecScript
	LockAll
	Movement Overworld.2 Action#2
	WaitMovement
	Message 26
	SetVar 0x8004 422
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#17
	CommonScript 2033
	SetFlag 162
	SetVar 0x410C 3
	SetVar 0x4090 1
	Message 28
	CloseMessage
	Movement Overworld.2 Action#3
	WaitMovement
	ReleaseAll
End

Script 13:
	MecScript
	LockAll
	Movement Overworld.2 Action#4
	WaitMovement
	Message 26
	SetVar 0x8004 422
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#17
	CommonScript 2033
	SetFlag 162
	SetVar 0x4090 1
	SetVar 0x410C 3
	Message 28
	CloseMessage
	Movement Overworld.2 Action#5
	WaitMovement
	ReleaseAll
End

Script 14:
	CompareVarValue 0x410C 1
	JumpIf GREATER Function#18
	VanishOverworld Overworld.12
	CompareVarValue 0x410C 0
	JumpIf DIFFERENT Function#19
	SetOWPosition Overworld.9 6 0 6 Right
	SetOWPosition Overworld.6 8 0 6 Left
	CompareVarValue 0x4009 222
	JumpIf DIFFERENT Function#20
	SetOWPosition Overworld.9 29 0 29 Down
	VanishOverworld Overworld.9
	GetPlayerDirection 0x4000
	CompareVarValue 0x4000 0
	JumpIf DIFFERENT Function#21
	SetOWPosition Overworld.12 7 0 6 Down
Jump Function#22

Script 15:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CompareVarValue 0x400A 10
	JumpIf EQUAL Function#23
	CompareVarValue 0x410C 1
	JumpIf EQUAL Function#24
	Message 36
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 16:
	MecScript
	LockAll
	Message 0
	CloseMessage
	Movement Overworld.9 Action#6
	WaitMovement
	GetPlayerPosition 0x8004 0x8005
	LockCamera 0x8004 0x8005
	Movement Camera Action#7
	WaitMovement
	WaitTime 10 0x800C
	Movement Overworld.9 Action#8
	WaitMovement
	Message 1
	CloseMessage
	Movement Overworld.6 Action#9
	WaitMovement
	Message 2
	CloseMessage
	Movement Overworld.9 Action#10
	WaitMovement
	Message 3
	CloseMessage
	Movement Overworld.6 Action#11
	WaitMovement
	Message 4
	CloseMessage
	Movement Overworld.9 Action#12
	WaitMovement
	Movement Overworld.9 Action#13
	Movement Camera Action#14
	WaitMovement
	ReleaseCamera
	ReleaseAll
	SetVar 0x410C 1
End

Script 17:
	MecScript
	LockAll
	SetVar 0x8000 11
	SetVar 0x410C 5
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	Movement Player Action#15
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	CheckVersion 0x800C
	CompareVarValue 0x800C 7
	JumpIf DIFFERENT Function#25
	Message 11
Jump Function#26

//===== FUNCTIONS =====//
Function 1:
	Message 29
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 2:
	Message 33
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 3:
	CompareVarValue 0x400B 0
	JumpIf DIFFERENT Function#27
	Message 32
Jump Function#28

Function 4:
	LostBattle
	ReleaseAll
End

Function 5:
	CompareVarValue 0x8004 1
	JumpIf DIFFERENT Function#29
	Movement Overworld.12 Action#16
Jump Function#6

Function 6:
	WaitMovement
	Message 7
	CloseMessage
	CompareVarValue 0x8004 0
	JumpIf DIFFERENT Function#30
	Movement Overworld.12 Action#17
Jump Function#31

Function 7:
	Message 8
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 8:
	TextPlayerName 0
	Message 9
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 9:
	Message 40
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 10:
	Message 41
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 11:
	TextPlayerName 0
	Message 42
	WaitButton
	CloseMessage
	SetFlag 263
	ReleaseAll
End

Function 12:
	Message 14
	WaitButton
	CloseMessage
	Call Function#32
End

Function 13:
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#33
	Movement Player Action#18
Jump Function#34

Function 14:
	StopMusic 30
	PlayMusic SEQ_GS_EYE_MAIKO
	Movement Overworld.10 Action#19
	WaitMovement
	Message 45
	CloseMessage
	WaitTime 10 0x800C
	TrainerBattle TRAINER_ZUKI_162 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#35
	Movement Overworld.10 Action#20
	WaitMovement
	StopMusic 30
	PlayMusic SEQ_GS_EYE_MAIKO
	Movement Overworld.4 Action#21
	WaitMovement
	Message 15
	CloseMessage
	TrainerBattle TRAINER_NAOKO_160 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#35
	Movement Overworld.4 Action#22
	WaitMovement
	StopMusic 30
	PlayMusic SEQ_GS_EYE_MAIKO
	Movement Overworld.8 Action#23
	WaitMovement
	Message 16
	CloseMessage
	TrainerBattle TRAINER_MIKI_164 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#35
	Movement Overworld.8 Action#24
	WaitMovement
	StopMusic 30
	PlayMusic SEQ_GS_EYE_MAIKO
	Movement Overworld.5 Action#25
	WaitMovement
	Message 17
	CloseMessage
	TrainerBattle TRAINER_SAYO_161 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#35
	Movement Overworld.5 Action#26
	WaitMovement
	StopMusic 30
	PlayMusic SEQ_GS_EYE_MAIKO
	Movement Overworld.7 Action#27
	WaitMovement
	Message 18
	CloseMessage
	TrainerBattle TRAINER_KUNI_163 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#35
	Movement Overworld.7 Action#28
	WaitMovement
	Movement Overworld.10 Action#29
	WaitMovement
	Message 20
	CheckVersion 0x800C
	CompareVarValue 0x800C 7
	JumpIf DIFFERENT Function#36
	SetVar 0x8004 474
	SetVar 0x8005 1
	CommonScript 2033
	SetFlag 259
Jump Function#37

Function 15:
	Message 43
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 16:
	Message 44
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 17:
	CommonScript 2009
	CloseMessage
	ReleaseAll
End

Function 18:
	CompareVarValue 0x410C 0
	JumpIf DIFFERENT Function#19
	SetOWPosition Overworld.9 6 0 6 Right
	SetOWPosition Overworld.6 8 0 6 Left
	CompareVarValue 0x4009 222
	JumpIf DIFFERENT Function#20
	SetOWPosition Overworld.9 29 0 29 Down
	VanishOverworld Overworld.9
	GetPlayerDirection 0x4000
	CompareVarValue 0x4000 0
	JumpIf DIFFERENT Function#21
	SetOWPosition Overworld.12 7 0 6 Down
Jump Function#22

Function 19:
	CompareVarValue 0x4009 222
	JumpIf DIFFERENT Function#20
	SetOWPosition Overworld.9 29 0 29 Down
	VanishOverworld Overworld.9
	GetPlayerDirection 0x4000
	CompareVarValue 0x4000 0
	JumpIf DIFFERENT Function#21
	SetOWPosition Overworld.12 7 0 6 Down
Jump Function#22

Function 20:
	CompareVarValue 0x400A 10
	JumpIf EQUAL Function#38
	CompareVarValue 0x410C 3
	JumpIf DIFFERENT Function#38
	SetOWPosition Overworld.6 7 0 6 Down
End

Function 21:
	CompareVarValue 0x4000 1
	JumpIf DIFFERENT Function#39
	SetOWPosition Overworld.12 7 0 6 Up
Jump Function#22

Function 22:
	UnvanishOverworld Overworld.12
	SetVar 0x4009 0
	CompareVarValue 0x400A 10
	JumpIf EQUAL Function#38
	CompareVarValue 0x410C 3
	JumpIf DIFFERENT Function#38
	SetOWPosition Overworld.6 7 0 6 Down
End

Function 23:
	Message 38
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 24:
	Message 37
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 25:
	Message 12
	OpenTouchScreen
	YesNoTouchScreen 0x8004
	CloseTouchScreen
	CompareVarValue 0x8004 1
	JumpIf EQUAL Function#12
	CloseMessage
	StopMusic 30
	PlayMusic SEQ_GS_EYE_MAIKO
	Movement Overworld.10 Action#19
	WaitMovement
	Message 45
	CloseMessage
	WaitTime 10 0x800C
	TrainerBattle TRAINER_ZUKI_162 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#35
	Movement Overworld.10 Action#20
	WaitMovement
	StopMusic 30
	PlayMusic SEQ_GS_EYE_MAIKO
	Movement Overworld.4 Action#21
	WaitMovement
	Message 15
	CloseMessage
	TrainerBattle TRAINER_NAOKO_160 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#35
	Movement Overworld.4 Action#22
	WaitMovement
	StopMusic 30
	PlayMusic SEQ_GS_EYE_MAIKO
	Movement Overworld.8 Action#23
	WaitMovement
	Message 16
	CloseMessage
	TrainerBattle TRAINER_MIKI_164 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#35
	Movement Overworld.8 Action#24
	WaitMovement
	StopMusic 30
	PlayMusic SEQ_GS_EYE_MAIKO
	Movement Overworld.5 Action#25
	WaitMovement
	Message 17
	CloseMessage
	TrainerBattle TRAINER_SAYO_161 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#35
	Movement Overworld.5 Action#26
	WaitMovement
	StopMusic 30
	PlayMusic SEQ_GS_EYE_MAIKO
	Movement Overworld.7 Action#27
	WaitMovement
	Message 18
	CloseMessage
	TrainerBattle TRAINER_KUNI_163 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#35
	Movement Overworld.7 Action#28
	WaitMovement
	Movement Overworld.10 Action#29
	WaitMovement
	Message 20
	CheckVersion 0x800C
	CompareVarValue 0x800C 7
	JumpIf DIFFERENT Function#36
	SetVar 0x8004 474
	SetVar 0x8005 1
	CommonScript 2033
	SetFlag 259
Jump Function#37

Function 26:
	OpenTouchScreen
	YesNoTouchScreen 0x8004
	CloseTouchScreen
	CompareVarValue 0x8004 1
	JumpIf EQUAL Function#12
	CloseMessage
	StopMusic 30
	PlayMusic SEQ_GS_EYE_MAIKO
	Movement Overworld.10 Action#19
	WaitMovement
	Message 45
	CloseMessage
	WaitTime 10 0x800C
	TrainerBattle TRAINER_ZUKI_162 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#35
	Movement Overworld.10 Action#20
	WaitMovement
	StopMusic 30
	PlayMusic SEQ_GS_EYE_MAIKO
	Movement Overworld.4 Action#21
	WaitMovement
	Message 15
	CloseMessage
	TrainerBattle TRAINER_NAOKO_160 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#35
	Movement Overworld.4 Action#22
	WaitMovement
	StopMusic 30
	PlayMusic SEQ_GS_EYE_MAIKO
	Movement Overworld.8 Action#23
	WaitMovement
	Message 16
	CloseMessage
	TrainerBattle TRAINER_MIKI_164 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#35
	Movement Overworld.8 Action#24
	WaitMovement
	StopMusic 30
	PlayMusic SEQ_GS_EYE_MAIKO
	Movement Overworld.5 Action#25
	WaitMovement
	Message 17
	CloseMessage
	TrainerBattle TRAINER_SAYO_161 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#35
	Movement Overworld.5 Action#26
	WaitMovement
	StopMusic 30
	PlayMusic SEQ_GS_EYE_MAIKO
	Movement Overworld.7 Action#27
	WaitMovement
	Message 18
	CloseMessage
	TrainerBattle TRAINER_KUNI_163 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#35
	Movement Overworld.7 Action#28
	WaitMovement
	Movement Overworld.10 Action#29
	WaitMovement
	Message 20
	CheckVersion 0x800C
	CompareVarValue 0x800C 7
	JumpIf DIFFERENT Function#36
	SetVar 0x8004 474
	SetVar 0x8005 1
	CommonScript 2033
	SetFlag 259
Jump Function#37

Function 27:
	CompareVarValue 0x400B 1
	JumpIf DIFFERENT Function#40
	Message 34
Jump Function#28

Function 28:
	WaitButton
	CloseMessage
	ReleaseAll
	CompareVarValue 0x400B 2
	JumpIf GREATER/EQUAL Function#41
	IncrementVar 0x400B 1
Jump Function#42

Function 29:
	CompareVarValue 0x8004 2
	JumpIf DIFFERENT Function#43
	Movement Overworld.12 Action#30
Jump Function#6

Function 30:
	CompareVarValue 0x8004 1
	JumpIf DIFFERENT Function#44
	Movement Overworld.12 Action#31
Jump Function#31

Function 31:
	WaitMovement
	RemoveOW Overworld.12
	SetFlag 570
	ReleaseAll
	SetVar 0x410C 2
	SetVar 0x400A 10
End

Function 32:
	CompareVarValue 0x8000 77
	JumpIf DIFFERENT Function#45
	ReleaseAll
Jump Function#46

Function 33:
	CompareVarValue 0x800C 2
	JumpIf DIFFERENT Function#47
	Movement Player Action#32
Jump Function#34

Function 34:
	Movement Overworld.10 Action#33
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
Return

Function 35:
	LostBattle
	Call Function#32
End

Function 36:
	SetVar 0x8004 503
	SetVar 0x8005 1
	CommonScript 2033
	SetFlag 260
	CloseMessage
	PlayFanfare SEQ_SE_DP_KI_GASYAN
	ShakeCamera 0 2 10 6
	WaitFanfare SEQ_SE_DP_KI_GASYAN
	ClearFlag 576
	AddOW Overworld.11
	Movement Overworld.11 Action#34
	WaitMovement
	Movement Overworld.10 Action#35
	WaitMovement
	CheckVersion 0x800C
	CompareVarValue 0x800C 7
	JumpIf DIFFERENT Function#48
	Message 21
Jump Function#49

Function 37:
	CloseMessage
	PlayFanfare SEQ_SE_DP_KI_GASYAN
	ShakeCamera 0 2 10 6
	WaitFanfare SEQ_SE_DP_KI_GASYAN
	ClearFlag 576
	AddOW Overworld.11
	Movement Overworld.11 Action#34
	WaitMovement
	Movement Overworld.10 Action#35
	WaitMovement
	CheckVersion 0x800C
	CompareVarValue 0x800C 7
	JumpIf DIFFERENT Function#48
	Message 21
Jump Function#49

Function 38:
End

Function 39:
	CompareVarValue 0x4000 2
	JumpIf DIFFERENT Function#50
	SetOWPosition Overworld.12 7 0 6 Right
Jump Function#22

Function 40:
	Message 35
	WaitButton
	CloseMessage
	ReleaseAll
	CompareVarValue 0x400B 2
	JumpIf GREATER/EQUAL Function#41
	IncrementVar 0x400B 1
Jump Function#42

Function 41:
	SetVar 0x400B 0
End

Function 42:
End

Function 43:
	Movement Overworld.12 Action#36
	WaitMovement
	Message 7
	CloseMessage
	CompareVarValue 0x8004 0
	JumpIf DIFFERENT Function#30
	Movement Overworld.12 Action#17
Jump Function#31

Function 44:
	CompareVarValue 0x8004 2
	JumpIf DIFFERENT Function#51
	Movement Overworld.12 Action#37
Jump Function#31

Function 45:
	ReleaseAll
Return

Function 46:
Return

Function 47:
	CompareVarValue 0x800C 3
	JumpIf DIFFERENT Function#34
	Movement Player Action#38
	Movement Overworld.10 Action#33
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
Return

Function 48:
	Message 22
	CloseMessage
	Movement Overworld.10 Action#39
	WaitMovement
	TextPlayerName 0
	CompareVarValue 0x800C 7
	JumpIf DIFFERENT Function#52
	Message 23
Jump Function#53

Function 49:
	CloseMessage
	Movement Overworld.10 Action#39
	WaitMovement
	TextPlayerName 0
	CompareVarValue 0x800C 7
	JumpIf DIFFERENT Function#52
	Message 23
Jump Function#53

Function 50:
	SetOWPosition Overworld.12 7 0 6 Left
	UnvanishOverworld Overworld.12
	SetVar 0x4009 0
	CompareVarValue 0x400A 10
	JumpIf EQUAL Function#38
	CompareVarValue 0x410C 3
	JumpIf DIFFERENT Function#38
	SetOWPosition Overworld.6 7 0 6 Down
End

Function 51:
	Movement Overworld.12 Action#40
	WaitMovement
	RemoveOW Overworld.12
	SetFlag 570
	ReleaseAll
	SetVar 0x410C 2
	SetVar 0x400A 10
End

Function 52:
	Message 24
	CloseMessage
	Movement Overworld.4 Action#41
	Movement Overworld.5 Action#42
	Movement Overworld.10 Action#43
	Movement Overworld.7 Action#44
	Movement Overworld.8 Action#45
	Movement Overworld.11 Action#46
	WaitMovement
	RemoveOW Overworld.4
	RemoveOW Overworld.5
	RemoveOW Overworld.10
	RemoveOW Overworld.7
	RemoveOW Overworld.8
	RemoveOW Overworld.11
	SetFlag 572
	SetFlag 576
	Call Function#32
	SetVar 0x410C 6
	SetVar 0x40FA 1
	CompareVarValue 0x800C 7
	JumpIf DIFFERENT Function#54
	ClearFlag 580
Jump Function#55

Function 53:
	CloseMessage
	Movement Overworld.4 Action#41
	Movement Overworld.5 Action#42
	Movement Overworld.10 Action#43
	Movement Overworld.7 Action#44
	Movement Overworld.8 Action#45
	Movement Overworld.11 Action#46
	WaitMovement
	RemoveOW Overworld.4
	RemoveOW Overworld.5
	RemoveOW Overworld.10
	RemoveOW Overworld.7
	RemoveOW Overworld.8
	RemoveOW Overworld.11
	SetFlag 572
	SetFlag 576
	Call Function#32
	SetVar 0x410C 6
	SetVar 0x40FA 1
	CompareVarValue 0x800C 7
	JumpIf DIFFERENT Function#54
	ClearFlag 580
Jump Function#55

Function 54:
	ClearFlag 581
End

Function 55:
End

//===== ACTIONS =====//
Action 1:
	LockDir 0x1
	WalkNorth8 0x1
	ReleaseDir 0x1
End

Action 2:
	WalkNorth8 0x1
	WalkWest8 0x5
	WalkNorth8 0x2
End

Action 3:
	WalkSouth8 0x2
	WalkEast8 0x5
	WalkSouth8 0x1
	FaceNorth 0x1
End

Action 4:
	WalkNorth8 0x1
	WalkEast8 0x3
	WalkNorth8 0x2
End

Action 5:
	WalkSouth8 0x2
	WalkWest8 0x3
	WalkSouth8 0x1
	FaceNorth 0x1
End

Action 6:
	FaceEast 0x1
End

Action 7:
	WalkNorth6 0x9
End

Action 8:
	WalkEast8 0x1
End

Action 9:
	WalkOnSpotWest4 0x1
End

Action 10:
	JumpOnSpotEast8 0x2
End

Action 11:
	LockDir 0x1
	WalkEast8 0x2
	ReleaseDir 0x1
End

Action 12:
	WalkOnSpotSouth8 0x1
End

Action 13:
	FaceWest 0x1
	Delay1 0x1
	FaceNorth 0x1
	Delay1 0x1
	FaceEast 0x1
	Delay1 0x1
	FaceSouth 0x1
	Delay1 0x1
	FaceWest 0x1
	Delay1 0x1
	FaceNorth 0x1
	Delay1 0x1
	FaceEast 0x1
	Delay1 0x1
	FaceSouth 0x1
	Delay1 0x1
	FaceWest 0x1
	Delay1 0x1
	FaceNorth 0x1
	Delay1 0x1
	FaceEast 0x1
	Delay1 0x1
	FaceSouth 0x1
	Delay1 0x1
	FaceWest 0x1
	Delay1 0x1
	FaceNorth 0x1
	Delay1 0x1
	FaceEast 0x1
	Delay1 0x1
	FaceSouth 0x1
	Delay1 0x1
	FaceWest 0x1
	Delay1 0x1
	FaceNorth 0x1
	Delay1 0x1
	FaceEast 0x1
	Delay1 0x1
	FaceSouth 0x1
	Delay1 0x1
	FaceWest 0x1
	Delay1 0x1
	FaceNorth 0x1
	Delay1 0x1
	FaceEast 0x1
	Delay1 0x1
	FaceSouth 0x1
	FaceWest 0x1
	Delay1 0x1
	FaceNorth 0x1
	Delay1 0x1
	FaceEast 0x1
	Delay1 0x1
	FaceSouth 0x1
End

Action 14:
	Delay32 0x1
	WalkSouth6 0x9
End

Action 15:
	WalkNorth8 0x5
	WalkWest8 0x4
	WalkNorth8 0x5
	WalkEast8 0x4
	WalkOnSpotNorth8 0x1
End

Action 16:
	LockDir 0x1
	WalkSouth8 0x1
	ReleaseDir 0x1
End

Action 17:
	WalkWest4 0x4
	WalkSouth4 0xC
End

Action 18:
	WalkEast8 0x1
	WalkSouth8 0x2
	WalkWest8 0x1
	WalkOnSpotNorth8 0x1
End

Action 19:
	FaceWest 0x1
	Delay4 0x1
	FaceNorth 0x1
	Delay4 0x1
	FaceEast 0x1
	Delay4 0x1
	FaceSouth 0x1
	Delay4 0x1
	FaceWest 0x1
	Delay4 0x1
	FaceNorth 0x1
	Delay4 0x1
	FaceEast 0x1
	Delay4 0x1
	WalkOnSpotSouth8 0x1
End

Action 20:
	WalkNorth8 0x1
	WalkOnSpotSouth8 0x1
End

Action 21:
	FaceEast 0x1
	Delay2 0x1
	FaceNorth 0x1
	Delay2 0x1
	FaceWest 0x1
	Delay2 0x1
	FaceSouth 0x1
	Delay2 0x1
	WalkOnSpotEast8 0x1
	WalkEast8 0x5
	WalkOnSpotSouth8 0x1
End

Action 22:
	WalkWest8 0x5
	WalkOnSpotSouth8 0x1
End

Action 23:
	FaceWest 0x1
	Delay2 0x1
	FaceNorth 0x1
	Delay2 0x1
	FaceEast 0x1
	Delay2 0x1
	FaceSouth 0x1
	Delay2 0x1
	WalkOnSpotWest8 0x1
	WalkWest8 0x5
	WalkOnSpotSouth8 0x1
End

Action 24:
	WalkEast8 0x5
	WalkOnSpotSouth8 0x1
End

Action 25:
	FaceEast 0x1
	Delay2 0x1
	FaceNorth 0x1
	Delay2 0x1
	FaceWest 0x1
	Delay2 0x1
	WalkOnSpotSouth8 0x1
	WalkSouth8 0x1
	WalkEast8 0x3
	WalkOnSpotSouth8 0x1
End

Action 26:
	WalkWest8 0x3
	WalkNorth8 0x1
	WalkOnSpotSouth8 0x1
End

Action 27:
	FaceWest 0x1
	Delay2 0x1
	FaceNorth 0x1
	Delay2 0x1
	FaceEast 0x1
	Delay2 0x1
	WalkOnSpotSouth8 0x1
	WalkSouth8 0x1
	WalkWest8 0x3
	WalkOnSpotSouth8 0x1
End

Action 28:
	WalkEast8 0x3
	WalkNorth8 0x1
	WalkOnSpotSouth8 0x1
End

Action 29:
	WalkSouth8 0x1
End

Action 30:
	LockDir 0x1
	WalkWest8 0x1
	ReleaseDir 0x1
End

Action 31:
	WalkWest4 0x4
	WalkSouth4 0xA
End

Action 32:
	WalkSouth8 0x1
	WalkWest8 0x1
	WalkOnSpotNorth8 0x1
End

Action 33:
	Delay8 0x2
	WalkOnSpotSouth8 0x1
End

Action 34:
	WalkNorth4 0xA
	WalkEast4 0x3
End

Action 35:
	WalkOnSpotWest8 0x1
End

Action 36:
	LockDir 0x1
	WalkEast8 0x1
	ReleaseDir 0x1
End

Action 37:
	WalkWest4 0x3
	WalkSouth4 0xA
End

Action 38:
	WalkSouth8 0x1
	WalkEast8 0x1
	WalkOnSpotNorth8 0x1
End

Action 39:
	EmoteExclamation 0x1
End

Action 40:
	WalkSouth4 0x1
	WalkEast4 0x3
	WalkSouth4 0x9
End

Action 41:
	WalkEast8 0x1
	WalkSouth8 0xB
End

Action 42:
	Delay8 0x1
	WalkWest8 0x1
	WalkSouth8 0xC
End

Action 43:
	Delay8 0x1
	WalkEast8 0x4
	WalkSouth8 0xB
End

Action 44:
	Delay8 0x1
	WalkEast8 0x1
	WalkSouth8 0xC
End

Action 45:
	WalkWest8 0x1
	WalkSouth8 0xB
End

Action 46:
	Delay8 0x2
	WalkEast8 0x5
	WalkSouth8 0xB
End

