/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0940
 * Generated: 3/6/2026 7:25:19 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckFlag 202
	JumpIf EQUAL Function#1
	CheckFlag 200
	JumpIf EQUAL Function#2
	Message 0
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== FUNCTIONS =====//
Function 1:
	OverlayManager 0 0
	CheckBornPokemonInParty 0x800C SPECIES_MAGIKARP
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#3
	Message 2
Jump Function#4

Function 2:
	Message 1
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 3:
	Message 3
	CloseMessage
	FadeScreen 6 1 0 0
	WaitFadeScreen
	ChoosePokemonSelection
	GetSelectedPartySlot 0x8002
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	CompareVarValue 0x8002 255
	JumpIf DIFFERENT Function#5
	Message 10
Jump Function#4

Function 4:
	WaitButton
	CloseMessage
	OverlayManager 0 1
	ReleaseAll
End

Function 5:
	GetPartyPokemonID 0x8002 0x8001
	CompareVarValue 0x8001 129
	JumpIf EQUAL Function#6
	Message 8
Jump Function#4

Function 6:
	ComparePokemonPlayerSize 0x800C 0x8002
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#7
	TextPartyPokemonSize 0 1 0x8002
	TextPokemonRecordSize 2 3 SPECIES_MAGIKARP
	Message 7
Jump Function#4

Function 7:
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#8
	TextPokemonRecordSize 0 1 SPECIES_MAGIKARP
	Message 6
Jump Function#4

Function 8:
	TextPartyPokemonSize 0 1 0x8002
	Message 4
	SetVar 0x8004 38
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#9
	CommonScript 2009
Jump Function#10

Function 9:
	CommonScript 2033
	SetPokemonSizeRecord 0x8002
	SetFlag 313
	Message 5
	WaitButton
	CloseMessage
	OverlayManager 0 1
	ReleaseAll
End

Function 10:
	CloseMessage
	OverlayManager 0 1
	ReleaseAll
End

//===== ACTIONS =====//
