/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0962
 * Generated: 3/6/2026 7:25:19 PM
 */

//===== SCRIPTS =====//
Script 1:
	GetDayOfWeek 0x4000
	CompareVarValue 0x4000 1
	JumpIf DIFFERENT Function#1
	ClearFlag 518
Jump Function#2

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	GetFirstAlivePokemonSlot 0x8002
	CheckRibbon 0x800C 0x8002 59
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#3
	CheckFlag 2748
	JumpIf EQUAL Function#4
	CompareVarValue 0x4094 7
	JumpIf EQUAL Function#5
	CheckFlag 215
	JumpIf EQUAL Function#6
	GetDayOfWeek 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#7
	GetCommonMessageArchive 0 0x800C
	MessageFromArchive 0x800C 3
Jump Function#8

Script 3:
	SetIconBoard 19 1 4 0x800C
	ShowBoard 3
	WaitBoard
	CloseBoard 0x800C
	CommonScript 2000
End

Script 4:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 0
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 5:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 6
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 6:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 3
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 7:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 9
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 8:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 18
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 9:
	MecScript
	LockAll
	Movement Overworld.5 Action#1
	WaitMovement
	GetPlayerPosition 0x8000 0x8001
	CompareVarValue 0x8000 252
	JumpIf DIFFERENT Function#9
	Movement Overworld.5 Action#2
Jump Function#10

Script 10:
	SetTextBoard 2 0
	ShowBoard 3
	WaitBoard
	BoardMessage 20 0x800C
	CommonScript 2000
End

//===== FUNCTIONS =====//
Function 1:
	SetFlag 518
End

Function 2:
End

Function 3:
	GetCommonMessageArchive 0 0x800C
	MessageFromArchive 0x800C 29
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 4:
	GetCommonMessageArchive 0 0x800C
	MessageFromArchive 0x800C 31
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 5:
	GetDayOfWeek 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#11
	GetCommonMessageArchive 0 0x800C
	MessageFromArchive 0x800C 3
Jump Function#8

Function 6:
	GetCommonMessageArchive 0 0x800C
	MessageFromArchive 0x800C 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 7:
	GetCommonMessageArchive 0 0x800C
	MessageFromArchive 0x800C 0
	SetVar 0x8004 244
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#12
	CommonScript 2033
	SetFlag 215
	IncrementVar 0x4094 1
	GetCommonMessageArchive 0 0x800C
	MessageFromArchive 0x800C 1
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 8:
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 9:
	CompareVarValue 0x8000 253
	JumpIf DIFFERENT Function#13
	Movement Overworld.5 Action#3
Jump Function#10

Function 10:
	WaitMovement
	CheckPokemonAlive 0x4002
	CompareVarValue 0x4002 0
	JumpIf EQUAL Function#14
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 56
	Movement Overworld.5 Action#4
	Movement Player Action#5
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	Message 15
	CloseMessage
	Movement Overworld.5 Action#1
	WaitMovement
	Message 16
	CloseMessage
	GetPlayerPosition 0x8000 0x8001
	CompareVarValue 0x8000 252
	JumpIf DIFFERENT Function#15
	Movement Overworld.5 Action#6
Jump Function#16

Function 11:
	GetCommonMessageArchive 0 0x800C
	MessageFromArchive 0x800C 28
	TextPartyPokemon 0 0x8002
	MessageFromArchive 0x800C 30
	GiveRibbon 0x8002 59
	PlaySound SEQ_ME_ITEM
	WaitSound
	SetFlag 2748
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 12:
	CommonScript 2009
	CloseMessage
	ReleaseAll
End

Function 13:
	CompareVarValue 0x8000 254
	JumpIf DIFFERENT Function#17
	Movement Overworld.5 Action#7
Jump Function#10

Function 14:
	Movement Overworld.5 Action#4
	Movement Player Action#5
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	Message 15
	CloseMessage
	Movement Overworld.5 Action#1
	WaitMovement
	Message 16
	CloseMessage
	GetPlayerPosition 0x8000 0x8001
	CompareVarValue 0x8000 252
	JumpIf DIFFERENT Function#15
	Movement Overworld.5 Action#6
Jump Function#16

Function 15:
	CompareVarValue 0x8000 253
	JumpIf DIFFERENT Function#18
	Movement Overworld.5 Action#8
Jump Function#16

Function 16:
	WaitMovement
	ReleaseAll
End

Function 17:
	Movement Overworld.5 Action#9
	WaitMovement
	CheckPokemonAlive 0x4002
	CompareVarValue 0x4002 0
	JumpIf EQUAL Function#14
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 56
	Movement Overworld.5 Action#4
	Movement Player Action#5
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	Message 15
	CloseMessage
	Movement Overworld.5 Action#1
	WaitMovement
	Message 16
	CloseMessage
	GetPlayerPosition 0x8000 0x8001
	CompareVarValue 0x8000 252
	JumpIf DIFFERENT Function#15
	Movement Overworld.5 Action#6
Jump Function#16

Function 18:
	CompareVarValue 0x8000 254
	JumpIf DIFFERENT Function#19
	Movement Overworld.5 Action#10
Jump Function#16

Function 19:
	Movement Overworld.5 Action#11
	WaitMovement
	ReleaseAll
End

//===== ACTIONS =====//
Action 1:
	EmoteExclamation 0x1
	Delay8 0x1
End

Action 2:
	WalkNorth4 0x5
	WalkOnSpotNorth8 0x2
End

Action 3:
	WalkNorth4 0x2
	WalkEast4 0x1
	WalkNorth4 0x3
	WalkOnSpotNorth8 0x2
End

Action 4:
	WalkNorth8 0x1
End

Action 5:
	LockDir 0x1
	WalkNorth8 0x1
	ReleaseDir 0x1
End

Action 6:
	WalkSouth4 0x6
	WalkOnSpotNorth8 0x1
End

Action 7:
	WalkNorth4 0x2
	WalkEast4 0x2
	WalkNorth4 0x3
	WalkOnSpotNorth8 0x2
End

Action 8:
	WalkSouth4 0x3
	WalkWest4 0x1
	WalkSouth4 0x3
	WalkOnSpotNorth8 0x1
End

Action 9:
	WalkNorth4 0x2
	WalkEast4 0x3
	WalkNorth4 0x3
	WalkOnSpotNorth8 0x2
End

Action 10:
	WalkSouth4 0x3
	WalkWest4 0x2
	WalkSouth4 0x3
	WalkOnSpotNorth8 0x1
End

Action 11:
	WalkSouth4 0x3
	WalkWest4 0x3
	WalkSouth4 0x3
	WalkOnSpotNorth8 0x1
End

