/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0007
 * Generated: 3/6/2026 7:25:18 PM
 */

//===== SCRIPTS =====//
Script 1:
	CommonScript 2031
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	Movement Overworld.0 Action#1
	Movement Player Action#2
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	TextPlayerName 0
	TextRivalName 1
	Message 0
	CloseMessage
	CheckStarter 0x800C
	CompareVarValue 0x800C 152
	JumpIf DIFFERENT Function#1
	TrainerBattle TRAINER_SILVER_286 TRAINER_NONE 0 0
Jump Function#2

//===== FUNCTIONS =====//
Function 1:
	CompareVarValue 0x800C 155
	JumpIf DIFFERENT Function#3
	TrainerBattle TRAINER_SILVER_287 TRAINER_NONE 0 0
Jump Function#2

Function 2:
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#4
	CommonScript 2070
	TextPlayerName 0
	TextRivalName 1
	Message 1
	CloseMessage
	Movement Overworld.0 Action#3
	WaitMovement
	RemoveOW Overworld.0
	CommonScript 2071
	SetFlag 604
	ClearFlag 736
	SetVar 0x40FC 1
	SetVar 0x40F5 1
	SetFlag 227
End

Function 3:
	TrainerBattle TRAINER_SILVER_285 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#4
	CommonScript 2070
	TextPlayerName 0
	TextRivalName 1
	Message 1
	CloseMessage
	Movement Overworld.0 Action#3
	WaitMovement
	RemoveOW Overworld.0
	CommonScript 2071
	SetFlag 604
	ClearFlag 736
	SetVar 0x40FC 1
	SetVar 0x40F5 1
	SetFlag 227
End

Function 4:
	LostBattle
End

//===== ACTIONS =====//
Action 1:
	EmoteExclamation 0x1
	WalkWest8 0x4
End

Action 2:
	Delay8 0x4
	WalkEast8 0x1
End

Action 3:
	WalkEast4 0x5
	WalkSouth4 0x9
End

