/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0010
 * Generated: 5/20/2026 9:55:26 PM
 */

//===== SCRIPTS =====//
Script 1:
	SetFlag 664
	GetDayOfWeek 0x4000
	CompareVarValue 0x4000 1
	JumpIf DIFFERENT Function#1
Jump Function#2

Script 2:
	SetTextBoard 2 0
	ShowBoard 3
	WaitBoard
	BoardMessage 1 0x800C
	CommonScript 2000
End

Script 3:
	MecScript
	LockAll
	ClearFlag 664
	GetPlayerPosition 0x8004 0x8005
	LockCamera 0x8004 0x8005
	Movement Camera Action#1
	Movement Overworld.0 Action#2
	Movement Overworld.1 Action#3
	Movement Overworld.2 Action#4
	Movement Overworld.3 Action#5
	Movement Overworld.4 Action#6
	Movement Overworld.5 Action#7
	WaitMovement
	PlayCry SPECIES_CLEFAIRY 0
	Movement Overworld.0 Action#8
	Movement Overworld.1 Action#9
	Movement Overworld.2 Action#10
	Movement Overworld.3 Action#11
	Movement Overworld.4 Action#12
	Movement Overworld.5 Action#13
	WaitMovement
	PlayCry SPECIES_CLEFAIRY 0
	Movement Overworld.0 Action#14
	Movement Overworld.1 Action#15
	Movement Overworld.2 Action#16
	Movement Overworld.3 Action#17
	Movement Overworld.4 Action#18
	Movement Overworld.5 Action#19
	WaitMovement
	PlayCry SPECIES_CLEFAIRY 0
	Movement Overworld.0 Action#20
	Movement Overworld.1 Action#21
	Movement Overworld.2 Action#22
	Movement Overworld.3 Action#23
	Movement Overworld.4 Action#24
	Movement Overworld.5 Action#25
	WaitMovement
	PlayCry SPECIES_CLEFAIRY 0
	Movement Overworld.0 Action#26
	Movement Overworld.1 Action#27
	Movement Overworld.2 Action#28
	Movement Overworld.3 Action#29
	Movement Overworld.4 Action#30
	Movement Overworld.5 Action#31
	WaitMovement
	PlayCry SPECIES_CLEFAIRY 0
	Movement Overworld.0 Action#32
	Movement Overworld.1 Action#33
	Movement Overworld.2 Action#34
	Movement Overworld.3 Action#35
	Movement Overworld.4 Action#36
	Movement Overworld.5 Action#37
	WaitMovement
	PlayCry SPECIES_CLEFAIRY 0
	Movement Overworld.0 Action#38
	Movement Overworld.1 Action#39
	Movement Overworld.2 Action#40
	Movement Overworld.3 Action#41
	Movement Overworld.4 Action#42
	Movement Overworld.5 Action#43
	WaitMovement
	AddOW Overworld.6
	Movement Overworld.3 Action#44
	Movement Overworld.5 Action#45
	WaitMovement
	RemoveOW Overworld.0
	RemoveOW Overworld.1
	RemoveOW Overworld.2
	RemoveOW Overworld.3
	RemoveOW Overworld.4
	RemoveOW Overworld.5
	SetFlag 622
	SetVar 0x40F6 1
	SetFlag 2741
	Movement Camera Action#46
	WaitMovement
	ReleaseCamera
	ReleaseAll
End

Script 4:
	SetVar 0x8008 81
	SetVar 0x8009 1
Jump Function#3

Script 5:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Message 5
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 6:
	GetDayOfWeek 0x4000
	CompareVarValue 0x4000 1
	JumpIf DIFFERENT Function#4
Jump Function#5

//===== FUNCTIONS =====//
Function 1:
	CompareVarValue 0x4000 2
	JumpIf DIFFERENT Function#6
Jump Function#7

Function 2:
	GetTimePeriod 0x4001
	CompareVarValue 0x4001 3
	JumpIf EQUAL Function#8
	SetVar 0x40F6 1
	SetFlag 622
End

Function 3:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	WaitFanfare SEQ_SE_CONFIRM
	SetVarFromVariable 0x8004 0x8008
	SetVarFromVariable 0x8005 0x8009
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#9
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#10
End

Function 4:
	CompareVarValue 0x4000 2
	JumpIf DIFFERENT Function#11
Jump Function#12

Function 5:
	GetTimePeriod 0x4001
	CompareVarValue 0x4001 3
	JumpIf EQUAL Function#13
Jump Function#14

Function 6:
	SetVar 0x40F6 1
	SetFlag 622
End

Function 7:
	GetTimePeriod 0x4001
	CompareVarValue 0x4001 4
	JumpIf EQUAL Function#8
	SetVar 0x40F6 1
	SetFlag 622
End

Function 8:
	SetVar 0x40F6 0
	ClearFlag 622
End

Function 9:
	CommonScript 2001
	RemoveOW 0x800D
	GiveItem 0x8004 0x8005 0x800C
	TextPlayerName 0
	TextItem 1 0x8004
	Message 2
	WaitSound
	TextPlayerName 0
	TextItem 1 0x8004
	GetItemPocket 0x8004 0x800C
	TextPocket 2 0x800C
	Message 3
	WaitButton
	SetVar 0x800C 1
	CloseMessage
	ReleaseAll
End

Function 10:
	TextItem 0 0x8004
	Message 4
	WaitButton
	SetVar 0x800C 0
Jump Function#15

Function 11:
Jump Function#14

Function 12:
	GetTimePeriod 0x4001
	CompareVarValue 0x4001 4
	JumpIf EQUAL Function#13
Jump Function#14

Function 13:
End

Function 14:
	CompareVarValue 0x40F6 1
	JumpIf EQUAL Function#13
	SetFlag 622
	RemoveOW Overworld.0
	RemoveOW Overworld.1
	RemoveOW Overworld.2
	RemoveOW Overworld.3
	RemoveOW Overworld.4
	RemoveOW Overworld.5
	SetVar 0x40F6 1
End

Function 15:
	CloseMessage
	ReleaseAll
End

//===== ACTIONS =====//
Action 1:
		WalkNorth6 0x2
End

Action 2:
		WalkOnSpotNorth8 0x5
		WalkOnSpotEast8 0x1
End

Action 3:
		WalkOnSpotWest8 0x5
		WalkOnSpotNorth8 0x1
End

Action 4:
		WalkOnSpotSouth8 0x5
		WalkOnSpotWest8 0x1
End

Action 5:
		WalkOnSpotEast8 0x5
		WalkOnSpotSouth8 0x1
End

Action 6:
		WalkOnSpotWest8 0x6
End

Action 7:
		WalkOnSpotEast8 0x6
End

Action 8:
		WalkOnSpotEast8 0x6
		WalkEast8 0x1
		JumpFarEast 0x1
End

Action 9:
		WalkOnSpotNorth8 0x6
		WalkNorth8 0x1
		JumpFarNorth 0x1
End

Action 10:
		WalkOnSpotWest8 0x6
		WalkWest8 0x1
		JumpFarWest 0x1
End

Action 11:
		WalkOnSpotSouth8 0x6
		WalkSouth8 0x1
		JumpFarSouth 0x1
End

Action 12:
		WalkOnSpotWest8 0x8
End

Action 13:
		WalkOnSpotEast8 0x8
End

Action 14:
		WalkOnSpotNorth8 0x1
		WalkOnSpotWest8 0x1
		WalkOnSpotSouth8 0x1
		WalkOnSpotEast8 0x1
		WalkNorth8 0x4
		JumpFarNorth 0x1
End

Action 15:
		WalkOnSpotWest8 0x1
		WalkOnSpotSouth8 0x1
		WalkOnSpotEast8 0x1
		WalkOnSpotNorth8 0x1
		WalkWest8 0x4
		JumpFarWest 0x1
End

Action 16:
		WalkOnSpotSouth8 0x1
		WalkOnSpotEast8 0x1
		WalkOnSpotNorth8 0x1
		WalkOnSpotWest8 0x1
		WalkSouth8 0x4
		JumpFarSouth 0x1
End

Action 17:
		WalkOnSpotEast8 0x1
		WalkOnSpotNorth8 0x1
		WalkOnSpotWest8 0x1
		WalkOnSpotSouth8 0x1
		WalkEast8 0x4
		JumpFarEast 0x1
End

Action 18:
		WalkOnSpotWest8 0x1
		WalkOnSpotSouth8 0x1
		WalkOnSpotEast8 0x1
		WalkOnSpotNorth8 0x1
		WalkOnSpotWest8 0x1
		WalkOnSpotSouth8 0x1
		WalkOnSpotEast8 0x1
		WalkOnSpotNorth8 0x1
End

Action 19:
		WalkOnSpotWest8 0x1
		WalkOnSpotSouth8 0x1
		WalkOnSpotEast8 0x1
		WalkOnSpotNorth8 0x1
		WalkOnSpotWest8 0x1
		WalkOnSpotSouth8 0x1
		WalkOnSpotEast8 0x1
		WalkOnSpotNorth8 0x1
End

Action 20:
		WalkOnSpotWest8 0x1
		WalkOnSpotSouth8 0x1
		WalkOnSpotEast8 0x1
		WalkOnSpotNorth8 0x1
		WalkWest8 0x4
		JumpFarWest 0x1
End

Action 21:
		WalkOnSpotSouth8 0x1
		WalkOnSpotEast8 0x1
		WalkOnSpotNorth8 0x1
		WalkOnSpotWest8 0x1
		WalkSouth8 0x4
		JumpFarSouth 0x1
End

Action 22:
		WalkOnSpotEast8 0x1
		WalkOnSpotNorth8 0x1
		WalkOnSpotWest8 0x1
		WalkOnSpotSouth8 0x1
		WalkEast8 0x4
		JumpFarEast 0x1
End

Action 23:
		WalkOnSpotNorth8 0x1
		WalkOnSpotWest8 0x1
		WalkOnSpotSouth8 0x1
		WalkOnSpotEast8 0x1
		WalkNorth8 0x4
		JumpFarNorth 0x1
End

Action 24:
		WalkOnSpotEast8 0x1
		WalkOnSpotNorth8 0x1
		WalkOnSpotWest8 0x1
		WalkOnSpotSouth8 0x1
		WalkOnSpotEast8 0x1
		WalkOnSpotNorth8 0x1
		WalkOnSpotWest8 0x1
		WalkOnSpotSouth8 0x1
End

Action 25:
		WalkOnSpotEast8 0x1
		WalkOnSpotNorth8 0x1
		WalkOnSpotWest8 0x1
		WalkOnSpotSouth8 0x1
		WalkOnSpotEast8 0x1
		WalkOnSpotNorth8 0x1
		WalkOnSpotWest8 0x1
		WalkOnSpotSouth8 0x1
End

Action 26:
		WalkOnSpotSouth8 0x1
		WalkOnSpotEast8 0x1
		WalkOnSpotNorth8 0x1
		WalkOnSpotWest8 0x1
		WalkSouth8 0x4
		JumpFarSouth 0x1
End

Action 27:
		WalkOnSpotEast8 0x1
		WalkOnSpotNorth8 0x1
		WalkOnSpotWest8 0x1
		WalkOnSpotSouth8 0x1
		WalkEast8 0x4
		JumpFarEast 0x1
End

Action 28:
		WalkOnSpotNorth8 0x1
		WalkOnSpotWest8 0x1
		WalkOnSpotSouth8 0x1
		WalkOnSpotEast8 0x1
		WalkNorth8 0x4
		JumpFarNorth 0x1
End

Action 29:
		WalkOnSpotWest8 0x1
		WalkOnSpotSouth8 0x1
		WalkOnSpotEast8 0x1
		WalkOnSpotNorth8 0x1
		WalkWest8 0x4
		JumpFarWest 0x1
End

Action 30:
		WalkOnSpotWest8 0x1
		WalkOnSpotSouth8 0x1
		WalkOnSpotEast8 0x1
		WalkOnSpotNorth8 0x1
		WalkOnSpotWest8 0x1
		WalkOnSpotSouth8 0x1
		WalkOnSpotEast8 0x1
		WalkOnSpotNorth8 0x1
End

Action 31:
		WalkOnSpotWest8 0x1
		WalkOnSpotSouth8 0x1
		WalkOnSpotEast8 0x1
		WalkOnSpotNorth8 0x1
		WalkOnSpotWest8 0x1
		WalkOnSpotSouth8 0x1
		WalkOnSpotEast8 0x1
		WalkOnSpotNorth8 0x1
End

Action 32:
		WalkOnSpotEast8 0x1
		WalkOnSpotNorth8 0x1
		WalkOnSpotWest8 0x1
		WalkOnSpotSouth8 0x1
		EmoteExclamation 0x1
End

Action 33:
		WalkOnSpotNorth8 0x1
		WalkOnSpotWest8 0x1
		WalkOnSpotSouth8 0x1
		WalkOnSpotEast8 0x1
		WalkNorth8 0x2
		JumpFarNorth 0x1
End

Action 34:
		WalkOnSpotWest8 0x1
		WalkOnSpotSouth8 0x1
		WalkOnSpotEast8 0x1
		WalkOnSpotNorth8 0x1
		WalkWest8 0x2
		JumpFarWest 0x1
End

Action 35:
		WalkOnSpotSouth8 0x1
		WalkOnSpotEast8 0x1
		WalkOnSpotNorth8 0x1
		WalkOnSpotWest8 0x1
		WalkSouth8 0x2
		JumpFarSouth 0x1
End

Action 36:
		WalkOnSpotEast8 0x1
		WalkOnSpotNorth8 0x1
		WalkOnSpotWest8 0x1
		WalkOnSpotSouth8 0x1
		WalkOnSpotEast8 0x1
		WalkOnSpotNorth8 0x1
		WalkOnSpotWest8 0x1
		WalkOnSpotSouth8 0x1
End

Action 37:
		WalkOnSpotEast8 0x1
		WalkOnSpotNorth8 0x1
		WalkOnSpotWest8 0x1
		WalkOnSpotSouth8 0x1
		WalkOnSpotEast8 0x1
		WalkOnSpotNorth8 0x1
		WalkOnSpotWest8 0x1
		WalkOnSpotSouth8 0x1
End

Action 38:
		JumpOnSpotNorth8 0x3
		WalkEast4 0x6
		WalkNorth4 0x3
		WalkEast4 0x3
		WalkSouth4 0x3
		WalkEast4 0x1
		JumpFarEast 0x1
		WalkEast4 0x2
End

Action 39:
		WalkOnSpotSouth8 0x1
		EmoteExclamation 0x1
		WalkSouth4 0x1
		WalkEast4 0x3
		WalkSouth4 0x2
		WalkEast4 0x1
		JumpFarEast 0x1
		WalkEast4 0x2
End

Action 40:
		WalkOnSpotSouth8 0x1
		EmoteExclamation 0x1
		WalkEast4 0x4
		WalkSouth4 0x3
		WalkEast4 0x3
		WalkSouth4 0x2
		WalkEast4 0x1
		JumpFarEast 0x1
		WalkEast4 0x2
End

Action 41:
		WalkOnSpotSouth8 0x1
		EmoteExclamation 0x1
		WalkSouth4 0x2
		WalkEast4 0x6
		WalkNorth4 0x3
		WalkEast4 0x2
		WalkSouth4 0x3
		JumpOnSpotWest8 0x2
End

Action 42:
		WalkOnSpotSouth8 0x1
		EmoteExclamation 0x1
		WalkSouth4 0x2
		WalkEast4 0x2
		JumpFarEast 0x1
		WalkEast4 0x3
End

Action 43:
		WalkOnSpotSouth8 0x1
		EmoteExclamation 0x1
		WalkEast8 0x2
		WalkSouth8 0x3
		WalkEast8 0x5
		JumpOnSpotEast8 0x2
End

Action 44:
		WalkOnSpotWest4 0x2
		WalkOnSpotNorth4 0x4
		JumpOnSpotNorth8 0x2
		WalkEast4 0x2
		JumpFarEast 0x1
		WalkEast4 0x3
End

Action 45:
		WalkEast8 0x1
		WalkNorth8 0x3
		WalkEast8 0x3
		WalkSouth8 0x3
		WalkEast8 0x1
		JumpFarEast 0x1
		WalkEast8 0x3
End

Action 46:
		Delay16 0x1
		WalkSouth6 0x2
End

