/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0011
 * Generated: 5/20/2026 9:55:26 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	PlayCry SPECIES_MEWTWO 0
	WaitCry
	SetFlag 164
	WildBattleSp SPECIES_MEWTWO 70 0
	ClearFlag 164
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#1
	GetBattleOutcome 0x4002
	CompareVarValue 0x4002 3
	JumpIf EQUAL Function#2
	CompareVarValue 0x4002 4
	CallIf EQUAL Function#3
	ReleaseAll
End

Script 2:
	CheckFlag 164
	JumpIf EQUAL Function#4
End

//===== FUNCTIONS =====//
Function 1:
	LostBattle
	ReleaseAll
End

Function 2:
	ReleaseAll
End

Function 3:
	SetFlag 363
Return

Function 4:
	SetFlag 773
	RemoveOW Overworld.14
	ClearFlag 164
End

//===== ACTIONS =====//
