/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0014
 * Generated: 3/6/2026 7:25:18 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	PlayCry SPECIES_ARTICUNO 0
	WaitCry
	SetFlag 164
	WildBattleSp SPECIES_ARTICUNO 50 0
	ClearFlag 164
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#1
	GetBattleOutcome 0x4002
	CompareVarValue 0x4002 3
	JumpIf EQUAL Function#2
	CompareVarValue 0x4002 4
	CallIf EQUAL Function#3
	ReleaseAll
End

Script 2:
	CheckFlag 164
	JumpIf EQUAL Function#4
End

//===== FUNCTIONS =====//
Function 1:
	LostBattle
	ReleaseAll
End

Function 2:
	ReleaseAll
End

Function 3:
	SetFlag 364
Return

Function 4:
	SetFlag 774
	RemoveOW Overworld.2
	ClearFlag 164
End

//===== ACTIONS =====//
