/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0024
 * Generated: 5/20/2026 9:55:26 PM
 */

//===== SCRIPTS =====//
Script 1:
	MecScript
	LockAll
	PlayCry SPECIES_RAIKOU 0
	Release Overworld.2
	ShakeOverworld Overworld.2 2 90 2 0
	Lock Overworld.2
	WaitCry
	PlayCry SPECIES_ENTEI 0
	Release Overworld.1
	ShakeOverworld Overworld.1 2 90 2 0
	Lock Overworld.1
	WaitCry
	PlayCry SPECIES_SUICUNE 0
	Release Overworld.0
	ShakeOverworld Overworld.0 2 90 2 0
	Lock Overworld.0
	WaitCry
	Movement Overworld.2 Action#1
	WaitMovement
	Movement Overworld.1 Action#2
	WaitMovement
	GetPlayerPosition 0x8004 0x8005
	CompareVarValue 0x8005 16
	JumpIf DIFFERENT Function#1
	Movement Overworld.0 Action#3
	WaitMovement
	PlayCry SPECIES_SUICUNE 0
	Movement Overworld.0 Action#4
	WaitCry
Jump Function#2

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	PlayCry SPECIES_SUICUNE 0
	WaitCry
	SetFlag 164
	WildBattleSp SPECIES_SUICUNE 40 0
	ClearFlag 164
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#3
	GetBattleOutcome 0x4002
	CompareVarValue 0x4002 3
	JumpIf EQUAL Function#4
	CompareVarValue 0x4002 4
	CallIf EQUAL Function#5
	ReleaseAll
End

Script 3:
	CheckFlag 164
	JumpIf EQUAL Function#6
End

//===== FUNCTIONS =====//
Function 1:
	Movement Overworld.0 Action#5
	WaitMovement
	PlayCry SPECIES_SUICUNE 0
	Movement Overworld.0 Action#6
	WaitCry
	WaitMovement
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	Movement Player Action#7
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	SetFlag 457
	SetFlag 458
	SetFlag 459
	RemoveOW Overworld.2
	RemoveOW Overworld.1
	RemoveOW Overworld.0
	AddRoamingPokemon 0
	AddRoamingPokemon 1
	WaitTime 15 0x800C
	ClearFlag 456
	PlayFanfare SEQ_SE_DP_KAIDAN2
	AddOW Overworld.3
	Lock Overworld.3
	WaitFanfare SEQ_SE_DP_KAIDAN2
	GetPlayerPosition 0x8004 0x8005
	CompareVarValue 0x8005 16
	JumpIf DIFFERENT Function#7
	Movement Overworld.3 Action#8
Jump Function#8

Function 2:
	WaitMovement
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	Movement Player Action#7
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	SetFlag 457
	SetFlag 458
	SetFlag 459
	RemoveOW Overworld.2
	RemoveOW Overworld.1
	RemoveOW Overworld.0
	AddRoamingPokemon 0
	AddRoamingPokemon 1
	WaitTime 15 0x800C
	ClearFlag 456
	PlayFanfare SEQ_SE_DP_KAIDAN2
	AddOW Overworld.3
	Lock Overworld.3
	WaitFanfare SEQ_SE_DP_KAIDAN2
	GetPlayerPosition 0x8004 0x8005
	CompareVarValue 0x8005 16
	JumpIf DIFFERENT Function#7
	Movement Overworld.3 Action#8
Jump Function#8

Function 3:
	LostBattle
	ReleaseAll
End

Function 4:
	ReleaseAll
End

Function 5:
	SetFlag 373
Return

Function 6:
	SetFlag 782
	RemoveOW Overworld.12
	ClearFlag 164
End

Function 7:
	Movement Overworld.3 Action#9
	Movement Player Action#10
	WaitMovement
	Message 0
	GetPlayerPosition 0x8004 0x8005
	CompareVarValue 0x8005 16
	JumpIf DIFFERENT Function#9
	Movement Overworld.3 Action#11
Jump Function#10

Function 8:
	WaitMovement
	Message 0
	GetPlayerPosition 0x8004 0x8005
	CompareVarValue 0x8005 16
	JumpIf DIFFERENT Function#9
	Movement Overworld.3 Action#11
Jump Function#10

Function 9:
	Movement Overworld.3 Action#12
	Movement Player Action#10
	WaitMovement
	TextPlayerName 0
	Message 1
	CloseMessage
	GetPlayerPosition 0x8004 0x8005
	CompareVarValue 0x8005 16
	JumpIf DIFFERENT Function#11
	Movement Overworld.3 Action#13
Jump Function#12

Function 10:
	WaitMovement
	TextPlayerName 0
	Message 1
	CloseMessage
	GetPlayerPosition 0x8004 0x8005
	CompareVarValue 0x8005 16
	JumpIf DIFFERENT Function#11
	Movement Overworld.3 Action#13
Jump Function#12

Function 11:
	Movement Overworld.3 Action#14
	WaitMovement
	PlayFanfare SEQ_SE_DP_KAIDAN2
	WaitTime 2 0x800C
	RemoveOW Overworld.3
	WaitFanfare SEQ_SE_DP_KAIDAN2
	SetFlag 456
	SetFlag 455
	SetFlag 460
	SetFlag 478
	SetFlag 479
	SetFlag 480
	ClearFlag 481
	SetVar 0x40A1 1
	SetVar 0x4076 1
	SetVar 0x4079 2
	SetFlag 583
	ClearFlag 584
	ReleaseAll
End

Function 12:
	WaitMovement
	PlayFanfare SEQ_SE_DP_KAIDAN2
	WaitTime 2 0x800C
	RemoveOW Overworld.3
	WaitFanfare SEQ_SE_DP_KAIDAN2
	SetFlag 456
	SetFlag 455
	SetFlag 460
	SetFlag 478
	SetFlag 479
	SetFlag 480
	ClearFlag 481
	SetVar 0x40A1 1
	SetVar 0x4076 1
	SetVar 0x4079 2
	SetFlag 583
	ClearFlag 584
	ReleaseAll
End

//===== ACTIONS =====//
Action 1:
		0069 0x1
		SetInvisible 0x1
End

Action 2:
		006A 0x1
		SetInvisible 0x1
End

Action 3:
		006B 0x1
		FaceEast 0x1
End

Action 4:
		Delay4 0x6
		006C 0x1
		SetInvisible 0x1
End

Action 5:
		006D 0x1
		FaceEast 0x1
End

Action 6:
		Delay4 0x6
		006E 0x1
		SetInvisible 0x1
End

Action 7:
		WalkWest8 0x1
		FaceSouth 0x1
End

Action 8:
		WalkSouth4 0x1
		WalkWest4 0x3
		FaceSouth 0x1
End

Action 9:
		WalkWest4 0x5
		WalkSouth4 0x1
		FaceSouth 0x1
End

Action 10:
		Delay4 0x6
		FaceWest 0x1
End

Action 11:
		WalkWest4 0x1
		FaceNorth 0x1
End

Action 12:
		FaceEast 0x1
End

Action 13:
		WalkEast4 0x4
		WalkNorth4 0x1
End

Action 14:
		WalkNorth4 0x1
		WalkEast4 0x5
		FaceNorth 0x1
End

