/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0025
 * Generated: 5/20/2026 9:55:26 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckFlag 270
	JumpIf EQUAL Function#1
	Message 2
	SetVar 0x8004 217
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#2
	CommonScript 2033
	SetFlag 270
	Message 4
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 2:
	SetTextBoard 2 0
	ShowBoard 3
	WaitBoard
	BoardMessage 22 0x800C
	CommonScript 2000
End

Script 3:
	SetTextBoard 3 0
	ShowBoard 3
	WaitBoard
	BoardMessage 23 0x800C
	CommonScript 2000
End

Script 4:
	SetTextBoard 3 0
	ShowBoard 3
	WaitBoard
	BoardMessage 24 0x800C
	CommonScript 2000
End

Script 5:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 0
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 6:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 1
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 7:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 5
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 8:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 6
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 9:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 9
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 10:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 7
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 11:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 8
	PlayCry SPECIES_PERSIAN 0
	WaitCry
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 12:
	CompareVarValue 0x40F7 1
	CallIf EQUAL Function#3
End

Script 13:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 45
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 14:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 48
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 15:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 51
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 16:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 54
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 17:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 57
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 18:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 60
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 19:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 63
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 20:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 66
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 21:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 69
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 22:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 72
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 23:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 42
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 24:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 0
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#4
	CheckAlbumPhoto 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#5
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 1
	CloseMessage
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	GetPlayerDirection 0x800C
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#6
	Movement Player Action#1
	Movement Overworld.26 Action#2
Jump Function#7

Script 25:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 0
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#4
	CheckAlbumPhoto 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#5
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 1
	CloseMessage
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	GetPlayerDirection 0x800C
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#8
	Movement Player Action#1
	Movement Overworld.27 Action#2
Jump Function#9

Script 26:
	CheckFlag 393
	JumpIf LESS Function#10
	ClearFlag 393
End

Script 27:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	GetDayOfWeek 0x4000
	CompareVarValue 0x4000 5
	JumpIf EQUAL Function#11
	TextPlayerName 0
	Message 84
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== FUNCTIONS =====//
Function 1:
	Message 4
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 2:
	CommonScript 2009
	CloseMessage
	ReleaseAll
End

Function 3:
	SetOWPosition Overworld.20 51 0 48 Down
	SetVar 0x4000 0
	SetVar 0x4001 10
	SetVar 0x4002 48
	OverlayManager 1 0
	CheckBugContestParticipant 0x4000 0x4004
	CompareVarValue 0x4004 1
	JumpIf DIFFERENT Function#12
	SetOWPosition 0x4001 0x4002 0 50 Up
	IncrementVar 0x4002 2
	IncrementVar 0x4000 1
	IncrementVar 0x4001 1
	CompareVarValue 0x4000 10
	JumpIf LESS Function#13
	OverlayManager 1 1
Return

Function 4:
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 5
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 5:
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 3
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 6:
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#14
	Movement Player Action#3
Jump Function#7

Function 7:
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	CheckPokemonAlive 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#15
	Movement Following Action#4
	WaitMovement
	SetFlag 393
	FadeScreen 6 1 0 0
	WaitFadeScreen
	TakePhoto 16
	LockAll
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ClearFlag 393
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 8:
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#16
	Movement Player Action#3
Jump Function#9

Function 9:
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	CheckPokemonAlive 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#17
	Movement Following Action#4
	WaitMovement
	SetFlag 393
	FadeScreen 6 1 0 0
	WaitFadeScreen
	TakePhoto 17
	LockAll
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ClearFlag 393
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 10:
	CompareVarValue 0x40F7 1
	JumpIf EQUAL Function#18
	GetDayOfWeek 0x4000
	CompareVarValue 0x4000 1
	JumpIf EQUAL Function#19
	CompareVarValue 0x4000 3
	JumpIf EQUAL Function#19
	CompareVarValue 0x4000 2
	JumpIf EQUAL Function#18
	CompareVarValue 0x4000 4
	JumpIf EQUAL Function#18
	CompareVarValue 0x4000 5
	JumpIf EQUAL Function#18
	SetFlag 638
	ClearFlag 639
Jump Function#20

Function 11:
	TextPlayerName 0
	Message 85
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#21
	CheckAlbumPhoto 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#22
	Message 86
	CloseMessage
	SetFlag 393
	FadeScreen 6 1 0 0
	WaitFadeScreen
	TakePhoto 7
	FacePlayer
	LockAll
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ClearFlag 393
	Message 87
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 12:
	IncrementVar 0x4000 1
	IncrementVar 0x4001 1
	CompareVarValue 0x4000 10
	JumpIf LESS Function#13
	OverlayManager 1 1
Return

Function 13:
	CheckBugContestParticipant 0x4000 0x4004
	CompareVarValue 0x4004 1
	JumpIf DIFFERENT Function#12
	SetOWPosition 0x4001 0x4002 0 50 Up
	IncrementVar 0x4002 2
	IncrementVar 0x4000 1
	IncrementVar 0x4001 1
	CompareVarValue 0x4000 10
	JumpIf LESS Function#13
	OverlayManager 1 1
Return

Function 14:
	CompareVarValue 0x800C 3
	JumpIf DIFFERENT Function#23
	Movement Player Action#5
	Movement Overworld.26 Action#2
Jump Function#7

Function 15:
	SetFlag 393
	FadeScreen 6 1 0 0
	WaitFadeScreen
	TakePhoto 16
	LockAll
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ClearFlag 393
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 16:
	CompareVarValue 0x800C 3
	JumpIf DIFFERENT Function#24
	Movement Player Action#6
	Movement Overworld.27 Action#2
Jump Function#9

Function 17:
	SetFlag 393
	FadeScreen 6 1 0 0
	WaitFadeScreen
	TakePhoto 17
	LockAll
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ClearFlag 393
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 18:
	SetFlag 638
	SetFlag 639
	ClearFlag 2454
	CheckFlag 2404
	JumpIf EQUAL Function#25
	SetFlag 648
End

Function 19:
	ClearFlag 638
	SetFlag 639
Jump Function#20

Function 20:
	CheckFlag 2404
	JumpIf EQUAL Function#25
	SetFlag 648
End

Function 21:
	Message 88
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 22:
	Message 89
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 23:
	Movement Player Action#7
	Movement Overworld.26 Action#2
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	CheckPokemonAlive 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#15
	Movement Following Action#4
	WaitMovement
	SetFlag 393
	FadeScreen 6 1 0 0
	WaitFadeScreen
	TakePhoto 16
	LockAll
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ClearFlag 393
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 24:
	Movement Player Action#7
	Movement Overworld.27 Action#2
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	CheckPokemonAlive 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#17
	Movement Following Action#4
	WaitMovement
	SetFlag 393
	FadeScreen 6 1 0 0
	WaitFadeScreen
	TakePhoto 17
	LockAll
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ClearFlag 393
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 25:
	CheckPokeGearRematch 34 0x4001
	CompareVarValue 0x4001 0
	JumpIf DIFFERENT Function#26
	GetDayOfWeek 0x4000
	CompareVarValue 0x4000 1
	JumpIf EQUAL Function#27
	CompareVarValue 0x4000 3
	JumpIf EQUAL Function#27
	CompareVarValue 0x4000 5
	JumpIf EQUAL Function#27
	SetFlag 648
End

Function 26:
	SetFlag 648
End

Function 27:
	ClearFlag 648
End

//===== ACTIONS =====//
Action 1:
		WalkEast8 0x1
		WalkNorth8 0x2
		WalkWest8 0x1
		WalkNorth8 0x3
		WalkOnSpotSouth8 0x1
End

Action 2:
		Delay8 0x1
		WalkOnSpotNorth8 0x1
End

Action 3:
		WalkNorth8 0x3
		WalkOnSpotSouth8 0x1
End

Action 4:
		WalkEast8 0x1
		WalkNorth8 0x1
		FaceSouth 0x1
End

Action 5:
		WalkNorth8 0x1
		WalkEast8 0x1
		WalkNorth8 0x3
		WalkOnSpotSouth8 0x1
End

Action 6:
		WalkSouth8 0x1
		WalkEast8 0x2
		WalkNorth8 0x2
		WalkWest8 0x1
		WalkNorth8 0x2
		WalkOnSpotSouth8 0x1
End

Action 7:
		WalkNorth8 0x1
		WalkWest8 0x1
		WalkNorth8 0x3
		WalkOnSpotSouth8 0x1
End

