/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0031
 * Generated: 3/6/2026 7:25:18 PM
 */

//===== SCRIPTS =====//
Script 1:
	SetFlag 439
	SetFlag 440
	CompareVarValue 0x4077 4
	JumpIf DIFFERENT Function#1
	ClearFlag 439
Jump Function#2

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 15
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 3:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 16
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 4:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CompareVarValue 0x4077 4
	JumpIf DIFFERENT Function#3
	Message 1
Jump Function#4

Script 5:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 0
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 6:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CompareVarValue 0x4077 4
	JumpIf DIFFERENT Function#5
	GetItemQuantity ITEM_BASEMENT_KEY 0x800C
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#6
	Message 3
Jump Function#7

Script 7:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	GetItemQuantity ITEM_CARD_KEY 0x800C
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#8
	Message 10
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 8:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckFlag 144
	JumpIf EQUAL Function#9
	Message 11
	CloseMessage
	GetItemQuantity ITEM_CARD_KEY 0x800C
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#8
	Message 13
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== FUNCTIONS =====//
Function 1:
	CompareVarValue 0x4077 5
	JumpIf DIFFERENT Function#2
	ClearFlag 440
End

Function 2:
End

Function 3:
	Message 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 4:
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 5:
Jump Function#10

Function 6:
	Message 4
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 7:
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 8:
	TextPlayerName 0
	Message 12
	CloseMessage
	Movement Overworld.7 Action#1
	Movement Overworld.8 Action#2
	WaitMovement
	ReleaseAll
	SetFlag 447
	RemoveOW Overworld.7
	RemoveOW Overworld.8
	SetFlag 144
End

Function 9:
	Message 14
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 10:
	CheckFlag 143
	JumpIf EQUAL Function#11
	Message 5
	SetVar 0x8004 338
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#12
	CommonScript 2033
	Message 7
	WaitButton
	CloseMessage
	ReleaseAll
	SetFlag 143
End

Function 11:
	Message 9
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 12:
	Message 8
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== ACTIONS =====//
Action 1:
	WalkWest8 0x2
End

Action 2:
	WalkEast8 0x2
End

