/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0038
 * Generated: 5/20/2026 9:55:26 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CountSeenUnown 0x800C
	CompareVarValue 0x800C 28
	JumpIf EQUAL Function#1
	CompareVarValue 0x40EC 1
	JumpIf GREATER/EQUAL Function#2
	CheckFlag 271
	JumpIf EQUAL Function#3
	Message 0
	SetFlag 271
	GetPlayerDirection 0x800C
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#4
	Movement Overworld.0 Action#1
Jump Function#5

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CompareVarValue 0x403E 8
	JumpIf EQUAL Function#6
	CompareVarValue 0x403E 7
	JumpIf EQUAL Function#7
	CompareVarValue 0x403E 4
	JumpIf GREATER/EQUAL Function#8
	CountSeenUnown 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#9
	CMD_770 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#10
	CompareVarValue 0x40EC 4
	JumpIf EQUAL Function#11
	CompareVarValue 0x40EC 3
	JumpIf EQUAL Function#12
	CompareVarValue 0x40EC 2
	JumpIf EQUAL Function#13
	CompareVarValue 0x40EC 1
	JumpIf EQUAL Function#14
	Message 4
Jump Function#15

Script 3:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CMD_770 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#16
	CountSeenUnown 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#17
	Message 19
Jump Function#15

Script 4:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CompareVarValue 0x403E 7
	JumpIf GREATER/EQUAL Function#18
	CMD_770 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#19
	Message 21
Jump Function#15

Script 5:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 24
Jump Function#15

Script 6:
	ClearFlag 271
End

//===== FUNCTIONS =====//
Function 1:
	Message 3
Jump Function#15

Function 2:
	Message 2
Jump Function#15

Function 3:
	Message 1
Jump Function#15

Function 4:
	Movement Overworld.0 Action#2
	WaitMovement
	Message 1
Jump Function#15

Function 5:
	WaitMovement
	Message 1
Jump Function#15

Function 6:
	Message 17
Jump Function#15

Function 7:
	CountSeenUnown 0x800C
	CompareVarValue 0x800C 28
	JumpIf EQUAL Function#20
Jump Function#21

Function 8:
	CompareVarValue 0x403E 6
	JumpIf EQUAL Function#21
	CompareVarValue 0x40F1 4
	JumpIf EQUAL Function#22
	CompareVarValue 0x403E 5
	JumpIf EQUAL Function#21
	CompareVarValue 0x40F1 1
	JumpIf GREATER/EQUAL Function#23
Jump Function#21

Function 9:
	CompareVarValue 0x40EC 1
	JumpIf EQUAL Function#24
	Message 4
Jump Function#15

Function 10:
	CompareVarValue 0x40EC 0
	JumpIf EQUAL Function#25
	CompareVarValue 0x40EC 1
	JumpIf EQUAL Function#14
	CompareVarValue 0x403E 4
	JumpIf EQUAL Function#21
	CompareVarValue 0x403E 3
	JumpIf EQUAL Function#26
	CompareVarValue 0x403E 2
	JumpIf EQUAL Function#27
	CompareVarValue 0x403E 1
	JumpIf EQUAL Function#28
Jump Function#29

Function 11:
	CompareVarValue 0x403E 3
	JumpIf EQUAL Function#21
	CompareVarValue 0x403E 2
	JumpIf EQUAL Function#27
	CompareVarValue 0x403E 1
	JumpIf EQUAL Function#28
Jump Function#29

Function 12:
	CompareVarValue 0x403E 2
	JumpIf EQUAL Function#21
	CompareVarValue 0x403E 1
	JumpIf EQUAL Function#28
Jump Function#29

Function 13:
	CompareVarValue 0x403E 1
	JumpIf EQUAL Function#21
Jump Function#29

Function 14:
	Message 5
Jump Function#15

Function 15:
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 16:
	Message 20
Jump Function#15

Function 17:
	Message 18
Jump Function#15

Function 18:
	Message 23
Jump Function#15

Function 19:
	Message 22
Jump Function#15

Function 20:
	Message 14
Jump Function#30

Function 21:
	Message 15
Jump Function#15

Function 22:
	CompareVarValue 0x403E 5
	JumpIf EQUAL Function#31
Jump Function#23

Function 23:
	Message 12
Jump Function#30

Function 24:
	Message 9
Jump Function#15

Function 25:
	Message 4
Jump Function#15

Function 26:
	Message 10
	Message 11
Jump Function#30

Function 27:
	Message 8
Jump Function#30

Function 28:
	Message 7
Jump Function#30

Function 29:
	Message 6
Jump Function#30

Function 30:
	TextPlayerName 0
	Message 16
	PlaySound SEQ_ME_LVUP
	WaitSound
	IncrementVar 0x403E 1
Jump Function#15

Function 31:
	Message 13
Jump Function#30

//===== ACTIONS =====//
Action 1:
		FaceWest 0x1
		FaceNorth 0x1
		FaceEast 0x1
		FaceSouth 0x1
		FaceWest 0x1
		FaceNorth 0x1
		FaceEast 0x1
		FaceSouth 0x1
		FaceWest 0x1
		FaceNorth 0x1
		FaceEast 0x1
		FaceSouth 0x1
		FaceWest 0x1
		FaceNorth 0x1
		FaceEast 0x1
		FaceSouth 0x1
		EmoteExclamation 0x1
End

Action 2:
		FaceSouth 0x1
		FaceWest 0x1
		FaceNorth 0x1
		FaceEast 0x1
		FaceSouth 0x1
		FaceWest 0x1
		FaceNorth 0x1
		FaceEast 0x1
		FaceSouth 0x1
		FaceWest 0x1
		FaceNorth 0x1
		FaceEast 0x1
		FaceSouth 0x1
		FaceWest 0x1
		FaceNorth 0x1
		FaceEast 0x1
		EmoteExclamation 0x1
End

