/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0053
 * Generated: 3/6/2026 7:25:18 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Message 0
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 2:
	MecScript
	LockAll
	Movement Overworld.0 Action#1
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	Movement Player Action#2
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	Message 1
	CloseMessage
	Movement Overworld.0 Action#3
	WaitMovement
	Message 2
	CloseMessage
	FadeOutMusic 0 30
	PlayFanfare SEQ_SE_GS_ZENIGAME_JOURO
	FadeScreen 6 6 0 0
	WaitFadeScreen
	WaitTime 1 0x800C
	FadeScreen 6 6 1 0
	WaitFadeScreen
	StopFanfare SEQ_SE_GS_ZENIGAME_JOURO
	Movement Overworld.0 Action#4
	WaitMovement
	Message 3
	CloseMessage
	PlayFanfare SEQ_SE_GS_ZENIGAME_JOURO
	FadeScreen 6 6 0 0
	WaitFadeScreen
	WaitTime 1 0x800C
	FadeScreen 6 6 1 0
	WaitFadeScreen
	StopFanfare SEQ_SE_GS_ZENIGAME_JOURO
	SetVar 0x40FB 3
	SetFlag 742
	SetFlag 743
	PlayFanfare SEQ_SE_DP_KAIDAN2
	FadeScreen 6 1 0 0
	WaitFadeScreen
	Warp 522 0 16 24 Down
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Script 3:
	MecScript
	LockAll
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	Movement Overworld.0 Action#5
	Movement Player Action#6
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	Movement Player Action#7
	WaitMovement
	Message 4
	CloseMessage
	Movement Overworld.0 Action#8
	WaitMovement
	Message 5
	CloseMessage
	Movement Overworld.0 Action#9
	WaitMovement
	RemoveOW Overworld.0
	SetFlag 743
	SetVar 0x40FB 10
	ReleaseAll
End

Script 4:
	MecScript
	LockAll
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	Movement Player Action#10
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	PlayFanfare SEQ_SE_GS_ZENIGAME_JOURO
	FadeScreen 6 6 0 0
	WaitFadeScreen
	WaitTime 1 0x800C
	FadeScreen 6 6 1 0
	WaitFadeScreen
	StopFanfare SEQ_SE_GS_ZENIGAME_JOURO
	Movement Player Action#11
	WaitMovement
	PlayFanfare SEQ_SE_GS_ZENIGAME_JOURO
	FadeScreen 6 6 0 0
	WaitFadeScreen
	WaitTime 1 0x800C
	FadeScreen 6 6 1 0
	WaitFadeScreen
	StopFanfare SEQ_SE_GS_ZENIGAME_JOURO
	SetVar 0x40FB 12
	SetVar 0x4104 1
	SetFlag 732
	SetFlag 733
	SetFlag 731
	PlayFanfare SEQ_SE_DP_KAIDAN2
	FadeScreen 6 1 0 0
	WaitFadeScreen
	Warp 522 0 16 24 Down
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Script 5:
	CMD_490 0x4004
	CompareVarValue 0x40FB 10
	JumpIf EQUAL Function#1
Jump Function#2

Script 6:
	MecScript
	LockAll
	PlayFanfare SEQ_SE_GS_RAKKA01
	Movement Player Action#12
	UnvanishOverworld Player
	WaitMovement
	ShakeCamera 0 1 1 8
	PlayFanfare SEQ_SE_DP_SUTYA2
	SetVar 0x40CE 0
	ReleaseAll
End

Script 7:
	CompareVarValue 0x40CE 1
	JumpIf DIFFERENT Function#3
	VanishOverworld Player
End

//===== FUNCTIONS =====//
Function 1:
	GetFirstAlivePokemonSlot 0x4005
	CompareVarValue 0x4102 1
	JumpIf EQUAL Function#4
	CompareVarValue 0x4102 2
	JumpIf EQUAL Function#5
Jump Function#2

Function 2:
End

Function 3:
End

Function 4:
	FollowingPokemonIsEventTrigger 1 0x4005 0x4007
	CompareVarValue 0x4007 1
	CallIf EQUAL Function#6
	CMD_490 0x4005
	CMD_490 0x4007
End

Function 5:
	FollowingPokemonIsEventTrigger 2 0x4005 0x4006
	CompareVarValue 0x4006 1
	CallIf EQUAL Function#6
	CMD_490 0x4005
	CMD_490 0x4006
End

Function 6:
	SetVar 0x40FB 11
Return

//===== ACTIONS =====//
Action 1:
	WalkWest8 0x4
	WalkOnSpotEast8 0x1
End

Action 2:
	WalkWest8 0x4
End

Action 3:
	EmoteExclamation 0x1
	Delay8 0x1
	WalkNorth4 0x3
	WalkOnSpotNorth8 0x1
	WalkWest4 0x2
	WalkOnSpotNorth8 0x1
	LockDir 0x1
	WalkWest16 0x1
	ReleaseDir 0x1
End

Action 4:
	WalkOnSpotEast8 0x1
	Delay8 0x1
	WalkOnSpotWest8 0x1
	Delay8 0x1
	WalkOnSpotSouth8 0x1
End

Action 5:
	Delay8 0x1
	WalkOnSpotWest8 0x1
	EmoteExclamation 0x1
	Delay8 0x1
	WalkWest4 0x3
End

Action 6:
	WalkEast8 0x1
End

Action 7:
	WalkOnSpotEast8 0x1
End

Action 8:
	WalkOnSpotWest8 0x1
End

Action 9:
	WalkEast8 0xA
End

Action 10:
	WalkWest8 0x1
	WalkSouth8 0x1
End

Action 11:
	WalkOnSpotEast8 0x1
	Delay8 0x1
	WalkOnSpotWest8 0x1
	Delay8 0x1
	WalkOnSpotSouth8 0x1
End

Action 12:
	TeleportDown 0x1
End

