/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0054
 * Generated: 5/20/2026 9:55:27 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Message 0
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 2:
End

Script 3:
	CheckFlag 393
	JumpIf LESS Function#1
	ClearFlag 393
End

Script 4:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 0
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#2
	CheckAlbumPhoto 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#3
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 1
	CloseMessage
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	GetPlayerDirection 0x800C
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#4
	Movement Player Action#1
	Movement Overworld.0 Action#2
Jump Function#5

//===== FUNCTIONS =====//
Function 1:
	CheckBadge 2 0x4000
	CompareVarValue 0x4000 0
	JumpIf EQUAL Function#6
	GetDayOfWeek 0x4001
	CompareVarValue 0x4001 1
	JumpIf EQUAL Function#7
	CompareVarValue 0x4001 2
	JumpIf EQUAL Function#7
	CompareVarValue 0x4001 4
	JumpIf EQUAL Function#7
	SetFlag 638
End

Function 2:
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 5
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 3:
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 3
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 4:
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#8
	Movement Player Action#3
Jump Function#5

Function 5:
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	Movement Following Action#4
	WaitMovement
	SetFlag 393
	FadeScreen 6 1 0 0
	WaitFadeScreen
	TakePhoto 4
	LockAll
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ClearFlag 393
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 6:
	SetFlag 638
End

Function 7:
	ClearFlag 638
End

Function 8:
	CompareVarValue 0x800C 3
	JumpIf DIFFERENT Function#9
	Movement Player Action#5
	Movement Overworld.0 Action#2
Jump Function#5

Function 9:
	Movement Player Action#6
	Movement Overworld.0 Action#2
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	Movement Following Action#4
	WaitMovement
	SetFlag 393
	FadeScreen 6 1 0 0
	WaitFadeScreen
	TakePhoto 4
	LockAll
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ClearFlag 393
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 2
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== ACTIONS =====//
Action 1:
		WalkEast8 0x1
		WalkNorth8 0x2
		WalkWest8 0x1
		WalkNorth8 0x3
		WalkOnSpotSouth8 0x1
End

Action 2:
		Delay8 0x1
		WalkOnSpotNorth8 0x1
End

Action 3:
		WalkNorth8 0x3
		WalkOnSpotSouth8 0x1
End

Action 4:
		WalkEast8 0x1
		WalkNorth8 0x1
		FaceSouth 0x1
End

Action 5:
		WalkNorth8 0x1
		WalkEast8 0x1
		WalkNorth8 0x3
		WalkOnSpotSouth8 0x1
End

Action 6:
		WalkNorth8 0x1
		WalkWest8 0x1
		WalkNorth8 0x3
		WalkOnSpotSouth8 0x1
End

