/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0061
 * Generated: 3/6/2026 7:25:18 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckFlag 122
	JumpIf EQUAL Function#1
	Message 0
	WaitAB
	CloseMessage
	SetVar 0x8004 221
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#2
	CommonScript 2033
	SetFlag 122
Jump Function#1

//===== FUNCTIONS =====//
Function 1:
	Message 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 2:
	CommonScript 2009
	CloseMessage
	ReleaseAll
End

//===== ACTIONS =====//
