/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0088
 * Generated: 3/6/2026 7:25:18 PM
 */

//===== SCRIPTS =====//
Script 1:
End

Script 2:
	VanishOverworld Overworld.1
	VanishOverworld Overworld.2
	VanishOverworld Overworld.3
	CompareVarValue 0x40AC 9
	JumpIf GREATER/EQUAL Function#1
	CompareVarValue 0x40A8 2
	JumpIf GREATER/EQUAL Function#2
	CompareVarValue 0x40A8 1
	JumpIf EQUAL Function#3
End

Script 3:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CompareVarValue 0x40A8 2
	JumpIf GREATER/EQUAL Function#4
	Message 0
	FreezeMessage
	SetVar 0x8004 28
	CommonScript 2052
	ReleaseAll
End

Script 4:
	CompareVarValue 0x40A8 2
	JumpIf GREATER/EQUAL Function#5
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 5:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	SetFlag 369
	Message 10
	FreezeMessage
	SetVar 0x8004 29
	CommonScript 2052
	ClearFlag 369
	ReleaseAll
End

Script 6:
End

Script 7:
	StopMusic 0
	PlayMusic SEQ_GS_D_AJITO
	MecScript
	LockAll
	Movement Player Action#1
	WaitMovement
	Message 4
	CloseMessage
	PlayFanfare SEQ_SE_GS_ZUTUKI
	Movement Overworld.8 Action#2
	WaitFanfare SEQ_SE_GS_PRESSHIT
	Movement Overworld.4 Action#3
	WaitMovement
	Movement Overworld.7 Action#4
	Movement Overworld.8 Action#5
	WaitMovement
	TextPlayerName 0
	GenderMessage 5 6
	CloseMessage
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	Movement Overworld.7 Action#6
	Movement Player Action#7
	Movement Overworld.8 Action#8
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	Movement Overworld.5 Action#9
	WaitMovement
	Movement Overworld.7 Action#10
	WaitMovement
	Message 7
	CloseMessage
	Movement Overworld.5 Action#11
	WaitMovement
	PlayFanfare SEQ_SE_DP_UG_023
	Movement Overworld.0 Action#12
	Movement Overworld.1 Action#12
	Movement Overworld.2 Action#12
	Movement Overworld.3 Action#12
	WaitMovement
	TextPlayerName 0
	GenderMessage 8 9
	CloseMessage
	Movement Overworld.7 Action#13
	WaitMovement
	RemoveOW Overworld.7
	Movement Overworld.8 Action#14
	WaitMovement
	RemoveOW Overworld.8
	SetFlag 504
	SetVar 0x40A8 2
	ReleaseAll
End

Script 8:
End

Script 9:
	CompareVarValue 0x40AC 3
	JumpIf EQUAL Function#6
	CompareVarValue 0x40AC 8
	JumpIf EQUAL Function#7
End

Script 10:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CompareVarValue 0x40AC 10
	JumpIf GREATER/EQUAL Function#8
	Message 15
Jump Function#9

//===== FUNCTIONS =====//
Function 1:
	SetOWPosition Overworld.0 9 0 3 Down
	SetOWPosition Overworld.1 8 0 3 Down
	SetOWPosition Overworld.2 9 0 4 Down
	SetOWPosition Overworld.3 8 0 4 Down
End

Function 2:
	SetOWPosition Overworld.4 10 0 7 Left
	SetOWPosition Overworld.5 4 0 3 Down
	SetOWPosition Overworld.0 9 0 3 Down
	SetOWPosition Overworld.1 8 0 3 Down
	SetOWPosition Overworld.2 9 0 4 Down
	SetOWPosition Overworld.3 8 0 4 Down
End

Function 3:
	SetOWPosition Overworld.4 8 0 7 Left
End

Function 4:
	Message 1
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 5:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 3
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 6:
	ClearFlag 640
	SetFlag 500
End

Function 7:
	SetFlag 485
	SetFlag 499
End

Function 8:
	CompareVarValue 0x4077 2
	JumpIf DIFFERENT Function#10
	Message 14
Jump Function#11

Function 9:
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 10:
	CompareVarValue 0x4077 3
	JumpIf DIFFERENT Function#12
	Message 14
Jump Function#11

Function 11:
Jump Function#9

Function 12:
	CompareVarValue 0x4077 4
	JumpIf DIFFERENT Function#13
	Message 14
Jump Function#11

Function 13:
Jump Function#14

Function 14:
	GetHour 0x4000
	CompareVarValue 0x4000 0
	JumpIf DIFFERENT Function#15
	Message 11
Jump Function#9

Function 15:
	CompareVarValue 0x4000 1
	JumpIf DIFFERENT Function#16
	Message 12
Jump Function#9

Function 16:
	CompareVarValue 0x4000 3
	JumpIf DIFFERENT Function#17
	Message 11
Jump Function#9

Function 17:
	CompareVarValue 0x4000 4
	JumpIf DIFFERENT Function#18
	Message 12
Jump Function#9

Function 18:
	CompareVarValue 0x4000 6
	JumpIf DIFFERENT Function#19
	Message 11
Jump Function#9

Function 19:
	CompareVarValue 0x4000 7
	JumpIf DIFFERENT Function#20
	Message 12
Jump Function#9

Function 20:
	CompareVarValue 0x4000 9
	JumpIf DIFFERENT Function#21
	Message 11
Jump Function#9

Function 21:
	CompareVarValue 0x4000 10
	JumpIf DIFFERENT Function#22
	Message 12
Jump Function#9

Function 22:
	CompareVarValue 0x4000 12
	JumpIf DIFFERENT Function#23
	Message 11
Jump Function#9

Function 23:
	CompareVarValue 0x4000 13
	JumpIf DIFFERENT Function#24
	Message 12
Jump Function#9

Function 24:
	CompareVarValue 0x4000 15
	JumpIf DIFFERENT Function#25
	Message 11
Jump Function#9

Function 25:
	CompareVarValue 0x4000 16
	JumpIf DIFFERENT Function#26
	Message 12
Jump Function#9

Function 26:
	CompareVarValue 0x4000 18
	JumpIf DIFFERENT Function#27
	Message 11
Jump Function#9

Function 27:
	CompareVarValue 0x4000 19
	JumpIf DIFFERENT Function#28
	Message 12
Jump Function#9

Function 28:
	CompareVarValue 0x4000 21
	JumpIf DIFFERENT Function#29
	Message 11
Jump Function#9

Function 29:
	CompareVarValue 0x4000 22
	JumpIf DIFFERENT Function#30
	Message 12
Jump Function#9

Function 30:
	Message 13
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== ACTIONS =====//
Action 1:
	EmoteExclamation 0x1
End

Action 2:
	WalkEast2 0x2
	LockDir 0x1
	WalkWest2 0x2
	ReleaseDir 0x1
End

Action 3:
	LockDir 0x1
	WalkEast2 0x2
	ReleaseDir 0x1
End

Action 4:
	Delay8 0x3
	FaceSouth 0x2
	WalkSouth8 0x1
	Delay8 0x5
End

Action 5:
	Delay8 0x3
	FaceSouth 0x2
End

Action 6:
	FaceNorth 0x2
	WalkNorth8 0x4
	FaceEast 0x2
	WalkEast8 0x1
	FaceNorth 0x2
	Delay8 0x5
End

Action 7:
	Delay8 0x1
	WalkNorth8 0x4
End

Action 8:
	Delay8 0x3
	FaceNorth 0x2
	WalkNorth8 0x2
End

Action 9:
	EmoteExclamation 0x1
	Delay8 0x1
	LockDir 0x1
	WalkWest2 0x2
	ReleaseDir 0x1
End

Action 10:
	WalkNorth8 0x1
	FaceEast 0x2
	Delay8 0x2
End

Action 11:
	FaceEast 0x2
	EmoteExclamation 0x1
End

Action 12:
	WalkEast8 0x1
End

Action 13:
	WalkEast8 0x1
End

Action 14:
	Delay8 0x3
	WalkNorth8 0x2
	FaceEast 0x2
	WalkEast8 0x1
End

