/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0089
 * Generated: 3/6/2026 7:25:18 PM
 */

//===== SCRIPTS =====//
Script 1:
	MecScript
	LockAll
	Movement Player Action#1
	WaitMovement
	Movement Overworld.0 Action#2
	WaitMovement
	PlayFanfare SEQ_SE_GS_AJITO_SIREN
	CMD_709
	StopFanfare SEQ_SE_GS_AJITO_SIREN
	GetPlayerPosition 0x4000 0x4001
	CompareVarValue 0x4001 4
	JumpIf DIFFERENT Function#1
	IncrementVar 0x4001 1
Jump Function#2

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	CompareVarValue 0x40AD 0
	JumpIf DIFFERENT Function#3
	Message 2
Jump Function#4

Script 3:
End

Script 4:
End

Script 5:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CompareVarValue 0x40AC 9
	JumpIf GREATER/EQUAL Function#5
	CheckFlag 214
	JumpIf EQUAL Function#6
	Message 5
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#7
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#8
	PlayFanfare SEQ_SE_DP_DENSI01
	Message 7
	CloseMessage
	SetFlag 214
	CompareVarValue 0x40AD 2
	JumpIf GREATER/EQUAL Function#9
	SetVar 0x40AD 1
	Movement Overworld.0 Action#3
	CompareVarValue 0x40AE 2
	JumpIf GREATER/EQUAL Function#10
	SetVar 0x40AE 1
	Movement Overworld.2 Action#3
	CompareVarValue 0x40AF 2
	JumpIf GREATER/EQUAL Function#11
	SetVar 0x40AF 1
	Movement Overworld.3 Action#3
	CompareVarValue 0x40B0 2
	JumpIf GREATER/EQUAL Function#12
	SetVar 0x40B0 1
	Movement Overworld.4 Action#3
	CompareVarValue 0x40B1 2
	JumpIf GREATER/EQUAL Function#13
	SetVar 0x40B1 1
	Movement Overworld.5 Action#3
	WaitMovement
	Message 9
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 6:
	MecScript
	LockAll
	Movement Player Action#1
	WaitMovement
	Movement Overworld.2 Action#2
	WaitMovement
	PlayFanfare SEQ_SE_GS_AJITO_SIREN
	CMD_709
	GetPlayerPosition 0x4000 0x4001
	CompareVarValue 0x4001 4
	JumpIf DIFFERENT Function#14
	IncrementVar 0x4001 1
Jump Function#15

Script 7:
	MecScript
	LockAll
	Movement Player Action#1
	WaitMovement
	Movement Overworld.3 Action#2
	WaitMovement
	PlayFanfare SEQ_SE_GS_AJITO_SIREN
	CMD_709
	GetPlayerPosition 0x4000 0x4001
	CompareVarValue 0x4001 11
	JumpIf DIFFERENT Function#16
	IncrementVar 0x4001 1
Jump Function#17

Script 8:
	MecScript
	LockAll
	Movement Player Action#1
	WaitMovement
	Movement Overworld.4 Action#2
	WaitMovement
	PlayFanfare SEQ_SE_GS_AJITO_SIREN
	CMD_709
	GetPlayerPosition 0x4000 0x4001
	CompareVarValue 0x4001 29
	JumpIf DIFFERENT Function#18
	IncrementVar 0x4001 1
Jump Function#19

Script 9:
	MecScript
	LockAll
	Movement Player Action#1
	WaitMovement
	Movement Overworld.5 Action#2
	WaitMovement
	PlayFanfare SEQ_SE_GS_AJITO_SIREN
	CMD_709
	GetPlayerPosition 0x4000 0x4001
	CompareVarValue 0x4001 29
	JumpIf DIFFERENT Function#20
	IncrementVar 0x4001 1
Jump Function#21

Script 10:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	CompareVarValue 0x40AE 0
	JumpIf DIFFERENT Function#22
	Message 2
Jump Function#4

Script 11:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	CompareVarValue 0x40AF 0
	JumpIf DIFFERENT Function#23
	Message 2
Jump Function#4

Script 12:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	CompareVarValue 0x40B0 0
	JumpIf DIFFERENT Function#24
	Message 2
Jump Function#4

Script 13:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	CompareVarValue 0x40B1 0
	JumpIf DIFFERENT Function#25
	Message 2
Jump Function#4

Script 14:
	MecScript
	LockAll
	FloorTrapAnimation 1
	PlayFanfare SEQ_SE_GS_DOKU_TRAP
	WildBattle SPECIES_KOFFING 21
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#26
	SetVar 0x40B2 1
	ReleaseAll
End

Script 15:
	MecScript
	LockAll
	FloorTrapAnimation 0
	PlayFanfare SEQ_SE_GS_DENKI_TRAP
	WildBattle SPECIES_VOLTORB 23
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#26
	SetVar 0x40B3 1
	ReleaseAll
End

Script 16:
	MecScript
	LockAll
	FloorTrapAnimation 2
	PlayFanfare SEQ_SE_GS_IWA_TRAP
	WildBattle SPECIES_GEODUDE 21
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#26
	SetVar 0x40B4 1
	ReleaseAll
End

Script 17:
	MecScript
	LockAll
	FloorTrapAnimation 0
	PlayFanfare SEQ_SE_GS_DENKI_TRAP
	WildBattle SPECIES_VOLTORB 23
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#26
	SetVar 0x40B5 1
	ReleaseAll
End

Script 18:
	MecScript
	LockAll
	FloorTrapAnimation 2
	PlayFanfare SEQ_SE_GS_IWA_TRAP
	WildBattle SPECIES_GEODUDE 21
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#26
	SetVar 0x40B6 1
	ReleaseAll
End

Script 19:
	MecScript
	LockAll
	FloorTrapAnimation 0
	PlayFanfare SEQ_SE_GS_DENKI_TRAP
	WildBattle SPECIES_VOLTORB 23
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#26
	SetVar 0x40B7 1
	ReleaseAll
End

Script 20:
	MecScript
	LockAll
	FloorTrapAnimation 0
	PlayFanfare SEQ_SE_GS_DENKI_TRAP
	WildBattle SPECIES_VOLTORB 23
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#26
	SetVar 0x40B8 1
	ReleaseAll
End

Script 21:
	MecScript
	LockAll
	FloorTrapAnimation 1
	PlayFanfare SEQ_SE_GS_DOKU_TRAP
	WildBattle SPECIES_KOFFING 21
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#26
	SetVar 0x40B9 1
	ReleaseAll
End

Script 22:
	MecScript
	LockAll
	FloorTrapAnimation 1
	PlayFanfare SEQ_SE_GS_DOKU_TRAP
	WildBattle SPECIES_KOFFING 21
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#26
	SetVar 0x40BA 1
	ReleaseAll
End

Script 23:
	MecScript
	LockAll
	FloorTrapAnimation 2
	PlayFanfare SEQ_SE_GS_IWA_TRAP
	WildBattle SPECIES_GEODUDE 21
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#26
	SetVar 0x40BB 1
	ReleaseAll
End

Script 24:
	MecScript
	LockAll
	FloorTrapAnimation 2
	PlayFanfare SEQ_SE_GS_IWA_TRAP
	WildBattle SPECIES_GEODUDE 21
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#26
	SetVar 0x40BC 1
	ReleaseAll
End

Script 25:
	MecScript
	LockAll
	FloorTrapAnimation 1
	PlayFanfare SEQ_SE_GS_DOKU_TRAP
	WildBattle SPECIES_KOFFING 21
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#26
	SetVar 0x40BD 1
	ReleaseAll
End

Script 26:
	MecScript
	LockAll
	FloorTrapAnimation 0
	PlayFanfare SEQ_SE_GS_DENKI_TRAP
	WildBattle SPECIES_VOLTORB 23
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#26
	SetVar 0x40BE 1
	ReleaseAll
End

Script 27:
	MecScript
	LockAll
	FloorTrapAnimation 0
	PlayFanfare SEQ_SE_GS_DENKI_TRAP
	WildBattle SPECIES_VOLTORB 23
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#26
	SetVar 0x40BF 1
	ReleaseAll
End

Script 28:
	MecScript
	LockAll
	FloorTrapAnimation 1
	PlayFanfare SEQ_SE_GS_DOKU_TRAP
	WildBattle SPECIES_KOFFING 21
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#26
	SetVar 0x40C0 1
	ReleaseAll
End

Script 29:
	MecScript
	LockAll
	FloorTrapAnimation 2
	PlayFanfare SEQ_SE_GS_IWA_TRAP
	WildBattle SPECIES_GEODUDE 21
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#26
	SetVar 0x40C1 1
	ReleaseAll
End

Script 30:
	MecScript
	LockAll
	PlayFanfare SEQ_SE_PL_BOWABOWA
	FadeScreen 6 1 0 0
	WaitFadeScreen
	WaitTime 15 0x800C
	Warp 247 0 50 4 Left
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Script 31:
	CompareVarValue 0x40AC 9
	CallIf GREATER/EQUAL Function#27
	CompareVarValue 0x40AD 2
	JumpIf DIFFERENT Function#28
	SetOWPosition Overworld.0 44 0 3 Left
Jump Function#29

Script 32:
	CompareVarValue 0x40AC 4
	JumpIf EQUAL Function#30
	CompareVarValue 0x40AC 5
	JumpIf EQUAL Function#30
	CompareVarValue 0x40AC 6
	JumpIf EQUAL Function#30
	CompareVarValue 0x40AC 7
	JumpIf EQUAL Function#30
End

Script 33:
End

//===== FUNCTIONS =====//
Function 1:
	DecrementVar 0x4001 1
Jump Function#31

Function 2:
	SetOWDefaultPosition Overworld.1 33 0
	ClearFlag 488
	AddOW Overworld.1
	SetOWPosition Overworld.1 33 0 0x4001 Left
	Movement Overworld.1 Action#4
	WaitMovement
	Movement Player Action#5
	WaitMovement
	Message 0
	CloseMessage
	TrainerBattle TRAINER_GRUNT_223 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#32
	Movement Overworld.1 Action#6
	WaitMovement
	SetOWPosition Overworld.1 33 0 0x4001 Right
	Movement Overworld.1 Action#4
	WaitMovement
	Message 1
	CloseMessage
	TrainerBattle TRAINER_GRUNT_224 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#32
	Movement Overworld.1 Action#6
	WaitMovement
Jump Function#33

Function 3:
	CompareVarValue 0x40AD 1
	JumpIf DIFFERENT Function#34
	Message 3
Jump Function#4

Function 4:
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 5:
	Message 8
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 6:
	Message 6
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#35
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#8
	PlayFanfare SEQ_SE_DP_DENSI01
	Message 7
	CloseMessage
	ClearFlag 214
	CompareVarValue 0x40AD 2
	JumpIf GREATER/EQUAL Function#36
	SetVar 0x40AD 0
	Movement Overworld.0 Action#7
	CompareVarValue 0x40AE 2
	JumpIf GREATER/EQUAL Function#37
	SetVar 0x40AE 0
	Movement Overworld.2 Action#7
	CompareVarValue 0x40AF 2
	JumpIf GREATER/EQUAL Function#38
	SetVar 0x40AF 0
	Movement Overworld.3 Action#7
	CompareVarValue 0x40B0 2
	JumpIf GREATER/EQUAL Function#39
	SetVar 0x40B0 0
	Movement Overworld.4 Action#7
	CompareVarValue 0x40B1 2
	JumpIf GREATER/EQUAL Function#40
	SetVar 0x40B1 0
	Movement Overworld.5 Action#7
	WaitMovement
	Message 10
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 7:
	PlayFanfare SEQ_SE_DP_DENSI01
	Message 7
	CloseMessage
	SetFlag 214
	CompareVarValue 0x40AD 2
	JumpIf GREATER/EQUAL Function#9
	SetVar 0x40AD 1
	Movement Overworld.0 Action#3
	CompareVarValue 0x40AE 2
	JumpIf GREATER/EQUAL Function#10
	SetVar 0x40AE 1
	Movement Overworld.2 Action#3
	CompareVarValue 0x40AF 2
	JumpIf GREATER/EQUAL Function#11
	SetVar 0x40AF 1
	Movement Overworld.3 Action#3
	CompareVarValue 0x40B0 2
	JumpIf GREATER/EQUAL Function#12
	SetVar 0x40B0 1
	Movement Overworld.4 Action#3
	CompareVarValue 0x40B1 2
	JumpIf GREATER/EQUAL Function#13
	SetVar 0x40B1 1
	Movement Overworld.5 Action#3
	WaitMovement
	Message 9
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 8:
	CloseMessage
	ReleaseAll
End

Function 9:
	CompareVarValue 0x40AE 2
	JumpIf GREATER/EQUAL Function#10
	SetVar 0x40AE 1
	Movement Overworld.2 Action#3
	CompareVarValue 0x40AF 2
	JumpIf GREATER/EQUAL Function#11
	SetVar 0x40AF 1
	Movement Overworld.3 Action#3
	CompareVarValue 0x40B0 2
	JumpIf GREATER/EQUAL Function#12
	SetVar 0x40B0 1
	Movement Overworld.4 Action#3
	CompareVarValue 0x40B1 2
	JumpIf GREATER/EQUAL Function#13
	SetVar 0x40B1 1
	Movement Overworld.5 Action#3
	WaitMovement
	Message 9
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 10:
	CompareVarValue 0x40AF 2
	JumpIf GREATER/EQUAL Function#11
	SetVar 0x40AF 1
	Movement Overworld.3 Action#3
	CompareVarValue 0x40B0 2
	JumpIf GREATER/EQUAL Function#12
	SetVar 0x40B0 1
	Movement Overworld.4 Action#3
	CompareVarValue 0x40B1 2
	JumpIf GREATER/EQUAL Function#13
	SetVar 0x40B1 1
	Movement Overworld.5 Action#3
	WaitMovement
	Message 9
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 11:
	CompareVarValue 0x40B0 2
	JumpIf GREATER/EQUAL Function#12
	SetVar 0x40B0 1
	Movement Overworld.4 Action#3
	CompareVarValue 0x40B1 2
	JumpIf GREATER/EQUAL Function#13
	SetVar 0x40B1 1
	Movement Overworld.5 Action#3
	WaitMovement
	Message 9
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 12:
	CompareVarValue 0x40B1 2
	JumpIf GREATER/EQUAL Function#13
	SetVar 0x40B1 1
	Movement Overworld.5 Action#3
	WaitMovement
	Message 9
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 13:
	Message 9
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 14:
	DecrementVar 0x4001 1
Jump Function#41

Function 15:
	SetOWDefaultPosition Overworld.1 27 0
	ClearFlag 488
	AddOW Overworld.1
	SetOWPosition Overworld.1 27 0 0x4001 Left
	Movement Overworld.1 Action#8
	WaitMovement
	Movement Player Action#5
	WaitMovement
	Message 0
	CloseMessage
	TrainerBattle TRAINER_GRUNT_223 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#32
	Movement Overworld.1 Action#9
	WaitMovement
	SetOWPosition Overworld.1 27 0 0x4001 Left
	Movement Overworld.1 Action#8
	WaitMovement
	Movement Player Action#5
	WaitMovement
	Message 1
	CloseMessage
	TrainerBattle TRAINER_GRUNT_224 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#32
	Movement Overworld.1 Action#9
	WaitMovement
Jump Function#42

Function 16:
	DecrementVar 0x4001 1
Jump Function#43

Function 17:
	SetOWDefaultPosition Overworld.1 33 0
	ClearFlag 488
	AddOW Overworld.1
	SetOWPosition Overworld.1 33 0 0x4001 Left
	Movement Overworld.1 Action#10
	WaitMovement
	Movement Player Action#5
	WaitMovement
	Message 0
	CloseMessage
	TrainerBattle TRAINER_GRUNT_223 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#32
	Movement Overworld.1 Action#11
	WaitMovement
	SetOWPosition Overworld.1 33 0 0x4001 Left
	Movement Overworld.1 Action#10
	WaitMovement
	Movement Player Action#5
	WaitMovement
	Message 1
	CloseMessage
	TrainerBattle TRAINER_GRUNT_224 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#32
	Movement Overworld.1 Action#11
	WaitMovement
Jump Function#44

Function 18:
	DecrementVar 0x4001 1
Jump Function#45

Function 19:
	SetOWDefaultPosition Overworld.1 33 0
	ClearFlag 488
	AddOW Overworld.1
	SetOWPosition Overworld.1 33 0 0x4001 Left
	Movement Overworld.1 Action#12
	WaitMovement
	Movement Player Action#5
	WaitMovement
	Message 0
	CloseMessage
	TrainerBattle TRAINER_GRUNT_223 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#32
	Movement Overworld.1 Action#13
	WaitMovement
	SetOWPosition Overworld.1 33 0 0x4001 Left
	Movement Overworld.1 Action#12
	WaitMovement
	Movement Player Action#5
	WaitMovement
	Message 1
	CloseMessage
	TrainerBattle TRAINER_GRUNT_224 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#32
	Movement Overworld.1 Action#13
	WaitMovement
Jump Function#46

Function 20:
	DecrementVar 0x4001 1
Jump Function#47

Function 21:
	SetOWDefaultPosition Overworld.1 27 0
	ClearFlag 488
	AddOW Overworld.1
	SetOWPosition Overworld.1 27 0 0x4001 Left
	Movement Overworld.1 Action#14
	WaitMovement
	Movement Player Action#5
	WaitMovement
	Message 0
	CloseMessage
	TrainerBattle TRAINER_GRUNT_223 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#32
	Movement Overworld.1 Action#15
	WaitMovement
	SetOWPosition Overworld.1 27 0 0x4001 Left
	Movement Overworld.1 Action#14
	WaitMovement
	Movement Player Action#5
	WaitMovement
	Message 1
	CloseMessage
	TrainerBattle TRAINER_GRUNT_224 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#32
	Movement Overworld.1 Action#15
	WaitMovement
Jump Function#48

Function 22:
	CompareVarValue 0x40AE 1
	JumpIf DIFFERENT Function#49
	Message 3
Jump Function#4

Function 23:
	CompareVarValue 0x40AF 1
	JumpIf DIFFERENT Function#50
	Message 3
Jump Function#4

Function 24:
	CompareVarValue 0x40B0 1
	JumpIf DIFFERENT Function#51
	Message 3
Jump Function#4

Function 25:
	CompareVarValue 0x40B1 1
	JumpIf DIFFERENT Function#52
	Message 3
Jump Function#4

Function 26:
	LostBattle
	ReleaseAll
End

Function 27:
	SetVar 0x40AD 2
	SetVar 0x40AE 2
	SetVar 0x40AF 2
	SetVar 0x40B0 2
	SetVar 0x40B1 2
Return

Function 28:
	CompareVarValue 0x40AD 1
	JumpIf DIFFERENT Function#53
	SetOWPosition Overworld.0 44 0 3 Down
Jump Function#29

Function 29:
	CompareVarValue 0x40AE 2
	JumpIf DIFFERENT Function#54
	SetOWPosition Overworld.2 18 0 3 Left
Jump Function#55

Function 30:
	SetVar 0x40AC 8
	SetVar 0x40A9 2
	SetFlag 587
	SetFlag 588
	SetFlag 589
	ClearFlag 594
End

Function 31:
	SetOWDefaultPosition Overworld.1 33 0
	ClearFlag 488
	AddOW Overworld.1
	SetOWPosition Overworld.1 33 0 0x4001 Left
	Movement Overworld.1 Action#16
	WaitMovement
	Movement Player Action#17
	WaitMovement
	Message 0
	CloseMessage
	TrainerBattle TRAINER_GRUNT_223 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#32
	Movement Overworld.1 Action#6
	WaitMovement
	SetOWPosition Overworld.1 33 0 0x4001 Right
	Movement Overworld.1 Action#16
	WaitMovement
	Message 1
	CloseMessage
	TrainerBattle TRAINER_GRUNT_224 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#32
	Movement Overworld.1 Action#6
	WaitMovement
	SetOWPosition Overworld.1 37 0 0 Left
	SetFlag 488
	SetVar 0x40AD 2
	Movement Overworld.0 Action#18
	WaitMovement
	ReleaseAll
End

Function 32:
	LostBattle
	ReleaseAll
End

Function 33:
	SetOWPosition Overworld.1 37 0 0 Left
	SetFlag 488
	SetVar 0x40AD 2
	Movement Overworld.0 Action#18
	WaitMovement
	ReleaseAll
End

Function 34:
	Message 4
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 35:
	PlayFanfare SEQ_SE_DP_DENSI01
	Message 7
	CloseMessage
	ClearFlag 214
	CompareVarValue 0x40AD 2
	JumpIf GREATER/EQUAL Function#36
	SetVar 0x40AD 0
	Movement Overworld.0 Action#7
	CompareVarValue 0x40AE 2
	JumpIf GREATER/EQUAL Function#37
	SetVar 0x40AE 0
	Movement Overworld.2 Action#7
	CompareVarValue 0x40AF 2
	JumpIf GREATER/EQUAL Function#38
	SetVar 0x40AF 0
	Movement Overworld.3 Action#7
	CompareVarValue 0x40B0 2
	JumpIf GREATER/EQUAL Function#39
	SetVar 0x40B0 0
	Movement Overworld.4 Action#7
	CompareVarValue 0x40B1 2
	JumpIf GREATER/EQUAL Function#40
	SetVar 0x40B1 0
	Movement Overworld.5 Action#7
	WaitMovement
	Message 10
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 36:
	CompareVarValue 0x40AE 2
	JumpIf GREATER/EQUAL Function#37
	SetVar 0x40AE 0
	Movement Overworld.2 Action#7
	CompareVarValue 0x40AF 2
	JumpIf GREATER/EQUAL Function#38
	SetVar 0x40AF 0
	Movement Overworld.3 Action#7
	CompareVarValue 0x40B0 2
	JumpIf GREATER/EQUAL Function#39
	SetVar 0x40B0 0
	Movement Overworld.4 Action#7
	CompareVarValue 0x40B1 2
	JumpIf GREATER/EQUAL Function#40
	SetVar 0x40B1 0
	Movement Overworld.5 Action#7
	WaitMovement
	Message 10
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 37:
	CompareVarValue 0x40AF 2
	JumpIf GREATER/EQUAL Function#38
	SetVar 0x40AF 0
	Movement Overworld.3 Action#7
	CompareVarValue 0x40B0 2
	JumpIf GREATER/EQUAL Function#39
	SetVar 0x40B0 0
	Movement Overworld.4 Action#7
	CompareVarValue 0x40B1 2
	JumpIf GREATER/EQUAL Function#40
	SetVar 0x40B1 0
	Movement Overworld.5 Action#7
	WaitMovement
	Message 10
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 38:
	CompareVarValue 0x40B0 2
	JumpIf GREATER/EQUAL Function#39
	SetVar 0x40B0 0
	Movement Overworld.4 Action#7
	CompareVarValue 0x40B1 2
	JumpIf GREATER/EQUAL Function#40
	SetVar 0x40B1 0
	Movement Overworld.5 Action#7
	WaitMovement
	Message 10
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 39:
	CompareVarValue 0x40B1 2
	JumpIf GREATER/EQUAL Function#40
	SetVar 0x40B1 0
	Movement Overworld.5 Action#7
	WaitMovement
	Message 10
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 40:
	Message 10
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 41:
	SetOWDefaultPosition Overworld.1 27 0
	ClearFlag 488
	AddOW Overworld.1
	SetOWPosition Overworld.1 27 0 0x4001 Left
	Movement Overworld.1 Action#19
	WaitMovement
	Movement Player Action#17
	WaitMovement
	Message 0
	CloseMessage
	TrainerBattle TRAINER_GRUNT_223 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#32
	Movement Overworld.1 Action#9
	WaitMovement
	SetOWPosition Overworld.1 27 0 0x4001 Left
	Movement Overworld.1 Action#19
	WaitMovement
	Movement Player Action#17
	WaitMovement
	Message 1
	CloseMessage
	TrainerBattle TRAINER_GRUNT_224 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#32
	Movement Overworld.1 Action#9
	WaitMovement
	RemoveOW Overworld.1
	SetFlag 488
	SetVar 0x40AE 2
	Movement Overworld.2 Action#18
	WaitMovement
	ReleaseAll
End

Function 42:
	RemoveOW Overworld.1
	SetFlag 488
	SetVar 0x40AE 2
	Movement Overworld.2 Action#18
	WaitMovement
	ReleaseAll
End

Function 43:
	SetOWDefaultPosition Overworld.1 33 0
	ClearFlag 488
	AddOW Overworld.1
	SetOWPosition Overworld.1 33 0 0x4001 Left
	Movement Overworld.1 Action#20
	WaitMovement
	Movement Player Action#17
	WaitMovement
	Message 0
	CloseMessage
	TrainerBattle TRAINER_GRUNT_223 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#32
	Movement Overworld.1 Action#11
	WaitMovement
	SetOWPosition Overworld.1 33 0 0x4001 Left
	Movement Overworld.1 Action#20
	WaitMovement
	Movement Player Action#17
	WaitMovement
	Message 1
	CloseMessage
	TrainerBattle TRAINER_GRUNT_224 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#32
	Movement Overworld.1 Action#11
	WaitMovement
	RemoveOW Overworld.1
	SetFlag 488
	SetVar 0x40AF 2
	Movement Overworld.3 Action#18
	WaitMovement
	ReleaseAll
End

Function 44:
	RemoveOW Overworld.1
	SetFlag 488
	SetVar 0x40AF 2
	Movement Overworld.3 Action#18
	WaitMovement
	ReleaseAll
End

Function 45:
	SetOWDefaultPosition Overworld.1 33 0
	ClearFlag 488
	AddOW Overworld.1
	SetOWPosition Overworld.1 33 0 0x4001 Left
	Movement Overworld.1 Action#21
	WaitMovement
	Movement Player Action#17
	WaitMovement
	Message 0
	CloseMessage
	TrainerBattle TRAINER_GRUNT_223 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#32
	Movement Overworld.1 Action#13
	WaitMovement
	SetOWPosition Overworld.1 33 0 0x4001 Left
	Movement Overworld.1 Action#21
	WaitMovement
	Movement Player Action#17
	WaitMovement
	Message 1
	CloseMessage
	TrainerBattle TRAINER_GRUNT_224 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#32
	Movement Overworld.1 Action#13
	WaitMovement
	RemoveOW Overworld.1
	SetVar 0x40B0 2
	Movement Overworld.4 Action#18
	WaitMovement
	ReleaseAll
End

Function 46:
	RemoveOW Overworld.1
	SetVar 0x40B0 2
	Movement Overworld.4 Action#18
	WaitMovement
	ReleaseAll
End

Function 47:
	SetOWDefaultPosition Overworld.1 27 0
	ClearFlag 488
	AddOW Overworld.1
	SetOWPosition Overworld.1 27 0 0x4001 Left
	Movement Overworld.1 Action#22
	WaitMovement
	Movement Player Action#17
	WaitMovement
	Message 0
	CloseMessage
	TrainerBattle TRAINER_GRUNT_223 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#32
	Movement Overworld.1 Action#15
	WaitMovement
	SetOWPosition Overworld.1 27 0 0x4001 Left
	Movement Overworld.1 Action#22
	WaitMovement
	Movement Player Action#17
	WaitMovement
	Message 1
	CloseMessage
	TrainerBattle TRAINER_GRUNT_224 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#32
	Movement Overworld.1 Action#15
	WaitMovement
	RemoveOW Overworld.1
	SetVar 0x40B1 2
	Movement Overworld.5 Action#18
	WaitMovement
	ReleaseAll
End

Function 48:
	RemoveOW Overworld.1
	SetVar 0x40B1 2
	Movement Overworld.5 Action#18
	WaitMovement
	ReleaseAll
End

Function 49:
	Message 4
Jump Function#4

Function 50:
	Message 4
Jump Function#4

Function 51:
	Message 4
Jump Function#4

Function 52:
	Message 4
Jump Function#4

Function 53:
	SetOWPosition Overworld.0 44 0 3 Up
	CompareVarValue 0x40AE 2
	JumpIf DIFFERENT Function#54
	SetOWPosition Overworld.2 18 0 3 Left
Jump Function#55

Function 54:
	CompareVarValue 0x40AE 1
	JumpIf DIFFERENT Function#56
	SetOWPosition Overworld.2 18 0 3 Down
Jump Function#55

Function 55:
	CompareVarValue 0x40AF 2
	JumpIf DIFFERENT Function#57
	SetOWPosition Overworld.3 44 0 10 Left
Jump Function#58

Function 56:
	SetOWPosition Overworld.2 18 0 3 Up
	CompareVarValue 0x40AF 2
	JumpIf DIFFERENT Function#57
	SetOWPosition Overworld.3 44 0 10 Left
Jump Function#58

Function 57:
	CompareVarValue 0x40AF 1
	JumpIf DIFFERENT Function#59
	SetOWPosition Overworld.3 44 0 10 Down
Jump Function#58

Function 58:
	CompareVarValue 0x40B0 2
	JumpIf DIFFERENT Function#60
	SetOWPosition Overworld.4 44 0 28 Left
Jump Function#61

Function 59:
	SetOWPosition Overworld.3 44 0 10 Up
	CompareVarValue 0x40B0 2
	JumpIf DIFFERENT Function#60
	SetOWPosition Overworld.4 44 0 28 Left
Jump Function#61

Function 60:
	CompareVarValue 0x40B0 1
	JumpIf DIFFERENT Function#62
	SetOWPosition Overworld.4 44 0 28 Down
Jump Function#61

Function 61:
	CompareVarValue 0x40B1 2
	JumpIf DIFFERENT Function#63
	SetOWPosition Overworld.5 18 0 28 Left
Jump Function#64

Function 62:
	SetOWPosition Overworld.4 44 0 28 Up
	CompareVarValue 0x40B1 2
	JumpIf DIFFERENT Function#63
	SetOWPosition Overworld.5 18 0 28 Left
Jump Function#64

Function 63:
	CompareVarValue 0x40B1 1
	JumpIf DIFFERENT Function#65
	SetOWPosition Overworld.5 18 0 28 Down
Jump Function#64

Function 64:
End

Function 65:
	SetOWPosition Overworld.5 18 0 28 Up
End

//===== ACTIONS =====//
Action 1:
	EmoteExclamation 0x1
	Delay8 0x2
	FaceEast 0x2
	Delay8 0x1
	FaceWest 0x2
	Delay8 0x1
	FaceEast 0x2
	Delay8 0x1
	FaceNorth 0x2
	Delay8 0x1
End

Action 2:
	EmoteExclamation 0x1
	Delay8 0x2
End

Action 3:
	FaceSouth 0x1
End

Action 4:
	WalkEast2 0xB
	FaceNorth 0x2
End

Action 5:
	FaceSouth 0x2
	Delay8 0x2
End

Action 6:
	FaceWest 0x2
	WalkWest2 0xA
End

Action 7:
	FaceNorth 0x1
End

Action 8:
	WalkWest2 0x9
	FaceNorth 0x2
End

Action 9:
	FaceEast 0x2
	WalkEast2 0xA
End

Action 10:
	WalkEast2 0xB
	FaceNorth 0x2
End

Action 11:
	FaceWest 0x2
	WalkWest2 0xA
End

Action 12:
	WalkEast2 0xB
	FaceNorth 0x2
End

Action 13:
	FaceWest 0x2
	WalkWest2 0xA
End

Action 14:
	WalkWest2 0x9
	FaceNorth 0x2
End

Action 15:
	FaceEast 0x2
	WalkEast2 0xA
End

Action 16:
	WalkEast2 0xB
	FaceSouth 0x2
End

Action 17:
	FaceNorth 0x2
	Delay8 0x2
End

Action 18:
	FaceWest 0x1
End

Action 19:
	WalkWest2 0x9
	FaceSouth 0x2
End

Action 20:
	WalkEast2 0xB
	FaceSouth 0x2
End

Action 21:
	WalkEast2 0xB
	FaceSouth 0x2
End

Action 22:
	WalkWest2 0x9
	FaceSouth 0x2
End

