/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0095
 * Generated: 3/6/2026 7:25:18 PM
 */

//===== SCRIPTS =====//
Script 1:
	CheckFlag 150
	JumpIf EQUAL Function#1
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Message 0
	CloseMessage
	Movement Overworld.1 Action#1
	Movement Overworld.7 Action#1
	Movement Overworld.9 Action#1
	Movement Overworld.10 Action#1
	Movement Overworld.11 Action#1
	WaitMovement
	SetFlag 150
	SetOWMovement Overworld.0 Move.9
	ReleaseAll
End

Script 2:
	GetOWPosition Overworld.4 0x4000 0x4001
	CompareVarValue 0x4001 15
	JumpIf DIFFERENT Function#2
Jump Function#3

Script 3:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	PlayCry SPECIES_MACHOKE 0
	Message 2
	WaitCry
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 4:
	VanishOverworld Overworld.9
	VanishOverworld Overworld.10
	VanishOverworld Overworld.11
	VanishOverworld Overworld.12
	VanishOverworld Overworld.13
	VanishOverworld Overworld.14
	VanishOverworld Overworld.15
	VanishOverworld Overworld.16
	VanishOverworld Overworld.17
	CheckFlag 150
	JumpIf EQUAL Function#4
	CheckFlag 151
	JumpIf EQUAL Function#5
	CheckFlag 152
	JumpIf EQUAL Function#6
End

//===== FUNCTIONS =====//
Function 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 1
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 2:
	CompareVarValue 0x4001 16
	JumpIf DIFFERENT Function#7
Jump Function#8

Function 3:
	CheckFlag 151
	JumpIf EQUAL Function#1
	GetOWDirection Overworld.4 0x4000
	CompareVarValue 0x4000 0
	JumpIf DIFFERENT Function#9
Jump Function#10

Function 4:
	CheckFlag 151
	JumpIf EQUAL Function#11
	CheckFlag 152
	JumpIf EQUAL Function#12
	SetOWMovement Overworld.0 Move.9
	SetOWPosition Overworld.1 19 0 16 Down
	SetOWPosition Overworld.7 19 0 18 Up
	SetOWPosition Overworld.9 19 0 17 Up
	SetOWPosition Overworld.10 20 0 17 Up
	SetOWPosition Overworld.11 20 0 18 Up
End

Function 5:
	CheckFlag 152
	JumpIf EQUAL Function#13
	SetOWPosition Overworld.2 3 0 14 Left
	SetOWPosition Overworld.6 1 0 14 Up
	SetOWPosition Overworld.12 1 0 13 Up
	SetOWPosition Overworld.13 2 0 13 Up
	SetOWPosition Overworld.14 2 0 14 Up
End

Function 6:
	SetOWPosition Overworld.3 7 0 17 Right
	SetOWPosition Overworld.5 8 0 18 Up
	SetOWPosition Overworld.15 8 0 17 Up
	SetOWPosition Overworld.16 9 0 17 Up
	SetOWPosition Overworld.17 9 0 18 Up
End

Function 7:
Jump Function#1

Function 8:
	CheckFlag 152
	JumpIf EQUAL Function#1
	GetOWDirection Overworld.4 0x4000
	CompareVarValue 0x4000 1
	JumpIf DIFFERENT Function#14
Jump Function#15

Function 9:
Jump Function#1

Function 10:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Message 0
	CloseMessage
	Movement Overworld.2 Action#2
	Movement Overworld.6 Action#2
	Movement Overworld.12 Action#2
	Movement Overworld.13 Action#2
	Movement Overworld.14 Action#2
	WaitMovement
	SetFlag 151
	ReleaseAll
End

Function 11:
	CheckFlag 152
	JumpIf EQUAL Function#16
	SetOWMovement Overworld.0 Move.9
	SetOWPosition Overworld.1 19 0 16 Down
	SetOWPosition Overworld.7 19 0 18 Up
	SetOWPosition Overworld.9 19 0 17 Up
	SetOWPosition Overworld.10 20 0 17 Up
	SetOWPosition Overworld.11 20 0 18 Up
	SetOWPosition Overworld.2 3 0 14 Left
	SetOWPosition Overworld.6 1 0 14 Up
	SetOWPosition Overworld.12 1 0 13 Up
	SetOWPosition Overworld.13 2 0 13 Up
	SetOWPosition Overworld.14 2 0 14 Up
End

Function 12:
	SetOWMovement Overworld.0 Move.9
	SetOWPosition Overworld.1 19 0 16 Down
	SetOWPosition Overworld.7 19 0 18 Up
	SetOWPosition Overworld.9 19 0 17 Up
	SetOWPosition Overworld.10 20 0 17 Up
	SetOWPosition Overworld.11 20 0 18 Up
	SetOWPosition Overworld.3 7 0 17 Right
	SetOWPosition Overworld.5 8 0 18 Up
	SetOWPosition Overworld.15 8 0 17 Up
	SetOWPosition Overworld.16 9 0 17 Up
	SetOWPosition Overworld.17 9 0 18 Up
End

Function 13:
	SetOWPosition Overworld.2 3 0 14 Left
	SetOWPosition Overworld.6 1 0 14 Up
	SetOWPosition Overworld.12 1 0 13 Up
	SetOWPosition Overworld.13 2 0 13 Up
	SetOWPosition Overworld.14 2 0 14 Up
	SetOWPosition Overworld.3 7 0 17 Right
	SetOWPosition Overworld.5 8 0 18 Up
	SetOWPosition Overworld.15 8 0 17 Up
	SetOWPosition Overworld.16 9 0 17 Up
	SetOWPosition Overworld.17 9 0 18 Up
End

Function 14:
Jump Function#1

Function 15:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Message 0
	CloseMessage
	Movement Overworld.3 Action#3
	Movement Overworld.5 Action#3
	Movement Overworld.15 Action#3
	Movement Overworld.16 Action#3
	Movement Overworld.17 Action#3
	WaitMovement
	SetFlag 152
	ReleaseAll
End

Function 16:
	SetOWMovement Overworld.0 Move.9
	SetOWPosition Overworld.1 19 0 16 Down
	SetOWPosition Overworld.7 19 0 18 Up
	SetOWPosition Overworld.9 19 0 17 Up
	SetOWPosition Overworld.10 20 0 17 Up
	SetOWPosition Overworld.11 20 0 18 Up
	SetOWPosition Overworld.2 3 0 14 Left
	SetOWPosition Overworld.6 1 0 14 Up
	SetOWPosition Overworld.12 1 0 13 Up
	SetOWPosition Overworld.13 2 0 13 Up
	SetOWPosition Overworld.14 2 0 14 Up
	SetOWPosition Overworld.3 7 0 17 Right
	SetOWPosition Overworld.5 8 0 18 Up
	SetOWPosition Overworld.15 8 0 17 Up
	SetOWPosition Overworld.16 9 0 17 Up
	SetOWPosition Overworld.17 9 0 18 Up
End

//===== ACTIONS =====//
Action 1:
	WalkSouth16 0x2
End

Action 2:
	WalkWest16 0x2
End

Action 3:
	WalkEast16 0x2
End

