/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0099
 * Generated: 5/20/2026 9:55:32 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CompareVarValue 0x4100 1
	JumpIf EQUAL Function#1
	CheckFlag 1111
	JumpIf EQUAL Function#2
	Message 1
	CloseMessage
	Movement Overworld.1 Action#1
	WaitMovement
	ReleaseAll
End

Script 2:
	CheckFlag 393
	JumpIf LESS Function#3
	ClearFlag 393
End

Script 3:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	CommonScript 2067
	GetPlayerDirection 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#4
Jump Function#5

Script 4:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 0
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#6
	CheckAlbumPhoto 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#7
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 1
	CloseMessage
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	GetPlayerDirection 0x800C
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#8
	Movement Player Action#2
	Movement Overworld.5 Action#3
Jump Function#9

Script 5:
	MecScript
	LockAll
	CheckFlag 1111
	JumpIf EQUAL Function#10
	Movement Overworld.1 Action#4
	Movement Player Action#5
	WaitMovement
	Message 1
	CloseMessage
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	Movement Overworld.1 Action#1
	Movement Player Action#6
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	ReleaseAll
End

//===== FUNCTIONS =====//
Function 1:
	Message 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 2:
	SetVar 0x4100 1
	Message 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 3:
	GetDayOfWeek 0x4000
	CompareVarValue 0x4000 5
	JumpIf EQUAL Function#11
	CompareVarValue 0x4000 6
	JumpIf EQUAL Function#11
	SetFlag 638
End

Function 4:
	TextPlayerName 0
	Message 3
	WaitButton
	CloseMessage
	ReleaseAll
	CommonScript 2068
End

Function 5:
	TextPlayerName 0
	Message 4
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#12
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#13
End

Function 6:
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 5
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 7:
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 3
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 8:
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#14
	Movement Player Action#7
Jump Function#9

Function 9:
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	CheckPokemonAlive 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#15
	Movement Following Action#8
	WaitMovement
	SetFlag 393
	FadeScreen 6 1 0 0
	WaitFadeScreen
	TakePhoto 43
	LockAll
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ClearFlag 393
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 10:
	Movement Overworld.1 Action#4
	Movement Player Action#5
	WaitMovement
	Message 2
	WaitButton
	CloseMessage
	ReleaseAll
	SetVar 0x4100 1
End

Function 11:
	ClearFlag 638
End

Function 12:
	PlayFanfare SEQ_SE_DP_WALL_HIT
	Message 5
	CloseMessage
	GetPlayerPosition 0x8004 0x8005
	LockCamera 0x8004 0x8005
	Movement Overworld.2 Action#9
	Movement Camera Action#10
	WaitMovement
	Message 7
	CloseMessage
	Movement Overworld.2 Action#11
	WaitMovement
	RemoveOW Overworld.2
	PlayFanfare SEQ_SE_DP_KAIDAN2
	WaitFanfare SEQ_SE_DP_KAIDAN2
	CommonScript 2068
	SetFlag 569
	SetVar 0x40E8 1
	Movement Camera Action#12
	WaitMovement
	ReleaseCamera
	ReleaseAll
End

Function 13:
	Message 6
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#12
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#13
End

Function 14:
	CompareVarValue 0x800C 3
	JumpIf DIFFERENT Function#16
	Movement Player Action#13
	Movement Overworld.5 Action#3
Jump Function#9

Function 15:
	SetFlag 393
	FadeScreen 6 1 0 0
	WaitFadeScreen
	TakePhoto 43
	LockAll
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ClearFlag 393
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 16:
	Movement Player Action#14
	Movement Overworld.5 Action#3
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	CheckPokemonAlive 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#15
	Movement Following Action#8
	WaitMovement
	SetFlag 393
	FadeScreen 6 1 0 0
	WaitFadeScreen
	TakePhoto 43
	LockAll
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ClearFlag 393
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 2
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== ACTIONS =====//
Action 1:
		FaceSouth 0x1
End

Action 2:
		WalkEast8 0x1
		WalkNorth8 0x2
		WalkWest8 0x1
		WalkNorth8 0x3
		WalkOnSpotSouth8 0x1
End

Action 3:
		Delay8 0x1
		WalkOnSpotNorth8 0x1
End

Action 4:
		FaceNorth 0x1
		EmoteExclamation 0x1
End

Action 5:
		Delay8 0x2
		FaceSouth 0x1
End

Action 6:
		WalkWest8 0x1
End

Action 7:
		WalkNorth8 0x3
		WalkOnSpotSouth8 0x1
End

Action 8:
		WalkEast8 0x1
		WalkNorth8 0x1
		FaceSouth 0x1
End

Action 9:
		PauseAnimation 0x0
		WalkSouth4 0x5
		ResumeAnimation 0x0
		WalkSouth8 0x2
		WalkOnSpotSouth8 0x1
		Delay8 0x1
		WalkOnSpotNorth8 0x2
End

Action 10:
		WalkSouth4 0x4
End

Action 11:
		WalkSouth8 0x4
End

Action 12:
		WalkNorth4 0x4
End

Action 13:
		WalkNorth8 0x1
		WalkEast8 0x1
		WalkNorth8 0x3
		WalkOnSpotSouth8 0x1
End

Action 14:
		WalkNorth8 0x1
		WalkWest8 0x1
		WalkNorth8 0x3
		WalkOnSpotSouth8 0x1
End

