/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0114
 * Generated: 3/6/2026 7:25:18 PM
 */

//===== SCRIPTS =====//
Script 1:
	CompareVarValue 0x40FE 4
	JumpIf EQUAL Function#1
	CompareVarValue 0x40FE 3
	JumpIf EQUAL Function#2
	CompareVarValue 0x40FE 2
	JumpIf EQUAL Function#3
End

Script 2:
	MecScript
	LockAll
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	Movement Player Action#1
	Movement Overworld.5 Action#2
	WaitMovement
	Movement Following Action#3
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	Movement Overworld.4 Action#4
	WaitMovement
	Message 0
	CloseMessage
	Movement Overworld.5 Action#2
	WaitMovement
	GenderMessage 8 7
	CloseMessage
	Movement Overworld.4 Action#5
	WaitMovement
	Message 1
	CloseMessage
	Movement Overworld.5 Action#6
	WaitMovement
	GenderMessage 10 9
	CloseMessage
	Movement Overworld.5 Action#7
	WaitMovement
	GenderMessage 12 11
	CloseMessage
	Movement Overworld.5 Action#8
	WaitMovement
	TextPlayerName 0
	GenderMessage 14 13
	CloseMessage
	StopMusic 0
	PlayFanfare SEQ_SE_PL_FR03
	PlayMusic SEQ_GS_SENKYO
	Message 2
	StopFanfare SEQ_SE_PL_FR03
	CloseMessage
	Movement Overworld.4 Action#5
	WaitMovement
	Message 3
	CloseMessage
	SetVar 0x40FE 3
	TrainerBattle TRAINER_GIOVANNI_700 TRAINER_NONE 1 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#4
	SetVar 0x40FE 4
	Movement Overworld.4 Action#9
	WaitMovement
	Message 4
	CloseMessage
	Movement Overworld.4 Action#10
	WaitMovement
	RemoveOW Overworld.4
	SetFlag 771
	Movement Player Action#11
	Movement Overworld.5 Action#11
	WaitMovement
	FadeOutMusic 0 30
	StopMusic 0
	PlayFanfare SEQ_SE_PL_FR03
	Message 5
	StopFanfare SEQ_SE_PL_FR03
	CloseMessage
	Movement Overworld.5 Action#12
	WaitMovement
	TextPlayerName 0
	GenderMessage 16 15
	CloseMessage
	GetFirstAlivePokemonSlot 0x4002
	GetPartyPokemonID 0x4002 0x800C
	CompareVarValue 0x800C 251
	CallIf DIFFERENT Function#5
	Movement Following Action#13
	WaitMovement
	PlayFanfare SEQ_SE_GS_SUZUSYUTUGEN_HO
	FadeScreen 6 6 0 0x7FFF
	WaitFadeScreen
	WaitTime 15 0x800C
	FadeScreen 6 6 1 0x7FFF
	WaitFadeScreen
	Movement Player Action#7
	WaitMovement
	Movement Overworld.5 Action#14
	WaitMovement
	CompareVarValue 0x4003 1
	JumpIf DIFFERENT Function#6
	GenderMessage 27 26
	CloseMessage
Jump Function#7

Script 3:
End

Script 4:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CompareVarValue 0x40FE 4
	JumpIf GREATER/EQUAL Function#8
	Message 20
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== FUNCTIONS =====//
Function 1:
End

Function 2:
	SetOWPosition Overworld.4 6 1 6 Down
	SetOWPosition Overworld.5 5 1 7 Up
	VanishOverworld Following
	BallResetFollowingPoke
End

Function 3:
	SetOWPosition Overworld.4 6 1 4 Up
	SetOWPosition Overworld.5 5 1 8 Down
End

Function 4:
	Message 6
	CloseMessage
	Movement Overworld.4 Action#15
	PlayFanfare SEQ_SE_GS_SUZUSYUTUGEN_HO
	FadeScreen 6 6 0 0x7FFF
	WaitFadeScreen
	WaitTime 15 0x800C
	FadeScreen 6 6 1 0x7FFF
	WaitFadeScreen
	WaitMovement
	RemoveOW Overworld.4
	SetFlag 771
	Message 19
	CloseMessage
	PlayFanfare SEQ_SE_GS_TIMESLIP
	CelebiTimeTravelAnimation
	SetFlag 376
	SetVar 0x40FE 0
	SetFlag 784
	Warp 117 0 16 57 Down
	FadeScreen 6 15 1 0x7FFF
	WaitFadeScreen
	CloseTouchScreen
	ReleaseAll
End

Function 5:
	SetVar 0x4003 1
	Movement Overworld.5 Action#16
	WaitMovement
	GenderMessage 23 22
	CloseMessage
	GenderMessage 25 24
	CloseMessage
	FadeScreen 6 1 0 0
	WaitFadeScreen
	PlaySound SEQ_ME_ASA
	WaitSound
	HealPokemon
	FinishOverworldScreen
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
Return

Function 6:
	GenderMessage 18 17
	CloseMessage
	PlayFanfare SEQ_SE_GS_TIMESLIP
	CelebiTimeTravelAnimation
	ClearFlag 784
	Warp 117 0 16 57 Down
	FadeScreen 6 15 1 0x7FFF
	WaitFadeScreen
	ReleaseAll
End

Function 7:
	PlayFanfare SEQ_SE_GS_TIMESLIP
	CelebiTimeTravelAnimation
	ClearFlag 784
	Warp 117 0 16 57 Down
	FadeScreen 6 15 1 0x7FFF
	WaitFadeScreen
	ReleaseAll
End

Function 8:
	Message 21
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== ACTIONS =====//
Action 1:
	WalkOnSpotNorth8 0x1
	WalkNorth8 0x1
End

Action 2:
	WalkOnSpotNorth8 0x1
End

Action 3:
	WalkEast8 0x1
	WalkNorth8 0x1
End

Action 4:
	EmoteExclamation 0x1
	Delay8 0x1
	WalkOnSpotSouth8 0x1
End

Action 5:
	WalkSouth8 0x1
End

Action 6:
	WalkNorth8 0x1
	WalkOnSpotEast8 0x1
End

Action 7:
	EmoteExclamation 0x1
	Delay8 0x1
End

Action 8:
	WalkOnSpotEast4 0x4
End

Action 9:
	LockDir 0x1
	WalkNorth16 0x1
	ReleaseDir 0x1
	WalkEast16 0x2
End

Action 10:
	WalkSouth8 0x4
	WalkWest8 0x2
	WalkSouth8 0x2
End

Action 11:
	Delay8 0x3
	WalkSouth8 0x1
End

Action 12:
	WalkSouth8 0x1
End

Action 13:
	JumpOnSpotSouth8 0x1
End

Action 14:
	WalkOnSpotWest8 0x1
	Delay8 0x1
	WalkOnSpotEast8 0x1
	Delay8 0x1
End

Action 15:
	WalkEast16 0x2
	WalkSouth16 0x3
	WalkWest16 0x2
	WalkSouth16 0x2
End

Action 16:
	WalkOnSpotEast8 0x1
	EmoteExclamation 0x1
	Delay8 0x1
	WalkEast4 0x1
	WalkOnSpotNorth8 0x1
End

