/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0116
 * Generated: 3/6/2026 7:25:18 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 3
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 3:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 4
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 4:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 5
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 5:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	PlayCry SPECIES_JIGGLYPUFF 0
	Message 6
	WaitCry
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 6:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CompareVarValue 0x400B 0
	JumpIf DIFFERENT Function#1
	Message 7
Jump Function#2

Script 7:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 9
	CommonScript 2011
	FreezeMessage
	SetVar 0x8004 6
	CommonScript 2052
	ReleaseAll
End

Script 8:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 10
	CommonScript 2011
	FreezeMessage
	SetVar 0x8004 14
	CommonScript 2052
	ReleaseAll
End

Script 9:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	PlayCry SPECIES_BUTTERFREE 0
	Message 11
	WaitCry
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 10:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 12
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 11:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	PlayCry SPECIES_SLOWPOKE 0
	Message 13
	WaitCry
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 12:
	SetTextBoard 2 0
	ShowBoard 3
	WaitBoard
	BoardMessage 17 0x800C
	CommonScript 2000
End

Script 13:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 14
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 14:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 0
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#3
	CheckAlbumPhoto 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#4
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 1
	CloseMessage
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	GetPlayerDirection 0x800C
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#5
	Movement Player Action#1
	Movement Overworld.12 Action#2
Jump Function#6

Script 15:
	CheckFlag 393
	JumpIf LESS Function#7
	ClearFlag 393
End

Script 16:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 15
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 17:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 16
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== FUNCTIONS =====//
Function 1:
	Message 8
	WaitButton
	CloseMessage
	ReleaseAll
	CompareVarValue 0x400B 0
	JumpIf DIFFERENT Function#8
	IncrementVar 0x400B 1
Jump Function#9

Function 2:
	WaitButton
	CloseMessage
	ReleaseAll
	CompareVarValue 0x400B 0
	JumpIf DIFFERENT Function#8
	IncrementVar 0x400B 1
Jump Function#9

Function 3:
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 5
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 4:
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 3
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 5:
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#10
	Movement Player Action#3
Jump Function#6

Function 6:
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	CheckPokemonAlive 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#11
	Movement Following Action#4
	WaitMovement
	SetFlag 393
	FadeScreen 6 1 0 0
	WaitFadeScreen
	TakePhoto 38
	LockAll
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ClearFlag 393
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 7:
	GetDayOfWeek 0x4000
	CompareVarValue 0x4000 2
	JumpIf EQUAL Function#12
	CompareVarValue 0x4000 4
	JumpIf EQUAL Function#12
	SetFlag 638
End

Function 8:
	SetVar 0x400B 0
End

Function 9:
End

Function 10:
	CompareVarValue 0x800C 3
	JumpIf DIFFERENT Function#13
	Movement Player Action#5
	Movement Overworld.12 Action#2
Jump Function#6

Function 11:
	SetFlag 393
	FadeScreen 6 1 0 0
	WaitFadeScreen
	TakePhoto 38
	LockAll
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ClearFlag 393
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 12:
	ClearFlag 638
End

Function 13:
	Movement Player Action#6
	Movement Overworld.12 Action#2
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	CheckPokemonAlive 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#11
	Movement Following Action#4
	WaitMovement
	SetFlag 393
	FadeScreen 6 1 0 0
	WaitFadeScreen
	TakePhoto 38
	LockAll
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ClearFlag 393
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 2
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== ACTIONS =====//
Action 1:
	WalkEast8 0x1
	WalkNorth8 0x2
	WalkWest8 0x1
	WalkNorth8 0x3
	WalkOnSpotSouth8 0x1
End

Action 2:
	Delay8 0x1
	WalkOnSpotNorth8 0x1
End

Action 3:
	WalkNorth8 0x3
	WalkOnSpotSouth8 0x1
End

Action 4:
	WalkEast8 0x1
	WalkNorth8 0x1
	FaceSouth 0x1
End

Action 5:
	WalkNorth8 0x1
	WalkEast8 0x1
	WalkNorth8 0x3
	WalkOnSpotSouth8 0x1
End

Action 6:
	WalkNorth8 0x1
	WalkWest8 0x1
	WalkNorth8 0x3
	WalkOnSpotSouth8 0x1
End

