/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0121
 * Generated: 5/20/2026 9:55:32 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CompareVarValue 0x40EB 1
	JumpIf EQUAL Function#1
	CheckFlag 245
	JumpIf EQUAL Function#2
	Message 0
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 5
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 3:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 6
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 4:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckFlag 245
	JumpIf EQUAL Function#3
	Message 10
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 5:
	MecScript
	LockAll
	CompareVarValue 0x4001 2
	JumpIf DIFFERENT Function#4
	Movement Overworld.3 Action#1
Jump Function#5

Script 6:
	CompareVarValue 0x40F9 2
	JumpIf EQUAL Function#6
	SetFlag 718
End

Script 7:
	CompareVarValue 0x40F9 2
	JumpIf EQUAL Function#7
End

//===== FUNCTIONS =====//
Function 1:
	Message 4
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 2:
	Message 1
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#8
	Message 3
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 3:
	Message 11
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 4:
	Movement Overworld.3 Action#2
	WaitMovement
	TextPlayerName 0
	Message 7
	CloseMessage
	CompareVarValue 0x4001 2
	JumpIf DIFFERENT Function#9
	Movement Overworld.3 Action#3
Jump Function#10

Function 5:
	WaitMovement
	TextPlayerName 0
	Message 7
	CloseMessage
	CompareVarValue 0x4001 2
	JumpIf DIFFERENT Function#9
	Movement Overworld.3 Action#3
Jump Function#10

Function 6:
	ClearFlag 718
End

Function 7:
	GetPlayerDirection 0x4001
	CompareVarValue 0x4001 2
	JumpIf EQUAL Function#11
	SetOWPosition Overworld.3 19 0 40 Down
End

Function 8:
	Message 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 9:
	Movement Overworld.3 Action#4
	WaitMovement
	Message 8
	CloseMessage
	CompareVarValue 0x4001 2
	JumpIf DIFFERENT Function#12
	Movement Overworld.3 Action#5
Jump Function#13

Function 10:
	WaitMovement
	Message 8
	CloseMessage
	CompareVarValue 0x4001 2
	JumpIf DIFFERENT Function#12
	Movement Overworld.3 Action#5
Jump Function#13

Function 11:
End

Function 12:
	Movement Overworld.3 Action#6
	WaitMovement
	Message 9
	CloseMessage
	CompareVarValue 0x4001 2
	JumpIf DIFFERENT Function#14
	Movement Player Action#7
	Movement Overworld.3 Action#8
Jump Function#15

Function 13:
	WaitMovement
	Message 9
	CloseMessage
	CompareVarValue 0x4001 2
	JumpIf DIFFERENT Function#14
	Movement Player Action#7
	Movement Overworld.3 Action#8
Jump Function#15

Function 14:
	Movement Overworld.3 Action#9
	WaitMovement
	PlayFanfare SEQ_SE_DP_KAIDAN2
	SetFlag 718
	RemoveOW Overworld.3
	SetVar 0x40F9 3
	ReleaseAll
End

Function 15:
	WaitMovement
	PlayFanfare SEQ_SE_DP_KAIDAN2
	SetFlag 718
	RemoveOW Overworld.3
	SetVar 0x40F9 3
	ReleaseAll
End

//===== ACTIONS =====//
Action 1:
		WalkOnSpotEast8 0x1
		Delay8 0x1
		WalkEast8 0x2
		WalkSouth8 0x1
		WalkEast8 0x1
End

Action 2:
		WalkOnSpotSouth8 0x1
		Delay8 0x1
		WalkSouth8 0x3
		WalkWest8 0x1
		WalkSouth8 0x1
End

Action 3:
		EmoteExclamation 0x1
		Delay8 0x1
End

Action 4:
		EmoteExclamation 0x1
		Delay8 0x1
End

Action 5:
		WalkOnSpotEast8 0x1
End

Action 6:
		WalkOnSpotSouth8 0x1
End

Action 7:
		LockDir 0x1
		WalkNorth8 0x1
		ReleaseDir 0x1
		WalkOnSpotSouth8 0x1
End

Action 8:
		Delay8 0x1
		WalkEast8 0x2
End

Action 9:
		Delay8 0x1
		WalkNorth8 0x4
		WalkEast8 0x2
		WalkNorth8 0x9
End

