/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0125
 * Generated: 3/6/2026 7:25:18 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 0
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckFlag 239
	JumpIf EQUAL Function#1
	Message 1
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 3:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 3
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 4:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 4
	CloseMessage
	Movement Overworld.4 Action#1
	WaitMovement
	PlayCry SPECIES_RATTATA 0
	Message 11
	WaitCry
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 5:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 5
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 6:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	PlayCry SPECIES_RATTATA 0
	Message 10
	WaitCry
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 7:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	PlayCry SPECIES_ZUBAT 0
	Message 12
	WaitCry
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 8:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	TextPlayerName 0
	Message 6
	CloseMessage
	FadeScreen 6 1 0 0
	WaitFadeScreen
	CMD_712 0
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Script 9:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 7
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 10:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 8
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 11:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 9
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 12:
	CompareVarValue 0x400B 1
	JumpIf DIFFERENT Function#2
	SetOWPosition Overworld.2 2 1 3 Right
	SetVar 0x400B 0
End

Script 13:
	CheckFlag 239
	JumpIf EQUAL Function#3
	SetVar 0x400B 0
End

Script 14:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 13
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== FUNCTIONS =====//
Function 1:
	Message 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 2:
End

Function 3:
	SetVar 0x400B 1
End

//===== ACTIONS =====//
Action 1:
	JumpOnSpotNorth8 0x2
End

