/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0131
 * Generated: 3/6/2026 7:25:18 PM
 */

//===== SCRIPTS =====//
Script 1:
End

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CompareVarValue 0x40FB 8
	JumpIf EQUAL Function#1
	GetFirstAlivePokemonSlot 0x4005
	FollowingPokemonIsEventTrigger 2 0x4005 0x4006
	CompareVarValue 0x4006 1
	JumpIf EQUAL Function#2
	FollowingPokemonIsEventTrigger 1 0x4005 0x4007
	CompareVarValue 0x4007 1
	JumpIf EQUAL Function#2
	Message 24
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 3:
	CompareVarValue 0x40FB 7
	JumpIf EQUAL Function#3
	CompareVarValue 0x40FB 8
	JumpIf EQUAL Function#3
	CompareVarValue 0x40FB 9
	JumpIf EQUAL Function#3
	CompareVarValue 0x40FB 12
	JumpIf EQUAL Function#3
	CompareVarValue 0x40FB 13
	JumpIf EQUAL Function#3
End

Script 4:
	MecScript
	LockAll
	CompareVarValue 0x40FB 13
	JumpIf LESS Function#4
	CompareVarValue 0x4103 2
	JumpIf EQUAL Function#5
	Call Function#6
	CompareVarValue 0x400A 0
	JumpIf EQUAL Function#7
	CompareVarValue 0x400A 2
	JumpIf EQUAL Function#8
	CompareVarValue 0x400A 3
	JumpIf EQUAL Function#9
	Message 28
Jump Function#10

Script 5:
	MecScript
	LockAll
	CompareVarValue 0x40FB 13
	JumpIf LESS Function#11
	CompareVarValue 0x4103 1
	JumpIf EQUAL Function#5
	Call Function#6
	CompareVarValue 0x400A 0
	JumpIf EQUAL Function#7
	CompareVarValue 0x400A 2
	JumpIf EQUAL Function#8
	CompareVarValue 0x400A 3
	JumpIf EQUAL Function#9
	Message 27
Jump Function#12

Script 6:
	MecScript
	LockAll
	CompareVarValue 0x40FB 13
	JumpIf LESS Function#13
	CompareVarValue 0x4103 3
	JumpIf EQUAL Function#5
	Call Function#6
	CompareVarValue 0x400A 0
	JumpIf EQUAL Function#7
	CompareVarValue 0x400A 2
	JumpIf EQUAL Function#8
	CompareVarValue 0x400A 3
	JumpIf EQUAL Function#9
	Message 29
Jump Function#14

Script 7:
	MecScript
	LockAll
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	Movement Player Action#1
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	SetVar 0x40FB 4
	ReleaseAll
End

Script 8:
	MecScript
	LockAll
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	Movement Player Action#1
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	SetVar 0x40FB 13
	ReleaseAll
End

//===== FUNCTIONS =====//
Function 1:
	Message 12
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 2:
	CompareVarValue 0x4004 1
	JumpIf EQUAL Function#15
	Message 0
	CloseMessage
	GetPartyCount 0x8004
	CompareVarValue 0x8004 2
	JumpIf GREATER/EQUAL Function#15
	Movement Overworld.0 Action#2
	WaitMovement
	Message 6
	CloseMessage
Jump Function#16

Function 3:
	InitMystriStageAnimation
End

Function 4:
	Message 14
	CMD_820 2
	SetVar 0x4009 484
Jump Function#17

Function 5:
	Message 30
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 6:
	GetPartyCount 0x8004
	CompareVarValue 0x8004 1
	JumpIf EQUAL Function#18
	CMD_490 0x4008
	SetVar 0x400A 2
Return

Function 7:
	Message 30
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 8:
	Message 31
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 9:
	Message 33
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 10:
	CMD_820 2
	SetVar 0x4009 484
Jump Function#17

Function 11:
	Message 13
	CMD_820 1
	SetVar 0x4009 483
Jump Function#17

Function 12:
	CMD_820 1
	SetVar 0x4009 483
Jump Function#17

Function 13:
	Message 15
	CMD_820 3
	SetVar 0x4009 487
Jump Function#17

Function 14:
	CMD_820 3
	SetVar 0x4009 487
Jump Function#17

Function 15:
	Message 2
	WaitButton
	CloseMessage
	SetVar 0x4004 1
	ReleaseAll
End

Function 16:
	SetVar 0x40FB 8
	SetVar 0x4104 1
	GetPlayerDirection 0x4002
	CompareVarValue 0x4002 0
	JumpIf DIFFERENT Function#19
	Movement Overworld.0 Action#3
Jump Function#20

Function 17:
	CMD_490 0x4009
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#21
	CompareVarValue 0x800C 1
	JumpIf GREATER/EQUAL Function#22
End

Function 18:
	GetFirstAlivePokemonSlot 0x4000
	CompareVarValue 0x4102 1
	JumpIf DIFFERENT Function#23
	FollowingPokemonIsEventTrigger 1 0x4000 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#24
	FollowingPokemonIsEventTrigger 2 0x4000 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#25
Jump Function#26

Function 19:
	CompareVarValue 0x4002 3
	JumpIf DIFFERENT Function#27
	Movement Overworld.0 Action#4
Jump Function#20

Function 20:
	WaitMovement
	Message 4
	CloseMessage
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	CompareVarValue 0x4002 2
	JumpIf DIFFERENT Function#28
	Movement Overworld.0 Action#5
Jump Function#29

Function 21:
	CloseMessage
	CompareVarValue 0x40FB 13
	JumpIf DIFFERENT Function#30
	SetVar 0x40FB 14
Jump Function#31

Function 22:
	CloseMessage
	CMD_820 0
	ReleaseAll
End

Function 23:
	CompareVarValue 0x4102 2
	JumpIf DIFFERENT Function#32
	FollowingPokemonIsEventTrigger 2 0x4000 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#24
	FollowingPokemonIsEventTrigger 1 0x4000 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#25
Jump Function#26

Function 24:
	SetVar 0x400A 1
Return

Function 25:
	SetVar 0x400A 3
Return

Function 26:
	SetVar 0x400A 0
Return

Function 27:
	Movement Overworld.0 Action#6
	WaitMovement
	Message 4
	CloseMessage
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	CompareVarValue 0x4002 2
	JumpIf DIFFERENT Function#28
	Movement Overworld.0 Action#5
Jump Function#29

Function 28:
	Movement Overworld.0 Action#7
	WaitMovement
	CompareVarValue 0x4002 0
	JumpIf DIFFERENT Function#33
	Movement Player Action#8
	Movement Overworld.0 Action#9
Jump Function#34

Function 29:
	WaitMovement
	CompareVarValue 0x4002 0
	JumpIf DIFFERENT Function#33
	Movement Player Action#8
	Movement Overworld.0 Action#9
Jump Function#34

Function 30:
	SetVar 0x40FB 9
	CMD_820 0
	SetVar 0x4104 0
	GetPlayerPosition 0x8004 0x8005
	LockCamera 0x8004 0x8005
	GetPlayerDirection 0x4002
	CompareVarValue 0x4009 483
	JumpIf DIFFERENT Function#35
Jump Function#36

Function 31:
	CMD_820 0
	SetVar 0x4104 0
	GetPlayerPosition 0x8004 0x8005
	LockCamera 0x8004 0x8005
	GetPlayerDirection 0x4002
	CompareVarValue 0x4009 483
	JumpIf DIFFERENT Function#35
Jump Function#36

Function 32:
Jump Function#26

Function 33:
	CompareVarValue 0x4002 3
	JumpIf DIFFERENT Function#37
	Movement Player Action#10
	Movement Overworld.0 Action#9
Jump Function#34

Function 34:
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	Message 5
	CloseMessage
	Movement Overworld.0 Action#11
	WaitMovement
	Message 7
	CloseMessage
	Movement Overworld.0 Action#12
	WaitMovement
	Message 8
	CloseMessage
	Movement Overworld.0 Action#13
	WaitMovement
	Message 9
	CloseMessage
	Movement Overworld.0 Action#14
	WaitMovement
	Message 10
	CloseMessage
	Movement Overworld.0 Action#15
	Movement Player Action#16
	WaitMovement
	Message 11
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 35:
	CompareVarValue 0x4009 484
	JumpIf DIFFERENT Function#38
Jump Function#39

Function 36:
	CompareVarValue 0x4002 0
	JumpIf DIFFERENT Function#40
	Movement Following Action#17
	Movement Camera Action#18
Jump Function#41

Function 37:
	Movement Player Action#19
	Movement Overworld.0 Action#20
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	Message 5
	CloseMessage
	Movement Overworld.0 Action#11
	WaitMovement
	Message 7
	CloseMessage
	Movement Overworld.0 Action#12
	WaitMovement
	Message 8
	CloseMessage
	Movement Overworld.0 Action#13
	WaitMovement
	Message 9
	CloseMessage
	Movement Overworld.0 Action#14
	WaitMovement
	Message 10
	CloseMessage
	Movement Overworld.0 Action#15
	Movement Player Action#16
	WaitMovement
	Message 11
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 38:
Jump Function#42

Function 39:
	CompareVarValue 0x4002 0
	JumpIf DIFFERENT Function#43
	Movement Following Action#21
	Movement Camera Action#22
Jump Function#44

Function 40:
	CompareVarValue 0x4002 3
	JumpIf DIFFERENT Function#45
	Movement Following Action#23
	Movement Camera Action#18
Jump Function#41

Function 41:
	WaitMovement
Jump Function#46

Function 42:
	CompareVarValue 0x4002 0
	JumpIf DIFFERENT Function#47
	Movement Following Action#24
	Movement Camera Action#25
Jump Function#48

Function 43:
	CompareVarValue 0x4002 3
	JumpIf DIFFERENT Function#49
	Movement Following Action#26
	Movement Camera Action#22
Jump Function#44

Function 44:
	WaitMovement
Jump Function#46

Function 45:
	CompareVarValue 0x4002 2
	JumpIf DIFFERENT Function#50
	Movement Following Action#27
	Movement Camera Action#18
Jump Function#41

Function 46:
	FadeOutMusic 0 30
	PlayFanfare SEQ_SE_GS_TAMASYUTUGEN
	UnownCircle
	StopFanfare SEQ_SE_GS_DOWSING_LOOP
	RenderCutscene 2
	CompareVarValue 0x40FB 14
	JumpIf EQUAL Function#51
	Release Overworld.0
	SetOWPosition Overworld.0 16 1 28 Up
	WaitTime 5 0x800C
	Lock Overworld.0
	CompareVarValue 0x4009 483
	JumpIf DIFFERENT Function#52
	Movement Player Action#28
Jump Function#53

Function 47:
	CompareVarValue 0x4002 3
	JumpIf DIFFERENT Function#54
	Movement Following Action#29
	Movement Camera Action#25
Jump Function#48

Function 48:
	WaitMovement
Jump Function#46

Function 49:
	CompareVarValue 0x4002 2
	JumpIf DIFFERENT Function#55
	Movement Following Action#30
	Movement Camera Action#22
Jump Function#44

Function 50:
	Movement Following Action#31
	Movement Camera Action#18
	WaitMovement
Jump Function#46

Function 51:
	CompareVarValue 0x4009 483
	JumpIf DIFFERENT Function#52
	Movement Player Action#28
Jump Function#53

Function 52:
	CompareVarValue 0x4009 484
	JumpIf DIFFERENT Function#56
	Movement Player Action#32
Jump Function#53

Function 53:
	WaitTime 150 0x800C
	FadeScreen 6 30 1 0
	WaitFadeScreen
	GetPlayerPosition 0x8004 0x8005
	LockCamera 0x8004 0x8005
	CMD_490 0x8004
	CMD_490 0x8005
	Movement Camera Action#33
	WaitMovement
	PlayFanfare SEQ_SE_GS_TAMASYUTUGEN
	CompareVarValue 0x4009 483
	JumpIf DIFFERENT Function#57
	CMD_817 0
Jump Function#58

Function 54:
	CompareVarValue 0x4002 2
	JumpIf DIFFERENT Function#59
	Movement Following Action#34
	Movement Camera Action#25
Jump Function#48

Function 55:
	Movement Following Action#35
	Movement Camera Action#22
	WaitMovement
Jump Function#46

Function 56:
	Movement Player Action#36
	WaitTime 150 0x800C
	FadeScreen 6 30 1 0
	WaitFadeScreen
	GetPlayerPosition 0x8004 0x8005
	LockCamera 0x8004 0x8005
	CMD_490 0x8004
	CMD_490 0x8005
	Movement Camera Action#33
	WaitMovement
	PlayFanfare SEQ_SE_GS_TAMASYUTUGEN
	CompareVarValue 0x4009 483
	JumpIf DIFFERENT Function#57
	CMD_817 0
Jump Function#58

Function 57:
	CompareVarValue 0x4009 484
	JumpIf DIFFERENT Function#60
	CMD_817 1
Jump Function#58

Function 58:
	StopFanfare SEQ_SE_GS_TAMASYUTUGEN
	Movement Player Action#37
	WaitMovement
	CMD_819
	WaitTime 2 0x800C
	Message 25
	CMD_490 0x4009
	TextPlayerName 0
	TextPokemon 1 0x4009 0 0
	PlaySound SEQ_ME_SHINKAOME
	Message 26
	WaitSound
	CloseMessage
	Movement Camera Action#38
	WaitMovement
	ReleaseCamera
	PlayDefaultMusic
	CMD_490 0x4009
	CompareVarValue 0x4009 483
	JumpIf DIFFERENT Function#61
	GivePokemon SPECIES_DIALGA 1 ITEM_ADAMANT_ORB 0 0 0x800C
	SetVar 0x4103 1
Jump Function#62

Function 59:
	Movement Following Action#39
	Movement Camera Action#25
	WaitMovement
Jump Function#46

Function 60:
	CMD_817 2
	StopFanfare SEQ_SE_GS_TAMASYUTUGEN
	Movement Player Action#37
	WaitMovement
	CMD_819
	WaitTime 2 0x800C
	Message 25
	CMD_490 0x4009
	TextPlayerName 0
	TextPokemon 1 0x4009 0 0
	PlaySound SEQ_ME_SHINKAOME
	Message 26
	WaitSound
	CloseMessage
	Movement Camera Action#38
	WaitMovement
	ReleaseCamera
	PlayDefaultMusic
	CMD_490 0x4009
	CompareVarValue 0x4009 483
	JumpIf DIFFERENT Function#61
	GivePokemon SPECIES_DIALGA 1 ITEM_ADAMANT_ORB 0 0 0x800C
	SetVar 0x4103 1
Jump Function#62

Function 61:
	CompareVarValue 0x4009 484
	JumpIf DIFFERENT Function#63
	GivePokemon SPECIES_PALKIA 1 ITEM_LUSTROUS_ORB 0 0 0x800C
	SetVar 0x4103 2
Jump Function#62

Function 62:
	OpenTouchScreen
	Message 32
	YesNoTouchScreen 0x800C
	CloseMessage
	CMD_815 0
	CompareVarValue 0x800C 0
	CallIf EQUAL Function#64
	CompareVarValue 0x40FB 14
	JumpIf EQUAL Function#65
	Movement Overworld.0 Action#40
	Movement Player Action#41
	Movement Following Action#42
	WaitMovement
	Message 16
	CloseMessage
	Movement Overworld.0 Action#43
	WaitMovement
	Message 17
	CloseMessage
	PlayFanfare SEQ_SE_GS_ZENIGAME_JOURO
	FadeScreen 6 6 0 0
	WaitFadeScreen
	WaitTime 1 0x800C
	FadeScreen 6 6 1 0
	WaitFadeScreen
	Movement Overworld.0 Action#44
	WaitMovement
	Message 18
	CloseMessage
	Movement Overworld.0 Action#45
	WaitMovement
	Message 19
	CloseMessage
	PlayFanfare SEQ_SE_GS_ZENIGAME_JOURO
	FadeScreen 6 6 0 0
	WaitFadeScreen
	WaitTime 1 0x800C
	FadeScreen 6 6 1 0
	WaitFadeScreen
	CompareVarValue 0x40FB 14
	JumpIf EQUAL Function#66
	GetFirstAlivePokemonSlot 0x4005
	FollowingPokemonIsEventTrigger 2 0x4005 0x4006
	CompareVarValue 0x4006 1
	JumpIf DIFFERENT Function#67
	SetVar 0x4102 1
Jump Function#68

Function 63:
	GivePokemon SPECIES_GIRATINA 1 ITEM_GRISEOUS_ORB 1 26 0x800C
	SetVar 0x4103 3
	OpenTouchScreen
	Message 32
	YesNoTouchScreen 0x800C
	CloseMessage
	CMD_815 0
	CompareVarValue 0x800C 0
	CallIf EQUAL Function#64
	CompareVarValue 0x40FB 14
	JumpIf EQUAL Function#65
	Movement Overworld.0 Action#40
	Movement Player Action#41
	Movement Following Action#42
	WaitMovement
	Message 16
	CloseMessage
	Movement Overworld.0 Action#43
	WaitMovement
	Message 17
	CloseMessage
	PlayFanfare SEQ_SE_GS_ZENIGAME_JOURO
	FadeScreen 6 6 0 0
	WaitFadeScreen
	WaitTime 1 0x800C
	FadeScreen 6 6 1 0
	WaitFadeScreen
	Movement Overworld.0 Action#44
	WaitMovement
	Message 18
	CloseMessage
	Movement Overworld.0 Action#45
	WaitMovement
	Message 19
	CloseMessage
	PlayFanfare SEQ_SE_GS_ZENIGAME_JOURO
	FadeScreen 6 6 0 0
	WaitFadeScreen
	WaitTime 1 0x800C
	FadeScreen 6 6 1 0
	WaitFadeScreen
	CompareVarValue 0x40FB 14
	JumpIf EQUAL Function#66
	GetFirstAlivePokemonSlot 0x4005
	FollowingPokemonIsEventTrigger 2 0x4005 0x4006
	CompareVarValue 0x4006 1
	JumpIf DIFFERENT Function#67
	SetVar 0x4102 1
Jump Function#68

Function 64:
	GetPartyCount 0x800C
	DecrementVar 0x800C 1
	SetVar 0x4008 0
	FadeScreen 6 1 0 0
	WaitFadeScreen
	ChoosePokemonNickname 0x800C 0x4008
	CMD_819
	FadeScreen 6 1 1 0
	WaitFadeScreen
Return

Function 65:
	PlayFanfare SEQ_SE_GS_ZENIGAME_JOURO
	FadeScreen 6 6 0 0
	WaitFadeScreen
	WaitTime 1 0x800C
	FadeScreen 6 6 1 0
	WaitFadeScreen
	CompareVarValue 0x40FB 14
	JumpIf EQUAL Function#66
	GetFirstAlivePokemonSlot 0x4005
	FollowingPokemonIsEventTrigger 2 0x4005 0x4006
	CompareVarValue 0x4006 1
	JumpIf DIFFERENT Function#67
	SetVar 0x4102 1
Jump Function#68

Function 66:
	PlayFanfare SEQ_SE_DP_KAIDAN2
	CompareVarValue 0x403E 6
	JumpIf DIFFERENT Function#69
	FadeScreen 6 1 0 0
	WaitFadeScreen
	Warp 490 0 9 24 Down
	FadeScreen 6 1 1 0
	WaitFadeScreen
Jump Function#70

Function 67:
	SetVar 0x4102 2
	ClearFlag 743
	PlayFanfare SEQ_SE_DP_KAIDAN2
	CompareVarValue 0x403E 6
	JumpIf DIFFERENT Function#69
	FadeScreen 6 1 0 0
	WaitFadeScreen
	Warp 490 0 9 24 Down
	FadeScreen 6 1 1 0
	WaitFadeScreen
Jump Function#70

Function 68:
	ClearFlag 743
	PlayFanfare SEQ_SE_DP_KAIDAN2
	CompareVarValue 0x403E 6
	JumpIf DIFFERENT Function#69
	FadeScreen 6 1 0 0
	WaitFadeScreen
	Warp 490 0 9 24 Down
	FadeScreen 6 1 1 0
	WaitFadeScreen
Jump Function#70

Function 69:
	CompareVarValue 0x403E 7
	JumpIf DIFFERENT Function#71
	FadeScreen 6 1 0 0
	WaitFadeScreen
	Warp 492 0 9 24 Down
	FadeScreen 6 1 1 0
	WaitFadeScreen
Jump Function#70

Function 70:
	ReleaseAll
End

Function 71:
	CompareVarValue 0x403E 8
	JumpIf DIFFERENT Function#72
	FadeScreen 6 1 0 0
	WaitFadeScreen
	Warp 492 0 9 24 Down
	FadeScreen 6 1 1 0
	WaitFadeScreen
Jump Function#70

Function 72:
	CompareVarValue 0x403E 9
	JumpIf DIFFERENT Function#73
	FadeScreen 6 1 0 0
	WaitFadeScreen
	Warp 492 0 9 24 Down
	FadeScreen 6 1 1 0
	WaitFadeScreen
Jump Function#70

Function 73:
	FadeScreen 6 1 0 0
	WaitFadeScreen
	Warp 315 0 9 24 Down
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

//===== ACTIONS =====//
Action 1:
	WalkSouth8 0x2
End

Action 2:
	WalkOnSpotNorth8 0x1
End

Action 3:
	WalkOnSpotSouth8 0x1
End

Action 4:
	WalkOnSpotWest8 0x1
End

Action 5:
	WalkWest8 0x1
	WalkOnSpotEast8 0x1
End

Action 6:
	WalkOnSpotEast8 0x1
End

Action 7:
	WalkEast8 0x1
	WalkOnSpotWest8 0x1
End

Action 8:
	WalkNorth8 0x6
	Delay16 0x1
	WalkOnSpotEast8 0x1
End

Action 9:
	Delay16 0x1
	WalkWest8 0x1
	WalkNorth8 0x3
	WalkEast8 0x1
	WalkNorth8 0x2
	WalkOnSpotWest8 0x1
End

Action 10:
	WalkEast8 0x1
	WalkNorth8 0x5
	Delay16 0x1
	WalkOnSpotEast8 0x1
End

Action 11:
	WalkEast8 0x3
	WalkSouth8 0x1
	WalkOnSpotWest8 0x1
End

Action 12:
	WalkSouth8 0x1
	WalkWest8 0x8
	WalkNorth8 0x1
	WalkOnSpotEast8 0x1
End

Action 13:
	WalkNorth8 0x3
	WalkEast8 0x2
	WalkNorth8 0x3
	WalkEast8 0x2
	WalkNorth8 0x1
	WalkOnSpotSouth8 0x1
End

Action 14:
	WalkSouth8 0x3
	WalkOnSpotSouth8 0x1
End

Action 15:
	WalkEast8 0x1
	WalkSouth8 0x6
	WalkWest8 0x1
	WalkOnSpotNorth8 0x1
End

Action 16:
	Delay8 0x2
	WalkOnSpotEast8 0x1
	Delay8 0x3
	WalkOnSpotEast8 0x1
End

Action 17:
	WalkEast16 0x4
	WalkNorth16 0x4
	WalkOnSpotSouth8 0x1
End

Action 18:
	WalkEast16 0x4
	WalkNorth16 0x3
End

Action 19:
	WalkWest8 0x1
	WalkNorth8 0x5
	Delay16 0x1
	WalkOnSpotEast8 0x1
End

Action 20:
	Delay16 0x1
	WalkEast8 0x1
	WalkNorth8 0x3
	WalkEast8 0x1
	WalkNorth8 0x2
	WalkOnSpotWest8 0x1
End

Action 21:
	WalkWest16 0x4
	WalkNorth16 0x4
	WalkOnSpotSouth8 0x1
End

Action 22:
	WalkWest16 0x4
	WalkNorth16 0x3
End

Action 23:
	WalkNorth16 0x2
	WalkEast16 0x5
	WalkNorth16 0x1
	WalkOnSpotSouth8 0x1
End

Action 24:
	WalkSouth16 0x3
	WalkOnSpotSouth8 0x1
End

Action 25:
	WalkSouth16 0x4
End

Action 26:
	WalkWest16 0x3
	WalkNorth16 0x3
	WalkOnSpotSouth8 0x1
End

Action 27:
	WalkEast16 0x3
	WalkNorth16 0x3
	WalkOnSpotSouth8 0x1
End

Action 28:
	WalkEast2 0x4
	FaceNorth 0x1
End

Action 29:
	WalkSouth16 0x4
	WalkEast16 0x1
	WalkOnSpotSouth8 0x1
End

Action 30:
	WalkNorth16 0x2
	WalkWest16 0x5
	WalkNorth16 0x1
	WalkOnSpotSouth8 0x1
End

Action 31:
	WalkEast16 0x4
	WalkNorth16 0x2
	WalkOnSpotSouth8 0x1
End

Action 32:
	WalkWest2 0x4
	FaceNorth 0x1
End

Action 33:
	WalkNorth8 0x3
End

Action 34:
	WalkSouth16 0x4
	WalkWest16 0x1
	WalkOnSpotSouth8 0x1
End

Action 35:
	WalkWest16 0x4
	WalkNorth16 0x2
	WalkOnSpotSouth8 0x1
End

Action 36:
	WalkSouth8 0x7
	FaceNorth 0x1
End

Action 37:
	Delay8 0x1
	EmoteExclamation 0x1
	Delay8 0x1
End

Action 38:
	WalkSouth8 0x3
End

Action 39:
	WalkEast16 0x1
	WalkSouth16 0x5
	WalkWest16 0x1
	WalkOnSpotSouth8 0x1
End

Action 40:
	WalkNorth8 0x9
End

Action 41:
	Delay16 0x2
	WalkSouth8 0x2
End

Action 42:
	Delay16 0x2
	WalkSouth8 0x4
End

Action 43:
	Delay8 0x1
	WalkOnSpotSouth8 0x1
End

Action 44:
	FaceEast 0x1
	Delay8 0x3
	FaceWest 0x1
	Delay8 0x3
End

Action 45:
	WalkOnSpotNorth8 0x1
End

