/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0132
 * Generated: 5/20/2026 9:55:34 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckFlag 158
	JumpIf EQUAL Function#1
	Message 0
	CloseMessage
	SetFlag 158
	CheckBornPokemonInParty 0x800C SPECIES_ARCEUS
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#2
	Message 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CompareVarValue 0x40FB 13
	JumpIf GREATER/EQUAL Function#3
	CheckFlag 157
	JumpIf EQUAL Function#4
	Message 7
	WaitButton
	CloseMessage
	SetFlag 157
	ReleaseAll
End

Script 3:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 10
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#5
	CompareVarValue 0x800C 1
	JumpIf GREATER/EQUAL Function#6
	Message 11
	CloseMessage
	PlayFanfare SEQ_SE_DP_TELE
	Movement Player Action#1
	WaitMovement
	CompareVarValue 0x40FB 13
	JumpIf DIFFERENT Function#7
	SetVar 0x40FB 10
Jump Function#8

Script 4:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	PlayCry SPECIES_ABRA 0
	Message 13
	WaitCry
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== FUNCTIONS =====//
Function 1:
	CheckBornPokemonInParty 0x800C SPECIES_ARCEUS
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#2
	Message 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 2:
	Movement Overworld.0 Action#2
	WaitMovement
	Message 1
	CloseMessage
	GetPlayerDirection 0x4002
	CompareVarValue 0x4002 0
	JumpIf DIFFERENT Function#9
Jump Function#10

Function 3:
	Message 9
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 4:
	Message 8
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 5:
	Message 11
	CloseMessage
	PlayFanfare SEQ_SE_DP_TELE
	Movement Player Action#1
	WaitMovement
	CompareVarValue 0x40FB 13
	JumpIf DIFFERENT Function#7
	SetVar 0x40FB 10
Jump Function#8

Function 6:
	Message 12
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 7:
	SetVar 0x40FB 1
	SetFlag 732
	ClearFlag 733
	ClearFlag 731
	FadeScreen 6 1 0 0
	WaitFadeScreen
	Warp 60 0 695 397 Down
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Function 8:
	FadeScreen 6 1 0 0
	WaitFadeScreen
	Warp 60 0 695 397 Down
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Function 9:
	CompareVarValue 0x4002 1
	JumpIf DIFFERENT Function#11
Jump Function#12

Function 10:
	Movement Overworld.0 Action#3
	WaitMovement
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	Movement Player Action#4
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	Movement Overworld.0 Action#5
	WaitMovement
	Message 3
	CloseMessage
	Movement Overworld.0 Action#6
	WaitMovement
	Movement Player Action#7
	WaitMovement
	Message 4
	CloseMessage
	Movement Overworld.0 Action#8
	WaitMovement
Jump Function#13

Function 11:
Jump Function#14

Function 12:
	Movement Overworld.0 Action#9
	WaitMovement
	Movement Overworld.0 Action#10
	WaitMovement
	Message 3
	CloseMessage
	Movement Overworld.0 Action#11
	WaitMovement
	Message 4
	CloseMessage
	Movement Overworld.0 Action#12
	WaitMovement
Jump Function#13

Function 13:
	PlayFanfare SEQ_SE_DP_KAIDAN2
	SetFlag 733
	RemoveOW Overworld.0
	ClearFlag 732
	WaitFanfare SEQ_SE_DP_KAIDAN2
	SetVar 0x40FB 7
	ReleaseAll
End

Function 14:
	Movement Overworld.0 Action#13
	WaitMovement
	Movement Overworld.0 Action#14
	WaitMovement
	Message 3
	CloseMessage
	Movement Overworld.0 Action#15
	WaitMovement
	Message 4
	CloseMessage
	Movement Overworld.0 Action#16
	WaitMovement
Jump Function#13

//===== ACTIONS =====//
Action 1:
		FaceEast 0x1
		Delay4 0x1
		FaceSouth 0x1
		Delay4 0x1
		FaceWest 0x1
		Delay4 0x1
		FaceNorth 0x1
		Delay4 0x1
		FaceEast 0x1
		Delay2 0x1
		FaceSouth 0x1
		Delay2 0x1
		FaceWest 0x1
		Delay2 0x1
		FaceNorth 0x1
		Delay2 0x1
		FaceEast 0x1
		FaceSouth 0x1
		FaceWest 0x1
		FaceNorth 0x1
		FaceEast 0x1
		FaceSouth 0x1
		FaceWest 0x1
		FaceNorth 0x1
		FaceEast 0x1
		FaceSouth 0x1
		FaceWest 0x1
		FaceNorth 0x1
End

Action 2:
		EmoteExclamation 0x1
		Delay8 0x1
End

Action 3:
		WalkOnSpotNorth8 0x1
		WalkNorth16 0x2
End

Action 4:
		WalkNorth16 0x1
End

Action 5:
		WalkOnSpotSouth8 0x1
End

Action 6:
		WalkEast8 0x1
		WalkSouth8 0x2
		WalkOnSpotWest8 0x1
End

Action 7:
		WalkOnSpotEast8 0x1
End

Action 8:
		WalkSouth8 0x2
		WalkWest8 0x5
		WalkOnSpotSouth8 0x1
End

Action 9:
		WalkOnSpotSouth8 0x1
		WalkSouth16 0x1
End

Action 10:
		WalkOnSpotNorth8 0x1
End

Action 11:
		WalkNorth8 0x1
End

Action 12:
		WalkSouth8 0x2
		WalkWest8 0x4
		WalkOnSpotSouth8 0x1
End

Action 13:
		WalkOnSpotNorth8 0x1
		WalkNorth16 0x2
End

Action 14:
		WalkOnSpotSouth8 0x1
End

Action 15:
		WalkSouth8 0x2
		WalkOnSpotEast8 0x1
End

Action 16:
		WalkSouth8 0x2
		WalkWest8 0x4
		WalkOnSpotSouth8 0x1
End

