/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0153
 * Generated: 5/20/2026 9:55:34 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckFlag 235
	JumpIf EQUAL Function#1
	Message 0
	CloseMessage
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	GetPlayerDirection 0x4000
	CompareVarValue 0x4000 2
	JumpIf DIFFERENT Function#2
	Movement Overworld.0 Action#1
	WaitMovement
	Movement Player Action#2
Jump Function#3

Script 2:
	CompareVarValue 0x40E1 2
	JumpIf EQUAL Function#4
End

Script 3:
	MecScript
	LockAll
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	Movement Player Action#3
	WaitMovement
	Movement Overworld.0 Action#4
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	SetVar 0x40E1 0
	ClearFlag 146
	ReleaseAll
End

Script 4:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Message 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 5:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 3
	CloseMessage
	Movement Overworld.2 Action#5
	WaitMovement
	ReleaseAll
End

Script 6:
	CMD_582 77 279 276
	CheckFlag 393
	JumpIf LESS Function#5
	ClearFlag 393
End

Script 7:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckPokegearNumberRegistered 35 0x4001
	CompareVarValue 0x4001 1
	JumpIf EQUAL Function#6
	CompareVarValue 0x4004 1
	JumpIf GREATER/EQUAL Function#7
	Message 4
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#8
	CompareVarValue 0x800C 1
	JumpIf GREATER/EQUAL Function#9
End

//===== FUNCTIONS =====//
Function 1:
	Message 1
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 2:
	CompareVarValue 0x4000 3
	JumpIf DIFFERENT Function#10
	Movement Overworld.0 Action#6
	WaitMovement
	Movement Player Action#7
Jump Function#3

Function 3:
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	PlayFanfare SEQ_SE_DP_KAIDAN2
	BoatAnimation 0 0 307 24 19
	ReleaseAll
End

Function 4:
	SetOWPosition Overworld.0 28 0 22 Left
End

Function 5:
	CheckPokegearNumberRegistered 35 0x4001
	CompareVarValue 0x4001 1
	JumpIf EQUAL Function#11
	CheckBadge 13 0x4000
	CompareVarValue 0x4000 1
	JumpIf EQUAL Function#12
Jump Function#13

Function 6:
	Message 9
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#14
	CheckAlbumPhoto 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#15
	Message 10
	CloseMessage
	SetFlag 393
	FadeScreen 6 1 0 0
	WaitFadeScreen
	TakePhoto 88
	FacePlayer
	LockAll
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ClearFlag 393
	Message 11
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 7:
	Message 8
Jump Function#16

Function 8:
	TextPlayerName 0
	Message 5
	PlaySound SEQ_ME_POKEGEAR_REGIST
	WaitSound
	RecordPokegearNumber 35
	Message 6
	WaitButton
	CloseMessage
	FadeScreen 6 1 0 0
	WaitFadeScreen
	SetFlag 713
	RemoveOW Overworld.3
	PlayFanfare SEQ_SE_DP_KAIDAN2
	WaitFanfare SEQ_SE_DP_KAIDAN2
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Function 9:
	SetVar 0x4004 1
	Message 7
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 10:
	CompareVarValue 0x4000 0
	JumpIf DIFFERENT Function#17
	Movement Overworld.0 Action#8
	WaitMovement
	Movement Player Action#9
Jump Function#3

Function 11:
	CheckPokeGearRematch 35 0x4001
	CompareVarValue 0x4001 0
	JumpIf DIFFERENT Function#13
	GetDayOfWeek 0x4000
	CompareVarValue 0x4000 1
	JumpIf DIFFERENT Function#13
	ClearFlag 713
End

Function 12:
	GetDayOfWeek 0x4000
	CompareVarValue 0x4000 5
	JumpIf DIFFERENT Function#13
	ClearFlag 713
End

Function 13:
	SetFlag 713
End

Function 14:
	Message 12
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 15:
	Message 13
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 16:
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#8
	CompareVarValue 0x800C 1
	JumpIf GREATER/EQUAL Function#9
End

Function 17:
	Movement Overworld.0 Action#8
	WaitMovement
	Movement Player Action#9
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	PlayFanfare SEQ_SE_DP_KAIDAN2
	BoatAnimation 0 0 307 24 19
	ReleaseAll
End

//===== ACTIONS =====//
Action 1:
		FaceWest 0x1
		WalkWest8 0x1
		WalkOnSpotEast8 0x1
End

Action 2:
		WalkWest8 0x1
		FaceNorth 0x1
		WalkNorth8 0x2
End

Action 3:
		WalkSouth8 0x3
End

Action 4:
		WalkWest8 0x1
		WalkOnSpotSouth8 0x1
End

Action 5:
		WalkOnSpotNorth8 0x1
End

Action 6:
		FaceEast 0x1
		WalkEast8 0x1
		WalkOnSpotWest8 0x1
End

Action 7:
		WalkEast8 0x1
		FaceNorth 0x1
		WalkNorth8 0x2
End

Action 8:
		FaceEast 0x1
		WalkEast8 0x1
		WalkOnSpotWest8 0x1
End

Action 9:
		WalkNorth8 0x2
End

