/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0154
 * Generated: 3/6/2026 7:25:18 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CompareVarValue 0x4002 1
	JumpIf GREATER/EQUAL Function#1
	GetPlayerDirection 0x4001
	CompareVarValue 0x4001 0
	JumpIf EQUAL Function#2
	GetDayOfWeek 0x800C
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#3
Jump Function#4

Script 2:
	GetPreviousHeaderID 0x4000
	CompareVarValue 0x4000 387
	JumpIf EQUAL Function#5
End

Script 3:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 3
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== FUNCTIONS =====//
Function 1:
	Message 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 2:
	Movement Overworld.0 Action#1
	WaitMovement
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	Movement Player Action#2
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	Movement Overworld.0 Action#3
	WaitMovement
	ReleaseAll
End

Function 3:
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#6
Jump Function#7

Function 4:
	Message 0
	CloseMessage
	Movement Overworld.0 Action#4
	WaitMovement
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	Movement Player Action#5
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	SetVar 0x4002 1
	SetVar 0x40E1 2
	SetVar 0x40DC 0
	ClearFlag 235
	SetFlag 554
	ClearFlag 556
	SetFlag 555
	ReleaseAll
End

Function 5:
	SetOWDefaultDirection Overworld.0 Down
End

Function 6:
	CompareVarValue 0x800C 2
	JumpIf DIFFERENT Function#8
Jump Function#7

Function 7:
	Message 1
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 8:
	CompareVarValue 0x800C 3
	JumpIf DIFFERENT Function#9
Jump Function#4

Function 9:
	CompareVarValue 0x800C 4
	JumpIf DIFFERENT Function#10
Jump Function#7

Function 10:
	CompareVarValue 0x800C 5
	JumpIf DIFFERENT Function#11
Jump Function#7

Function 11:
Jump Function#7

//===== ACTIONS =====//
Action 1:
	LockDir 0x1
	WalkNorth8 0x1
	ReleaseDir 0x1
	FaceWest 0x2
	LockDir 0x1
	WalkEast8 0x1
	ReleaseDir 0x1
End

Action 2:
	Delay8 0x1
	WalkNorth8 0x4
End

Action 3:
	WalkWest8 0x1
	FaceSouth 0x2
	WalkSouth8 0x1
	WalkOnSpotNorth8 0x1
End

Action 4:
	LockDir 0x1
	WalkSouth8 0x1
	ReleaseDir 0x1
	FaceWest 0x2
	LockDir 0x1
	WalkEast8 0x1
	ReleaseDir 0x1
End

Action 5:
	WalkSouth8 0x2
End

