/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0155
 * Generated: 5/20/2026 9:55:34 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckFlag 235
	JumpIf EQUAL Function#1
	Message 0
	CloseMessage
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	GetPlayerDirection 0x4000
	CompareVarValue 0x4000 2
	JumpIf DIFFERENT Function#2
	Movement Overworld.0 Action#1
	WaitMovement
	Movement Player Action#2
Jump Function#3

Script 2:
	MecScript
	LockAll
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	Movement Player Action#3
	WaitMovement
	Movement Overworld.0 Action#4
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	SetVar 0x40E1 0
	ClearFlag 146
	ReleaseAll
End

Script 3:
	CompareVarValue 0x40E1 1
	JumpIf EQUAL Function#4
End

Script 4:
	CheckFlag 360
	JumpIf EQUAL Function#5
	SetFlag 2456
	UpdateTownMap 2
	SetFlag 360
	SetFlag 2485
	CMD_582 54 1309 340
End

//===== FUNCTIONS =====//
Function 1:
	Message 1
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 2:
	CompareVarValue 0x4000 3
	JumpIf DIFFERENT Function#6
	Movement Overworld.0 Action#5
	WaitMovement
	Movement Player Action#6
Jump Function#3

Function 3:
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	PlayFanfare SEQ_SE_DP_KAIDAN2
	BoatAnimation 1 0 307 24 19
	ReleaseAll
End

Function 4:
	SetOWPosition Overworld.0 24 0 19 Left
End

Function 5:
	UpdateTownMap 2
	SetFlag 360
	SetFlag 2485
	CMD_582 54 1309 340
End

Function 6:
	Movement Overworld.0 Action#7
	WaitMovement
	Movement Player Action#8
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	PlayFanfare SEQ_SE_DP_KAIDAN2
	BoatAnimation 1 0 307 24 19
	ReleaseAll
End

//===== ACTIONS =====//
Action 1:
		FaceWest 0x1
		WalkWest8 0x1
		WalkOnSpotEast8 0x1
End

Action 2:
		WalkWest8 0x1
		FaceNorth 0x1
		WalkNorth8 0x2
End

Action 3:
		WalkSouth8 0x3
End

Action 4:
		WalkWest8 0x1
		WalkOnSpotSouth8 0x1
End

Action 5:
		FaceEast 0x1
		WalkEast8 0x1
		WalkOnSpotWest8 0x1
End

Action 6:
		WalkEast8 0x1
		FaceNorth 0x1
		WalkNorth8 0x2
End

Action 7:
		FaceEast 0x1
		WalkEast8 0x1
		WalkOnSpotWest8 0x1
End

Action 8:
		WalkNorth8 0x2
End

