/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0158
 * Generated: 3/6/2026 7:25:18 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckFlag 237
	JumpIf LESS Function#1
	GetPlayerDirection 0x800C
	CompareVarValue 0x800C 3
	JumpIf EQUAL Function#2
	Movement Overworld.0 Action#1
	WaitMovement
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	Movement Overworld.0 Action#2
	Movement Player Action#3
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	Message 5
	CloseMessage
	TrainerBattle TRAINER_STANLY_238 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#3
	Message 6
	CloseMessage
	Movement Overworld.0 Action#4
	WaitMovement
	SetVar 0x40CB 3
	RemoveOW Overworld.0
	SetFlag 538
	ReleaseAll
End

Script 2:
	MecScript
	LockAll
	Movement Player Action#5
	WaitMovement
	Message 0
	CloseMessage
	FadeScreen 6 1 0 0
	WaitFadeScreen
	PlaySound SEQ_ME_ASA
	WaitSound
	HealPokemon
	FinishOverworldScreen
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	Message 1
	CloseMessage
	CheckPokemonAlive 0x4002
	CompareVarValue 0x4002 0
	JumpIf EQUAL Function#4
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 56
	Movement Player Action#6
	WaitMovement
	CompareVarValue 0x4002 0
	JumpIf EQUAL Function#5
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	CompareVarValue 0x40CB 7
	JumpIf GREATER/EQUAL Function#6
	ReleaseAll
End

//===== FUNCTIONS =====//
Function 1:
	Message 4
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 2:
	Movement Overworld.0 Action#7
	WaitMovement
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	Movement Overworld.0 Action#8
	Movement Player Action#9
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	Message 5
	CloseMessage
	TrainerBattle TRAINER_STANLY_238 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#3
	Message 6
	CloseMessage
	Movement Overworld.0 Action#10
	WaitMovement
	SetVar 0x40CB 3
	RemoveOW Overworld.0
	SetFlag 538
	ReleaseAll
End

Function 3:
	LostBattle
	ReleaseAll
End

Function 4:
	Movement Player Action#6
	WaitMovement
	CompareVarValue 0x4002 0
	JumpIf EQUAL Function#5
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	CompareVarValue 0x40CB 7
	JumpIf GREATER/EQUAL Function#6
	ReleaseAll
End

Function 5:
	CompareVarValue 0x40CB 7
	JumpIf GREATER/EQUAL Function#6
	ReleaseAll
End

Function 6:
	CheckFlag 235
	JumpIf EQUAL Function#7
	PlayFanfare SEQ_SE_DP_PINPON
	WaitFanfare SEQ_SE_DP_PINPON
	SetFlag 235
	CompareVarValue 0x40E1 1
	JumpIf DIFFERENT Function#8
	Message 3
Jump Function#9

Function 7:
	ReleaseAll
End

Function 8:
	Message 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 9:
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== ACTIONS =====//
Action 1:
	EmoteExclamation 0x1
	Delay8 0x1
	FaceEast 0x2
	FaceWest 0x2
	FaceEast 0x2
	LockDir 0x1
	JumpFarWest 0x1
	ReleaseDir 0x1
End

Action 2:
	FaceNorth 0x2
	WalkNorth4 0x2
	FaceEast 0x2
	WalkEast4 0x4
	FaceSouth 0x2
	WalkSouth4 0x1
End

Action 3:
	Delay16 0x1
	FaceEast 0x2
	WalkEast8 0x1
	FaceNorth 0x2
End

Action 4:
	FaceNorth 0x2
	WalkNorth4 0x7
End

Action 5:
	FaceSouth 0x2
	Delay16 0x1
	EmoteExclamation 0x1
End

Action 6:
	FaceEast 0x2
	JumpEast8 0x1
End

Action 7:
	EmoteExclamation 0x1
	Delay8 0x1
	FaceWest 0x2
	FaceEast 0x2
	FaceWest 0x2
	LockDir 0x1
	JumpFarEast 0x1
	ReleaseDir 0x1
End

Action 8:
	FaceNorth 0x2
	WalkNorth4 0x2
	FaceWest 0x2
	WalkWest4 0x4
	FaceSouth 0x2
	WalkSouth4 0x1
End

Action 9:
	Delay16 0x1
	FaceWest 0x2
	WalkWest8 0x1
	FaceNorth 0x2
End

Action 10:
	FaceNorth 0x2
	WalkNorth4 0x3
	FaceEast 0x2
	WalkEast4 0x4
	FaceNorth 0x2
	WalkNorth4 0x4
End

