/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0161
 * Generated: 3/6/2026 7:25:18 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CompareVarValue 0x40CB 3
	JumpIf GREATER Function#1
	Movement Overworld.0 Action#1
	WaitMovement
	Message 1
Jump Function#2

Script 2:
	CompareVarValue 0x40CB 7
	JumpIf GREATER/EQUAL Function#3
	CompareVarValue 0x40CB 4
	JumpIf GREATER Function#4
	SetFlag 536
Jump Function#5

Script 3:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 8
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 4:
	MecScript
	LockAll
	Movement Overworld.4 Action#2
	WaitMovement
	GenderMessage 2 3
	CloseMessage
	Movement Overworld.0 Action#3
	WaitMovement
	TextPlayerName 0
	GenderMessage 4 5
	SetVar 0x8004 233
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#6
	CommonScript 2033
	SetVar 0x40CB 6
	SetFlag 554
	PlayFanfare SEQ_SE_DP_PINPON
	WaitFanfare SEQ_SE_DP_PINPON
	SetFlag 235
	Message 6
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== FUNCTIONS =====//
Function 1:
	CompareVarValue 0x40CB 4
	JumpIf DIFFERENT Function#7
	Message 0
Jump Function#2

Function 2:
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 3:
	SetFlag 534
	SetFlag 536
End

Function 4:
	ClearFlag 536
End

Function 5:
End

Function 6:
	CommonScript 2009
	CloseMessage
Jump Function#8

Function 7:
	Message 7
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 8:
	SetVar 0x40CB 6
	SetFlag 554
	PlayFanfare SEQ_SE_DP_PINPON
	WaitFanfare SEQ_SE_DP_PINPON
	SetFlag 235
	Message 6
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== ACTIONS =====//
Action 1:
	JumpOnSpotSouth8 0x2
End

Action 2:
	JumpOnSpotEast8 0x3
End

Action 3:
	WalkSouth16 0x1
End

