/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0162
 * Generated: 5/20/2026 9:55:34 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CompareVarValue 0x40CB 3
	JumpIf GREATER/EQUAL Function#1
	Message 1
	WaitButton
	CloseMessage
	SetFlag 237
	ReleaseAll
End

Script 2:
	MecScript
	LockAll
	SetFlag 237
	GetPlayerPosition 0x4000 0x4001
	CompareVarValue 0x4001 19
	JumpIf EQUAL Function#2
	Movement Overworld.1 Action#1
	CheckPokemonAlive 0x4002
	CompareVarValue 0x4002 0
	JumpIf EQUAL Function#3
	Movement Following Action#2
	Movement Player Action#3
	WaitMovement
	Message 0
	CloseMessage
	Movement Overworld.1 Action#4
	WaitMovement
	ReleaseAll
End

Script 3:
	CompareVarValue 0x40CB 4
	JumpIf DIFFERENT Function#4
	ClearFlag 537
Jump Function#5

Script 4:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Movement Overworld.0 Action#5
	WaitMovement
	CheckPokemonAlive 0x4002
	CompareVarValue 0x4002 0
	JumpIf EQUAL Function#6
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 56
	GetPlayerDirection 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#7
	Movement Player Action#6
	Movement Overworld.0 Action#7
Jump Function#8

//===== FUNCTIONS =====//
Function 1:
	Message 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 2:
	Movement Overworld.1 Action#8
	CompareVarValue 0x4002 0
	JumpIf EQUAL Function#9
	Movement Following Action#2
	Movement Player Action#3
	WaitMovement
	Message 0
	CloseMessage
	Movement Overworld.1 Action#9
	WaitMovement
	ReleaseAll
End

Function 3:
	Movement Player Action#3
	WaitMovement
	Message 0
	CloseMessage
	Movement Overworld.1 Action#4
	WaitMovement
	ReleaseAll
End

Function 4:
	SetFlag 537
End

Function 5:
End

Function 6:
	GetPlayerDirection 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#7
	Movement Player Action#6
	Movement Overworld.0 Action#7
Jump Function#8

Function 7:
	Movement Player Action#10
	Movement Overworld.0 Action#11
	WaitMovement
	CompareVarValue 0x4002 0
	JumpIf EQUAL Function#10
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	Message 6
	CloseMessage
	PlayFanfare SEQ_SE_DP_KAIDAN2
	WaitFanfare SEQ_SE_DP_KAIDAN2
	SetVar 0x40CB 5
	FadeScreen 6 1 0 0
	WaitFadeScreen
	Warp 328 0 9 10 Up
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Function 8:
	WaitMovement
	CompareVarValue 0x4002 0
	JumpIf EQUAL Function#10
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	Message 6
	CloseMessage
	PlayFanfare SEQ_SE_DP_KAIDAN2
	WaitFanfare SEQ_SE_DP_KAIDAN2
	SetVar 0x40CB 5
	FadeScreen 6 1 0 0
	WaitFadeScreen
	Warp 328 0 9 10 Up
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Function 9:
	Movement Player Action#3
	WaitMovement
	Message 0
	CloseMessage
	Movement Overworld.1 Action#9
	WaitMovement
	ReleaseAll
End

Function 10:
	Message 6
	CloseMessage
	PlayFanfare SEQ_SE_DP_KAIDAN2
	WaitFanfare SEQ_SE_DP_KAIDAN2
	SetVar 0x40CB 5
	FadeScreen 6 1 0 0
	WaitFadeScreen
	Warp 328 0 9 10 Up
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

//===== ACTIONS =====//
Action 1:
		FaceNorth 0x2
		WalkNorth8 0x1
		FaceWest 0x2
End

Action 2:
		LockDir 0x1
		WalkWest8 0x1
		ReleaseDir 0x1
End

Action 3:
		LockDir 0x1
		WalkWest8 0x1
		ReleaseDir 0x1
End

Action 4:
		FaceSouth 0x2
		WalkSouth8 0x1
		FaceWest 0x2
End

Action 5:
		EmoteExclamation 0x1
		Delay8 0x1
End

Action 6:
		LockDir 0x1
		WalkNorth16 0x1
		ReleaseDir 0x1
End

Action 7:
		FaceNorth 0x2
		WalkNorth16 0x1
End

Action 8:
		FaceSouth 0x2
		WalkSouth8 0x1
		FaceWest 0x2
End

Action 9:
		FaceNorth 0x2
		WalkNorth8 0x1
		FaceWest 0x2
End

Action 10:
		LockDir 0x1
		WalkEast16 0x2
		ReleaseDir 0x1
End

Action 11:
		FaceEast 0x2
		WalkEast16 0x2
End

