/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0191
 * Generated: 5/20/2026 9:55:34 PM
 */

//===== SCRIPTS =====//
Script 1:
	MecScript
	LockAll
	CheckFlag 280
	JumpIf EQUAL Function#1
	CheckPokemonAlive 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#2
	GetFollowingPokeSize 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#2
	SendBackFollowingPoke
	PlayFanfare SEQ_SE_DP_KAIDAN2
	FadeScreen 6 1 0 0
	WaitFadeScreen
	Warp 489 0 7 20 Up
	FadeScreen 6 1 1 0
	WaitFadeScreen
	CMD_582 18 1423 185
	ReleaseAll
End

Script 2:
	CheckBadge 15 0x4004
	CompareVarValue 0x4004 1
	JumpIf EQUAL Function#3
Jump Function#4

Script 3:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckPokegearNumberRegistered 36 0x4001
	CompareVarValue 0x4001 1
	JumpIf EQUAL Function#5
	CheckBike 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#6
	GetFirstAlivePokemonSlot 0x4000
	GetPartyPokemonID 0x4000 0x4001
	CompareVarValue 0x4001 25
	JumpIf DIFFERENT Function#6
	CompareVarValue 0x4002 1
	JumpIf GREATER/EQUAL Function#7
	Message 0
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#8
	CompareVarValue 0x800C 1
	JumpIf GREATER/EQUAL Function#9
End

Script 4:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	PlayCry SPECIES_ZAPDOS 0
	WaitCry
	SetFlag 164
	WildBattleSp SPECIES_ZAPDOS 50 0
	ClearFlag 164
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#10
	GetBattleOutcome 0x4002
	CompareVarValue 0x4002 3
	JumpIf EQUAL Function#11
	CompareVarValue 0x4002 4
	CallIf EQUAL Function#12
	ReleaseAll
End

Script 5:
	CheckFlag 164
	JumpIf EQUAL Function#13
End

Script 6:
	SetTextBoard 2 0
	ShowBoard 3
	WaitBoard
	BoardMessage 8 0x800C
	CommonScript 2000
End

Script 7:
	SetTextBoard 2 0
	ShowBoard 3
	WaitBoard
	BoardMessage 9 0x800C
	CommonScript 2000
End

//===== FUNCTIONS =====//
Function 1:
	CheckPokemonAlive 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#14
	GetFollowingPokeSize 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#14
	SendBackFollowingPoke
	PlayFanfare SEQ_SE_DP_KAIDAN2
	FadeScreen 6 1 0 0
	WaitFadeScreen
	Warp 467 0 7 20 Up
	FadeScreen 6 1 1 0
	WaitFadeScreen
	CMD_582 18 1423 185
	ReleaseAll
End

Function 2:
	PlayFanfare SEQ_SE_DP_KAIDAN2
	FadeScreen 6 1 0 0
	WaitFadeScreen
	Warp 489 0 7 20 Up
	FadeScreen 6 1 1 0
	WaitFadeScreen
	CMD_582 18 1423 185
	ReleaseAll
End

Function 3:
	CheckFlag 330
	JumpIf LESS Function#4
	CheckPokegearNumberRegistered 36 0x4001
	CompareVarValue 0x4001 1
	JumpIf EQUAL Function#4
	GetHour 0x4000
	CompareVarValue 0x4000 9
	JumpIf DIFFERENT Function#15
	ClearFlag 612
Jump Function#16

Function 4:
End

Function 5:
	Message 2
	WaitButton
	CloseMessage
	FadeScreen 6 1 0 0
	WaitFadeScreen
	SetFlag 612
	RemoveOW Overworld.0
	PlayFanfare SEQ_SE_DP_KAIDAN2
	WaitFanfare SEQ_SE_DP_KAIDAN2
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Function 6:
	Message 5
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 7:
	Message 4
Jump Function#17

Function 8:
	TextPlayerName 0
	Message 1
	PlaySound SEQ_ME_POKEGEAR_REGIST
	WaitSound
	RecordPokegearNumber 36
	Message 2
	WaitButton
	CloseMessage
	FadeScreen 6 1 0 0
	WaitFadeScreen
	SetFlag 612
	RemoveOW Overworld.0
	PlayFanfare SEQ_SE_DP_KAIDAN2
	WaitFanfare SEQ_SE_DP_KAIDAN2
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Function 9:
	SetVar 0x4002 1
	Message 3
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 10:
	LostBattle
	ReleaseAll
End

Function 11:
	ReleaseAll
End

Function 12:
	SetFlag 330
Return

Function 13:
	SetFlag 663
	RemoveOW Overworld.1
	ClearFlag 164
End

Function 14:
	PlayFanfare SEQ_SE_DP_KAIDAN2
	FadeScreen 6 1 0 0
	WaitFadeScreen
	Warp 467 0 7 20 Up
	FadeScreen 6 1 1 0
	WaitFadeScreen
	CMD_582 18 1423 185
	ReleaseAll
End

Function 15:
	CompareVarValue 0x4000 10
	JumpIf DIFFERENT Function#18
	ClearFlag 612
Jump Function#16

Function 16:
End

Function 17:
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#8
	CompareVarValue 0x800C 1
	JumpIf GREATER/EQUAL Function#9
End

Function 18:
	CompareVarValue 0x4000 11
	JumpIf DIFFERENT Function#19
	ClearFlag 612
Jump Function#16

Function 19:
	SetFlag 612
End

//===== ACTIONS =====//
