/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0199
 * Generated: 5/20/2026 9:55:34 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 0
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#1
	CheckAlbumPhoto 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#2
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 1
	CloseMessage
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	GetPlayerDirection 0x800C
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#3
	Movement Player Action#1
	Movement Overworld.13 Action#2
Jump Function#4

Script 2:
	CheckFlag 393
	JumpIf LESS Function#5
	ClearFlag 393
End

Script 3:
	SetIconBoard 0 1 3 0x800C
	ShowBoard 3
	WaitBoard
	CloseBoard 0x800C
	CommonScript 2000
End

Script 4:
	SetTextBoard 2 0
	ShowBoard 3
	WaitBoard
	BoardMessage 1 0x800C
	CommonScript 2000
End

Script 5:
	CheckFlag 164
	JumpIf EQUAL Function#6
	CheckFlag 249
	JumpIf EQUAL Function#7
End

Script 6:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	CheckCurrentRadioSong 5 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#8
	Message 2
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== FUNCTIONS =====//
Function 1:
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 5
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 2:
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 3
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 3:
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#9
	Movement Player Action#3
Jump Function#4

Function 4:
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	CheckPokemonAlive 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#10
	Movement Following Action#4
	WaitMovement
	SetFlag 393
	FadeScreen 6 1 0 0
	WaitFadeScreen
	TakePhoto 59
	LockAll
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ClearFlag 393
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 5:
	GetDayOfWeek 0x4000
	CompareVarValue 0x4000 1
	JumpIf EQUAL Function#11
	CompareVarValue 0x4000 3
	JumpIf EQUAL Function#11
	SetFlag 638
End

Function 6:
	SetFlag 795
	RemoveOW Overworld.15
	RemoveOW Overworld.16
	RemoveOW Overworld.17
	RemoveOW Overworld.18
	ClearFlag 164
End

Function 7:
End

Function 8:
	PlayCry SPECIES_SNORLAX 0
	Message 3
	WaitCry
	CloseMessage
	SetFlag 164
	WildBattleSp SPECIES_SNORLAX 50 0
	ClearFlag 164
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#12
	GetBattleOutcome 0x4005
	CompareVarValue 0x4005 4
	CallIf EQUAL Function#13
	SetFlag 249
	ReleaseAll
End

Function 9:
	CompareVarValue 0x800C 3
	JumpIf DIFFERENT Function#14
	Movement Player Action#5
	Movement Overworld.13 Action#2
Jump Function#4

Function 10:
	SetFlag 393
	FadeScreen 6 1 0 0
	WaitFadeScreen
	TakePhoto 59
	LockAll
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ClearFlag 393
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 11:
	ClearFlag 638
End

Function 12:
	LostBattle
	ReleaseAll
End

Function 13:
	SetFlag 371
Return

Function 14:
	Movement Player Action#6
	Movement Overworld.13 Action#2
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	CheckPokemonAlive 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#10
	Movement Following Action#4
	WaitMovement
	SetFlag 393
	FadeScreen 6 1 0 0
	WaitFadeScreen
	TakePhoto 59
	LockAll
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ClearFlag 393
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 2
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== ACTIONS =====//
Action 1:
		WalkEast8 0x1
		WalkNorth8 0x2
		WalkWest8 0x1
		WalkNorth8 0x3
		WalkOnSpotSouth8 0x1
End

Action 2:
		Delay8 0x1
		WalkOnSpotNorth8 0x1
End

Action 3:
		WalkNorth8 0x3
		WalkOnSpotSouth8 0x1
End

Action 4:
		WalkEast8 0x1
		WalkNorth8 0x1
		FaceSouth 0x1
End

Action 5:
		WalkNorth8 0x1
		WalkEast8 0x1
		WalkNorth8 0x3
		WalkOnSpotSouth8 0x1
End

Action 6:
		WalkNorth8 0x1
		WalkWest8 0x1
		WalkNorth8 0x3
		WalkOnSpotSouth8 0x1
End

