/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0206
 * Generated: 5/20/2026 9:55:34 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 0
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckFlag 2746
	JumpIf EQUAL Function#1
	CMD_540 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#2
	Message 1
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#3
	CMD_538 0x800C 0
	CompareVarValue 0x800C 0xFFFF
	JumpIf EQUAL Function#2
	SetFlag 2746
	Message 2
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== FUNCTIONS =====//
Function 1:
	Message 4
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 2:
	Message 5
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 3:
	Message 3
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== ACTIONS =====//
