/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0215
 * Generated: 5/20/2026 9:55:34 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	CompareVarValue 0x4087 2
	JumpIf DIFFERENT Function#1
Jump Function#2

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	CompareVarValue 0x4087 2
	JumpIf DIFFERENT Function#3
Jump Function#4

Script 3:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	StopMusic 1061
	PlayMusic SEQ_GS_EYE_ROCKET
	Message 0
	CloseMessage
	TrainerBattle TRAINER_GRUNT_353 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#5
	Message 2
	CloseMessage
	FadeOutMusic 0 30
	Message 3
	CloseMessage
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 56
	Movement Overworld.2 Action#1
	Movement Player Action#2
	Movement Overworld.0 Action#3
	Movement Overworld.1 Action#4
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	RemoveOW Overworld.2
	SetFlag 597
	ClearFlag 599
	PlayMusic SEQ_GS_R_12_24
	SetVar 0x4087 3
	ReleaseAll
End

Script 4:
	MecScript
	LockAll
	GetPlayerDirection 0x4000
	CompareVarValue 0x4000 0
	JumpIf DIFFERENT Function#6
	Movement Overworld.2 Action#5
	Movement Overworld.0 Action#6
	Movement Overworld.1 Action#7
Jump Function#7

Script 5:
	CompareVarValue 0x4087 2
	JumpIf EQUAL Function#8
End

//===== FUNCTIONS =====//
Function 1:
	CompareVarValue 0x4087 3
	JumpIf DIFFERENT Function#9
	FacePlayer
	Message 5
Jump Function#10

Function 2:
	Message 4
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 3:
	CompareVarValue 0x4087 3
	JumpIf DIFFERENT Function#11
	FacePlayer
	Message 8
Jump Function#12

Function 4:
	Message 7
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 5:
	LostBattle
	ReleaseAll
End

Function 6:
	Movement Overworld.2 Action#8
	Movement Overworld.0 Action#6
	Movement Overworld.1 Action#7
	WaitMovement
	SetVar 0x4087 2
	ReleaseAll
End

Function 7:
	WaitMovement
	SetVar 0x4087 2
	ReleaseAll
End

Function 8:
	SetVar 0x4087 1
End

Function 9:
	FacePlayer
	Message 6
Jump Function#10

Function 10:
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 11:
	FacePlayer
	Message 9
Jump Function#12

Function 12:
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== ACTIONS =====//
Action 1:
		WalkEast4 0x1
		WalkSouth4 0xA
End

Action 2:
		LockDir 0x1
		WalkEast4 0x1
		ReleaseDir 0x1
		FaceSouth 0x1
End

Action 3:
		Delay4 0xC
		FaceWest 0x1
End

Action 4:
		Delay4 0x1
		FaceSouth 0x1
		Delay4 0xA
		WalkNorth8 0x1
		FaceWest 0x1
End

Action 5:
		EmoteExclamation 0x1
		WalkWest4 0x3
End

Action 6:
		Delay16 0x3
		FaceSouth 0x1
End

Action 7:
		Delay16 0x3
		WalkSouth4 0x1
		FaceNorth 0x1
End

Action 8:
		FaceNorth 0x1
		EmoteExclamation 0x1
		WalkWest4 0x3
End

