/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0221
 * Generated: 5/20/2026 9:55:34 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 1
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 2:
	MecScript
	LockAll
	Movement Overworld.0 Action#1
	WaitMovement
	Message 0
	CloseMessage
	GetPlayerPosition 0x4000 0x4001
	CompareVarValue 0x4001 402
	JumpIf DIFFERENT Function#1
	Movement Overworld.0 Action#2
Jump Function#2

Script 3:
	SetTextBoard 2 0
	ShowBoard 3
	WaitBoard
	BoardMessage 2 0x800C
	CommonScript 2000
End

Script 4:
	CheckFlag 360
	JumpIf EQUAL Function#3
	UpdateTownMap 1
End

Script 5:
	SetIconBoard 3 1 5 0x800C
	ShowBoard 3
	WaitBoard
	CloseBoard 0x800C
	CommonScript 2000
End

//===== FUNCTIONS =====//
Function 1:
	CompareVarValue 0x4001 403
	JumpIf DIFFERENT Function#4
	Movement Overworld.0 Action#3
Jump Function#2

Function 2:
	WaitMovement
	Message 1
	WaitButton
	CloseMessage
	ReleaseAll
	SetVar 0x408A 1
End

Function 3:
End

Function 4:
	Movement Overworld.0 Action#4
	WaitMovement
	Message 1
	WaitButton
	CloseMessage
	ReleaseAll
	SetVar 0x408A 1
End

//===== ACTIONS =====//
Action 1:
		EmoteExclamation 0x1
End

Action 2:
		WalkNorth8 0x1
		WalkWest8 0x4
End

Action 3:
		WalkWest8 0x4
End

Action 4:
		WalkSouth8 0x1
		WalkWest8 0x4
End

