/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0224
 * Generated: 5/20/2026 9:55:34 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckFlag 311
	JumpIf EQUAL Function#1
	FacePlayer
	GetPlayerDirection 0x800C
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#2
	Movement Overworld.0 Action#1
Jump Function#3

Script 2:
	PlayCry SPECIES_FEAROW 0
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 3
	WaitButton
	CloseMessage
	ReleaseAll
	WaitCry
End

Script 3:
	Movement Overworld.0 Action#2
	WaitMovement
	SetVar 0x4126 1
End

//===== FUNCTIONS =====//
Function 1:
	Message 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 2:
	CompareVarValue 0x800C 2
	JumpIf DIFFERENT Function#4
	Movement Overworld.0 Action#3
Jump Function#3

Function 3:
	WaitMovement
	Message 0
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#5
	Movement Overworld.0 Action#4
Jump Function#6

Function 4:
	CompareVarValue 0x800C 3
	JumpIf DIFFERENT Function#7
	Movement Overworld.0 Action#5
Jump Function#3

Function 5:
	CompareVarValue 0x800C 2
	JumpIf DIFFERENT Function#8
	Movement Overworld.0 Action#5
Jump Function#6

Function 6:
	WaitMovement
	Message 1
	SetVar 0x8004 374
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#9
	CommonScript 2033
	SetFlag 311
	Message 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 7:
	Movement Overworld.0 Action#4
	WaitMovement
	Message 0
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#5
	Movement Overworld.0 Action#4
Jump Function#6

Function 8:
	CompareVarValue 0x800C 3
	JumpIf DIFFERENT Function#10
	Movement Overworld.0 Action#3
Jump Function#6

Function 9:
	CommonScript 2009
	CloseMessage
	ReleaseAll
End

Function 10:
	Movement Overworld.0 Action#1
	WaitMovement
	Message 1
	SetVar 0x8004 374
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#9
	CommonScript 2033
	SetFlag 311
	Message 2
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== ACTIONS =====//
Action 1:
		Delay8 0x1
		WalkOnSpotNorth8 0x1
End

Action 2:
		FaceSouth 0x1
		EmoteExclamation 0x1
End

Action 3:
		Delay8 0x1
		WalkOnSpotWest8 0x1
End

Action 4:
		Delay8 0x1
		WalkOnSpotSouth8 0x1
End

Action 5:
		Delay8 0x1
		WalkOnSpotEast8 0x1
End

