/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0226
 * Generated: 5/20/2026 9:55:34 PM
 */

//===== SCRIPTS =====//
Script 1:
End

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 0
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 3:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 1
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== FUNCTIONS =====//
//===== ACTIONS =====//
