/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0227
 * Generated: 5/20/2026 9:55:34 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Message 0
	CloseMessage
	Movement Overworld.6 Action#1
	WaitMovement
	Movement Overworld.7 Action#2
	WaitMovement
	PlayFanfare SEQ_SE_CONFIRM
	FacePlayer
	Message 1
	CloseMessage
	Movement Overworld.8 Action#3
	WaitMovement
	ReleaseAll
End

Script 2:
	SetFlag 238
	SetVar 0x8004 1
	SetVar 0x8005 2
	SetVar 0x8006 0
	CommonScript 2039
	SetVar 0x408C 3
End

Script 3:
	MecScript
	LockAll
	DoorAnimation 17 11 11 3 77
	OpenDoor 77
	WaitDoor 77
	ClearFlag 591
	AddOW Overworld.13
	Movement Overworld.13 Action#4
	WaitMovement
	CloseDoor 77
	WaitDoor 77
	FreeDoor 77
	Movement Overworld.13 Action#5
	WaitMovement
	Message 5
	CloseMessage
	GetPlayerPosition 0x4000 0x4001
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	CompareVarValue 0x4000 558
	JumpIf DIFFERENT Function#1
	Movement Player Action#6
Jump Function#2

Script 4:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 13
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 5:
	MecScript
	LockAll
	SetVar 0x8004 0
	SetVar 0x8005 2
	SetVar 0x8006 0
	CommonScript 2039
	SetVar 0x4095 0
	SetFlag 167
	ReleaseAll
End

Script 6:
	SetIconBoard 9 1 6 0x800C
	ShowBoard 3
	WaitBoard
	CloseBoard 0x800C
	CommonScript 2000
End

Script 7:
	SetIconBoard 10 1 3 0x800C
	ShowBoard 3
	WaitBoard
	CloseBoard 0x800C
	CommonScript 2000
End

Script 8:
	SetTextBoard 3 0
	ShowBoard 3
	WaitBoard
	BoardMessage 12 0x800C
	CommonScript 2000
End

Script 9:
	SetTextBoard 2 0
	ShowBoard 3
	WaitBoard
	BoardMessage 11 0x800C
	CommonScript 2000
End

Script 10:
	CheckFlag 107
	JumpIf EQUAL Function#3
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 11:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 4
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== FUNCTIONS =====//
Function 1:
	CompareVarValue 0x4000 559
	JumpIf DIFFERENT Function#4
	Movement Player Action#7
Jump Function#2

Function 2:
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	Message 6
	SetVar 0x8004 468
	SetVar 0x8005 1
	CommonScript 2033
	Message 8
	CloseMessage
	Movement Overworld.13 Action#8
	WaitMovement
	DoorAnimation 17 11 11 3 77
	OpenDoor 77
	WaitDoor 77
	Movement Overworld.13 Action#9
	WaitMovement
	CloseDoor 77
	WaitDoor 77
	FreeDoor 77
	RemoveOW Overworld.13
	SetFlag 591
	ReleaseAll
	SetFlag 109
	SetVar 0x408C 1
End

Function 3:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 3
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 4:
	CompareVarValue 0x4000 560
	JumpIf DIFFERENT Function#5
	Movement Player Action#10
Jump Function#2

Function 5:
	Movement Player Action#11
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	Message 6
	SetVar 0x8004 468
	SetVar 0x8005 1
	CommonScript 2033
	Message 8
	CloseMessage
	Movement Overworld.13 Action#8
	WaitMovement
	DoorAnimation 17 11 11 3 77
	OpenDoor 77
	WaitDoor 77
	Movement Overworld.13 Action#9
	WaitMovement
	CloseDoor 77
	WaitDoor 77
	FreeDoor 77
	RemoveOW Overworld.13
	SetFlag 591
	ReleaseAll
	SetFlag 109
	SetVar 0x408C 1
End

//===== ACTIONS =====//
Action 1:
		JumpOnSpotNorth8 0x3
End

Action 2:
		JumpOnSpotSouth8 0x2
End

Action 3:
		WalkOnSpotNorth8 0x1
End

Action 4:
		WalkSouth8 0x1
End

Action 5:
		WalkOnSpotEast8 0x1
End

Action 6:
		WalkSouth8 0x2
		WalkOnSpotWest8 0x1
		Delay8 0x2
		WalkWest8 0x2
End

Action 7:
		WalkSouth8 0x2
		WalkOnSpotWest8 0x1
		Delay8 0x2
		WalkWest8 0x3
End

Action 8:
		WalkOnSpotNorth8 0x1
End

Action 9:
		WalkNorth8 0x1
		SetInvisible 0x1
End

Action 10:
		WalkSouth8 0x2
		WalkOnSpotWest8 0x1
		Delay8 0x2
		WalkWest8 0x4
End

Action 11:
		WalkSouth8 0x2
		WalkOnSpotWest8 0x1
		Delay8 0x2
		WalkWest8 0x5
End

