/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0233
 * Generated: 3/6/2026 7:25:18 PM
 */

//===== SCRIPTS =====//
Script 1:
	SetVar 0x8007 3
	CommonScript 2002
End

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckFlag 117
	JumpIf EQUAL Function#1
	Message 0
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#2
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#3
End

Script 3:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckFlag 372
	JumpIf EQUAL Function#4
	Message 7
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#5
	Message 8
Jump Function#6

Script 4:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 6
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== FUNCTIONS =====//
Function 1:
	Message 5
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 2:
	SetVar 0x8004 445
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#7
	CommonScript 2033
	SetFlag 117
	Message 3
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 3:
	Message 4
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 4:
	Message 11
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 5:
	Message 9
	SetVar 0x8004 494
	SetVar 0x8005 2
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#8
	CommonScript 2033
	Message 10
	WaitButton
	CloseMessage
	ReleaseAll
	SetFlag 372
End

Function 6:
	SetVar 0x8004 494
	SetVar 0x8005 2
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#8
	CommonScript 2033
	Message 10
	WaitButton
	CloseMessage
	ReleaseAll
	SetFlag 372
End

Function 7:
	CommonScript 2009
	CloseMessage
	ReleaseAll
End

Function 8:
	CommonScript 2009
	CloseMessage
	ReleaseAll
End

//===== ACTIONS =====//
