/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0743
 * Generated: 3/6/2026 7:25:19 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckBadge 15 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#1
	Message 0
	CloseMessage
	TrainerBattle TRAINER_BLUE_261 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#2
	GiveBadge 15
	IncrementVar 0x4135 1
	SetFlag 2456
	AddTrainerScore 22
	SetTrainerFlag TRAINER_ARABELLA_681
	SetTrainerFlag TRAINER_SALMA_683
	SetTrainerFlag TRAINER_BONITA_682
	SetTrainerFlag TRAINER_ELAN_AND_IDA_684
	SetFlag 2431
	ClearFlag 663
	SetFlag 783
	SetVar 0x4096 1
	Message 1
	TextPlayerName 0
	Message 2
	PlaySound SEQ_ME_BADGE
	WaitSound
	Message 3
Jump Function#3

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckBadge 15 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#4
	Message 6
	SendBackFollowingPoke
	SetFollowingPokeStatus 1
	NoBallResetFollowingPoke
	SetOWMovement Following Move.56
	SetVar 0x4127 1
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 3:
	ViridianGymInit
	SetVar 0x4127 0
	CheckPokeGearRematch 31 0x4001
	CompareVarValue 0x4001 0
	JumpIf DIFFERENT Function#5
	CompareVarValue 0x40FD 0
	JumpIf EQUAL Function#6
	GetDayOfWeek 0x4002
	CompareVarValue 0x4002 5
	JumpIf DIFFERENT Function#7
	SetFlag 758
Jump Function#8

Script 4:
	MecScript
	LockAll
	CheckFlag 314
	JumpIf EQUAL Function#9
	GetPlayerPosition 0x4000 0x4001
	CompareVarValue 0x4000 1
	JumpIf DIFFERENT Function#10
	Movement Overworld.4 Action#1
	Movement Player Action#2
Jump Function#11

Script 5:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckBadge 15 0x800C
	TextPlayerName 0
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#12
	Message 9
Jump Function#13

//===== FUNCTIONS =====//
Function 1:
	CheckFlag 382
	JumpIf LESS Function#3
	Message 5
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 2:
	LostBattle
	ReleaseAll
End

Function 3:
	SetVar 0x8004 419
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#14
	CommonScript 2033
	SetFlag 382
	TextPlayerName 0
	Message 4
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 4:
	Message 7
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 5:
	SetFlag 758
End

Function 6:
	ClearFlag 758
End

Function 7:
	ClearFlag 758
End

Function 8:
End

Function 9:
	SendBackFollowingPoke
	SetFollowingPokeStatus 1
	NoBallResetFollowingPoke
	SetOWMovement Following Move.56
	SetVar 0x4127 1
	ReleaseAll
End

Function 10:
	CompareVarValue 0x4000 2
	JumpIf DIFFERENT Function#15
	Movement Overworld.4 Action#3
	Movement Player Action#2
Jump Function#11

Function 11:
	WaitMovement
	Message 8
	CloseMessage
	SetFlag 314
	CompareVarValue 0x4000 1
	JumpIf DIFFERENT Function#16
	Movement Overworld.4 Action#4
Jump Function#17

Function 12:
	Message 10
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 13:
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 14:
	CommonScript 2009
	CloseMessage
	ReleaseAll
End

Function 15:
	CompareVarValue 0x4000 3
	JumpIf DIFFERENT Function#18
	Movement Overworld.4 Action#5
	Movement Player Action#2
Jump Function#11

Function 16:
	CompareVarValue 0x4000 2
	JumpIf DIFFERENT Function#19
	Movement Overworld.4 Action#6
Jump Function#17

Function 17:
	WaitMovement
	SendBackFollowingPoke
	SetFollowingPokeStatus 1
	NoBallResetFollowingPoke
	SetOWMovement Following Move.56
	SetVar 0x4127 1
	ReleaseAll
End

Function 18:
	CompareVarValue 0x4000 4
	JumpIf DIFFERENT Function#20
	Movement Overworld.4 Action#7
	Movement Player Action#8
Jump Function#11

Function 19:
	CompareVarValue 0x4000 3
	JumpIf DIFFERENT Function#21
	Movement Overworld.4 Action#9
Jump Function#17

Function 20:
	CompareVarValue 0x4000 5
	JumpIf DIFFERENT Function#22
	Movement Overworld.4 Action#10
	Movement Player Action#8
Jump Function#11

Function 21:
	CompareVarValue 0x4000 4
	JumpIf DIFFERENT Function#23
	Movement Overworld.4 Action#11
Jump Function#17

Function 22:
	CompareVarValue 0x4000 6
	JumpIf DIFFERENT Function#24
	Movement Overworld.4 Action#12
	Movement Player Action#8
Jump Function#11

Function 23:
	CompareVarValue 0x4000 5
	JumpIf DIFFERENT Function#25
	Movement Overworld.4 Action#13
Jump Function#17

Function 24:
	CompareVarValue 0x4000 8
	JumpIf DIFFERENT Function#26
	Movement Overworld.4 Action#14
	Movement Player Action#15
Jump Function#11

Function 25:
	CompareVarValue 0x4000 6
	JumpIf DIFFERENT Function#27
	Movement Overworld.4 Action#16
Jump Function#17

Function 26:
	Movement Overworld.4 Action#17
	Movement Player Action#15
	WaitMovement
	Message 8
	CloseMessage
	SetFlag 314
	CompareVarValue 0x4000 1
	JumpIf DIFFERENT Function#16
	Movement Overworld.4 Action#4
Jump Function#17

Function 27:
	CompareVarValue 0x4000 8
	JumpIf DIFFERENT Function#28
	Movement Overworld.4 Action#16
Jump Function#17

Function 28:
	Movement Overworld.4 Action#18
	WaitMovement
	SendBackFollowingPoke
	SetFollowingPokeStatus 1
	NoBallResetFollowingPoke
	SetOWMovement Following Move.56
	SetVar 0x4127 1
	ReleaseAll
End

//===== ACTIONS =====//
Action 1:
	FaceWest 0x1
	EmoteExclamation 0x1
	WalkWest8 0x5
End

Action 2:
	Delay16 0x2
	FaceEast 0x1
End

Action 3:
	FaceWest 0x1
	EmoteExclamation 0x1
	WalkWest8 0x4
End

Action 4:
	WalkEast8 0x5
	FaceSouth 0x1
End

Action 5:
	FaceWest 0x1
	EmoteExclamation 0x1
	WalkWest8 0x3
End

Action 6:
	WalkEast8 0x4
	FaceSouth 0x1
End

Action 7:
	FaceWest 0x1
	EmoteExclamation 0x1
	WalkWest8 0x2
End

Action 8:
	Delay8 0x2
	FaceEast 0x1
End

Action 9:
	WalkEast8 0x3
	FaceSouth 0x1
End

Action 10:
	FaceWest 0x1
	EmoteExclamation 0x1
	WalkWest8 0x1
End

Action 11:
	WalkEast8 0x2
	FaceSouth 0x1
End

Action 12:
	FaceWest 0x1
	EmoteExclamation 0x1
End

Action 13:
	WalkEast8 0x1
	FaceSouth 0x1
End

Action 14:
	FaceEast 0x1
	EmoteExclamation 0x1
End

Action 15:
	Delay8 0x2
	FaceWest 0x1
End

Action 16:
	FaceSouth 0x1
End

Action 17:
	FaceEast 0x1
	EmoteExclamation 0x1
	WalkEast8 0x1
End

Action 18:
	WalkWest8 0x1
	FaceSouth 0x1
End

