/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0752
 * Generated: 5/20/2026 9:55:36 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckBadge 8 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#1
	Message 0
	CloseMessage
	TrainerBattle TRAINER_BROCK_253 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#2
	GiveBadge 8
	IncrementVar 0x4135 1
	AddTrainerScore 22
	SetTrainerFlag TRAINER_JERRY_308
	SetTrainerFlag TRAINER_EDWIN_685
	Message 1
	TextPlayerName 0
	Message 2
	PlaySound SEQ_ME_BADGE
	WaitSound
	TextPlayerName 0
	GenderMessage 3 4
Jump Function#3

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckBadge 8 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#4
	Message 6
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 3:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckBadge 8 0x800C
	TextPlayerName 0
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#5
	Message 8
Jump Function#6

Script 4:
	CheckPokeGearRematch 33 0x4001
	CompareVarValue 0x4001 0
	JumpIf DIFFERENT Function#7
	CheckPokegearNumberRegistered 33 0x4001
	CompareVarValue 0x4001 1
	JumpIf EQUAL Function#8
	CheckBadge 15 0x4002
	CompareVarValue 0x4002 1
	JumpIf EQUAL Function#9
Jump Function#10

//===== FUNCTIONS =====//
Function 1:
	CheckFlag 383
	JumpIf LESS Function#3
	TextPlayerName 0
	Message 5
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 2:
	LostBattle
	ReleaseAll
End

Function 3:
	SetVar 0x8004 407
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#11
	CommonScript 2033
	SetFlag 383
	CheckFlag 383
	JumpIf LESS Function#3
	TextPlayerName 0
	Message 5
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 4:
	Message 7
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 5:
	Message 9
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 6:
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 7:
	SetFlag 756
End

Function 8:
	GetHour 0x4000
	CompareVarValue 0x4000 17
	JumpIf DIFFERENT Function#12
	SetFlag 756
Jump Function#13

Function 9:
	GetHour 0x4000
	CompareVarValue 0x4000 12
	JumpIf DIFFERENT Function#14
	SetFlag 756
Jump Function#15

Function 10:
	ClearFlag 756
End

Function 11:
	CommonScript 2009
	CloseMessage
	ReleaseAll
End

Function 12:
	CompareVarValue 0x4000 18
	JumpIf DIFFERENT Function#16
	SetFlag 756
Jump Function#13

Function 13:
End

Function 14:
	CompareVarValue 0x4000 13
	JumpIf DIFFERENT Function#17
	SetFlag 756
Jump Function#15

Function 15:
End

Function 16:
	CompareVarValue 0x4000 19
	JumpIf DIFFERENT Function#18
	SetFlag 756
Jump Function#13

Function 17:
	CompareVarValue 0x4000 14
	JumpIf DIFFERENT Function#19
	SetFlag 756
Jump Function#15

Function 18:
Jump Function#10

Function 19:
Jump Function#10

//===== ACTIONS =====//
