/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0775
 * Generated: 3/6/2026 7:25:19 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 0
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 1
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 3:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 4:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckFlag 287
	JumpIf EQUAL Function#1
	CheckFlag 280
	JumpIf EQUAL Function#2
	Message 3
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 5:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckFlag 287
	JumpIf EQUAL Function#3
	Message 8
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 6:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Message 10
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 7:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Message 11
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== FUNCTIONS =====//
Function 1:
	Message 7
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 2:
	TextPlayerName 0
	GenderMessage 4 5
	Message 6
	PlaySound SEQ_ME_KEYITEM
	WaitSound
	SetFlag 287
	CheckFlag 138
	JumpIf EQUAL Function#1
	UpgradePokegear 2
	Message 7
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 3:
	Message 9
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== ACTIONS =====//
