/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0785
 * Generated: 5/20/2026 9:55:38 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 0
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	PlayCry SPECIES_POLIWRATH 0
	Message 1
	WaitCry
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 3:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 4:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 3
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 5:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 4
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 6:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 5
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 7:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 6
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 8:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 7
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 9:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 8
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 10:
	SetIconBoard 30 0 7 0x800C
	ShowBoard 3
	WaitBoard
	CloseBoard 0x800C
	CommonScript 2000
End

Script 11:
	SetTextBoard 2 0
	ShowBoard 3
	WaitBoard
	BoardMessage 31 0x800C
	CommonScript 2000
End

Script 12:
	SetTextBoard 2 0
	ShowBoard 3
	WaitBoard
	BoardMessage 32 0x800C
	CommonScript 2000
End

Script 13:
	SetTextBoard 2 0
	ShowBoard 3
	WaitBoard
	BoardMessage 33 0x800C
	CommonScript 2000
End

Script 14:
	SetTextBoard 2 0
	ShowBoard 3
	WaitBoard
	BoardMessage 34 0x800C
	CommonScript 2000
End

Script 15:
	SetTextBoard 3 0
	ShowBoard 3
	WaitBoard
	BoardMessage 35 0x800C
	CommonScript 2000
End

Script 16:
	CheckFlag 393
	JumpIf LESS Function#1
	ClearFlag 393
End

Script 17:
	CheckPokegearNumberRegistered 28 0x4001
	CompareVarValue 0x4001 1
	JumpIf EQUAL Function#2
	CompareVarValue 0x4005 2
	JumpIf EQUAL Function#3
	CompareVarValue 0x4005 1
	JumpIf EQUAL Function#4
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	SetVar 0x4005 1
	Movement Overworld.9 Action#1
	WaitMovement
	Message 9
	CloseMessage
	Movement Overworld.10 Action#2
	WaitMovement
	Message 10
	CloseMessage
	Movement Overworld.9 Action#1
	WaitMovement
	Message 11
	CloseMessage
	Movement Overworld.10 Action#2
	WaitMovement
	Message 12
	CloseMessage
	Movement Overworld.9 Action#1
	WaitMovement
	Message 13
	CloseMessage
	Movement Overworld.10 Action#2
	WaitMovement
	Message 14
	CloseMessage
	Movement Overworld.9 Action#1
	WaitMovement
	Message 15
	CloseMessage
	Movement Overworld.10 Action#2
	WaitMovement
	Message 16
	CloseMessage
	Movement Overworld.9 Action#1
	WaitMovement
	Message 17
	CloseMessage
	Movement Overworld.10 Action#2
	WaitMovement
	Message 18
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 18:
	CompareVarValue 0x4002 1
	JumpIf GREATER/EQUAL Function#5
Jump Function#6

Script 19:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 0
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#7
	CheckAlbumPhoto 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#8
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 1
	CloseMessage
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	GetPlayerDirection 0x800C
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#9
	Movement Player Action#3
	Movement Overworld.13 Action#4
Jump Function#10

//===== FUNCTIONS =====//
Function 1:
	GetDayOfWeek 0x4000
	CompareVarValue 0x4000 2
	JumpIf DIFFERENT Function#11
	ClearFlag 638
Jump Function#12

Function 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 24
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#13
	CheckAlbumPhoto 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#14
	Message 25
	CloseMessage
	SetFlag 393
	FadeScreen 6 1 0 0
	WaitFadeScreen
	TakePhoto 81
	FacePlayer
	LockAll
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ClearFlag 393
	Message 26
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 3:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 23
Jump Function#15

Function 4:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	SetVar 0x4005 2
	TextPlayerName 0
	Message 19
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#16
	CompareVarValue 0x800C 1
	JumpIf GREATER/EQUAL Function#17
End

Function 5:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 29
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 6:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	SetVar 0x4005 1
	Movement Overworld.9 Action#1
	WaitMovement
	Message 9
	CloseMessage
	Movement Overworld.10 Action#2
	WaitMovement
	Message 10
	CloseMessage
	Movement Overworld.9 Action#1
	WaitMovement
	Message 11
	CloseMessage
	Movement Overworld.10 Action#2
	WaitMovement
	Message 12
	CloseMessage
	Movement Overworld.9 Action#1
	WaitMovement
	Message 13
	CloseMessage
	Movement Overworld.10 Action#2
	WaitMovement
	Message 14
	CloseMessage
	Movement Overworld.9 Action#1
	WaitMovement
	Message 15
	CloseMessage
	Movement Overworld.10 Action#2
	WaitMovement
	Message 16
	CloseMessage
	Movement Overworld.9 Action#1
	WaitMovement
	Message 17
	CloseMessage
	Movement Overworld.10 Action#2
	WaitMovement
	Message 18
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 7:
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 5
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 8:
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 3
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 9:
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#18
	Movement Player Action#5
Jump Function#10

Function 10:
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	CheckPokemonAlive 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#19
	Movement Following Action#6
	WaitMovement
	SetFlag 393
	FadeScreen 6 1 0 0
	WaitFadeScreen
	TakePhoto 57
	LockAll
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ClearFlag 393
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 11:
	CompareVarValue 0x4000 5
	JumpIf DIFFERENT Function#20
	ClearFlag 638
Jump Function#12

Function 12:
	CheckPokegearNumberRegistered 28 0x4001
	CompareVarValue 0x4001 1
	JumpIf EQUAL Function#21
	CheckBadge 15 0x4002
	CompareVarValue 0x4002 1
	JumpIf EQUAL Function#22
Jump Function#23

Function 13:
	Message 27
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 14:
	Message 28
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 15:
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#16
	CompareVarValue 0x800C 1
	JumpIf GREATER/EQUAL Function#17
End

Function 16:
	TextPlayerName 0
	Message 20
	PlaySound SEQ_ME_POKEGEAR_REGIST
	WaitSound
	RecordPokegearNumber 28
	Message 21
	WaitButton
	CloseMessage
	FadeScreen 6 1 0 0
	WaitFadeScreen
	SetFlag 605
	RemoveOW Overworld.9
	RemoveOW Overworld.10
	PlayFanfare SEQ_SE_DP_KAIDAN2
	WaitFanfare SEQ_SE_DP_KAIDAN2
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Function 17:
	Message 22
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 18:
	CompareVarValue 0x800C 3
	JumpIf DIFFERENT Function#24
	Movement Player Action#7
	Movement Overworld.13 Action#4
Jump Function#10

Function 19:
	SetFlag 393
	FadeScreen 6 1 0 0
	WaitFadeScreen
	TakePhoto 57
	LockAll
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ClearFlag 393
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 20:
	SetFlag 638
	CheckPokegearNumberRegistered 28 0x4001
	CompareVarValue 0x4001 1
	JumpIf EQUAL Function#21
	CheckBadge 15 0x4002
	CompareVarValue 0x4002 1
	JumpIf EQUAL Function#22
Jump Function#23

Function 21:
	CheckPokeGearRematch 28 0x4001
	CompareVarValue 0x4001 0
	JumpIf DIFFERENT Function#23
	GetDayOfWeek 0x4000
	CompareVarValue 0x4000 1
	JumpIf DIFFERENT Function#25
	ClearFlag 605
	SetFlag 737
Jump Function#26

Function 22:
	GetDayOfWeek 0x4000
	CompareVarValue 0x4000 6
	JumpIf DIFFERENT Function#27
Jump Function#28

Function 23:
	SetFlag 605
	SetFlag 737
End

Function 24:
	Movement Player Action#8
	Movement Overworld.13 Action#4
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	CheckPokemonAlive 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#19
	Movement Following Action#6
	WaitMovement
	SetFlag 393
	FadeScreen 6 1 0 0
	WaitFadeScreen
	TakePhoto 57
	LockAll
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ClearFlag 393
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 25:
Jump Function#23

Function 26:
End

Function 27:
	CompareVarValue 0x4000 0
	JumpIf DIFFERENT Function#29
Jump Function#28

Function 28:
	GetHour 0x4000
	CompareVarValue 0x4000 14
	JumpIf DIFFERENT Function#30
	ClearFlag 605
	ClearFlag 737
Jump Function#31

Function 29:
Jump Function#23

Function 30:
	CompareVarValue 0x4000 15
	JumpIf DIFFERENT Function#32
	ClearFlag 605
	ClearFlag 737
Jump Function#31

Function 31:
End

Function 32:
	CompareVarValue 0x4000 16
	JumpIf DIFFERENT Function#33
	ClearFlag 605
	ClearFlag 737
Jump Function#31

Function 33:
Jump Function#23

//===== ACTIONS =====//
Action 1:
		WalkOnSpotEast8 0x1
End

Action 2:
		WalkOnSpotWest8 0x1
End

Action 3:
		WalkEast8 0x1
		WalkNorth8 0x2
		WalkWest8 0x1
		WalkNorth8 0x3
		WalkOnSpotSouth8 0x1
End

Action 4:
		Delay8 0x1
		WalkOnSpotNorth8 0x1
End

Action 5:
		WalkNorth8 0x3
		WalkOnSpotSouth8 0x1
End

Action 6:
		WalkEast8 0x1
		WalkNorth8 0x1
		FaceSouth 0x1
End

Action 7:
		WalkNorth8 0x1
		WalkEast8 0x1
		WalkNorth8 0x3
		WalkOnSpotSouth8 0x1
End

Action 8:
		WalkNorth8 0x1
		WalkWest8 0x1
		WalkNorth8 0x3
		WalkOnSpotSouth8 0x1
End

