/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0790
 * Generated: 5/20/2026 9:55:38 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CommonScript 2011
	FreezeMessage
	SetVar 0x8004 18
	CommonScript 2052
	ReleaseAll
End

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CommonScript 2011
	FreezeMessage
	SetVar 0x8004 19
	CommonScript 2052
	ReleaseAll
End

Script 3:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 0
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 4:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 1
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 5:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Message 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 6:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 0
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#1
	CheckAlbumPhoto 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#2
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 1
	CloseMessage
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	GetPlayerDirection 0x800C
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#3
	Movement Player Action#1
	Movement Overworld.4 Action#2
Jump Function#4

Script 7:
	CheckFlag 393
	JumpIf LESS Function#5
	ClearFlag 393
End

Script 8:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	CheckItem ITEM_FASHION_CASE 1 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#6
	Message 3
	GetPlayerDirection 0x4000
	CompareVarValue 0x4000 2
	JumpIf DIFFERENT Function#7
	Movement Overworld.5 Action#3
Jump Function#8

//===== FUNCTIONS =====//
Function 1:
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 5
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 2:
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 3
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 3:
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#9
	Movement Player Action#4
Jump Function#4

Function 4:
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	CheckPokemonAlive 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#10
	Movement Following Action#5
	WaitMovement
	SetFlag 393
	FadeScreen 6 1 0 0
	WaitFadeScreen
	TakePhoto 58
	LockAll
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ClearFlag 393
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 5:
	GetDayOfWeek 0x4000
	CompareVarValue 0x4000 5
	JumpIf DIFFERENT Function#11
	ClearFlag 638
Jump Function#12

Function 6:
	Message 9
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 7:
	Movement Overworld.5 Action#6
	WaitMovement
	Message 4
	Movement Overworld.5 Action#7
	WaitMovement
	CompareVarValue 0x4000 0
	JumpIf DIFFERENT Function#13
	Movement Overworld.5 Action#8
Jump Function#14

Function 8:
	WaitMovement
	Message 4
	Movement Overworld.5 Action#7
	WaitMovement
	CompareVarValue 0x4000 0
	JumpIf DIFFERENT Function#13
	Movement Overworld.5 Action#8
Jump Function#14

Function 9:
	CompareVarValue 0x800C 3
	JumpIf DIFFERENT Function#15
	Movement Player Action#9
	Movement Overworld.4 Action#2
Jump Function#4

Function 10:
	SetFlag 393
	FadeScreen 6 1 0 0
	WaitFadeScreen
	TakePhoto 58
	LockAll
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ClearFlag 393
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 11:
	SetFlag 638
End

Function 12:
End

Function 13:
	CompareVarValue 0x4000 2
	JumpIf DIFFERENT Function#16
	Movement Overworld.5 Action#10
Jump Function#14

Function 14:
	WaitMovement
	Message 5
	SetVar 0x8004 92
	SetVar 0x8005 1
	CommonScript 2007
	Message 6
	SetVar 0x8004 93
	SetVar 0x8005 1
	CommonScript 2007
	Message 7
	SetVar 0x8004 94
	SetVar 0x8005 1
	CommonScript 2007
	Message 8
	CloseMessage
	CompareVarValue 0x4000 3
	CallIf EQUAL Function#17
	CompareVarValue 0x4000 3
	JumpIf DIFFERENT Function#18
	Movement Overworld.5 Action#11
Jump Function#19

Function 15:
	Movement Player Action#12
	Movement Overworld.4 Action#2
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	CheckPokemonAlive 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#10
	Movement Following Action#5
	WaitMovement
	SetFlag 393
	FadeScreen 6 1 0 0
	WaitFadeScreen
	TakePhoto 58
	LockAll
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ClearFlag 393
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 16:
	Movement Overworld.5 Action#13
	WaitMovement
	Message 5
	SetVar 0x8004 92
	SetVar 0x8005 1
	CommonScript 2007
	Message 6
	SetVar 0x8004 93
	SetVar 0x8005 1
	CommonScript 2007
	Message 7
	SetVar 0x8004 94
	SetVar 0x8005 1
	CommonScript 2007
	Message 8
	CloseMessage
	CompareVarValue 0x4000 3
	CallIf EQUAL Function#17
	CompareVarValue 0x4000 3
	JumpIf DIFFERENT Function#18
	Movement Overworld.5 Action#11
Jump Function#19

Function 17:
	CheckPokemonAlive 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#20
	GetOWPosition Following 0x8004 0x8005
	CompareVarValue 0x8005 5
	JumpIf DIFFERENT Function#20
	Release Following
	Movement Following Action#14
	WaitMovement
	Lock Following
Return

Function 18:
	Movement Overworld.5 Action#15
	WaitMovement
	RemoveOW Overworld.5
	SetFlag 787
	ClearFlag 735
	ReleaseAll
End

Function 19:
	WaitMovement
	RemoveOW Overworld.5
	SetFlag 787
	ClearFlag 735
	ReleaseAll
End

Function 20:
Return

//===== ACTIONS =====//
Action 1:
		WalkEast8 0x1
		WalkNorth8 0x2
		WalkWest8 0x1
		WalkNorth8 0x3
		WalkOnSpotSouth8 0x1
End

Action 2:
		Delay8 0x1
		WalkOnSpotNorth8 0x1
End

Action 3:
		WalkWest8 0x1
		WalkOnSpotNorth8 0x1
		Delay8 0x1
		WalkEast8 0x1
		WalkOnSpotNorth8 0x1
End

Action 4:
		WalkNorth8 0x3
		WalkOnSpotSouth8 0x1
End

Action 5:
		WalkEast8 0x1
		WalkNorth8 0x1
		FaceSouth 0x1
End

Action 6:
		WalkEast8 0x1
		WalkOnSpotNorth8 0x1
		Delay8 0x1
		WalkWest8 0x1
		WalkOnSpotNorth8 0x1
End

Action 7:
		EmoteExclamation 0x1
End

Action 8:
		WalkOnSpotSouth8 0x1
End

Action 9:
		WalkNorth8 0x1
		WalkEast8 0x1
		WalkNorth8 0x3
		WalkOnSpotSouth8 0x1
End

Action 10:
		WalkOnSpotEast8 0x1
End

Action 11:
		WalkSouth8 0x1
		WalkWest8 0x6
		WalkNorth8 0x1
		WalkWest8 0x4
End

Action 12:
		WalkNorth8 0x1
		WalkWest8 0x1
		WalkNorth8 0x3
		WalkOnSpotSouth8 0x1
End

Action 13:
		WalkOnSpotWest8 0x1
End

Action 14:
		WalkWest6 0x1
		WalkNorth6 0x1
		FaceSouth 0x1
End

Action 15:
		WalkWest8 0x2
		WalkSouth8 0x1
		WalkWest8 0x4
		WalkNorth8 0x1
		WalkWest8 0x4
End

