/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0800
 * Generated: 3/6/2026 7:25:19 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckFlag 344
	JumpIf EQUAL Function#1
	Message 0
	GetTimePeriod 0x4000
	CompareVarValue 0x4000 3
	JumpIf EQUAL Function#2
	CompareVarValue 0x4000 4
	JumpIf EQUAL Function#2
	Message 1
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== FUNCTIONS =====//
Function 1:
	Message 3
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 2:
	Message 2
	SetVar 0x8004 247
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#3
	CommonScript 2033
	SetFlag 344
	Message 3
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 3:
	CommonScript 2009
	CloseMessage
	ReleaseAll
End

//===== ACTIONS =====//
