/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0819
 * Generated: 5/20/2026 9:55:39 PM
 */

//===== SCRIPTS =====//
Script 1:
	SetVar 0x8007 0
	CommonScript 2002
End

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 0
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 3:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 1
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 4:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	PlayCry SPECIES_ABRA 0
	Message 2
	WaitCry
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 5:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CommonScript 2011
	FreezeMessage
	SetVar 0x8004 13
	CommonScript 2052
	ReleaseAll
End

Script 6:
	SetFlag 523
	SetFlag 524
	SetFlag 525
	SetFlag 526
	ClearFlag 529
	ClearFlag 530
	ClearFlag 531
	ClearFlag 532
	ClearFlag 228
	ClearFlag 229
	ClearFlag 230
	ClearFlag 231
	CompareVarValue 0x40FC 1
	JumpIf LESS/EQUAL Function#1
	CheckFlag 2729
	JumpIf EQUAL Function#1
	GetDayOfWeek 0x4000
	CompareVarValue 0x4000 1
	JumpIf DIFFERENT Function#2
	SetVar 0x4119 1
Jump Function#3

Script 7:
	MecScript
	LockAll
	FadeOutMusic 0 3
	Movement Player Action#1
	WaitMovement
	CommonScript 2031
	GetPlayerPosition 0x8000 0x8001
	ClearFlag 592
	AddOW Overworld.5
	SetOWPosition Overworld.5 0x8000 0 23 Up
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	Movement Overworld.5 Action#2
	Movement Player Action#3
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	TextRivalName 0
	Message 3
	CloseMessage
	CheckStarter 0x800C
	CompareVarValue 0x800C 152
	JumpIf DIFFERENT Function#4
	TrainerBattle TRAINER_SILVER_490 TRAINER_NONE 0 0
Jump Function#5

Script 8:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 7
	OpenTouchScreen
	MultiTouchLocalText 1 1 0 1 0x800C
	CreateMultiTouchBox 8 255 0
	CreateMultiTouchBox 9 255 1
	CreateMultiTouchBox 10 255 2
	CloseMultiTouch
	SetVarFromVariable 0x8008 0x800C
	CompareVarValue 0x8008 0
	JumpIf EQUAL Function#6
	CompareVarValue 0x8008 1
	JumpIf EQUAL Function#7
Jump Function#8

Script 9:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CompareVarValue 0x4005 1
	JumpIf GREATER/EQUAL Function#9
	Message 5
	CloseMessage
	GetPlayerDirection 0x4000
	CompareVarValue 0x4000 2
	JumpIf DIFFERENT Function#10
	Movement Overworld.8 Action#4
Jump Function#11

//===== FUNCTIONS =====//
Function 1:
End

Function 2:
	CompareVarValue 0x4000 3
	JumpIf DIFFERENT Function#12
	SetVar 0x4119 1
Jump Function#3

Function 3:
End

Function 4:
	CompareVarValue 0x800C 155
	JumpIf DIFFERENT Function#13
	TrainerBattle TRAINER_SILVER_491 TRAINER_NONE 0 0
Jump Function#5

Function 5:
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#14
	CommonScript 2070
	TextRivalName 0
	Message 4
	CloseMessage
	Movement Overworld.5 Action#5
	WaitMovement
	SetVar 0x4119 0
	SetFlag 2729
	RemoveOW Overworld.5
	CommonScript 2071
	ReleaseAll
End

Function 6:
	CompareVarValue 0x40E6 0
	JumpIf EQUAL Function#15
	Message 11
	MultiTouchLocalText 1 1 0 1 0x800C
	CreateMultiTouchBox 12 255 0
	CreateMultiTouchBox 13 255 1
	CreateMultiTouchBox 14 255 2
	CloseMultiTouch
	SetVarFromVariable 0x8008 0x800C
	CompareVarValue 0x8008 0
	JumpIf EQUAL Function#15
	CompareVarValue 0x8008 1
	JumpIf EQUAL Function#16
Jump Function#17

Function 7:
	CompareVarValue 0x40E6 0
	JumpIf EQUAL Function#18
	Message 11
	MultiTouchLocalText 1 1 0 1 0x800C
	CreateMultiTouchBox 12 255 0
	CreateMultiTouchBox 13 255 1
	CreateMultiTouchBox 14 255 2
	CloseMultiTouch
	SetVarFromVariable 0x8008 0x800C
	CompareVarValue 0x8008 0
	JumpIf EQUAL Function#18
	CompareVarValue 0x8008 1
	JumpIf EQUAL Function#19
Jump Function#20

Function 8:
	CloseTouchScreen
	CloseMessage
	ReleaseAll
End

Function 9:
	Message 6
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 10:
	Movement Overworld.8 Action#6
	WaitMovement
	WaitMovement
	SetVar 0x4005 1
	ReleaseAll
End

Function 11:
	WaitMovement
	SetVar 0x4005 1
	ReleaseAll
End

Function 12:
	SetVar 0x4119 0
End

Function 13:
	TrainerBattle TRAINER_SILVER_489 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#14
	CommonScript 2070
	TextRivalName 0
	Message 4
	CloseMessage
	Movement Overworld.5 Action#5
	WaitMovement
	SetVar 0x4119 0
	SetFlag 2729
	RemoveOW Overworld.5
	CommonScript 2071
	ReleaseAll
End

Function 14:
	RemoveOW Overworld.5
	SetFlag 592
	LostBattle
	ReleaseAll
End

Function 15:
	Message 15
	MultiTouchLocalText 1 1 0 1 0x800C
	CreateMultiTouchBox 16 255 0
	CreateMultiTouchBox 17 255 1
	CreateMultiTouchBox 18 255 2
	CreateMultiTouchBox 19 255 3
	CreateMultiTouchBox 26 255 4
	CloseMultiTouch
	CompareVarValue 0x800C 4
	JumpIf EQUAL Function#21
	CloseMessage
	RankingView 4 0x800C
	Message 7
	OpenTouchScreen
Jump Function#20

Function 16:
	Message 15
	MultiTouchLocalText 1 1 0 1 0x800C
	CreateMultiTouchBox 20 255 0
	CreateMultiTouchBox 21 255 1
	CreateMultiTouchBox 22 255 2
	CreateMultiTouchBox 23 255 3
	CreateMultiTouchBox 24 255 4
	CreateMultiTouchBox 25 255 5
	CreateMultiTouchBox 26 255 6
	CloseMultiTouch
	CompareVarValue 0x800C 6
	JumpIf EQUAL Function#21
	CloseMessage
	RankingView 3 0x800C
	Message 7
	OpenTouchScreen
Jump Function#20

Function 17:
	Message 7
Jump Function#20

Function 18:
	Message 15
	MultiTouchLocalText 1 1 0 1 0x800C
	CreateMultiTouchBox 16 255 0
	CreateMultiTouchBox 17 255 1
	CreateMultiTouchBox 18 255 2
	CreateMultiTouchBox 19 255 3
	CreateMultiTouchBox 26 255 4
	CloseMultiTouch
	CompareVarValue 0x800C 4
	JumpIf EQUAL Function#22
	CloseMessage
	RankingView 1 0x800C
	Message 7
	OpenTouchScreen
Jump Function#20

Function 19:
	Message 15
	MultiTouchLocalText 1 1 0 1 0x800C
	CreateMultiTouchBox 20 255 0
	CreateMultiTouchBox 21 255 1
	CreateMultiTouchBox 22 255 2
	CreateMultiTouchBox 23 255 3
	CreateMultiTouchBox 24 255 4
	CreateMultiTouchBox 25 255 5
	CreateMultiTouchBox 26 255 6
	CloseMultiTouch
	CompareVarValue 0x800C 6
	JumpIf EQUAL Function#22
	CloseMessage
	RankingView 0 0x800C
	Message 7
	OpenTouchScreen
Jump Function#20

Function 20:
	MultiTouchLocalText 1 1 0 1 0x800C
	CreateMultiTouchBox 8 255 0
	CreateMultiTouchBox 9 255 1
	CreateMultiTouchBox 10 255 2
	CloseMultiTouch
	SetVarFromVariable 0x8008 0x800C
	CompareVarValue 0x8008 0
	JumpIf EQUAL Function#6
	CompareVarValue 0x8008 1
	JumpIf EQUAL Function#7
Jump Function#8

Function 21:
	CompareVarValue 0x40E6 0
	JumpIf DIFFERENT Function#23
	Message 7
Jump Function#20

Function 22:
	CompareVarValue 0x40E6 0
	JumpIf DIFFERENT Function#24
	Message 7
Jump Function#20

Function 23:
Jump Function#6

Function 24:
Jump Function#7

//===== ACTIONS =====//
Action 1:
		EmoteExclamation 0x1
		Delay8 0x1
End

Action 2:
		WalkNorth8 0x7
End

Action 3:
		Delay8 0x2
		WalkSouth8 0x1
End

Action 4:
		LockDir 0x1
		WalkWest8 0x1
		ReleaseDir 0x1
End

Action 5:
		WalkOnSpotSouth8 0x1
		WalkSouth8 0x7
End

Action 6:
		LockDir 0x1
		WalkEast8 0x1
		ReleaseDir 0x1
End

