/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0822
 * Generated: 5/20/2026 9:55:39 PM
 */

//===== SCRIPTS =====//
Script 1:
	MecScript
	LockAll
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	Movement Player Action#1
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	PlayFanfare SEQ_SE_DP_KI_GASYAN
	ClearFlag 525
	AddOW Overworld.1
	SetVar 0x4001 1
	ReleaseAll
End

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckFlag 230
	JumpIf EQUAL Function#1
	TextPlayerName 0
	Message 0
	CloseMessage
	CompareVarValue 0x4135 8
	JumpIf LESS Function#2
	TrainerBattle TRAINER_BRUNO_704 TRAINER_NONE 0 0
Jump Function#3

Script 3:
	CheckFlag 230
	JumpIf EQUAL Function#4
	VanishOverworld Overworld.3
	VanishOverworld Overworld.4
End

//===== FUNCTIONS =====//
Function 1:
	Message 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 2:
	TrainerBattle TRAINER_BRUNO_418 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#5
	SetFlag 230
	Message 1
	CloseMessage
	PlayFanfare SEQ_SE_DP_KI_GASYAN
	RemoveOW Overworld.2
	RemoveOW Overworld.3
	RemoveOW Overworld.4
	ReleaseAll
End

Function 3:
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#5
	SetFlag 230
	Message 1
	CloseMessage
	PlayFanfare SEQ_SE_DP_KI_GASYAN
	RemoveOW Overworld.2
	RemoveOW Overworld.3
	RemoveOW Overworld.4
	ReleaseAll
End

Function 4:
End

Function 5:
	LostBattle
	ReleaseAll
End

//===== ACTIONS =====//
Action 1:
		WalkNorth8 0x6
End

