/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0829
 * Generated: 3/6/2026 7:25:19 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckBadge 13 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#1
	Message 0
	CloseMessage
	TrainerBattle TRAINER_SABRINA_258 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#2
	GiveBadge 13
	IncrementVar 0x4135 1
	AddTrainerScore 22
	SetFlag 2456
	SetTrainerFlag TRAINER_FRANKLIN_230
	SetTrainerFlag TRAINER_JARED_415
	SetTrainerFlag TRAINER_REBECCA_368
	SetTrainerFlag TRAINER_DARCY_369
	Message 1
	TextPlayerName 0
	Message 2
	PlaySound SEQ_ME_BADGE
	WaitSound
	Message 3
Jump Function#3

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckBadge 13 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#4
	Message 6
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 3:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckBadge 13 0x800C
	TextPlayerName 0
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#5
	Message 8
Jump Function#6

Script 4:
	MecScript
	LockAll
	SendBackFollowingPoke
	PlayFanfare SEQ_SE_PL_BOWABOWA
	Movement Player Action#1
	WaitMovement
	FadeScreen 6 1 0 0
	WaitFadeScreen
	Warp 410 0 15 23 Down
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Script 5:
	CheckPokeGearRematch 35 0x4001
	CompareVarValue 0x4001 0
	JumpIf DIFFERENT Function#7
	CheckPokegearNumberRegistered 35 0x4001
	CompareVarValue 0x4001 1
	JumpIf EQUAL Function#8
	CheckBadge 13 0x4000
	CompareVarValue 0x4000 1
	JumpIf EQUAL Function#9
Jump Function#10

//===== FUNCTIONS =====//
Function 1:
	CheckFlag 386
	JumpIf LESS Function#3
	Message 5
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 2:
	LostBattle
	ReleaseAll
End

Function 3:
	SetVar 0x8004 375
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#11
	CommonScript 2033
	SetFlag 386
	Message 4
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 4:
	Message 7
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 5:
	Message 9
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 6:
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 7:
	SetFlag 753
End

Function 8:
	GetDayOfWeek 0x4000
	CompareVarValue 0x4000 1
	JumpIf DIFFERENT Function#10
	SetFlag 753
End

Function 9:
	GetDayOfWeek 0x4000
	CompareVarValue 0x4000 5
	JumpIf DIFFERENT Function#10
	SetFlag 753
End

Function 10:
	ClearFlag 753
End

Function 11:
	CommonScript 2009
	CloseMessage
	ReleaseAll
End

//===== ACTIONS =====//
Action 1:
	FaceSouth 0x2
	FaceWest 0x2
	FaceNorth 0x2
	FaceEast 0x2
	FaceSouth 0x2
	FaceWest 0x2
	FaceNorth 0x2
	FaceEast 0x2
	FaceSouth 0x2
	FaceWest 0x2
	FaceNorth 0x2
	FaceEast 0x2
	FaceSouth 0x2
	FaceWest 0x2
	FaceNorth 0x2
	FaceEast 0x1
	SetInvisible 0x0
End

