/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0834
 * Generated: 5/20/2026 9:55:39 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckFlag 280
	JumpIf EQUAL Function#1
	Message 0
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckFlag 280
	JumpIf EQUAL Function#2
	Message 8
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 3:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 10
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 4:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 11
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 5:
	MecScript
	LockAll
	Movement Player Action#1
	WaitMovement
	CheckFlag 291
	JumpIf EQUAL Function#3
	Message 1
	CloseMessage
	SetFlag 291
	WaitTime 50 0x8004
	CheckItem ITEM_PASS 1 0x800C
	CompareVarValue 0x800C 1
	JumpIf GREATER/EQUAL Function#4
	Message 2
	CloseMessage
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	Movement Player Action#2
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	ReleaseAll
End

Script 6:
	CheckFlag 280
	JumpIf EQUAL Function#5
End

Script 7:
	CMD_582 76 1290 209
	CheckFlag 280
	JumpIf EQUAL Function#6
Jump Function#7

Script 8:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 12
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#8
	Message 14
	CloseMessage
	FadeScreen 6 1 0 0
	WaitFadeScreen
	PartyPokemonTradeScreen
	GetSelectedPartySlot 0x800C
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	CompareVarValue 0x800C 255
	JumpIf EQUAL Function#8
	InitTrade 10
	SetVarFromVariable 0x8004 0x800C
	GetPartyPokemonID 0x8004 0x8005
	GetRequestedPokemon 0x800C
	CompareVars 0x8005 0x800C
	JumpIf DIFFERENT Function#9
	TradePokemonScreen 0x8004
	EndTrade
	SetFlag 354
	Message 16
	CloseMessage
	GetPlayerDirection 0x800C
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#10
	Movement Overworld.4 Action#3
Jump Function#11

Script 9:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Message 18
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== FUNCTIONS =====//
Function 1:
	GetPlayerDirection 0x800C
	CompareVarValue 0x800C 2
	JumpIf DIFFERENT Function#12
	Message 5
	WaitButton
	CloseMessage
Jump Function#13

Function 2:
	Message 9
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 3:
	Message 3
	CloseMessage
Jump Function#14

Function 4:
	Message 4
	WaitButton
	CloseMessage
	SetVar 0x411D 1
	SetVar 0x411F 1
	ReleaseAll
End

Function 5:
	SetOWPosition Overworld.0 12 0 7 Right
End

Function 6:
	SetVar 0x411D 0
	SetFlag 759
	CheckPokegearNumberRegistered 36 0x4001
	CompareVarValue 0x4001 0
	JumpIf EQUAL Function#15
	CheckPokeGearRematch 36 0x4001
	CompareVarValue 0x4001 0
	JumpIf DIFFERENT Function#15
	CheckFlag 354
	JumpIf EQUAL Function#15
	ClearFlag 759
End

Function 7:
	SetFlag 759
	CheckPokegearNumberRegistered 36 0x4001
	CompareVarValue 0x4001 0
	JumpIf EQUAL Function#15
	CheckPokeGearRematch 36 0x4001
	CompareVarValue 0x4001 0
	JumpIf DIFFERENT Function#15
	CheckFlag 354
	JumpIf EQUAL Function#15
	ClearFlag 759
End

Function 8:
	Message 15
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 9:
	EndTrade
	Message 17
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 10:
	Movement Overworld.4 Action#4
	WaitMovement
	RemoveOW Overworld.4
	SetFlag 759
	ReleaseAll
End

Function 11:
	WaitMovement
	RemoveOW Overworld.4
	SetFlag 759
	ReleaseAll
End

Function 12:
	Message 7
	CloseMessage
	Movement Overworld.0 Action#5
	WaitMovement
	ReleaseAll
End

Function 13:
	ReleaseAll
End

Function 14:
	WaitTime 50 0x8004
	CheckItem ITEM_PASS 1 0x800C
	CompareVarValue 0x800C 1
	JumpIf GREATER/EQUAL Function#4
	Message 2
	CloseMessage
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	Movement Player Action#2
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	ReleaseAll
End

Function 15:
End

//===== ACTIONS =====//
Action 1:
		WalkOnSpotWest8 0x1
End

Action 2:
		WalkSouth8 0x2
End

Action 3:
		WalkWest6 0x5
		WalkSouth6 0xA
End

Action 4:
		WalkSouth6 0xA
End

Action 5:
		FaceEast 0x1
End

