/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0848
 * Generated: 5/20/2026 9:55:39 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckFlag 741
	JumpIf EQUAL Function#1
	CompareVarValue 0x4108 1
	JumpIf GREATER/EQUAL Function#2
	TextPlayerName 0
	GenderMessage 0 1
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== FUNCTIONS =====//
Function 1:
	TextPlayerName 0
	GenderMessage 2 3
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 2:
	TextPlayerName 0
	GenderMessage 4 5
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== ACTIONS =====//
