/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0849
 * Generated: 5/20/2026 9:55:39 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckBadge 0 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#1
	TextPlayerName 0
	CheckFlag 106
	JumpIf EQUAL Function#2
	GenderMessage 0 1
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 4
	PlayCry SPECIES_MARILL 0
	WaitCry
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 3:
	CheckFlag 741
	JumpIf EQUAL Function#3
	GetCounterpartSprite 0x4020
End

Script 4:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Message 17
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 5:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Message 18
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== FUNCTIONS =====//
Function 1:
	GetFirstAlivePokemonSlot 0x8006
	GetShinyLeafCount 0x8006 0x800C
	CheckFlag 353
	JumpIf EQUAL Function#4
	CompareVarValue 0x800C 1
	JumpIf GREATER/EQUAL Function#5
	TextPlayerName 0
	GenderMessage 5 6
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 2:
	TextPartyPokemon 1 0x800C
	GenderMessage 2 3
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 3:
End

Function 4:
	SetVarFromVariable 0x8004 0x800C
	CompareVarValue 0x8004 6
	JumpIf EQUAL Function#6
	CompareVarValue 0x8004 5
	JumpIf EQUAL Function#7
	CompareVarValue 0x8004 1
	JumpIf GREATER/EQUAL Function#8
Jump Function#9

Function 5:
	SetFlag 353
	TextPlayerName 0
	GenderMessage 7 8
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 6:
	TextPlayerName 0
	GetFollowingPokePartySlot 0x800C
	TextPokeNickname 1 0x800C
	GenderMessage 15 16
	CloseMessage
Jump Function#10

Function 7:
	TryGiveShinyLeafCrown 0x8006
	SetFlag 388
	TextPlayerName 0
	GenderMessage 11 12
	CloseMessage
	FadeScreen 6 1 0 0
	WaitFadeScreen
	OpenPokedexScreen 2
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	GenderMessage 13 14
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 8:
	CompareVarValue 0x8004 1
	JumpIf DIFFERENT Function#11
	SetVar 0x8005 4
Jump Function#12

Function 9:
	TextPlayerName 0
	GenderMessage 5 6
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 10:
	FadeScreen 6 1 0 0
	WaitFadeScreen
	OpenPokedexScreen 2
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	GenderMessage 13 14
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 11:
	CompareVarValue 0x8004 2
	JumpIf DIFFERENT Function#13
	SetVar 0x8005 3
Jump Function#12

Function 12:
	TextPlayerName 0
	TextNumber 1 0x8004
	TextNumber 2 0x8005
	GenderMessage 9 10
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 13:
	CompareVarValue 0x8004 3
	JumpIf DIFFERENT Function#14
	SetVar 0x8005 2
Jump Function#12

Function 14:
	SetVar 0x8005 1
	TextPlayerName 0
	TextNumber 1 0x8004
	TextNumber 2 0x8005
	GenderMessage 9 10
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== ACTIONS =====//
