/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0851
 * Generated: 5/20/2026 9:55:39 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CommonScript 2011
	FreezeMessage
	SetVar 0x8004 0
	CommonScript 2048
	ReleaseAll
End

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 3:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CompareVarValue 0x4108 4
	JumpIf LESS Function#1
	Message 1
Jump Function#2

Script 4:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CommonScript 2011
	FreezeMessage
	SetVar 0x8004 0
	CommonScript 2052
	ReleaseAll
End

//===== FUNCTIONS =====//
Function 1:
	Message 0
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 2:
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== ACTIONS =====//
