/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0857
 * Generated: 5/20/2026 9:55:40 PM
 */

//===== SCRIPTS =====//
Script 1:
	SetFlag 159
	SetVar 0x8004 1
	SetVar 0x8005 2
	SetVar 0x8006 1
	CommonScript 2039
	SetVar 0x4074 2
	ClearFlag 407
	SetFlag 582
End

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	GetPlayerDirection 0x800C
	CompareVarValue 0x800C 2
	JumpIf DIFFERENT Function#1
	Movement Overworld.2 Action#1
Jump Function#2

Script 3:
End

Script 4:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Call Function#3
	Call Function#4
	CompareVarValue 0x8006 1
	JumpIf EQUAL Function#5
	Message 17
	CloseMessage
	Call Function#3
	ReleaseAll
End

Script 5:
	MecScript
	LockAll
	CommonScript 2067
	Movement Overworld.7 Action#2
	WaitMovement
	Message 13
	CloseMessage
	Movement Overworld.7 Action#3
	WaitMovement
	Message 14
	CloseMessage
	Movement Overworld.7 Action#4
	WaitMovement
	Message 15
	CloseMessage
	Movement Overworld.7 Action#5
	WaitMovement
	Message 16
	CloseMessage
	Movement Overworld.7 Action#6
	WaitMovement
	CommonScript 2068
	RemoveOW Overworld.7
	SetFlag 568
	ReleaseAll
	SetVar 0x4074 4
End

Script 6:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 26
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 7:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 27
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 8:
	SetTextBoard 2 0
	ShowBoard 3
	WaitBoard
	BoardMessage 12 0x800C
	CommonScript 2000
End

Script 9:
	SetIconBoard 9 0 13 0x800C
	ShowBoard 3
	WaitBoard
	CloseBoard 0x800C
	CommonScript 2000
End

Script 10:
	SetTextBoard 2 0
	ShowBoard 3
	WaitBoard
	BoardMessage 10 0x800C
	CommonScript 2000
End

Script 11:
	SetTextBoard 2 0
	ShowBoard 3
	WaitBoard
	BoardMessage 11 0x800C
	CommonScript 2000
End

Script 12:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 5
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 13:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 6
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 14:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 7
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 15:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 8
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== FUNCTIONS =====//
Function 1:
	CompareVarValue 0x800C 3
	JumpIf DIFFERENT Function#6
	Movement Overworld.2 Action#7
Jump Function#2

Function 2:
	WaitMovement
	Message 1
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#7
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#8
End

Function 3:
	GetPlayerDirection 0x800C
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#9
	Movement Overworld.10 Action#8
	WaitMovement
Jump Function#10

Function 4:
	CheckItem ITEM_RED_SHARD 1 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#11
	SetVar 0x8000 1
	SetVar 0x8006 1
	CheckItem ITEM_BLUE_SHARD 1 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#12
	SetVar 0x8001 1
	SetVar 0x8006 1
	CheckItem ITEM_YELLOW_SHARD 1 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#13
	SetVar 0x8002 1
	SetVar 0x8006 1
	CheckItem ITEM_GREEN_SHARD 1 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#14
	SetVar 0x8003 1
	SetVar 0x8006 1
Return

Function 5:
	Message 18
	OpenTouchScreen
	MultiTouchStandardText 1 1 0 1 0x800C
	CompareVarValue 0x8000 1
	JumpIf DIFFERENT Function#15
	CreateMultiTouchBox 205 255 0
	CompareVarValue 0x8001 1
	JumpIf DIFFERENT Function#16
	CreateMultiTouchBox 206 255 1
	CompareVarValue 0x8002 1
	JumpIf DIFFERENT Function#17
	CreateMultiTouchBox 207 255 2
	CompareVarValue 0x8003 1
	JumpIf DIFFERENT Function#18
	CreateMultiTouchBox 208 255 3
	CreateMultiTouchBox 126 255 4
	CloseMultiTouch
	CloseTouchScreen
	SetVarFromVariable 0x8008 0x800C
	CompareVarValue 0x8008 0
	JumpIf EQUAL Function#19
	CompareVarValue 0x8008 1
	JumpIf EQUAL Function#20
	CompareVarValue 0x8008 2
	JumpIf EQUAL Function#21
	CompareVarValue 0x8008 3
	JumpIf EQUAL Function#22
Jump Function#23

Function 6:
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#24
	Movement Overworld.2 Action#9
Jump Function#2

Function 7:
	Message 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 8:
	Message 3
	CloseMessage
	GetPlayerDirection 0x800C
	CompareVarValue 0x800C 2
	JumpIf DIFFERENT Function#25
	Movement Overworld.2 Action#10
Jump Function#26

Function 9:
	CompareVarValue 0x800C 2
	JumpIf DIFFERENT Function#27
	Movement Overworld.10 Action#11
	WaitMovement
Jump Function#10

Function 10:
Return

Function 11:
	CheckItem ITEM_BLUE_SHARD 1 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#12
	SetVar 0x8001 1
	SetVar 0x8006 1
	CheckItem ITEM_YELLOW_SHARD 1 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#13
	SetVar 0x8002 1
	SetVar 0x8006 1
	CheckItem ITEM_GREEN_SHARD 1 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#14
	SetVar 0x8003 1
	SetVar 0x8006 1
Return

Function 12:
	CheckItem ITEM_YELLOW_SHARD 1 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#13
	SetVar 0x8002 1
	SetVar 0x8006 1
	CheckItem ITEM_GREEN_SHARD 1 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#14
	SetVar 0x8003 1
	SetVar 0x8006 1
Return

Function 13:
	CheckItem ITEM_GREEN_SHARD 1 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#14
	SetVar 0x8003 1
	SetVar 0x8006 1
Return

Function 14:
Return

Function 15:
	CompareVarValue 0x8001 1
	JumpIf DIFFERENT Function#16
	CreateMultiTouchBox 206 255 1
	CompareVarValue 0x8002 1
	JumpIf DIFFERENT Function#17
	CreateMultiTouchBox 207 255 2
	CompareVarValue 0x8003 1
	JumpIf DIFFERENT Function#18
	CreateMultiTouchBox 208 255 3
	CreateMultiTouchBox 126 255 4
	CloseMultiTouch
	CloseTouchScreen
	SetVarFromVariable 0x8008 0x800C
	CompareVarValue 0x8008 0
	JumpIf EQUAL Function#19
	CompareVarValue 0x8008 1
	JumpIf EQUAL Function#20
	CompareVarValue 0x8008 2
	JumpIf EQUAL Function#21
	CompareVarValue 0x8008 3
	JumpIf EQUAL Function#22
Jump Function#23

Function 16:
	CompareVarValue 0x8002 1
	JumpIf DIFFERENT Function#17
	CreateMultiTouchBox 207 255 2
	CompareVarValue 0x8003 1
	JumpIf DIFFERENT Function#18
	CreateMultiTouchBox 208 255 3
	CreateMultiTouchBox 126 255 4
	CloseMultiTouch
	CloseTouchScreen
	SetVarFromVariable 0x8008 0x800C
	CompareVarValue 0x8008 0
	JumpIf EQUAL Function#19
	CompareVarValue 0x8008 1
	JumpIf EQUAL Function#20
	CompareVarValue 0x8008 2
	JumpIf EQUAL Function#21
	CompareVarValue 0x8008 3
	JumpIf EQUAL Function#22
Jump Function#23

Function 17:
	CompareVarValue 0x8003 1
	JumpIf DIFFERENT Function#18
	CreateMultiTouchBox 208 255 3
	CreateMultiTouchBox 126 255 4
	CloseMultiTouch
	CloseTouchScreen
	SetVarFromVariable 0x8008 0x800C
	CompareVarValue 0x8008 0
	JumpIf EQUAL Function#19
	CompareVarValue 0x8008 1
	JumpIf EQUAL Function#20
	CompareVarValue 0x8008 2
	JumpIf EQUAL Function#21
	CompareVarValue 0x8008 3
	JumpIf EQUAL Function#22
Jump Function#23

Function 18:
	CreateMultiTouchBox 126 255 4
	CloseMultiTouch
	CloseTouchScreen
	SetVarFromVariable 0x8008 0x800C
	CompareVarValue 0x8008 0
	JumpIf EQUAL Function#19
	CompareVarValue 0x8008 1
	JumpIf EQUAL Function#20
	CompareVarValue 0x8008 2
	JumpIf EQUAL Function#21
	CompareVarValue 0x8008 3
	JumpIf EQUAL Function#22
Jump Function#23

Function 19:
	Message 21
	SetVar 0x8004 149
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#28
	SetVar 0x8004 151
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#28
	SetVar 0x8004 154
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#28
	SetVar 0x8004 149
	SetVar 0x8005 1
	CommonScript 2033
	SetVar 0x8004 151
	SetVar 0x8005 1
	CommonScript 2033
	SetVar 0x8004 154
	SetVar 0x8005 1
	CommonScript 2033
	TakeItem ITEM_RED_SHARD 1 0x800C
Jump Function#29

Function 20:
	Message 22
	SetVar 0x8004 155
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#28
	SetVar 0x8004 150
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#28
	SetVar 0x8004 160
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#28
	SetVar 0x8004 155
	SetVar 0x8005 1
	CommonScript 2033
	SetVar 0x8004 150
	SetVar 0x8005 1
	CommonScript 2033
	SetVar 0x8004 160
	SetVar 0x8005 1
	CommonScript 2033
	TakeItem ITEM_BLUE_SHARD 1 0x800C
Jump Function#29

Function 21:
	Message 23
	SetVar 0x8004 153
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#28
	SetVar 0x8004 158
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#28
	SetVar 0x8004 163
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#28
	SetVar 0x8004 153
	SetVar 0x8005 1
	CommonScript 2033
	SetVar 0x8004 158
	SetVar 0x8005 1
	CommonScript 2033
	SetVar 0x8004 163
	SetVar 0x8005 1
	CommonScript 2033
	TakeItem ITEM_YELLOW_SHARD 1 0x800C
Jump Function#29

Function 22:
	Message 24
	SetVar 0x8004 152
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#28
	SetVar 0x8004 157
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#28
	SetVar 0x8004 162
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#28
	SetVar 0x8004 152
	SetVar 0x8005 1
	CommonScript 2033
	SetVar 0x8004 157
	SetVar 0x8005 1
	CommonScript 2033
	SetVar 0x8004 162
	SetVar 0x8005 1
	CommonScript 2033
	TakeItem ITEM_GREEN_SHARD 1 0x800C
Jump Function#29

Function 23:
	Message 20
	CloseMessage
	Call Function#3
	ReleaseAll
End

Function 24:
	Movement Overworld.2 Action#12
	WaitMovement
	Message 1
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#7
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#8
End

Function 25:
	CompareVarValue 0x800C 3
	JumpIf DIFFERENT Function#30
	Movement Overworld.2 Action#13
Jump Function#26

Function 26:
	WaitMovement
	GetPlayerDirection 0x800C
	CompareVarValue 0x800C 2
	JumpIf EQUAL Function#31
	CompareVarValue 0x800C 3
	JumpIf EQUAL Function#32
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#33
Jump Function#34

Function 27:
	Movement Overworld.10 Action#14
	WaitMovement
Return

Function 28:
	Message 25
	CloseMessage
	Call Function#3
	ReleaseAll
End

Function 29:
	SetVar 0x8000 0
	SetVar 0x8001 0
	SetVar 0x8002 0
	SetVar 0x8003 0
	SetVar 0x8006 0
	Call Function#4
	CompareVarValue 0x8006 1
	JumpIf DIFFERENT Function#35
	Message 19
Jump Function#36

Function 30:
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#37
	Movement Overworld.2 Action#15
Jump Function#26

Function 31:
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	Movement Overworld.2 Action#16
	Movement Player Action#17
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
Jump Function#38

Function 32:
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	Movement Overworld.2 Action#16
	Movement Player Action#18
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
Jump Function#38

Function 33:
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	Movement Overworld.2 Action#19
	Movement Player Action#20
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
Jump Function#38

Function 34:
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	Movement Overworld.2 Action#16
	Movement Player Action#21
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
Jump Function#38

Function 35:
Jump Function#23

Function 36:
	OpenTouchScreen
	MultiTouchStandardText 1 1 0 1 0x800C
	CompareVarValue 0x8000 1
	JumpIf DIFFERENT Function#15
	CreateMultiTouchBox 205 255 0
	CompareVarValue 0x8001 1
	JumpIf DIFFERENT Function#16
	CreateMultiTouchBox 206 255 1
	CompareVarValue 0x8002 1
	JumpIf DIFFERENT Function#17
	CreateMultiTouchBox 207 255 2
	CompareVarValue 0x8003 1
	JumpIf DIFFERENT Function#18
	CreateMultiTouchBox 208 255 3
	CreateMultiTouchBox 126 255 4
	CloseMultiTouch
	CloseTouchScreen
	SetVarFromVariable 0x8008 0x800C
	CompareVarValue 0x8008 0
	JumpIf EQUAL Function#19
	CompareVarValue 0x8008 1
	JumpIf EQUAL Function#20
	CompareVarValue 0x8008 2
	JumpIf EQUAL Function#21
	CompareVarValue 0x8008 3
	JumpIf EQUAL Function#22
Jump Function#23

Function 37:
	Movement Overworld.2 Action#22
	WaitMovement
	GetPlayerDirection 0x800C
	CompareVarValue 0x800C 2
	JumpIf EQUAL Function#31
	CompareVarValue 0x800C 3
	JumpIf EQUAL Function#32
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#33
Jump Function#34

Function 38:
	Message 4
	CloseMessage
	Movement Overworld.2 Action#23
	WaitMovement
	DoorAnimation 15 8 15 1 77
	OpenDoor 77
	WaitDoor 77
	Movement Overworld.2 Action#24
	WaitMovement
	CloseDoor 77
	WaitDoor 77
	FreeDoor 77
	RemoveOW Overworld.2
	SetFlag 410
	ClearFlag 411
	ReleaseAll
End

//===== ACTIONS =====//
Action 1:
		FaceSouth 0x1
		FaceWest 0x1
		FaceNorth 0x1
		FaceEast 0x1
		FaceSouth 0x1
		FaceWest 0x1
		FaceNorth 0x1
		FaceEast 0x1
End

Action 2:
		EmoteExclamation 0x1
		WalkWest8 0x5
		WalkNorth8 0x1
End

Action 3:
		WalkNorth8 0x1
End

Action 4:
		LockDir 0x1
		WalkSouth16 0x1
		ReleaseDir 0x1
End

Action 5:
		FaceEast 0x1
		Delay2 0x1
		FaceSouth 0x1
		Delay2 0x1
		FaceWest 0x1
		Delay2 0x1
		FaceNorth 0x1
		Delay2 0x1
		FaceEast 0x1
		Delay2 0x1
		FaceSouth 0x1
		Delay2 0x1
		FaceWest 0x1
		Delay2 0x1
		FaceNorth 0x1
		Delay2 0x1
End

Action 6:
		WalkSouth8 0x2
		WalkWest8 0x1
		WalkSouth8 0x7
End

Action 7:
		FaceNorth 0x1
		FaceEast 0x1
		FaceSouth 0x1
		FaceWest 0x1
		FaceNorth 0x1
		FaceEast 0x1
		FaceSouth 0x1
		FaceWest 0x1
End

Action 8:
		FaceEast 0x1
		FaceNorth 0x1
		FaceWest 0x1
		FaceSouth 0x1
		FaceEast 0x1
		FaceNorth 0x1
		FaceWest 0x1
		FaceSouth 0x1
		FaceEast 0x1
		FaceNorth 0x1
		FaceWest 0x1
		FaceSouth 0x1
		FaceEast 0x1
		FaceNorth 0x1
		FaceWest 0x1
		FaceSouth 0x1
End

Action 9:
		FaceWest 0x1
		FaceNorth 0x1
		FaceEast 0x1
		FaceSouth 0x1
		FaceWest 0x1
		FaceNorth 0x1
		FaceEast 0x1
		FaceSouth 0x1
End

Action 10:
		FaceSouth 0x1
		FaceWest 0x1
		FaceNorth 0x1
		FaceEast 0x1
		FaceSouth 0x1
		FaceWest 0x1
		FaceNorth 0x1
		FaceEast 0x1
		FaceSouth 0x1
End

Action 11:
		FaceNorth 0x1
		FaceWest 0x1
		FaceSouth 0x1
		FaceEast 0x1
		FaceNorth 0x1
		FaceWest 0x1
		FaceSouth 0x1
		FaceEast 0x1
		FaceNorth 0x1
		FaceWest 0x1
		FaceSouth 0x1
		FaceEast 0x1
		FaceNorth 0x1
		FaceWest 0x1
		FaceSouth 0x1
		FaceEast 0x1
End

Action 12:
		FaceEast 0x1
		FaceSouth 0x1
		FaceWest 0x1
		FaceNorth 0x1
		FaceEast 0x1
		FaceSouth 0x1
		FaceWest 0x1
		FaceNorth 0x1
End

Action 13:
		FaceNorth 0x1
		FaceEast 0x1
		FaceSouth 0x1
		FaceWest 0x1
		FaceNorth 0x1
		FaceEast 0x1
		FaceSouth 0x1
End

Action 14:
		FaceSouth 0x1
		FaceEast 0x1
		FaceNorth 0x1
		FaceWest 0x1
		FaceSouth 0x1
		FaceEast 0x1
		FaceNorth 0x1
		FaceWest 0x1
		FaceSouth 0x1
		FaceEast 0x1
		FaceNorth 0x1
		FaceWest 0x1
		FaceSouth 0x1
		FaceEast 0x1
		FaceNorth 0x1
		FaceWest 0x1
End

Action 15:
		FaceWest 0x1
		FaceNorth 0x1
		FaceEast 0x1
		FaceSouth 0x1
		FaceWest 0x1
		FaceNorth 0x1
		FaceEast 0x1
		FaceSouth 0x1
End

Action 16:
		WalkSouth4 0x8
		FaceWest 0x1
		FaceNorth 0x1
		FaceEast 0x1
		FaceSouth 0x1
		FaceWest 0x1
		FaceNorth 0x1
		FaceEast 0x1
		WalkEast4 0x15
		FaceSouth 0x1
		FaceWest 0x1
		FaceNorth 0x1
		FaceEast 0x1
		FaceSouth 0x1
		FaceWest 0x1
		FaceNorth 0x1
		WalkNorth4 0x1
		WalkOnSpotSouth8 0x1
End

Action 17:
		Delay8 0x1
		RunWest 0x1
		RunSouth 0x8
		WalkOnSpotEast8 0x1
		Delay4 0x1
		RunEast 0x15
		WalkOnSpotNorth8 0x1
End

Action 18:
		Delay8 0x1
		RunEast 0x1
		RunSouth 0x8
		WalkOnSpotEast8 0x1
		Delay4 0x1
		RunEast 0x15
		WalkOnSpotNorth8 0x1
End

Action 19:
		WalkWest4 0x2
		FaceSouth 0x1
		FaceWest 0x1
		FaceNorth 0x1
		FaceEast 0x1
		FaceSouth 0x1
		WalkSouth4 0x3
		FaceWest 0x1
		FaceNorth 0x1
		FaceEast 0x1
		FaceSouth 0x1
		FaceWest 0x1
		WalkEast4 0x2
		FaceNorth 0x1
		FaceEast 0x1
		FaceSouth 0x1
		FaceWest 0x1
		FaceNorth 0x1
		FaceEast 0x1
		FaceSouth 0x1
		WalkSouth4 0x5
		FaceWest 0x1
		FaceNorth 0x1
		FaceEast 0x1
		FaceSouth 0x1
		FaceWest 0x1
		FaceNorth 0x1
		FaceEast 0x1
		WalkEast4 0x15
		FaceSouth 0x1
		FaceWest 0x1
		FaceNorth 0x1
		FaceEast 0x1
		FaceSouth 0x1
		FaceWest 0x1
		FaceNorth 0x1
		FaceEast 0x1
		FaceSouth 0x1
		FaceWest 0x1
		FaceNorth 0x1
		WalkNorth4 0x1
		FaceEast 0x1
		FaceSouth 0x1
		FaceWest 0x1
		FaceNorth 0x1
		FaceEast 0x1
		FaceSouth 0x1
		FaceWest 0x1
		FaceNorth 0x1
		FaceEast 0x1
		FaceSouth 0x1
		FaceWest 0x1
		FaceNorth 0x1
		FaceEast 0x1
		FaceSouth 0x1
		FaceWest 0x1
		FaceNorth 0x1
		FaceEast 0x1
		FaceSouth 0x1
End

Action 20:
		WalkSouth4 0x1
		WalkEast4 0x1
		WalkOnSpotWest4 0x1
		Delay8 0x2
		WalkOnSpotSouth4 0x1
		Delay8 0x2
		WalkWest4 0x1
		RunSouth 0x6
		WalkOnSpotEast8 0x1
		Delay4 0x1
		RunEast 0x15
		WalkOnSpotNorth8 0x1
End

Action 21:
		Delay8 0x1
		RunSouth 0x9
		WalkOnSpotEast8 0x1
		Delay4 0x1
		RunEast 0x15
		WalkOnSpotNorth8 0x1
End

Action 22:
		FaceEast 0x1
		FaceSouth 0x1
		FaceWest 0x1
		FaceNorth 0x1
		FaceEast 0x1
		FaceSouth 0x1
		FaceWest 0x1
		FaceNorth 0x1
		FaceEast 0x1
		FaceSouth 0x1
End

Action 23:
		WalkNorth8 0x2
End

Action 24:
		WalkNorth8 0x1
End

