/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0869
 * Generated: 3/6/2026 7:25:19 PM
 */

//===== SCRIPTS =====//
Script 1:
End

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckBadge 1 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#1
	Message 0
	CloseMessage
	TrainerBattle TRAINER_BUGSY_021 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#2
	Message 1
	TextPlayerName 0
	Message 2
	PlaySound SEQ_ME_BADGE
	WaitSound
	GiveBadge 1
	SetTrainerFlag TRAINER_AL_068
	SetTrainerFlag TRAINER_BENNY_067
	SetTrainerFlag TRAINER_JOSH_069
	SetTrainerFlag TRAINER_AMY_AND_MIMI_010
	AddTrainerScore 22
	Message 3
	SetVar 0x8004 416
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#3
	CommonScript 2033
	SetFlag 127
	Message 5
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 3:
	AzaleaGym 0
End

Script 4:
	AzaleaGym 1
End

Script 5:
	AzaleaGym 2
End

Script 6:
	AzaleaGym 3
End

Script 7:
	AzaleaGym 4
End

Script 8:
	AzaleaGym 5
End

Script 9:
	AzaleaGym 6
End

Script 10:
	AzaleaGym 7
End

Script 11:
	AzaleaGym 8
End

Script 12:
	AzaleaGym 9
End

Script 13:
	AzaleaGym 10
End

Script 14:
	AzaleaGym 11
End

Script 15:
	AzaleaGym2 0
End

Script 16:
	AzaleaGym2 1
End

Script 17:
	InitAzaleaGym
	CheckPokeGearRematch 34 0x4001
	CompareVarValue 0x4001 0
	JumpIf DIFFERENT Function#4
	CheckFlag 2404
	JumpIf EQUAL Function#5
	ClearFlag 746
End

//===== FUNCTIONS =====//
Function 1:
	CheckFlag 127
	JumpIf LESS Function#6
	Message 6
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 2:
	LostBattle
	ReleaseAll
End

Function 3:
	CommonScript 2009
	CloseMessage
	ReleaseAll
End

Function 4:
	SetFlag 746
End

Function 5:
	CheckPokegearNumberRegistered 34 0x4001
	CompareVarValue 0x4001 1
	JumpIf EQUAL Function#7
	GetDayOfWeek 0x4002
	CompareVarValue 0x4002 4
	JumpIf DIFFERENT Function#7
	SetFlag 746
End

Function 6:
	SetVar 0x8004 416
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#3
	CommonScript 2033
	SetFlag 127
	Message 5
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 7:
	GetDayOfWeek 0x4001
	CompareVarValue 0x4001 1
	JumpIf EQUAL Function#8
	CompareVarValue 0x4001 3
	JumpIf EQUAL Function#8
	CompareVarValue 0x4001 5
	JumpIf EQUAL Function#8
	ClearFlag 746
End

Function 8:
	SetFlag 746
End

//===== ACTIONS =====//
