/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0873
 * Generated: 3/6/2026 7:25:19 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckFlag 123
	JumpIf EQUAL Function#1
	Message 0
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckFlag 128
	JumpIf EQUAL Function#2
	Message 3
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 3:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	PlayCry SPECIES_FARFETCH’D 0
	Message 8
	WaitCry
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== FUNCTIONS =====//
Function 1:
	CheckFlag 128
	JumpIf EQUAL Function#3
	Message 1
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 2:
	CheckFlag 129
	JumpIf EQUAL Function#4
	Message 4
	WaitAB
	SetVar 0x8004 249
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#5
	CommonScript 2008
	SetFlag 129
	CloseMessage
	ReleaseAll
End

Function 3:
	Message 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 4:
	Message 6
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 5:
	CommonScript 2009
	CloseMessage
	ReleaseAll
End

//===== ACTIONS =====//
