/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0875
 * Generated: 3/6/2026 7:25:19 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckFlag 2404
	JumpIf EQUAL Function#1
	CheckFlag 187
	JumpIf EQUAL Function#2
	Message 0
	Message 1
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 2:
End

Script 3:
	MecScript
	LockAll
	Movement Player Action#1
	WaitMovement
	PlayCry SPECIES_SUICUNE 0
	Release Overworld.5
	ShakeOverworld Overworld.5 2 90 2 0
	Lock Overworld.5
	WaitCry
	Movement Overworld.5 Action#2
	WaitMovement
	Movement Overworld.5 Action#3
	Movement Player Action#4
	WaitMovement
	WaitTime 30 0x800C
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	Movement Overworld.5 Action#5
	Movement Player Action#6
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	RemoveOW Overworld.5
	SetFlag 481
	IncrementVar 0x4076 1
	ClearFlag 482
	AddOW Overworld.6
	CommonScript 2042
	Movement Overworld.6 Action#7
	Movement Player Action#8
	WaitMovement
	TextPlayerName 0
	Message 15
	WaitAB
	CloseMessage
	TrainerBattle TRAINER_EUSINE_498 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#3
	TextPlayerName 0
	Message 16
	CloseMessage
	Movement Overworld.6 Action#9
	WaitMovement
	RemoveOW Overworld.6
	SetFlag 482
	ClearFlag 670
	SetVar 0x4092 1
	ReleaseAll
End

Script 4:
End

Script 5:
	SetTextBoard 2 0
	ShowBoard 3
	WaitBoard
	BoardMessage 22 0x800C
	CommonScript 2000
End

Script 6:
	ClearFlag 2433
	SetVar 0x40EB 0
End

Script 7:
	MecScript
	LockAll
	Movement Overworld.0 Action#10
	Movement Player Action#11
	WaitMovement
	Message 2
	SetVar 0x8004 421
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#4
	CommonScript 2033
	SetFlag 187
	SetVar 0x4116 2
	Message 4
	WaitButton
	CloseMessage
	Movement Overworld.0 Action#12
	WaitMovement
	CompareVarValue 0x4134 4
	JumpIf EQUAL Function#5
	ReleaseAll
End

Script 8:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 6
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#6
	CheckAlbumPhoto 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#7
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 7
	CloseMessage
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	GetPlayerDirection 0x800C
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#8
	Movement Player Action#13
Jump Function#9

Script 9:
	SetIconBoard 18 0 15 0x800C
	ShowBoard 3
	WaitBoard
	CloseBoard 0x800C
	CommonScript 2000
End

Script 10:
	SetTextBoard 2 0
	ShowBoard 3
	WaitBoard
	BoardMessage 19 0x800C
	CommonScript 2000
End

Script 11:
	SetTextBoard 2 0
	ShowBoard 3
	WaitBoard
	BoardMessage 20 0x800C
	CommonScript 2000
End

Script 12:
	SetTextBoard 2 0
	ShowBoard 3
	WaitBoard
	BoardMessage 21 0x800C
	CommonScript 2000
End

Script 13:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 12
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 14:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 13
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 15:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 14
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 16:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 17
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== FUNCTIONS =====//
Function 1:
	CheckPokegearNumberRegistered 32 0x4001
	CompareVarValue 0x4001 1
	JumpIf EQUAL Function#10
	CompareVarValue 0x4002 1
	JumpIf GREATER/EQUAL Function#11
	Message 7
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#12
	CompareVarValue 0x800C 1
	JumpIf GREATER/EQUAL Function#13
End

Function 2:
	Message 5
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 3:
	RemoveOW Overworld.6
	SetFlag 482
	ClearFlag 670
	SetVar 0x4092 1
	LostBattle
	ReleaseAll
End

Function 4:
	CommonScript 2009
	CloseMessage
	ReleaseAll
End

Function 5:
	SetVar 0x4077 2
	SetFlag 197
	SetFlag 2459
	CompareVarValue 0x40F8 0
	JumpIf DIFFERENT Function#14
	SetVar 0x40F8 2
	SetVar 0x8004 1
	SetVar 0x8005 2
	SetVar 0x8006 2
	CommonScript 2039
	SetVar 0x4134 5
	ReleaseAll
End

Function 6:
	CloseMessage
	ReleaseAll
End

Function 7:
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 9
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 8:
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#15
	Movement Player Action#14
Jump Function#9

Function 9:
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	CheckPokemonAlive 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#16
	Movement Following Action#15
	WaitMovement
	FadeScreen 6 1 0 0
	WaitFadeScreen
	TakePhoto 35
	LockAll
	FadeScreen 6 1 1 0
	WaitFadeScreen
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 8
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 10:
	Message 9
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 11:
	Message 11
Jump Function#17

Function 12:
	TextPlayerName 0
	Message 8
	PlaySound SEQ_ME_POKEGEAR_REGIST
	WaitSound
	RecordPokegearNumber 32
	Message 9
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 13:
	SetVar 0x4002 1
	Message 10
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 14:
	SetVar 0x8004 1
	SetVar 0x8005 2
	SetVar 0x8006 2
	CommonScript 2039
	SetVar 0x4134 5
	ReleaseAll
End

Function 15:
	Movement Player Action#16
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	CheckPokemonAlive 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#16
	Movement Following Action#15
	WaitMovement
	FadeScreen 6 1 0 0
	WaitFadeScreen
	TakePhoto 35
	LockAll
	FadeScreen 6 1 1 0
	WaitFadeScreen
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 8
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 16:
	FadeScreen 6 1 0 0
	WaitFadeScreen
	TakePhoto 35
	LockAll
	FadeScreen 6 1 1 0
	WaitFadeScreen
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 8
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 17:
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#12
	CompareVarValue 0x800C 1
	JumpIf GREATER/EQUAL Function#13
End

//===== ACTIONS =====//
Action 1:
	FaceNorth 0x1
	EmoteExclamation 0x1
End

Action 2:
	006F 0x1
End

Action 3:
	FaceSouth 0x1
End

Action 4:
	FaceNorth 0x1
End

Action 5:
	0070 0x1
	SetInvisible 0x1
End

Action 6:
	FaceEast 0x1
	Delay8 0x1
	WalkEast8 0x2
End

Action 7:
	WalkNorth8 0x5
	WalkEast8 0x2
	WalkNorth8 0x2
End

Action 8:
	Delay8 0x6
	FaceSouth 0x1
End

Action 9:
	WalkSouth8 0x2
	WalkWest8 0x2
	WalkSouth8 0x5
End

Action 10:
	WalkOnSpotNorth4 0x1
	EmoteExclamation 0x1
	WalkNorth8 0x2
	FaceWest 0x1
End

Action 11:
	Delay16 0x3
	FaceEast 0x1
End

Action 12:
	WalkSouth8 0x2
	WalkOnSpotNorth4 0x1
End

Action 13:
	WalkEast8 0x1
	WalkNorth8 0x2
	WalkWest8 0x1
	WalkNorth8 0x3
	WalkOnSpotSouth8 0x1
End

Action 14:
	WalkNorth8 0x3
	WalkOnSpotSouth8 0x1
End

Action 15:
	WalkEast8 0x1
	WalkNorth8 0x1
	FaceSouth 0x1
End

Action 16:
	WalkNorth8 0x1
	WalkWest8 0x1
	WalkNorth8 0x3
	WalkOnSpotSouth8 0x1
End

