/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0877
 * Generated: 5/20/2026 9:55:40 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CompareVarValue 0x4000 0
	JumpIf EQUAL Function#1
	CheckBadge 4 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#2
	Message 0
	CloseMessage
	TrainerBattle TRAINER_CHUCK_034 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#3
	Message 3
	SetTrainerFlag TRAINER_YOSHI_156
	SetTrainerFlag TRAINER_LAO_157
	SetTrainerFlag TRAINER_NOB_251
	SetTrainerFlag TRAINER_LUNG_159
	TextPlayerName 0
	Message 4
	GiveBadge 4
	PlaySound SEQ_ME_BADGE
	WaitSound
	IncrementVar 0x4134 1
	AddTrainerScore 22
	SetVar 0x4116 1
	CompareVarValue 0x4134 3
	JumpIf DIFFERENT Function#4
	SetVar 0x4077 1
	Message 5
Jump Function#5

Script 2:
	CianwoodGymInit
	ClearFlag 2433
End

Script 3:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CompareVarValue 0x4000 0
	JumpIf EQUAL Function#6
	Message 12
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 4:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckBadge 4 0x800C
	TextPlayerName 0
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#7
	Message 13
Jump Function#8

//===== FUNCTIONS =====//
Function 1:
	Message 9
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 2:
	CheckFlag 186
	JumpIf LESS Function#5
	Message 8
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 3:
	LostBattle
	ReleaseAll
End

Function 4:
	Message 5
Jump Function#5

Function 5:
	SetVar 0x8004 328
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#9
	CommonScript 2033
	SetFlag 186
	Message 6
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 6:
	Message 10
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#10
	CloseMessage
	ReleaseAll
End

Function 7:
	Message 14
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 8:
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 9:
	Message 7
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 10:
	TextPlayerName 0
	Message 11
	CloseMessage
	SetFlag 2433
	StopFanfare SEQ_SE_GS_N_TAKI
	PlayFanfare SEQ_SE_DP_SHIP03
	PlayFanfare SEQ_SE_GS_TAKI2
	CianwoodGymTurnWinch 0x4000
	ReleaseAll
End

//===== ACTIONS =====//
