/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0878
 * Generated: 5/20/2026 9:55:40 PM
 */

//===== SCRIPTS =====//
Script 1:
	SetVar 0x8007 3
	CommonScript 2002
End

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 0
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 3:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CountPCFreeSpace 0x800C
	CompareVarValue 0x800C 540
	JumpIf DIFFERENT Function#1
Jump Function#2

Script 4:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckBadge 4 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#3
	Message 2
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== FUNCTIONS =====//
Function 1:
Jump Function#4

Function 2:
	GetPartyCount 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#5
Jump Function#6

Function 3:
	TextPlayerName 0
	Message 3
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 4:
	Message 1
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 5:
Jump Function#4

Function 6:
	Message 4
	TextPlayerName 0
	Message 5
	PlaySound SEQ_ME_POKEGET
	WaitSound
	GivePokemon SPECIES_TENTACOOL 15 ITEM_NONE 0 0 0x800C
	Message 6
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#7
	CloseTouchScreen
	CloseMessage
Jump Function#8

Function 7:
	CloseMessage
	CMD_815 0
	FadeScreen 6 1 0 0
	WaitFadeScreen
	ChoosePokemonNickname 1 0x800C
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Function 8:
	ReleaseAll
End

//===== ACTIONS =====//
