/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0881
 * Generated: 3/6/2026 7:25:19 PM
 */

//===== SCRIPTS =====//
Script 1:
	CheckFlag 185
	JumpIf EQUAL Function#1
	CompareVarValue 0x40A5 1
	JumpIf EQUAL Function#2
Jump Function#1

//===== FUNCTIONS =====//
Function 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	SetFlag 367
	Message 3
	FreezeMessage
	SetVar 0x8004 11
	CommonScript 2052
	Movement Overworld.0 Action#1
	WaitMovement
	ClearFlag 367
	ReleaseAll
End

Function 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 0
	WaitAB
	SetVar 0x8004 464
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#3
	CommonScript 2033
	SetFlag 185
	Message 2
	WaitAB
	CloseMessage
	Movement Overworld.0 Action#1
	WaitMovement
	ReleaseAll
End

Function 3:
	CommonScript 2009
	CloseMessage
	ReleaseAll
End

//===== ACTIONS =====//
Action 1:
	FaceNorth 0x1
End

