/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0886
 * Generated: 3/6/2026 7:25:19 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckBadge 2 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#1
	CheckFlag 183
	JumpIf EQUAL Function#2
	CompareVarValue 0x410A 1
	JumpIf EQUAL Function#3
	Message 0
	CloseMessage
	TrainerBattle TRAINER_WHITNEY_030 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#4
	SetTrainerFlag TRAINER_CARRIE_022
	SetTrainerFlag TRAINER_CATHY_071
	SetTrainerFlag TRAINER_VICTORIA_005
	SetTrainerFlag TRAINER_SAMANTHA_070
	AddTrainerScore 22
	SetOWPosition Overworld.1 13 0 15 Up
	Message 2
	WaitButton
	CloseMessage
	ReleaseAll
	SetVar 0x410A 1
	SetFlag 132
	SetVar 0x40DA 1
	ClearFlag 547
	SetFlag 548
End

Script 2:
	MecScript
	LockAll
	Movement Overworld.1 Action#1
	WaitMovement
	Message 9
	CloseMessage
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	Movement Overworld.1 Action#2
	Movement Player Action#3
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	SetFlag 183
	ReleaseAll
End

Script 3:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckBadge 2 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#5
	Message 10
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 4:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckBadge 2 0x800C
	TextPlayerName 0
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#6
	Message 12
Jump Function#7

Script 5:
	CheckPokeGearRematch 17 0x4001
	CompareVarValue 0x4001 0
	JumpIf DIFFERENT Function#8
	CheckFlag 2404
	JumpIf LESS Function#9
	CheckPokegearNumberRegistered 17 0x4001
	CompareVarValue 0x4001 1
	JumpIf EQUAL Function#10
	GetHour 0x4000
	CompareVarValue 0x4000 12
	JumpIf DIFFERENT Function#11
	SetFlag 748
Jump Function#12

//===== FUNCTIONS =====//
Function 1:
	CheckFlag 133
	JumpIf LESS Function#13
	Message 8
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 2:
	Message 3
	TextPlayerName 0
	Message 4
	PlaySound SEQ_ME_BADGE
	WaitSound
	GiveBadge 2
	SetVar 0x410A 2
	ClearFlag 132
	SetFlag 2456
	Message 5
	SetVar 0x8004 372
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#14
	CommonScript 2033
	Message 7
	WaitButton
	CloseMessage
	SetFlag 133
	ReleaseAll
End

Function 3:
	Message 2
	WaitButton
	CloseMessage
	ReleaseAll
	SetVar 0x410A 1
	SetFlag 132
	SetVar 0x40DA 1
	ClearFlag 547
	SetFlag 548
End

Function 4:
	LostBattle
	ReleaseAll
End

Function 5:
	Message 11
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 6:
	Message 13
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 7:
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 8:
	SetFlag 748
End

Function 9:
	ClearFlag 748
End

Function 10:
	GetHour 0x4000
	CompareVarValue 0x4000 18
	JumpIf DIFFERENT Function#15
	SetFlag 748
Jump Function#16

Function 11:
	CompareVarValue 0x4000 13
	JumpIf DIFFERENT Function#17
	SetFlag 748
Jump Function#12

Function 12:
End

Function 13:
	SetVar 0x8004 372
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#14
	CommonScript 2033
	Message 7
	WaitButton
	CloseMessage
	SetFlag 133
	ReleaseAll
End

Function 14:
	CommonScript 2009
	CloseMessage
	ReleaseAll
End

Function 15:
	CompareVarValue 0x4000 19
	JumpIf DIFFERENT Function#18
	SetFlag 748
Jump Function#16

Function 16:
End

Function 17:
	CompareVarValue 0x4000 14
	JumpIf DIFFERENT Function#19
	SetFlag 748
Jump Function#12

Function 18:
	CompareVarValue 0x4000 20
	JumpIf DIFFERENT Function#20
	SetFlag 748
Jump Function#16

Function 19:
	CompareVarValue 0x4000 15
	JumpIf DIFFERENT Function#21
	SetFlag 748
Jump Function#12

Function 20:
Jump Function#9

Function 21:
Jump Function#9

//===== ACTIONS =====//
Action 1:
	EmoteExclamation 0x1
	WalkNorth8 0x3
End

Action 2:
	WalkSouth8 0x3
	WalkOnSpotNorth8 0x1
End

Action 3:
	Delay8 0x1
	WalkNorth8 0x1
End

