/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0891
 * Generated: 3/6/2026 7:25:19 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	GetFirstAlivePokemonSlot 0x8000
	Message 0
	GetPokemonHappiness 0x800C 0x8000
	CompareVarValue 0x800C 250
	JumpIf GREATER/EQUAL Function#1
	CompareVarValue 0x800C 200
	JumpIf GREATER/EQUAL Function#2
	CompareVarValue 0x800C 150
	JumpIf GREATER/EQUAL Function#3
	CompareVarValue 0x800C 100
	JumpIf GREATER/EQUAL Function#4
	CompareVarValue 0x800C 50
	JumpIf GREATER/EQUAL Function#5
Jump Function#6

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 7
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 3:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 8
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== FUNCTIONS =====//
Function 1:
	Message 1
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 2:
	Message 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 3:
	Message 3
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 4:
	Message 4
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 5:
	Message 5
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 6:
	Message 6
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== ACTIONS =====//
