/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0900
 * Generated: 3/6/2026 7:25:19 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CommonScript 2011
	FreezeMessage
	SetVar 0x8004 3
	CommonScript 2052
	ReleaseAll
End

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CommonScript 2011
	FreezeMessage
	SetVar 0x8004 4
	CommonScript 2052
	ReleaseAll
End

Script 3:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CompareVarValue 0x4077 3
	JumpIf DIFFERENT Function#1
	Message 1
Jump Function#2

Script 4:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CompareVarValue 0x4077 3
	JumpIf DIFFERENT Function#3
	Message 5
Jump Function#4

Script 5:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CompareVarValue 0x4077 3
	JumpIf DIFFERENT Function#5
	Message 3
Jump Function#6

Script 6:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Message 6
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== FUNCTIONS =====//
Function 1:
	Message 0
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 2:
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 3:
	Message 4
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 4:
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 5:
	Message 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 6:
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== ACTIONS =====//
