/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0906
 * Generated: 3/6/2026 7:25:19 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 0
	CheckItem ITEM_COIN_CASE 1 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#1
	Message 1
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	OverlayManager 3 0
	Message 7
	OpenTouchScreen
	ShowSpecialCurrency 0 20 2
	MultiTouchLocalText 1 1 0 1 0x4000
	CreateMultiTouchBox 37 255 0
	CreateMultiTouchBox 38 255 1
	CreateMultiTouchBox 36 255 2
	CloseMultiTouch
	SetVarFromVariable 0x8008 0x4000
	CompareVarValue 0x8008 0
	JumpIf EQUAL Function#2
	CompareVarValue 0x8008 1
	JumpIf EQUAL Function#3
Jump Function#4

Script 3:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	OverlayManager 3 0
	Message 16
	OpenTouchScreen
	ShowSpecialCurrency 0 20 2
	CheckVersion 0x4000
	CompareVarValue 0x4000 7
	JumpIf DIFFERENT Function#5
Jump Function#6

Script 4:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 18
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 5:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 19
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 6:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 27
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#7
	Message 31
	WaitButton
	Message 28
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#7
	Message 32
	WaitButton
	Message 28
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#7
	Message 33
	WaitButton
	Message 28
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#7
	Message 34
	WaitButton
	Message 28
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#7
	Message 35
	WaitButton
	Message 30
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 7:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 21
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 8:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 22
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 9:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 23
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 10:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 24
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 11:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Call Function#8
	CompareVarValue 0x4001 1
	JumpIf EQUAL Function#9
	FadeScreen 6 1 0 0
	WaitFadeScreen
	OpenVoltorbFlip 0 0
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Script 12:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Call Function#8
	CompareVarValue 0x4001 1
	JumpIf EQUAL Function#10
	FadeScreen 6 1 0 0
	WaitFadeScreen
	OpenVoltorbFlip 1 0
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Script 13:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Call Function#8
	CompareVarValue 0x4001 1
	JumpIf EQUAL Function#11
	FadeScreen 6 1 0 0
	WaitFadeScreen
	OpenVoltorbFlip 2 0
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Script 14:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Call Function#8
	CompareVarValue 0x4001 1
	JumpIf EQUAL Function#12
	FadeScreen 6 1 0 0
	WaitFadeScreen
	OpenVoltorbFlip 3 0
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Script 15:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Call Function#8
	CompareVarValue 0x4001 1
	JumpIf EQUAL Function#13
	FadeScreen 6 1 0 0
	WaitFadeScreen
	OpenVoltorbFlip 4 0
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Script 16:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Call Function#8
	CompareVarValue 0x4001 1
	JumpIf EQUAL Function#14
	FadeScreen 6 1 0 0
	WaitFadeScreen
	OpenVoltorbFlip 5 0
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Script 17:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Call Function#8
	CompareVarValue 0x4001 1
	JumpIf EQUAL Function#15
	FadeScreen 6 1 0 0
	WaitFadeScreen
	OpenVoltorbFlip 6 0
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Script 18:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Call Function#8
	CompareVarValue 0x4001 1
	JumpIf EQUAL Function#16
	FadeScreen 6 1 0 0
	WaitFadeScreen
	OpenVoltorbFlip 7 0
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Script 19:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Call Function#8
	CompareVarValue 0x4001 1
	JumpIf EQUAL Function#17
	FadeScreen 6 1 0 0
	WaitFadeScreen
	OpenVoltorbFlip 8 0
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Script 20:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Call Function#8
	CompareVarValue 0x4001 1
	JumpIf EQUAL Function#18
	FadeScreen 6 1 0 0
	WaitFadeScreen
	OpenVoltorbFlip 9 0
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Script 21:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Call Function#8
	CompareVarValue 0x4001 1
	JumpIf EQUAL Function#19
	FadeScreen 6 1 0 0
	WaitFadeScreen
	OpenVoltorbFlip 10 0
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Script 22:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Call Function#8
	CompareVarValue 0x4001 1
	JumpIf EQUAL Function#20
	FadeScreen 6 1 0 0
	WaitFadeScreen
	OpenVoltorbFlip 11 0
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Script 23:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Call Function#8
	CompareVarValue 0x4001 1
	JumpIf EQUAL Function#21
	FadeScreen 6 1 0 0
	WaitFadeScreen
	OpenVoltorbFlip 21 0
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Script 24:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Call Function#8
	CompareVarValue 0x4001 1
	JumpIf EQUAL Function#22
	FadeScreen 6 1 0 0
	WaitFadeScreen
	OpenVoltorbFlip 12 0
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Script 25:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Call Function#8
	CompareVarValue 0x4001 1
	JumpIf EQUAL Function#23
	FadeScreen 6 1 0 0
	WaitFadeScreen
	OpenVoltorbFlip 13 0
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Script 26:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Call Function#8
	CompareVarValue 0x4001 1
	JumpIf EQUAL Function#24
	FadeScreen 6 1 0 0
	WaitFadeScreen
	OpenVoltorbFlip 14 0
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Script 27:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Call Function#8
	CompareVarValue 0x4001 1
	JumpIf EQUAL Function#25
	FadeScreen 6 1 0 0
	WaitFadeScreen
	OpenVoltorbFlip 15 0
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Script 28:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Call Function#8
	CompareVarValue 0x4001 1
	JumpIf EQUAL Function#26
	FadeScreen 6 1 0 0
	WaitFadeScreen
	OpenVoltorbFlip 16 0
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Script 29:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Call Function#8
	CompareVarValue 0x4001 1
	JumpIf EQUAL Function#27
	FadeScreen 6 1 0 0
	WaitFadeScreen
	OpenVoltorbFlip 17 0
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Script 30:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Call Function#8
	CompareVarValue 0x4001 1
	JumpIf EQUAL Function#28
	FadeScreen 6 1 0 0
	WaitFadeScreen
	OpenVoltorbFlip 18 0
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Script 31:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Call Function#8
	CompareVarValue 0x4001 1
	JumpIf EQUAL Function#29
	FadeScreen 6 1 0 0
	WaitFadeScreen
	OpenVoltorbFlip 19 0
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Script 32:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Call Function#8
	CompareVarValue 0x4001 1
	JumpIf EQUAL Function#30
	FadeScreen 6 1 0 0
	WaitFadeScreen
	OpenVoltorbFlip 20 0
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Script 33:
	GetDayOfWeek 0x4000
	CompareVarValue 0x4000 0
	JumpIf DIFFERENT Function#31
Jump Function#32

//===== FUNCTIONS =====//
Function 1:
	OverlayManager 3 0
	Message 2
	OpenTouchScreen
	ShowSpecialCurrency 0 20 2
	ShowMoney 20 7
	MultiTouchStandardText 1 1 0 1 0x800C
	CreateMultiTouchBox 127 255 0
	CreateMultiTouchBox 128 255 1
	CreateMultiTouchBox 129 255 2
	CloseMultiTouch
	SetVarFromVariable 0x8008 0x800C
	CompareVarValue 0x8008 0
	JumpIf EQUAL Function#33
	CompareVarValue 0x8008 1
	JumpIf EQUAL Function#34
	Message 6
Jump Function#35

Function 2:
	MultiTouchLocalText 1 1 0 1 0x4000
	CreateMultiTouchBox 39 255 0
	CreateMultiTouchBox 40 255 1
	CreateMultiTouchBox 41 255 2
	CreateMultiTouchBox 42 255 3
	CreateMultiTouchBox 43 255 4
	CreateMultiTouchBox 44 255 5
	CreateMultiTouchBox 36 255 6
	CloseMultiTouch
	SetVarFromVariable 0x8008 0x4000
	CompareVarValue 0x8008 0
	JumpIf EQUAL Function#36
	CompareVarValue 0x8008 1
	JumpIf EQUAL Function#37
	CompareVarValue 0x8008 2
	JumpIf EQUAL Function#38
	CompareVarValue 0x8008 3
	JumpIf EQUAL Function#39
	CompareVarValue 0x8008 4
	JumpIf EQUAL Function#40
	CompareVarValue 0x8008 5
	JumpIf EQUAL Function#41
Jump Function#42

Function 3:
	MultiTouchLocalText 1 1 0 1 0x4000
	CreateMultiTouchBox 45 255 0
	CreateMultiTouchBox 46 255 1
	CreateMultiTouchBox 47 255 2
	CreateMultiTouchBox 48 255 3
	CreateMultiTouchBox 36 255 4
	CloseMultiTouch
	SetVarFromVariable 0x8008 0x4000
	CompareVarValue 0x8008 0
	JumpIf EQUAL Function#43
	CompareVarValue 0x8008 1
	JumpIf EQUAL Function#44
	CompareVarValue 0x8008 2
	JumpIf EQUAL Function#45
	CompareVarValue 0x8008 3
	JumpIf EQUAL Function#46
Jump Function#42

Function 4:
	Message 8
	WaitButton
	CloseMessage
Jump Function#47

Function 5:
Jump Function#48

Function 6:
	MultiTouchLocalText 1 1 0 1 0x4000
	CreateMultiTouchBox 49 255 0
	CreateMultiTouchBox 50 255 1
	CreateMultiTouchBox 51 255 2
	CreateMultiTouchBox 36 255 3
	CloseMultiTouch
	SetVarFromVariable 0x8008 0x4000
	CompareVarValue 0x8008 0
	JumpIf EQUAL Function#49
	CompareVarValue 0x8008 1
	JumpIf EQUAL Function#50
	CompareVarValue 0x8008 2
	JumpIf EQUAL Function#51
Jump Function#4

Function 7:
	Message 29
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 8:
	CheckItem ITEM_COIN_CASE 1 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#52
	OverlayManager 3 0
	HasCoinsImmediate 0x800C 3
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#53
	OverlayManager 3 1
	SetVar 0x4001 0
Return

Function 9:
	ReleaseAll
End

Function 10:
	ReleaseAll
End

Function 11:
	ReleaseAll
End

Function 12:
	ReleaseAll
End

Function 13:
	ReleaseAll
End

Function 14:
	ReleaseAll
End

Function 15:
	ReleaseAll
End

Function 16:
	ReleaseAll
End

Function 17:
	ReleaseAll
End

Function 18:
	ReleaseAll
End

Function 19:
	ReleaseAll
End

Function 20:
	ReleaseAll
End

Function 21:
	ReleaseAll
End

Function 22:
	ReleaseAll
End

Function 23:
	ReleaseAll
End

Function 24:
	ReleaseAll
End

Function 25:
	ReleaseAll
End

Function 26:
	ReleaseAll
End

Function 27:
	ReleaseAll
End

Function 28:
	ReleaseAll
End

Function 29:
	ReleaseAll
End

Function 30:
	ReleaseAll
End

Function 31:
Jump Function#54

Function 32:
	GetHour 0x4000
	CompareVarValue 0x4000 7
	JumpIf DIFFERENT Function#55
	SetFlag 730
Jump Function#56

Function 33:
	CompareMoney 0x800C 1000
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#57
	CanGiveCoins 0x800C 50
	Nop
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#58
	TakeMoney 1000
	GiveCoins 50
	UpdateSpecialCurrency 0
	UpdateMoney
	PlayFanfare SEQ_SE_DP_REGI
	WaitFanfare SEQ_SE_DP_REGI
	Message 3
Jump Function#59

Function 34:
	CompareMoney 0x800C 0x2710
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#57
	CanGiveCoins 0x800C 500
	Nop
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#58
	TakeMoney 0x2710
	GiveCoins 500
	UpdateSpecialCurrency 0
	UpdateMoney
	PlayFanfare SEQ_SE_DP_REGI
	WaitFanfare SEQ_SE_DP_REGI
	Message 3
Jump Function#59

Function 35:
	WaitButton
	CloseMessage
	CloseTouchScreen
	HideSpecialCurrency
	HideMoney
	OverlayManager 3 1
	ReleaseAll
End

Function 36:
	SetVar 0x8004 417
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#60
	TextItem 0 0x8004
	Message 10
	YesNoTouchScreen 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#61
	CloseMessage
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#2
	GetCoins 0x8006
	CompareVarValue 0x8006 2000
	JumpIf LESS Function#62
	Message 11
	PlayFanfare SEQ_SE_DP_REGI
	TakeCoins 2000
	UpdateSpecialCurrency 0
	TextItem 0 0x8004
	GetItemPocket 0x8004 0x800C
	TextPocket 1 0x800C
	Message 17
	GiveItem 0x8004 1 0x800C
Jump Function#2

Function 37:
	SetVar 0x8004 402
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#60
	TextItem 0 0x8004
	Message 10
	YesNoTouchScreen 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#63
	CloseMessage
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#2
	GetCoins 0x8006
	CompareVarValue 0x8006 0xFA0
	JumpIf LESS Function#62
	Message 11
	PlayFanfare SEQ_SE_DP_REGI
	TakeCoins 0xFA0
	UpdateSpecialCurrency 0
	TextItem 0 0x8004
	GetItemPocket 0x8004 0x800C
	TextPocket 1 0x800C
	Message 17
	GiveItem 0x8004 1 0x800C
Jump Function#2

Function 38:
	SetVar 0x8004 371
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#60
	TextItem 0 0x8004
	Message 10
	YesNoTouchScreen 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#64
	CloseMessage
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#2
	GetCoins 0x8006
	CompareVarValue 0x8006 0x1770
	JumpIf LESS Function#62
	Message 11
	PlayFanfare SEQ_SE_DP_REGI
	TakeCoins 0x1770
	UpdateSpecialCurrency 0
	TextItem 0 0x8004
	GetItemPocket 0x8004 0x800C
	TextPocket 1 0x800C
	Message 17
	GiveItem 0x8004 1 0x800C
Jump Function#2

Function 39:
	SetVar 0x8004 362
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#60
	TextItem 0 0x8004
	Message 10
	YesNoTouchScreen 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#65
	CloseMessage
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#2
	GetCoins 0x8006
	CompareVarValue 0x8006 0x2710
	JumpIf LESS Function#62
	Message 11
	PlayFanfare SEQ_SE_DP_REGI
	TakeCoins 0x2710
	UpdateSpecialCurrency 0
	TextItem 0 0x8004
	GetItemPocket 0x8004 0x800C
	TextPocket 1 0x800C
	Message 17
	GiveItem 0x8004 1 0x800C
Jump Function#2

Function 40:
	SetVar 0x8004 340
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#60
	TextItem 0 0x8004
	Message 10
	YesNoTouchScreen 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#66
	CloseMessage
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#2
	GetCoins 0x8006
	CompareVarValue 0x8006 0x2710
	JumpIf LESS Function#62
	Message 11
	PlayFanfare SEQ_SE_DP_REGI
	TakeCoins 0x2710
	UpdateSpecialCurrency 0
	TextItem 0 0x8004
	GetItemPocket 0x8004 0x800C
	TextPocket 1 0x800C
	Message 17
	GiveItem 0x8004 1 0x800C
Jump Function#2

Function 41:
	SetVar 0x8004 351
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#60
	TextItem 0 0x8004
	Message 10
	YesNoTouchScreen 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#67
	CloseMessage
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#2
	GetCoins 0x8006
	CompareVarValue 0x8006 0x2710
	JumpIf LESS Function#62
	Message 11
	PlayFanfare SEQ_SE_DP_REGI
	TakeCoins 0x2710
	UpdateSpecialCurrency 0
	TextItem 0 0x8004
	GetItemPocket 0x8004 0x800C
	TextPocket 1 0x800C
	Message 17
	GiveItem 0x8004 1 0x800C
Jump Function#2

Function 42:
	MultiTouchLocalText 1 1 0 1 0x4000
	CreateMultiTouchBox 37 255 0
	CreateMultiTouchBox 38 255 1
	CreateMultiTouchBox 36 255 2
	CloseMultiTouch
	SetVarFromVariable 0x8008 0x4000
	CompareVarValue 0x8008 0
	JumpIf EQUAL Function#2
	CompareVarValue 0x8008 1
	JumpIf EQUAL Function#3
Jump Function#4

Function 43:
	SetVar 0x8004 251
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#60
	TextItem 0 0x8004
	Message 10
	YesNoTouchScreen 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#68
	CloseMessage
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#3
	GetCoins 0x8006
	CompareVarValue 0x8006 1000
	JumpIf LESS Function#62
	Message 11
	PlayFanfare SEQ_SE_DP_REGI
	TakeCoins 1000
	UpdateSpecialCurrency 0
	TextItem 0 0x8004
	GetItemPocket 0x8004 0x800C
	TextPocket 1 0x800C
	Message 17
	GiveItem 0x8004 1 0x800C
Jump Function#3

Function 44:
	SetVar 0x8004 265
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#60
	TextItem 0 0x8004
	Message 10
	YesNoTouchScreen 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#69
	CloseMessage
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#3
	GetCoins 0x8006
	CompareVarValue 0x8006 1000
	JumpIf LESS Function#62
	Message 11
	PlayFanfare SEQ_SE_DP_REGI
	TakeCoins 1000
	UpdateSpecialCurrency 0
	TextItem 0 0x8004
	GetItemPocket 0x8004 0x800C
	TextPocket 1 0x800C
	Message 17
	GiveItem 0x8004 1 0x800C
Jump Function#3

Function 45:
	SetVar 0x8004 276
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#60
	TextItem 0 0x8004
	Message 10
	YesNoTouchScreen 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#70
	CloseMessage
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#3
	GetCoins 0x8006
	CompareVarValue 0x8006 1000
	JumpIf LESS Function#62
	Message 11
	PlayFanfare SEQ_SE_DP_REGI
	TakeCoins 1000
	UpdateSpecialCurrency 0
	TextItem 0 0x8004
	GetItemPocket 0x8004 0x800C
	TextPocket 1 0x800C
	Message 17
	GiveItem 0x8004 1 0x800C
Jump Function#3

Function 46:
	SetVar 0x8004 277
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#60
	TextItem 0 0x8004
	Message 10
	YesNoTouchScreen 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#71
	CloseMessage
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#3
	GetCoins 0x8006
	CompareVarValue 0x8006 1000
	JumpIf LESS Function#62
	Message 11
	PlayFanfare SEQ_SE_DP_REGI
	TakeCoins 1000
	UpdateSpecialCurrency 0
	TextItem 0 0x8004
	GetItemPocket 0x8004 0x800C
	TextPocket 1 0x800C
	Message 17
	GiveItem 0x8004 1 0x800C
Jump Function#3

Function 47:
	HideSpecialCurrency
	CloseTouchScreen
	OverlayManager 3 1
	ReleaseAll
End

Function 48:
	MultiTouchLocalText 1 1 0 1 0x4000
	CreateMultiTouchBox 49 255 0
	CreateMultiTouchBox 52 255 1
	CreateMultiTouchBox 51 255 2
	CreateMultiTouchBox 36 255 3
	CloseMultiTouch
	SetVarFromVariable 0x8008 0x4000
	CompareVarValue 0x8008 0
	JumpIf EQUAL Function#49
	CompareVarValue 0x8008 1
	JumpIf EQUAL Function#72
	CompareVarValue 0x8008 2
	JumpIf EQUAL Function#51
Jump Function#4

Function 49:
	SetVarFromFlexible 0x4002 63
Jump Function#73

Function 50:
	SetVarFromFlexible 0x4002 23
Jump Function#73

Function 51:
	SetVarFromFlexible 0x4002 147
Jump Function#73

Function 52:
	Message 25
	WaitButton
	CloseMessage
	SetVar 0x4001 1
Return

Function 53:
	Message 26
	WaitButton
	CloseMessage
	OverlayManager 3 1
	SetVar 0x4001 1
Return

Function 54:
	ClearFlag 730
End

Function 55:
	CompareVarValue 0x4000 8
	JumpIf DIFFERENT Function#74
	SetFlag 730
Jump Function#56

Function 56:
End

Function 57:
	Message 4
	WaitButton
	CloseMessage
	CloseTouchScreen
	HideSpecialCurrency
	HideMoney
	OverlayManager 3 1
	ReleaseAll
End

Function 58:
	Message 5
Jump Function#35

Function 59:
	MultiTouchStandardText 1 1 0 1 0x800C
	CreateMultiTouchBox 127 255 0
	CreateMultiTouchBox 128 255 1
	CreateMultiTouchBox 129 255 2
	CloseMultiTouch
	SetVarFromVariable 0x8008 0x800C
	CompareVarValue 0x8008 0
	JumpIf EQUAL Function#33
	CompareVarValue 0x8008 1
	JumpIf EQUAL Function#34
	Message 6
Jump Function#35

Function 60:
	Message 12
	CloseMessage
	CompareVarValue 0x8004 417
	JumpIf DIFFERENT Function#75
Jump Function#2

Function 61:
	GetCoins 0x8006
	CompareVarValue 0x8006 2000
	JumpIf LESS Function#62
	Message 11
	PlayFanfare SEQ_SE_DP_REGI
	TakeCoins 2000
	UpdateSpecialCurrency 0
	TextItem 0 0x8004
	GetItemPocket 0x8004 0x800C
	TextPocket 1 0x800C
	Message 17
	GiveItem 0x8004 1 0x800C
Jump Function#2

Function 62:
	Message 9
Jump Function#76

Function 63:
	GetCoins 0x8006
	CompareVarValue 0x8006 0xFA0
	JumpIf LESS Function#62
	Message 11
	PlayFanfare SEQ_SE_DP_REGI
	TakeCoins 0xFA0
	UpdateSpecialCurrency 0
	TextItem 0 0x8004
	GetItemPocket 0x8004 0x800C
	TextPocket 1 0x800C
	Message 17
	GiveItem 0x8004 1 0x800C
Jump Function#2

Function 64:
	GetCoins 0x8006
	CompareVarValue 0x8006 0x1770
	JumpIf LESS Function#62
	Message 11
	PlayFanfare SEQ_SE_DP_REGI
	TakeCoins 0x1770
	UpdateSpecialCurrency 0
	TextItem 0 0x8004
	GetItemPocket 0x8004 0x800C
	TextPocket 1 0x800C
	Message 17
	GiveItem 0x8004 1 0x800C
Jump Function#2

Function 65:
	GetCoins 0x8006
	CompareVarValue 0x8006 0x2710
	JumpIf LESS Function#62
	Message 11
	PlayFanfare SEQ_SE_DP_REGI
	TakeCoins 0x2710
	UpdateSpecialCurrency 0
	TextItem 0 0x8004
	GetItemPocket 0x8004 0x800C
	TextPocket 1 0x800C
	Message 17
	GiveItem 0x8004 1 0x800C
Jump Function#2

Function 66:
	GetCoins 0x8006
	CompareVarValue 0x8006 0x2710
	JumpIf LESS Function#62
	Message 11
	PlayFanfare SEQ_SE_DP_REGI
	TakeCoins 0x2710
	UpdateSpecialCurrency 0
	TextItem 0 0x8004
	GetItemPocket 0x8004 0x800C
	TextPocket 1 0x800C
	Message 17
	GiveItem 0x8004 1 0x800C
Jump Function#2

Function 67:
	GetCoins 0x8006
	CompareVarValue 0x8006 0x2710
	JumpIf LESS Function#62
	Message 11
	PlayFanfare SEQ_SE_DP_REGI
	TakeCoins 0x2710
	UpdateSpecialCurrency 0
	TextItem 0 0x8004
	GetItemPocket 0x8004 0x800C
	TextPocket 1 0x800C
	Message 17
	GiveItem 0x8004 1 0x800C
Jump Function#2

Function 68:
	GetCoins 0x8006
	CompareVarValue 0x8006 1000
	JumpIf LESS Function#62
	Message 11
	PlayFanfare SEQ_SE_DP_REGI
	TakeCoins 1000
	UpdateSpecialCurrency 0
	TextItem 0 0x8004
	GetItemPocket 0x8004 0x800C
	TextPocket 1 0x800C
	Message 17
	GiveItem 0x8004 1 0x800C
Jump Function#3

Function 69:
	GetCoins 0x8006
	CompareVarValue 0x8006 1000
	JumpIf LESS Function#62
	Message 11
	PlayFanfare SEQ_SE_DP_REGI
	TakeCoins 1000
	UpdateSpecialCurrency 0
	TextItem 0 0x8004
	GetItemPocket 0x8004 0x800C
	TextPocket 1 0x800C
	Message 17
	GiveItem 0x8004 1 0x800C
Jump Function#3

Function 70:
	GetCoins 0x8006
	CompareVarValue 0x8006 1000
	JumpIf LESS Function#62
	Message 11
	PlayFanfare SEQ_SE_DP_REGI
	TakeCoins 1000
	UpdateSpecialCurrency 0
	TextItem 0 0x8004
	GetItemPocket 0x8004 0x800C
	TextPocket 1 0x800C
	Message 17
	GiveItem 0x8004 1 0x800C
Jump Function#3

Function 71:
	GetCoins 0x8006
	CompareVarValue 0x8006 1000
	JumpIf LESS Function#62
	Message 11
	PlayFanfare SEQ_SE_DP_REGI
	TakeCoins 1000
	UpdateSpecialCurrency 0
	TextItem 0 0x8004
	GetItemPocket 0x8004 0x800C
	TextPocket 1 0x800C
	Message 17
	GiveItem 0x8004 1 0x800C
Jump Function#3

Function 72:
	SetVarFromFlexible 0x4002 27
Jump Function#73

Function 73:
	GetPartyCount 0x8005
	CompareVarValue 0x8005 6
	JumpIf DIFFERENT Function#77
	Message 13
	WaitButton
	CloseMessage
Jump Function#47

Function 74:
	CompareVarValue 0x4000 9
	JumpIf DIFFERENT Function#78
	SetFlag 730
Jump Function#56

Function 75:
	CompareVarValue 0x8004 402
	JumpIf DIFFERENT Function#79
Jump Function#2

Function 76:
	CompareVarValue 0x8004 417
	JumpIf DIFFERENT Function#75
Jump Function#2

Function 77:
	TextPokemon 1 0x4002 0 0
	Message 14
	YesNoTouchScreen 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#80
	CloseMessage
	CheckVersion 0x4000
	CompareVarValue 0x4000 7
	JumpIf DIFFERENT Function#81
Jump Function#6

Function 78:
Jump Function#54

Function 79:
	CompareVarValue 0x8004 371
	JumpIf DIFFERENT Function#82
Jump Function#2

Function 80:
	CompareVarValue 0x4002 63
	JumpIf DIFFERENT Function#83
	GetCoins 0x8006
	CompareVarValue 0x8006 200
	JumpIf LESS Function#84
Jump Function#85

Function 81:
Jump Function#48

Function 82:
	CompareVarValue 0x8004 362
	JumpIf DIFFERENT Function#86
Jump Function#2

Function 83:
	CompareVarValue 0x4002 23
	JumpIf DIFFERENT Function#87
	GetCoins 0x8006
	CompareVarValue 0x8006 700
	JumpIf LESS Function#84
Jump Function#85

Function 84:
	Message 9
	CheckVersion 0x4000
	CompareVarValue 0x4000 7
	JumpIf DIFFERENT Function#88
Jump Function#6

Function 85:
	Message 11
	PlayFanfare SEQ_SE_DP_REGI
	GivePokemon 0x4002 15 ITEM_NONE 0 0 0x800C
	TextPlayerName 0
	TextPokemon 1 0x4002 0 0
	Message 15
	CompareVarValue 0x4002 63
	JumpIf DIFFERENT Function#89
	TakeCoins 200
Jump Function#90

Function 86:
	CompareVarValue 0x8004 340
	JumpIf DIFFERENT Function#91
Jump Function#2

Function 87:
	CompareVarValue 0x4002 27
	JumpIf DIFFERENT Function#92
	GetCoins 0x8006
	CompareVarValue 0x8006 700
	JumpIf LESS Function#84
Jump Function#85

Function 88:
Jump Function#48

Function 89:
	CompareVarValue 0x4002 23
	JumpIf DIFFERENT Function#93
	TakeCoins 700
Jump Function#90

Function 90:
	UpdateSpecialCurrency 0
	CheckVersion 0x4000
	CompareVarValue 0x4000 7
	JumpIf DIFFERENT Function#94
Jump Function#6

Function 91:
	CompareVarValue 0x8004 351
	JumpIf DIFFERENT Function#95
Jump Function#2

Function 92:
	GetCoins 0x8006
	CompareVarValue 0x8006 2100
	JumpIf LESS Function#84
	Message 11
	PlayFanfare SEQ_SE_DP_REGI
	GivePokemon 0x4002 15 ITEM_NONE 0 0 0x800C
	TextPlayerName 0
	TextPokemon 1 0x4002 0 0
	Message 15
	CompareVarValue 0x4002 63
	JumpIf DIFFERENT Function#89
	TakeCoins 200
Jump Function#90

Function 93:
	CompareVarValue 0x4002 27
	JumpIf DIFFERENT Function#96
	TakeCoins 700
Jump Function#90

Function 94:
Jump Function#48

Function 95:
Jump Function#3

Function 96:
	TakeCoins 2100
	UpdateSpecialCurrency 0
	CheckVersion 0x4000
	CompareVarValue 0x4000 7
	JumpIf DIFFERENT Function#94
Jump Function#6

//===== ACTIONS =====//
