/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0913
 * Generated: 5/20/2026 9:55:40 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckBadge 5 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#1
	Message 0
	CloseMessage
	TrainerBattle TRAINER_JASMINE_033 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#2
	Message 1
	TextPlayerName 0
	Message 2
	PlaySound SEQ_ME_BADGE
	WaitSound
	GiveBadge 5
	IncrementVar 0x4134 1
	AddTrainerScore 22
	CompareVarValue 0x4134 3
	JumpIf DIFFERENT Function#3
	SetVar 0x4077 1
	Message 3
	SetVar 0x8004 350
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#4
	CommonScript 2033
	Message 5
	WaitButton
	CloseMessage
	ReleaseAll
	SetFlag 194
End

Script 2:
	MecScript
	LockAll
	Movement Overworld.2 Action#1
	WaitMovement
	GetPlayerPosition 0x4000 0x4001
	CompareVarValue 0x4000 5
	JumpIf DIFFERENT Function#5
	Movement Overworld.2 Action#2
Jump Function#6

Script 3:
	MecScript
	LockAll
	Movement Overworld.1 Action#1
	WaitMovement
	GetPlayerPosition 0x4000 0x4001
	CompareVarValue 0x4000 5
	JumpIf DIFFERENT Function#7
	Movement Overworld.1 Action#3
Jump Function#8

Script 4:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckBadge 5 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#9
	Message 20
Jump Function#10

Script 5:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckBadge 5 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#11
	Message 22
Jump Function#12

Script 6:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckBadge 5 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#13
	CompareVarValue 0x410E 0
	JumpIf DIFFERENT Function#14
	Message 16
Jump Function#15

Script 7:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckBadge 5 0x800C
	TextPlayerName 0
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#16
	Message 23
Jump Function#17

Script 8:
	CheckPokeGearRematch 38 0x4001
	CompareVarValue 0x4001 0
	JumpIf DIFFERENT Function#18
	CheckFlag 2404
	JumpIf LESS Function#19
	ClearFlag 473
	CheckPokegearNumberRegistered 38 0x4001
	CompareVarValue 0x4001 1
	JumpIf EQUAL Function#20
	GetHour 0x4000
	CompareVarValue 0x4000 13
	JumpIf DIFFERENT Function#21
	SetFlag 473
Jump Function#22

//===== FUNCTIONS =====//
Function 1:
	CheckFlag 194
	JumpIf LESS Function#23
	CheckPokegearNumberRegistered 38 0x4001
	CompareVarValue 0x4001 1
	JumpIf EQUAL Function#24
	Message 6
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 2:
	LostBattle
	ReleaseAll
End

Function 3:
	Message 3
	SetVar 0x8004 350
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#4
	CommonScript 2033
	Message 5
	WaitButton
	CloseMessage
	ReleaseAll
	SetFlag 194
End

Function 4:
	CommonScript 2009
	CloseMessage
	ReleaseAll
End

Function 5:
	CompareVarValue 0x4000 6
	JumpIf DIFFERENT Function#25
	Movement Overworld.2 Action#4
Jump Function#6

Function 6:
	Movement Player Action#5
	WaitMovement
	Message 19
	WaitButton
	CloseMessage
	ReleaseAll
	CompareVarValue 0x410E 1
	JumpIf DIFFERENT Function#26
	SetVar 0x410E 2
End

Function 7:
	CompareVarValue 0x4000 6
	JumpIf DIFFERENT Function#27
	Movement Overworld.1 Action#6
Jump Function#8

Function 8:
	Movement Player Action#7
	WaitMovement
	Message 21
	WaitButton
	CloseMessage
	ReleaseAll
	CompareVarValue 0x410E 2
	JumpIf DIFFERENT Function#28
	SetVar 0x410E 3
End

Function 9:
	Message 19
	WaitButton
	CloseMessage
	ReleaseAll
	CompareVarValue 0x410E 1
	JumpIf DIFFERENT Function#29
	SetVar 0x410E 2
End

Function 10:
	WaitButton
	CloseMessage
	ReleaseAll
	CompareVarValue 0x410E 1
	JumpIf DIFFERENT Function#29
	SetVar 0x410E 2
End

Function 11:
	Message 21
	WaitButton
	CloseMessage
	ReleaseAll
	CompareVarValue 0x410E 2
	JumpIf DIFFERENT Function#30
	SetVar 0x410E 3
End

Function 12:
	WaitButton
	CloseMessage
	ReleaseAll
	CompareVarValue 0x410E 2
	JumpIf DIFFERENT Function#30
	SetVar 0x410E 3
End

Function 13:
	Message 18
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 14:
	Message 17
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 15:
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 16:
	Message 24
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 17:
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 18:
	SetFlag 473
End

Function 19:
End

Function 20:
	GetHour 0x4000
	CompareVarValue 0x4000 12
	JumpIf DIFFERENT Function#31
	SetFlag 473
Jump Function#32

Function 21:
Jump Function#33

Function 22:
End

Function 23:
	SetVar 0x8004 350
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#4
	CommonScript 2033
	Message 5
	WaitButton
	CloseMessage
	ReleaseAll
	SetFlag 194
End

Function 24:
	CheckFlag 358
	JumpIf EQUAL Function#34
	CompareVarValue 0x4000 77
	JumpIf EQUAL Function#35
	SetVar 0x4000 77
	Message 7
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 25:
	Movement Overworld.2 Action#8
	Movement Player Action#5
	WaitMovement
	Message 19
	WaitButton
	CloseMessage
	ReleaseAll
	CompareVarValue 0x410E 1
	JumpIf DIFFERENT Function#26
	SetVar 0x410E 2
End

Function 26:
End

Function 27:
	Movement Overworld.1 Action#9
	Movement Player Action#7
	WaitMovement
	Message 21
	WaitButton
	CloseMessage
	ReleaseAll
	CompareVarValue 0x410E 2
	JumpIf DIFFERENT Function#28
	SetVar 0x410E 3
End

Function 28:
End

Function 29:
End

Function 30:
End

Function 31:
Jump Function#33

Function 32:
End

Function 33:
	CheckPokegearNumberRegistered 28 0x4001
	CompareVarValue 0x4001 1
	JumpIf EQUAL Function#19
	CheckBadge 15 0x4002
	CompareVarValue 0x4002 1
	JumpIf EQUAL Function#36
Jump Function#19

Function 34:
	CompareVarValue 0x4000 55
	JumpIf DIFFERENT Function#37
	Message 11
Jump Function#38

Function 35:
	Message 8
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#39
	Message 9
	CloseMessage
	FadeScreen 6 1 0 0
	WaitFadeScreen
	PartyPokemonTradeScreen
	GetSelectedPartySlot 0x800C
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	CompareVarValue 0x800C 255
	JumpIf EQUAL Function#39
	SetVarFromVariable 0x8004 0x800C
	GetPartyPokemonID 0x8004 0x4003
	CheckPartyPokemonForm 0x8004 0x4004
	CompareVarValue 0x4003 0
	JumpIf EQUAL Function#40
	CompareVarValue 0x4004 0
	JumpIf EQUAL Function#41
	CompareVarValue 0x4003 487
	JumpIf EQUAL Function#42
	CompareVarValue 0x4003 492
	JumpIf EQUAL Function#42
	CompareVarValue 0x4003 172
	JumpIf EQUAL Function#42
	CompareVarValue 0x4003 479
	JumpIf EQUAL Function#42
	TextPokeNickname 1 0x8004
	Message 13
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#39
	CloseMessage
	InitTrade 5
	TradePokemonScreen 0x8004
	EndTrade
	SetFlag 358
	SetVar 0x4000 55
	Message 11
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 36:
	GetDayOfWeek 0x4000
	CompareVarValue 0x4000 6
	JumpIf DIFFERENT Function#43
Jump Function#44

Function 37:
	Message 12
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 38:
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 39:
	Message 10
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 40:
	TextPlayerName 0
	Message 14
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 41:
	TextPokeNickname 1 0x8004
	Message 13
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#39
	CloseMessage
	InitTrade 5
	TradePokemonScreen 0x8004
	EndTrade
	SetFlag 358
	SetVar 0x4000 55
	Message 11
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 42:
	Message 15
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 43:
	CompareVarValue 0x4000 0
	JumpIf DIFFERENT Function#45
Jump Function#44

Function 44:
	GetHour 0x4000
	CompareVarValue 0x4000 14
	JumpIf DIFFERENT Function#46
	SetFlag 473
Jump Function#47

Function 45:
Jump Function#19

Function 46:
	CompareVarValue 0x4000 15
	JumpIf DIFFERENT Function#48
	SetFlag 473
Jump Function#47

Function 47:
End

Function 48:
	CompareVarValue 0x4000 16
	JumpIf DIFFERENT Function#49
	SetFlag 473
Jump Function#47

Function 49:
Jump Function#19

//===== ACTIONS =====//
Action 1:
		EmoteExclamation 0x1
End

Action 2:
		WalkEast8 0x1
End

Action 3:
		WalkWest8 0x3
End

Action 4:
		WalkEast8 0x2
End

Action 5:
		WalkOnSpotWest8 0x1
End

Action 6:
		WalkWest8 0x2
End

Action 7:
		WalkOnSpotEast8 0x1
End

Action 8:
		WalkEast8 0x3
End

Action 9:
		WalkWest8 0x1
End

