/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0917
 * Generated: 3/6/2026 7:25:19 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 0
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 1
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 3:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckFlag 2745
	JumpIf LESS Function#1
	Message 4
Jump Function#2

//===== FUNCTIONS =====//
Function 1:
	Message 2
	CheckItem ITEM_SEAL_CASE 1 0x800C
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#3
	Message 5
Jump Function#2

Function 2:
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 3:
	GiveRandomSeals 0x8000 0x8001 0x8002
	CompareVarValue 0x8000 0
	JumpIf DIFFERENT Function#4
	Message 3
Jump Function#2

Function 4:
	SetFlag 2745
	TextSealSingular 0 0x8000
	Message 6
	PlaySound SEQ_ME_ITEM
	Message 11
	WaitSound
	CompareVarValue 0x8001 0
	JumpIf EQUAL Function#5
	TextSealSingular 0 0x8001
	Message 7
	PlaySound SEQ_ME_ITEM
	Message 11
	WaitSound
	CompareVarValue 0x8002 0
	JumpIf EQUAL Function#5
	TextSealSingular 0 0x8002
	Message 8
	PlaySound SEQ_ME_ITEM
	Message 11
	WaitSound
	Message 9
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 5:
	Message 10
Jump Function#2

//===== ACTIONS =====//
