/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0922
 * Generated: 3/6/2026 7:25:19 PM
 */

//===== SCRIPTS =====//
Script 1:
	InitEcruteakGym
	CheckPokeGearRematch 37 0x4001
	CompareVarValue 0x4001 0
	JumpIf DIFFERENT Function#1
	CheckFlag 2404
	JumpIf LESS Function#2
	CheckPokegearNumberRegistered 37 0x4001
	CompareVarValue 0x4001 1
	JumpIf EQUAL Function#3
	GetDayOfWeek 0x4000
	CompareVarValue 0x4000 1
	JumpIf DIFFERENT Function#4
	SetFlag 749
Jump Function#5

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckBadge 3 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#6
	Message 0
	CloseMessage
	TrainerBattle TRAINER_MORTY_031 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#7
	Message 1
	GiveBadge 3
	IncrementVar 0x4134 1
	AddTrainerScore 22
	SetFlag 2456
	TextPlayerName 0
	Message 2
	PlaySound SEQ_ME_BADGE
	WaitSound
	Message 3
Jump Function#8

Script 3:
	MecScript
	LockAll
	PlayFanfare SEQ_SE_DP_GYURU
	Movement Player Action#1
	WaitMovement
	FadeScreen 6 1 0 0
	WaitFadeScreen
	Warp 80 0 16 49 Up
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Script 4:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckBadge 3 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#9
	Message 7
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 5:
	MecScript
	LockAll
	Movement Overworld.6 Action#2
	WaitMovement
	Message 9
	CloseMessage
	Movement Overworld.6 Action#3
	Movement Player Action#4
	WaitMovement
	SetVar 0x4079 1
	FadeScreen 6 1 0 0
	WaitFadeScreen
	Warp 78 7 376 182 Down
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Script 6:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckBadge 3 0x800C
	TextPlayerName 0
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#10
	Message 10
Jump Function#11

//===== FUNCTIONS =====//
Function 1:
	SetFlag 749
End

Function 2:
	ClearFlag 749
End

Function 3:
	GetDayOfWeek 0x4000
	CompareVarValue 0x4000 5
	JumpIf DIFFERENT Function#12
	SetFlag 749
Jump Function#13

Function 4:
	CompareVarValue 0x4000 2
	JumpIf DIFFERENT Function#14
	SetFlag 749
Jump Function#5

Function 5:
End

Function 6:
	CheckFlag 166
	JumpIf LESS Function#8
	Message 6
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 7:
	LostBattle
	ReleaseAll
End

Function 8:
	SetVar 0x8004 357
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#15
	CommonScript 2033
	SetFlag 166
	Message 5
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 9:
	TextPlayerName 0
	Message 8
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 10:
	Message 11
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 11:
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 12:
	ClearFlag 749
End

Function 13:
End

Function 14:
	ClearFlag 749
End

Function 15:
	CommonScript 2009
	CloseMessage
	ReleaseAll
End

//===== ACTIONS =====//
Action 1:
	FaceSouth 0x2
	FaceWest 0x2
	FaceNorth 0x2
	FaceEast 0x2
	FaceSouth 0x2
	FaceWest 0x2
	FaceNorth 0x2
	FaceEast 0x2
	FaceSouth 0x2
	FaceWest 0x2
	FaceNorth 0x2
	FaceEast 0x2
	FaceSouth 0x2
	FaceWest 0x2
	FaceNorth 0x2
	FaceEast 0x1
	SetInvisible 0x0
End

Action 2:
	EmoteExclamation 0x1
	WalkSouth8 0x3
	Delay8 0x1
End

Action 3:
	WalkSouth16 0x1
	LockDir 0x1
	WalkNorth8 0x1
End

Action 4:
	Delay8 0x1
	WalkSouth8 0x1
	Delay8 0x1
End

