/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0923
 * Generated: 3/6/2026 7:25:19 PM
 */

//===== SCRIPTS =====//
Script 1:
	SetVar 0x8007 0
	CommonScript 2002
End

Script 2:
	MecScript
	LockAll
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	Movement Overworld.4 Action#1
	Movement Player Action#2
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	TextPlayerName 0
	Message 0
	Message 1
	CloseMessage
	Movement Overworld.4 Action#3
	Movement Player Action#4
	WaitMovement
	RemoveOW Overworld.4
	SetFlag 453
	ClearFlag 574
	SetFlag 2422
	SetVar 0x410D 1
	ReleaseAll
End

Script 3:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 4:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 3
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 5:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 4
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== FUNCTIONS =====//
//===== ACTIONS =====//
Action 1:
	WalkSouth8 0x4
	WalkEast8 0x6
	WalkNorth8 0x2
	Delay4 0xC
	FaceSouth 0x1
	Delay4 0x4
End

Action 2:
	Delay4 0x14
	WalkNorth8 0x4
End

Action 3:
	WalkEast8 0x1
	WalkSouth8 0x4
	WalkWest8 0x1
	WalkSouth8 0x2
End

Action 4:
	Delay4 0x6
	FaceSouth 0x1
End

