/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0929
 * Generated: 5/20/2026 9:55:41 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckFlag 163
	JumpIf EQUAL Function#1
	Message 0
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#2
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#3
End

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 5
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#4
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#5
End

//===== FUNCTIONS =====//
Function 1:
	Message 3
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 2:
	Message 1
	WaitAB
	SetVar 0x8004 471
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#6
	CommonScript 2033
	SetFlag 163
Jump Function#1

Function 3:
	Message 4
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 4:
	Message 6
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#7
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#5
End

Function 5:
	CloseMessage
	ReleaseAll
End

Function 6:
	CommonScript 2009
	CloseMessage
	ReleaseAll
End

Function 7:
	Message 7
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== ACTIONS =====//
