/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0938
 * Generated: 3/6/2026 7:25:19 PM
 */

//===== SCRIPTS =====//
Script 1:
	CheckFlag 201
	JumpIf EQUAL Function#1
	SetFlag 508
	SetFlag 510
	SetFlag 17
	SetFlag 19
	SetFlag 20
	SetFlag 21
	SetFlag 649
	SetFlag 651
	SetFlag 652
End

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	PlayCry SPECIES_GYARADOS 0
	Message 0
	WaitCry
	CloseMessage
	SetFlag 164
	WildBattleSp SPECIES_GYARADOS 30 1
	ClearFlag 164
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#2
	GetBattleOutcome 0x4002
	CompareVarValue 0x4002 3
	JumpIf EQUAL Function#3
	CompareVarValue 0x4002 4
	CallIf EQUAL Function#4
	CheckFlag 201
	JumpIf EQUAL Function#5
	OpenMessage
	SetVar 0x8004 478
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#6
	CommonScript 2033
	SetFlag 201
	ClearFlag 650
	CloseMessage
	ReleaseAll
End

Script 3:
	CheckFlag 164
	JumpIf EQUAL Function#7
End

Script 4:
	CheckFlag 195
	JumpIf EQUAL Function#8
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Message 2
	FacePlayer
	TextPlayerName 0
	GenderMessage 3 4
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#9
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#10
	TextPlayerName 0
	GenderMessage 5 6
	WaitButton
	CloseMessage
	Movement Overworld.10 Action#1
	WaitMovement
	Movement Overworld.8 Action#2
	WaitMovement
	CMD_775 8 10
	SetFlag 484
	RemoveOW Overworld.8
	RemoveOW Overworld.10
	ClearFlag 504
	SetVar 0x40A8 1
	ReleaseAll
End

Script 5:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckFlag 202
	JumpIf EQUAL Function#11
	Message 9
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 6:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	GetFirstAlivePokemonSlot 0x8002
	CheckRibbon 0x800C 0x8002 61
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#12
	CheckFlag 2748
	JumpIf EQUAL Function#13
	CompareVarValue 0x4094 7
	JumpIf EQUAL Function#14
	CheckFlag 213
	JumpIf EQUAL Function#15
	GetDayOfWeek 0x800C
	CompareVarValue 0x800C 3
	JumpIf EQUAL Function#16
	GetCommonMessageArchive 0 0x800C
	MessageFromArchive 0x800C 11
Jump Function#17

Script 7:
	CheckFlag 313
	JumpIf EQUAL Function#18
	SetTextBoard 2 0
	ShowBoard 3
	WaitBoard
	BoardMessage 31 0x800C
	CommonScript 2000
End

Script 8:
	SetTextBoard 2 0
	ShowBoard 3
	WaitBoard
	BoardMessage 30 0x800C
	CommonScript 2000
End

Script 9:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 12
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 10:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 11
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 11:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 18
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 12:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 21
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 13:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 24
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 14:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 27
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 15:
	SetVar 0x4001 1
	SetVar 0x8008 27
	SetVar 0x8009 1
Jump Function#19

Script 16:
	SetVar 0x4001 2
	SetVar 0x8008 29
	SetVar 0x8009 1
Jump Function#19

Script 17:
	SetVar 0x4001 3
	SetVar 0x8008 23
	SetVar 0x8009 1
Jump Function#19

Script 18:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CompareVarValue 0x4004 1
	JumpIf GREATER/EQUAL Function#20
	Message 13
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#21
	CompareVarValue 0x800C 1
	JumpIf GREATER/EQUAL Function#22
End

Script 19:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	PlayCry SPECIES_DRAGONITE 0
	Message 1
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== FUNCTIONS =====//
Function 1:
Jump Function#23

Function 2:
	LostBattle
	ReleaseAll
End

Function 3:
	ReleaseAll
End

Function 4:
	SetFlag 362
Return

Function 5:
	ClearFlag 484
	RemoveOW Overworld.8
	RemoveOW Overworld.10
	ReleaseAll
End

Function 6:
	CommonScript 2009
	CloseMessage
	ReleaseAll
End

Function 7:
	SetFlag 483
	RemoveOW Overworld.3
	ClearFlag 484
	AddOW Overworld.8
	AddOW Overworld.10
	ClearFlag 164
End

Function 8:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 8
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#9
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#10
End

Function 9:
	TextPlayerName 0
	GenderMessage 5 6
	WaitButton
	CloseMessage
	Movement Overworld.10 Action#1
	WaitMovement
	Movement Overworld.8 Action#2
	WaitMovement
	CMD_775 8 10
	SetFlag 484
	RemoveOW Overworld.8
	RemoveOW Overworld.10
	ClearFlag 504
	SetVar 0x40A8 1
	ReleaseAll
End

Function 10:
	SetFlag 195
	Message 7
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 11:
	Message 10
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 12:
	GetCommonMessageArchive 0 0x800C
	MessageFromArchive 0x800C 37
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 13:
	GetCommonMessageArchive 0 0x800C
	MessageFromArchive 0x800C 39
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 14:
	GetDayOfWeek 0x800C
	CompareVarValue 0x800C 3
	JumpIf EQUAL Function#24
	GetCommonMessageArchive 0 0x800C
	MessageFromArchive 0x800C 11
Jump Function#17

Function 15:
	GetCommonMessageArchive 0 0x800C
	MessageFromArchive 0x800C 10
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 16:
	GetCommonMessageArchive 0 0x800C
	MessageFromArchive 0x800C 8
	SetVar 0x8004 241
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#25
	CommonScript 2033
	SetFlag 213
	IncrementVar 0x4094 1
	GetCommonMessageArchive 0 0x800C
	MessageFromArchive 0x800C 9
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 17:
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 18:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	OverlayManager 0 0
	TextPokemonRecordSize 0 1 SPECIES_MAGIKARP
	OverlayManager 0 1
	TextPlayerName 2
	SetTextBoard 2 0
	ShowBoard 3
	WaitBoard
	BoardMessage 32 0x800C
	CommonScript 2000
	DummyGetPokemonFootprint
	DummyGetPokemonFootprint
	ReleaseAll
End

Function 19:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	WaitFanfare SEQ_SE_CONFIRM
	SetVarFromVariable 0x8004 0x8008
	SetVarFromVariable 0x8005 0x8009
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#26
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#27
End

Function 20:
	Message 17
Jump Function#28

Function 21:
	TextPlayerName 0
	Message 14
	PlaySound SEQ_ME_POKEGEAR_REGIST
	WaitSound
	RecordPokegearNumber 39
	Message 15
	WaitButton
	CloseMessage
	FadeScreen 6 1 0 0
	WaitFadeScreen
	SetFlag 716
	RemoveOW Overworld.20
	PlayFanfare SEQ_SE_DP_KAIDAN2
	WaitFanfare SEQ_SE_DP_KAIDAN2
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Function 22:
	SetVar 0x4004 1
	Message 16
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 23:
	CheckPokegearNumberRegistered 39 0x4001
	CompareVarValue 0x4001 1
	JumpIf EQUAL Function#29
	CheckFlag 2404
	JumpIf EQUAL Function#30
Jump Function#29

Function 24:
	GetCommonMessageArchive 0 0x800C
	MessageFromArchive 0x800C 36
	TextPartyPokemon 0 0x8002
	MessageFromArchive 0x800C 38
	GiveRibbon 0x8002 61
	PlaySound SEQ_ME_ITEM
	WaitSound
	SetFlag 2748
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 25:
	CommonScript 2009
	CloseMessage
	ReleaseAll
End

Function 26:
	CommonScript 2001
	RemoveOW 0x800D
	CompareVarValue 0x4001 1
	JumpIf DIFFERENT Function#31
	SetFlag 326
Jump Function#32

Function 27:
	TextItem 0 0x8004
	Message 35
	WaitButton
	SetVar 0x800C 0
Jump Function#33

Function 28:
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#21
	CompareVarValue 0x800C 1
	JumpIf GREATER/EQUAL Function#22
End

Function 29:
	SetFlag 716
Jump Function#34

Function 30:
	GetHour 0x4000
	CompareVarValue 0x4000 6
	JumpIf DIFFERENT Function#35
	ClearFlag 716
Jump Function#36

Function 31:
	CompareVarValue 0x4001 2
	JumpIf DIFFERENT Function#37
	SetFlag 327
Jump Function#32

Function 32:
	GiveItem 0x8004 0x8005 0x800C
	TextPlayerName 0
	TextItem 1 0x8004
	Message 33
	WaitSound
	TextPlayerName 0
	TextItem 1 0x8004
	GetItemPocket 0x8004 0x800C
	TextPocket 2 0x800C
	Message 34
	WaitButton
	SetVar 0x800C 1
	CloseMessage
	ReleaseAll
End

Function 33:
	CloseMessage
	ReleaseAll
End

Function 34:
	CompareVarValue 0x4037 0xF229
	JumpIf EQUAL Function#38
	SetFlag 508
	SetFlag 510
	ClearFlag 511
	SetFlag 17
	SetFlag 19
	SetFlag 20
	SetFlag 21
	SetFlag 649
	SetFlag 651
	SetFlag 652
End

Function 35:
	CompareVarValue 0x4000 7
	JumpIf DIFFERENT Function#39
	ClearFlag 716
Jump Function#36

Function 36:
Jump Function#34

Function 37:
	SetFlag 328
	GiveItem 0x8004 0x8005 0x800C
	TextPlayerName 0
	TextItem 1 0x8004
	Message 33
	WaitSound
	TextPlayerName 0
	TextItem 1 0x8004
	GetItemPocket 0x8004 0x800C
	TextPocket 2 0x800C
	Message 34
	WaitButton
	SetVar 0x800C 1
	CloseMessage
	ReleaseAll
End

Function 38:
	ClearFlag 508
	ClearFlag 510
	SetFlag 511
	ClearFlag 649
	ClearFlag 651
	ClearFlag 652
	CheckFlag 326
	JumpIf EQUAL Function#40
Jump Function#41

Function 39:
	CompareVarValue 0x4000 8
	JumpIf DIFFERENT Function#42
	ClearFlag 716
Jump Function#36

Function 40:
	SetFlag 649
	CheckFlag 327
	JumpIf EQUAL Function#43
Jump Function#44

Function 41:
	CheckFlag 327
	JumpIf EQUAL Function#43
Jump Function#44

Function 42:
	CompareVarValue 0x4000 9
	JumpIf DIFFERENT Function#45
	ClearFlag 716
Jump Function#36

Function 43:
	SetFlag 651
	CheckFlag 328
	JumpIf EQUAL Function#46
Jump Function#47

Function 44:
	CheckFlag 328
	JumpIf EQUAL Function#46
Jump Function#47

Function 45:
Jump Function#29

Function 46:
	SetFlag 652
End

Function 47:
End

//===== ACTIONS =====//
Action 1:
	WalkOnSpotWest8 0x1
	JumpOnSpotWest8 0x2
End

Action 2:
	WalkOnSpotSouth8 0x1
End

