/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0941
 * Generated: 3/6/2026 7:25:19 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 0
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckFlag 209
	JumpIf EQUAL Function#1
	Message 1
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 3:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 3
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 4:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 4
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 5:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CompareVarValue 0x4077 2
	JumpIf DIFFERENT Function#2
	Message 5
Jump Function#3

Script 6:
	CompareVarValue 0x40C4 1
	JumpIf DIFFERENT Function#4
	SetFlag 521
	SetVar 0x40C4 2
	CheckFlag 393
	JumpIf LESS Function#5
	ClearFlag 393
End

Script 7:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	GetFirstAlivePokemonSlot 0x8002
	CheckRibbon 0x800C 0x8002 64
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#6
	CheckFlag 2748
	JumpIf EQUAL Function#7
	CompareVarValue 0x4094 7
	JumpIf EQUAL Function#8
	CheckFlag 212
	JumpIf EQUAL Function#9
	GetDayOfWeek 0x800C
	CompareVarValue 0x800C 6
	JumpIf EQUAL Function#10
	GetCommonMessageArchive 0 0x800C
	MessageFromArchive 0x800C 23
Jump Function#11

Script 8:
	SetVar 0x8004 1
	SetVar 0x8005 2
	SetVar 0x8006 3
	CommonScript 2039
	SetVar 0x407B 2
End

Script 9:
	SetIconBoard 10 0 20 0x800C
	ShowBoard 3
	WaitBoard
	CloseBoard 0x800C
	CommonScript 2000
End

Script 10:
	SetTextBoard 2 0
	ShowBoard 3
	WaitBoard
	BoardMessage 11 0x800C
	CommonScript 2000
End

Script 11:
	SetTextBoard 2 0
	ShowBoard 3
	WaitBoard
	BoardMessage 12 0x800C
	CommonScript 2000
End

Script 12:
	SetTextBoard 2 0
	ShowBoard 3
	WaitBoard
	BoardMessage 13 0x800C
	CommonScript 2000
End

Script 13:
	SetTextBoard 3 0
	ShowBoard 3
	WaitBoard
	BoardMessage 14 0x800C
	CommonScript 2000
End

Script 14:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 7
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 15:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 8
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 16:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 9
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 17:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 0
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#12
	CheckAlbumPhoto 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#13
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 1
	CloseMessage
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	GetPlayerDirection 0x800C
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#14
	Movement Player Action#1
	Movement Overworld.9 Action#2
Jump Function#15

//===== FUNCTIONS =====//
Function 1:
	Message 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 2:
	Message 6
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 3:
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 4:
	CheckFlag 393
	JumpIf LESS Function#5
	ClearFlag 393
End

Function 5:
	GetDayOfWeek 0x4000
	CompareVarValue 0x4000 0
	JumpIf DIFFERENT Function#16
	ClearFlag 638
Jump Function#17

Function 6:
	GetCommonMessageArchive 0 0x800C
	MessageFromArchive 0x800C 49
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 7:
	GetCommonMessageArchive 0 0x800C
	MessageFromArchive 0x800C 51
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 8:
	GetDayOfWeek 0x800C
	CompareVarValue 0x800C 6
	JumpIf EQUAL Function#18
	GetCommonMessageArchive 0 0x800C
	MessageFromArchive 0x800C 23
Jump Function#11

Function 9:
	GetCommonMessageArchive 0 0x800C
	MessageFromArchive 0x800C 22
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 10:
	GetCommonMessageArchive 0 0x800C
	MessageFromArchive 0x800C 20
	SetVar 0x8004 237
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#19
	CommonScript 2033
	SetFlag 212
	IncrementVar 0x4094 1
	GetCommonMessageArchive 0 0x800C
	MessageFromArchive 0x800C 21
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 11:
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 12:
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 5
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 13:
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 3
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 14:
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#20
	Movement Player Action#3
Jump Function#15

Function 15:
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	CheckPokemonAlive 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#21
	Movement Following Action#4
	WaitMovement
	SetFlag 393
	FadeScreen 6 1 0 0
	WaitFadeScreen
	TakePhoto 44
	LockAll
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ClearFlag 393
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 16:
	CompareVarValue 0x4000 2
	JumpIf DIFFERENT Function#22
	ClearFlag 638
Jump Function#17

Function 17:
	GetDayOfWeek 0x4000
	CompareVarValue 0x4000 6
	JumpIf DIFFERENT Function#23
	ClearFlag 516
Jump Function#24

Function 18:
	GetCommonMessageArchive 0 0x800C
	MessageFromArchive 0x800C 48
	TextPartyPokemon 0 0x8002
	MessageFromArchive 0x800C 50
	GiveRibbon 0x8002 64
	PlaySound SEQ_ME_ITEM
	WaitSound
	SetFlag 2748
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 19:
	CommonScript 2009
	CloseMessage
	ReleaseAll
End

Function 20:
	Movement Player Action#5
	Movement Overworld.9 Action#2
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	CheckPokemonAlive 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#21
	Movement Following Action#4
	WaitMovement
	SetFlag 393
	FadeScreen 6 1 0 0
	WaitFadeScreen
	TakePhoto 44
	LockAll
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ClearFlag 393
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 21:
	SetFlag 393
	FadeScreen 6 1 0 0
	WaitFadeScreen
	TakePhoto 44
	LockAll
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ClearFlag 393
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 22:
	SetFlag 638
	GetDayOfWeek 0x4000
	CompareVarValue 0x4000 6
	JumpIf DIFFERENT Function#23
	ClearFlag 516
Jump Function#24

Function 23:
	SetFlag 516
End

Function 24:
End

//===== ACTIONS =====//
Action 1:
	WalkWest8 0x1
	WalkNorth8 0x2
	WalkEast8 0x1
	WalkNorth8 0x3
	WalkOnSpotSouth8 0x1
End

Action 2:
	Delay8 0x1
	WalkOnSpotNorth8 0x1
End

Action 3:
	WalkNorth8 0x3
	WalkOnSpotSouth8 0x1
End

Action 4:
	WalkEast8 0x1
	WalkNorth8 0x1
	FaceSouth 0x1
End

Action 5:
	WalkNorth8 0x1
	WalkEast8 0x1
	WalkNorth8 0x3
	WalkOnSpotSouth8 0x1
End

