/*
 * DSPRE Script File
 * Rom ID: pokeheartgold
 * Game: HGSS
 * File: 0947
 * Generated: 5/20/2026 9:55:41 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckFlag 208
	JumpIf EQUAL Function#1
	Message 0
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#2
Jump Function#3

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	GetFirstAlivePokemonSlot 0x8000
	CheckRibbon 0x800C 0x8000 24
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#4
	TextPartyPokemon 0 0x8000
	Message 5
	CountPokemonEVs 0x800C 0x8000
	CompareVarValue 0x800C 510
	JumpIf LESS Function#5
	Message 6
	GiveRibbon 0x8000 24
	PlaySound SEQ_ME_ITEM
	TextPlayerName 1
	Message 7
	WaitSound
	TextPartyPokemon 0 0x8000
	Message 8
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== FUNCTIONS =====//
Function 1:
	Message 4
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 2:
	CloseMessage
	FadeScreen 6 1 0 0
	WaitFadeScreen
	PartyPokemonTradeScreen
	GetSelectedPartySlot 0x800C
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	CompareVarValue 0x800C 255
	JumpIf EQUAL Function#3
	InitTrade 3
	SetVarFromVariable 0x8004 0x800C
	GetPartyPokemonID 0x8004 0x8005
	GetPokemonGender 0x8004 0x8006
	CompareVarValue 0x8006 0
	JumpIf EQUAL Function#6
	GetRequestedPokemon 0x800C
	CompareVars 0x8005 0x800C
	JumpIf DIFFERENT Function#6
	TradePokemonScreen 0x8004
	EndTrade
	SetFlag 208
	Message 1
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 3:
	Message 3
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 4:
	TextPartyPokemon 0 0x8000
	Message 14
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 5:
	CompareVarValue 0x800C 506
	JumpIf DIFFERENT Function#7
	Message 10
Jump Function#8

Function 6:
	EndTrade
	Message 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 7:
	CompareVarValue 0x800C 507
	JumpIf DIFFERENT Function#9
	Message 11
Jump Function#8

Function 8:
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 9:
	CompareVarValue 0x800C 508
	JumpIf DIFFERENT Function#10
	Message 12
Jump Function#8

Function 10:
	CompareVarValue 0x800C 509
	JumpIf DIFFERENT Function#11
	Message 13
Jump Function#8

Function 11:
	Message 9
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== ACTIONS =====//
