/*
 * DSPRE Script File
 * Rom ID: spawn - Copy
 * Game: HGSS
 * File: 0004
 * Generated: 2/25/2026 10:00:56 PM
 */

//===== SCRIPTS =====//
Script 1:
	CompareVarValue 0x4133 2
	JumpIf EQUAL Function#1
	CompareVarValue 0x4133 1
	JumpIf EQUAL Function#1
End

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	PartyLegalCheck 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#2
	CheckPlayerForm 0x800C
	CompareVarValue 0x800C 3
	JumpIf EQUAL Function#3
	Message 0
Jump Function#4

Script 3:
	CMD_230
	EnterBattleRoom
End

Script 4:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	PartyLegalCheck 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#2
	CheckPlayerForm 0x800C
	CompareVarValue 0x800C 3
	JumpIf EQUAL Function#5
	GetPartyCount 0x4009
	SetVar 0x400A 0
	GetPartyPokemonID 0x400A 0x800C
	CompareVarValue 0x800C 172
	JumpIf DIFFERENT Function#6
	CheckPartyPokemonForm 0x400A 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#6
Jump Function#7

Script 5:
End

Script 6:
End

Script 7:
End

Script 8:
End

Script 9:
End

Script 10:
End

Script 11:
	FinishOverworldScreen
	CMD_152
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
End

Script 12:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	SetFlag 102
	Message 116
Jump Function#8

Script 13:
	MecScript
	LockAll
	GetCurrentHeaderID 0x800C
	CMD_840 0x800C 0x8004
	GetPlayerPosition 0x4000 0x4001
	CompareVarValue 0x8004 0
	JumpIf DIFFERENT Function#9
Jump Function#10

Script 14:
	MecScript
	LockAll
	GetCurrentHeaderID 0x800C
	CMD_840 0x800C 0x8004
	GetPlayerPosition 0x4000 0x4001
	CompareVarValue 0x8004 0
	JumpIf DIFFERENT Function#11
Jump Function#10

Script 15:
	UseScript_#13

Script 16:
	UseScript_#13

Script 17:
	Call Function#12
	LocalScript
End

Script 18:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 149
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== FUNCTIONS =====//
Function 1:
	VanishOverworld Player
End

Function 2:
	Call Function#12
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 3:
	Message 144
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 4:
	Message 2
	OpenTouchScreen
	MultiTouchStandardText 1 1 0 1 0x800C
	CreateMultiTouchBox 166 255 0
	CreateMultiTouchBox 167 255 1
	CreateMultiTouchBox 11 255 2
	CreateMultiTouchBox 12 255 3
	CloseMultiTouch
	SetVarFromVariable 0x8008 0x800C
	CompareVarValue 0x8008 0
	JumpIf EQUAL Function#13
	CompareVarValue 0x8008 1
	JumpIf EQUAL Function#14
	CompareVarValue 0x8008 2
	JumpIf EQUAL Function#15
Jump Function#16

Function 5:
	Message 146
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 6:
	IncrementVar 0x400A 1
	CompareVars 0x400A 0x4009
	JumpIf GREATER/EQUAL Function#17
Jump Function#18

Function 7:
	CompareVarValue 0x412F 0
	JumpIf DIFFERENT Function#19
	Message 172
Jump Function#20

Function 8:
	Message 117
	MultiStandardText 1 1 0 1 0x800C
	AddMultiOption 42 0
	AddMultiOption 43 1
	AddMultiOption 11 2
	ShowMulti
	SetVarFromVariable 0x8008 0x800C
	CompareVarValue 0x8008 0
	JumpIf EQUAL Function#21
	CompareVarValue 0x8008 1
	JumpIf EQUAL Function#22
	CompareVarValue 0x8008 2
	JumpIf EQUAL Function#23
Jump Function#22

Function 9:
	CompareVarValue 0x8004 1
	JumpIf DIFFERENT Function#24
	CompareVarValue 0x4000 12
	JumpIf EQUAL Function#25
Jump Function#10

Function 10:
	SetVar 0x4133 0
	UnvanishOverworld Player
	ReleaseAll
End

Function 11:
	CompareVarValue 0x8004 1
	JumpIf DIFFERENT Function#26
	CompareVarValue 0x4000 7
	JumpIf EQUAL Function#27
Jump Function#10

Function 12:
	Message 142
Return

Function 13:
	Message 1
	MultiTouchStandardText 1 1 0 1 0x800C
	CreateMultiTouchBox 6 255 0
	CreateMultiTouchBox 7 255 1
	CreateMultiTouchBox 8 255 2
	CreateMultiTouchBox 10 255 3
	CreateMultiTouchBox 13 255 4
	CloseMultiTouch
	SetVarFromVariable 0x4003 0x800C
	SetVarFromVariable 0x8008 0x800C
	CompareVarValue 0x8008 0
	JumpIf EQUAL Function#28
	CompareVarValue 0x8008 1
	JumpIf EQUAL Function#29
	CompareVarValue 0x8008 2
	JumpIf EQUAL Function#30
	CompareVarValue 0x8008 3
	JumpIf EQUAL Function#31
Jump Function#4

Function 14:
	Message 3
	MultiTouchLocalText 1 1 0 1 0x800C
	CreateMultiTouchBox 4 255 0
	CreateMultiTouchBox 5 255 1
	CloseMultiTouch
	SetVarFromVariable 0x8008 0x800C
	CompareVarValue 0x8008 0
	JumpIf EQUAL Function#32
Jump Function#4

Function 15:
	Message 6
	CloseMessage
Jump Function#4

Function 16:
	Message 29
	WaitButton
	CloseMessage
	CloseTouchScreen
	ReleaseAll
End

Function 17:
Jump Function#33

Function 18:
	GetPartyPokemonID 0x400A 0x800C
	CompareVarValue 0x800C 172
	JumpIf DIFFERENT Function#6
	CheckPartyPokemonForm 0x400A 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#6
Jump Function#7

Function 19:
	Message 147
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 20:
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 21:
	CloseMessage
	FadeScreen 6 1 0 0
	WaitFadeScreen
	CMD_252
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
Jump Function#22

Function 22:
	Message 118
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 23:
	Message 119
Jump Function#8

Function 24:
	CompareVarValue 0x8004 2
	JumpIf DIFFERENT Function#34
	CompareVarValue 0x4000 18
	JumpIf EQUAL Function#35
Jump Function#10

Function 25:
	CompareVarValue 0x4001 2
	JumpIf EQUAL Function#36
Jump Function#10

Function 26:
	CompareVarValue 0x8004 2
	JumpIf DIFFERENT Function#37
	CompareVarValue 0x4000 4
	JumpIf EQUAL Function#38
Jump Function#10

Function 27:
	CompareVarValue 0x4001 2
	JumpIf EQUAL Function#39
Jump Function#10

Function 28:
	SetVar 0x8004 1
Jump Function#40

Function 29:
	SetVar 0x8004 2
	CountPartyBornPokemon 0x800C
	CompareVarValue 0x800C 2
	JumpIf LESS Function#41
Jump Function#40

Function 30:
	SetVar 0x8004 3
	CountPartyBornPokemon 0x800C
	CompareVarValue 0x800C 3
	JumpIf LESS Function#42
Jump Function#43

Function 31:
	SetVar 0x8004 37
Jump Function#44

Function 32:
	SetVar 0x8004 4
	CountPartyBornPokemon 0x800C
	CompareVarValue 0x800C 3
	JumpIf LESS Function#45
Jump Function#43

Function 33:
	Message 71
	OpenTouchScreen
	MultiTouchStandardText 1 1 0 1 0x800C
	CreateMultiTouchBox 42 255 0
	CreateMultiTouchBox 11 255 1
	CreateMultiTouchBox 45 255 2
	CloseMultiTouch
	SetVarFromVariable 0x8008 0x800C
	CompareVarValue 0x8008 0
	JumpIf EQUAL Function#46
	CompareVarValue 0x8008 1
	JumpIf EQUAL Function#47
	CompareVarValue 0x8008 2
	JumpIf EQUAL Function#16
Jump Function#16

Function 34:
Jump Function#10

Function 35:
	CompareVarValue 0x4001 11
	JumpIf EQUAL Function#48
Jump Function#10

Function 36:
	SetVar 0x4000 12
	SetVar 0x4001 2
	SetVar 0x4002 5
Jump Function#49

Function 37:
Jump Function#10

Function 38:
	CompareVarValue 0x4001 11
	JumpIf EQUAL Function#50
Jump Function#10

Function 39:
	SetVar 0x4000 7
	SetVar 0x4001 2
	SetVar 0x4002 5
Jump Function#49

Function 40:
	Message 120
	MultiTouchLocalText 1 1 0 1 0x4000
	CreateMultiTouchBox 20 255 12
	TextRulesetName 0
	CreateMultiTouchBox 19 255 0
	TextRulesetName 1
	CreateMultiTouchBox 19 255 1
	TextRulesetName 2
	CreateMultiTouchBox 19 255 2
	TextRulesetName 3
	CreateMultiTouchBox 19 255 3
	TextRulesetName 4
	CreateMultiTouchBox 19 255 4
	CMD_837 0x4000
	CompareVarValue 0x4000 0
	JumpIf EQUAL Function#51
	TextRulesetName 5
	CreateMultiTouchBox 19 255 5
	CreateMultiTouchBox 22 255 255
	CloseMultiTouch
	SetVarFromVariable 0x8008 0x4000
	CompareVarValue 0x8008 12
	JumpIf EQUAL Function#52
	CompareVarValue 0x8008 0
	JumpIf EQUAL Function#53
	CompareVarValue 0x8008 1
	JumpIf EQUAL Function#53
	CompareVarValue 0x8008 2
	JumpIf EQUAL Function#53
	CompareVarValue 0x8008 3
	JumpIf EQUAL Function#53
	CompareVarValue 0x8008 4
	JumpIf EQUAL Function#53
	CompareVarValue 0x8008 5
	JumpIf EQUAL Function#53
Jump Function#4

Function 41:
	Message 10
	WaitButton
	CloseMessage
	CloseTouchScreen
	ReleaseAll
End

Function 42:
	Message 141
	WaitButton
	CloseMessage
	CloseTouchScreen
	ReleaseAll
End

Function 43:
	CommonScript 2006
	SetVarFromVariable 0x800C 0x4000
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#54
Jump Function#55

Function 44:
	SetVar 0x8004 37
	Message 120
	MultiTouchLocalText 1 1 0 1 0x4000
	CreateMultiTouchBox 20 255 6
	TextRulesetName 7
	CreateMultiTouchBox 19 255 7
	TextRulesetName 8
	CreateMultiTouchBox 19 255 8
	TextRulesetName 9
	CreateMultiTouchBox 19 255 9
	TextRulesetName 10
	CreateMultiTouchBox 23 255 10
	TextRulesetName 11
	CreateMultiTouchBox 19 255 11
	CreateMultiTouchBox 22 255 255
	CloseMultiTouch
	SetVarFromVariable 0x8008 0x4000
	CompareVarValue 0x8008 6
	JumpIf EQUAL Function#52
	CompareVarValue 0x8008 7
	JumpIf EQUAL Function#53
	CompareVarValue 0x8008 8
	JumpIf EQUAL Function#53
	CompareVarValue 0x8008 9
	JumpIf EQUAL Function#56
	CompareVarValue 0x8008 10
	JumpIf EQUAL Function#57
	CompareVarValue 0x8008 11
	JumpIf EQUAL Function#56
Jump Function#4

Function 45:
	Message 140
	WaitButton
	CloseMessage
	CloseTouchScreen
	ReleaseAll
End

Function 46:
	SetVar 0x8004 9
	Message 139
	YesNoTouchScreen 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#16
	CommSanitizeParty 0x800C
	CompareVarValue 0x800C 255
	JumpIf EQUAL Function#58
	SetVar 0x4133 2
	SetFlag 2406
	CommonScript 2006
	SetVarFromVariable 0x800C 0x4000
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#59
	SetVar 0x4133 0
	ClearFlag 2406
Jump Function#55

Function 47:
	Message 72
	YesNoTouchScreen 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#46
Jump Function#16

Function 48:
	SetVar 0x4000 18
	SetVar 0x4001 11
	SetVar 0x4002 14
Jump Function#49

Function 49:
	DoorAnimation 0 0 0x4000 0x4001 77
	Call Function#60
	Movement Player Action#1
	WaitMovement
	Call Function#61
	DoorAnimation 0 0 0x4000 0x4002 77
	Call Function#60
	Movement Player Action#2
	WaitMovement
	Call Function#61
	BallResetFollowingPoke
	ClearFlag 2406
	SetVar 0x4133 0
	SetVar 0x4133 0
	ReleaseAll
End

Function 50:
	SetVar 0x4000 4
	SetVar 0x4001 11
	SetVar 0x4002 14
Jump Function#49

Function 51:
	CreateMultiTouchBox 22 255 255
	CloseMultiTouch
	SetVarFromVariable 0x8008 0x4000
	CompareVarValue 0x8008 12
	JumpIf EQUAL Function#52
	CompareVarValue 0x8008 0
	JumpIf EQUAL Function#53
	CompareVarValue 0x8008 1
	JumpIf EQUAL Function#53
	CompareVarValue 0x8008 2
	JumpIf EQUAL Function#53
	CompareVarValue 0x8008 3
	JumpIf EQUAL Function#53
	CompareVarValue 0x8008 4
	JumpIf EQUAL Function#53
	CompareVarValue 0x8008 5
	JumpIf EQUAL Function#53
Jump Function#4

Function 52:
	CMD_800 0x4000
Jump Function#43

Function 53:
	CMD_800 0x4000
Jump Function#62

Function 54:
	OpenTouchScreen
	CompareVarValue 0x8004 1
	CallIf EQUAL Function#63
	CompareVarValue 0x8004 2
	CallIf EQUAL Function#63
	CompareVarValue 0x8004 3
	CallIf EQUAL Function#63
	CompareVarValue 0x8004 37
	CallIf EQUAL Function#63
	CompareVarValue 0x8004 38
	CallIf EQUAL Function#63
	CompareVarValue 0x8004 4
	CallIf EQUAL Function#64
	MultiTouchStandardText 1 1 0 1 0x800C
	CreateMultiTouchBox 14 255 0
	CreateMultiTouchBox 15 255 1
	CreateMultiTouchBox 5 255 2
	CloseMultiTouch
	SetVarFromVariable 0x8008 0x800C
	CompareVarValue 0x8008 0
	JumpIf EQUAL Function#65
	CompareVarValue 0x8008 1
	JumpIf EQUAL Function#66
Jump Function#16

Function 55:
	Message 29
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 56:
	SetVar 0x8004 38
Jump Function#53

Function 57:
	SetVar 0x8004 38
	CMD_800 0x4000
	CMD_803 0x4000 0x4002
	CompareVarValue 0x4002 1
	JumpIf EQUAL Function#41
Jump Function#43

Function 58:
	CommonScript 2041
End

Function 59:
	SetVar 0x4133 2
	SetFlag 2406
	Message 77
	CloseMessage
	SendBackFollowingPoke
	HealPokemon
	Movement Player Action#3
	WaitMovement
	CMD_815 0
Jump Function#67

Function 60:
	OpenDoor 77
	WaitDoor 77
Return

Function 61:
	CloseDoor 77
	WaitDoor 77
	FreeDoor 77
Return

Function 62:
	CMD_799 0x4000
	Message 121
	MultiTouchLocalText 1 1 0 1 0x800C
	CreateMultiTouchBox 130 255 0
	CreateMultiTouchBox 131 255 1
	CompareVarValue 0x4000 11
	JumpIf DIFFERENT Function#68
	CreateMultiTouchBox 24 255 2
	CreateMultiTouchBox 22 255 3
	CloseMultiTouch
	SetVarFromVariable 0x8008 0x800C
	CompareVarValue 0x8008 0
	JumpIf EQUAL Function#69
	CompareVarValue 0x8008 1
	JumpIf EQUAL Function#70
	CompareVarValue 0x4000 11
	JumpIf DIFFERENT Function#71
	CompareVarValue 0x8008 2
	JumpIf EQUAL Function#72
Jump Function#73

Function 63:
	Message 36
Return

Function 64:
	Message 57
Return

Function 65:
	Message 139
	YesNoTouchScreen 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#74
	CloseMessage
	CMD_226 0x8004 0x8005 0 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#75
	CompareVarValue 0x800C 3
	JumpIf EQUAL Function#76
	CompareVarValue 0x800C 4
	JumpIf EQUAL Function#77
Jump Function#78

Function 66:
	Message 139
	YesNoTouchScreen 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#74
	CloseMessage
	CMD_227 0x8004 0x8005 0 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#79
	CompareVarValue 0x800C 3
	JumpIf EQUAL Function#80
	CompareVarValue 0x800C 4
	JumpIf EQUAL Function#81
Jump Function#78

Function 67:
	GetCurrentHeaderID 0x800C
	CompareVarValue 0x800C 300
	JumpIf DIFFERENT Function#82
	SetVar 0x4000 4
	SetVar 0x4001 11
	SetVar 0x4002 14
Jump Function#83

Function 68:
	CreateMultiTouchBox 22 255 3
	CloseMultiTouch
	SetVarFromVariable 0x8008 0x800C
	CompareVarValue 0x8008 0
	JumpIf EQUAL Function#69
	CompareVarValue 0x8008 1
	JumpIf EQUAL Function#70
	CompareVarValue 0x4000 11
	JumpIf DIFFERENT Function#71
	CompareVarValue 0x8008 2
	JumpIf EQUAL Function#72
Jump Function#73

Function 69:
	CMD_803 0x4000 0x4002
	CompareVarValue 0x4002 0
	JumpIf EQUAL Function#43
	CompareVarValue 0x4002 1
	JumpIf EQUAL Function#84
Jump Function#85

Function 70:
	CloseMessage
	CMD_801 0x4000
	WaitAB
	CMD_802
Jump Function#62

Function 71:
Jump Function#73

Function 72:
	CloseTouchScreen
	TextPlayerName 0
	Message 25
	SetVar 0x4005 0
	CheckPokemonIsSeen 150 0x4004
	CompareVarValue 0x4004 1
	JumpIf DIFFERENT Function#86
	TextPokemon 0 SPECIES_MEWTWO 0 0
	Message 26
	SetVar 0x4005 1
	CheckPokemonIsSeen 249 0x4004
	CompareVarValue 0x4004 1
	JumpIf DIFFERENT Function#87
	TextPokemon 0 SPECIES_LUGIA 0 0
	Message 26
	SetVar 0x4005 1
	CheckPokemonIsSeen 250 0x4004
	CompareVarValue 0x4004 1
	JumpIf DIFFERENT Function#88
	TextPokemon 0 SPECIES_HO_OH 0 0
	Message 26
	SetVar 0x4005 1
	CheckPokemonIsSeen 382 0x4004
	CompareVarValue 0x4004 1
	JumpIf DIFFERENT Function#89
	TextPokemon 0 SPECIES_KYOGRE 0 0
	Message 26
	SetVar 0x4005 1
	CheckPokemonIsSeen 383 0x4004
	CompareVarValue 0x4004 1
	JumpIf DIFFERENT Function#90
	TextPokemon 0 SPECIES_GROUDON 0 0
	Message 26
	SetVar 0x4005 1
	CheckPokemonIsSeen 384 0x4004
	CompareVarValue 0x4004 1
	JumpIf DIFFERENT Function#91
	TextPokemon 0 SPECIES_RAYQUAZA 0 0
	Message 26
	SetVar 0x4005 1
	CheckPokemonIsSeen 483 0x4004
	CompareVarValue 0x4004 1
	JumpIf DIFFERENT Function#92
	TextPokemon 0 SPECIES_DIALGA 0 0
	Message 26
	SetVar 0x4005 1
	CheckPokemonIsSeen 484 0x4004
	CompareVarValue 0x4004 1
	JumpIf DIFFERENT Function#93
	TextPokemon 0 SPECIES_PALKIA 0 0
	Message 26
	SetVar 0x4005 1
	CheckPokemonIsSeen 487 0x4004
	CompareVarValue 0x4004 1
	JumpIf DIFFERENT Function#94
	TextPokemon 0 SPECIES_GIRATINA 0 0
	Message 26
	SetVar 0x4005 1
	CompareVarValue 0x4005 1
	JumpIf DIFFERENT Function#95
	Message 27
Jump Function#96

Function 73:
	CompareVarValue 0x4003 3
	JumpIf EQUAL Function#44
Jump Function#40

Function 74:
	CompareVarValue 0x8004 1
	CallIf EQUAL Function#63
	CompareVarValue 0x8004 2
	CallIf EQUAL Function#63
	CompareVarValue 0x8004 3
	CallIf EQUAL Function#63
	CompareVarValue 0x8004 37
	CallIf EQUAL Function#63
	CompareVarValue 0x8004 38
	CallIf EQUAL Function#63
	CompareVarValue 0x8004 4
	CallIf EQUAL Function#64
	MultiTouchStandardText 1 1 0 1 0x800C
	CreateMultiTouchBox 14 255 0
	CreateMultiTouchBox 15 255 1
	CreateMultiTouchBox 5 255 2
	CloseMultiTouch
	SetVarFromVariable 0x8008 0x800C
	CompareVarValue 0x8008 0
	JumpIf EQUAL Function#65
	CompareVarValue 0x8008 1
	JumpIf EQUAL Function#66
Jump Function#16

Function 75:
	EndWirelessComms
	OpenTouchScreen
Jump Function#74

Function 76:
	EndWirelessComms
	CloseTouchScreen
	Message 30
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 77:
	EndWirelessComms
	Message 29
	WaitButton
	CloseMessage
	CloseTouchScreen
	ReleaseAll
End

Function 78:
	SetVar 0x4133 1
	SetFlag 2406
	MessageNoSkip 66
	WaitTimeOrAB 45
	CMD_257 96
	CloseMessage
	SendBackFollowingPoke
	HealPokemon
	CMD_815 0
	GetCurrentHeaderID 0x800C
	CompareVarValue 0x800C 300
	JumpIf DIFFERENT Function#97
	Movement Player Action#4
	WaitMovement
	SetVar 0x4000 18
	SetVar 0x4001 11
	SetVar 0x4002 14
Jump Function#98

Function 79:
	EndWirelessComms
	OpenTouchScreen
Jump Function#74

Function 80:
	EndWirelessComms
	Message 30
	WaitButton
	CloseMessage
	CloseTouchScreen
	ReleaseAll
End

Function 81:
	EndWirelessComms
	Message 29
	WaitButton
	CloseMessage
	CloseTouchScreen
	ReleaseAll
End

Function 82:
	SetVar 0x4000 7
	SetVar 0x4001 2
	SetVar 0x4002 5
Jump Function#83

Function 83:
	DoorAnimation 0 0 0x4000 0x4002 77
	Call Function#60
	Movement Player Action#5
	WaitMovement
	Call Function#61
	Movement Player Action#6
	WaitMovement
	DoorAnimation 0 0 0x4000 0x4001 77
	Call Function#60
	Movement Player Action#7
	WaitMovement
	Call Function#61
	ReleaseAll
	UnionMapChange
End

Function 84:
	Message 122
	WaitAB
	CompareVarValue 0x4003 3
	JumpIf EQUAL Function#44
Jump Function#40

Function 85:
	Message 136
	WaitAB
Jump Function#40

Function 86:
	CheckPokemonIsSeen 249 0x4004
	CompareVarValue 0x4004 1
	JumpIf DIFFERENT Function#87
	TextPokemon 0 SPECIES_LUGIA 0 0
	Message 26
	SetVar 0x4005 1
	CheckPokemonIsSeen 250 0x4004
	CompareVarValue 0x4004 1
	JumpIf DIFFERENT Function#88
	TextPokemon 0 SPECIES_HO_OH 0 0
	Message 26
	SetVar 0x4005 1
	CheckPokemonIsSeen 382 0x4004
	CompareVarValue 0x4004 1
	JumpIf DIFFERENT Function#89
	TextPokemon 0 SPECIES_KYOGRE 0 0
	Message 26
	SetVar 0x4005 1
	CheckPokemonIsSeen 383 0x4004
	CompareVarValue 0x4004 1
	JumpIf DIFFERENT Function#90
	TextPokemon 0 SPECIES_GROUDON 0 0
	Message 26
	SetVar 0x4005 1
	CheckPokemonIsSeen 384 0x4004
	CompareVarValue 0x4004 1
	JumpIf DIFFERENT Function#91
	TextPokemon 0 SPECIES_RAYQUAZA 0 0
	Message 26
	SetVar 0x4005 1
	CheckPokemonIsSeen 483 0x4004
	CompareVarValue 0x4004 1
	JumpIf DIFFERENT Function#92
	TextPokemon 0 SPECIES_DIALGA 0 0
	Message 26
	SetVar 0x4005 1
	CheckPokemonIsSeen 484 0x4004
	CompareVarValue 0x4004 1
	JumpIf DIFFERENT Function#93
	TextPokemon 0 SPECIES_PALKIA 0 0
	Message 26
	SetVar 0x4005 1
	CheckPokemonIsSeen 487 0x4004
	CompareVarValue 0x4004 1
	JumpIf DIFFERENT Function#94
	TextPokemon 0 SPECIES_GIRATINA 0 0
	Message 26
	SetVar 0x4005 1
	CompareVarValue 0x4005 1
	JumpIf DIFFERENT Function#95
	Message 27
Jump Function#96

Function 87:
	CheckPokemonIsSeen 250 0x4004
	CompareVarValue 0x4004 1
	JumpIf DIFFERENT Function#88
	TextPokemon 0 SPECIES_HO_OH 0 0
	Message 26
	SetVar 0x4005 1
	CheckPokemonIsSeen 382 0x4004
	CompareVarValue 0x4004 1
	JumpIf DIFFERENT Function#89
	TextPokemon 0 SPECIES_KYOGRE 0 0
	Message 26
	SetVar 0x4005 1
	CheckPokemonIsSeen 383 0x4004
	CompareVarValue 0x4004 1
	JumpIf DIFFERENT Function#90
	TextPokemon 0 SPECIES_GROUDON 0 0
	Message 26
	SetVar 0x4005 1
	CheckPokemonIsSeen 384 0x4004
	CompareVarValue 0x4004 1
	JumpIf DIFFERENT Function#91
	TextPokemon 0 SPECIES_RAYQUAZA 0 0
	Message 26
	SetVar 0x4005 1
	CheckPokemonIsSeen 483 0x4004
	CompareVarValue 0x4004 1
	JumpIf DIFFERENT Function#92
	TextPokemon 0 SPECIES_DIALGA 0 0
	Message 26
	SetVar 0x4005 1
	CheckPokemonIsSeen 484 0x4004
	CompareVarValue 0x4004 1
	JumpIf DIFFERENT Function#93
	TextPokemon 0 SPECIES_PALKIA 0 0
	Message 26
	SetVar 0x4005 1
	CheckPokemonIsSeen 487 0x4004
	CompareVarValue 0x4004 1
	JumpIf DIFFERENT Function#94
	TextPokemon 0 SPECIES_GIRATINA 0 0
	Message 26
	SetVar 0x4005 1
	CompareVarValue 0x4005 1
	JumpIf DIFFERENT Function#95
	Message 27
Jump Function#96

Function 88:
	CheckPokemonIsSeen 382 0x4004
	CompareVarValue 0x4004 1
	JumpIf DIFFERENT Function#89
	TextPokemon 0 SPECIES_KYOGRE 0 0
	Message 26
	SetVar 0x4005 1
	CheckPokemonIsSeen 383 0x4004
	CompareVarValue 0x4004 1
	JumpIf DIFFERENT Function#90
	TextPokemon 0 SPECIES_GROUDON 0 0
	Message 26
	SetVar 0x4005 1
	CheckPokemonIsSeen 384 0x4004
	CompareVarValue 0x4004 1
	JumpIf DIFFERENT Function#91
	TextPokemon 0 SPECIES_RAYQUAZA 0 0
	Message 26
	SetVar 0x4005 1
	CheckPokemonIsSeen 483 0x4004
	CompareVarValue 0x4004 1
	JumpIf DIFFERENT Function#92
	TextPokemon 0 SPECIES_DIALGA 0 0
	Message 26
	SetVar 0x4005 1
	CheckPokemonIsSeen 484 0x4004
	CompareVarValue 0x4004 1
	JumpIf DIFFERENT Function#93
	TextPokemon 0 SPECIES_PALKIA 0 0
	Message 26
	SetVar 0x4005 1
	CheckPokemonIsSeen 487 0x4004
	CompareVarValue 0x4004 1
	JumpIf DIFFERENT Function#94
	TextPokemon 0 SPECIES_GIRATINA 0 0
	Message 26
	SetVar 0x4005 1
	CompareVarValue 0x4005 1
	JumpIf DIFFERENT Function#95
	Message 27
Jump Function#96

Function 89:
	CheckPokemonIsSeen 383 0x4004
	CompareVarValue 0x4004 1
	JumpIf DIFFERENT Function#90
	TextPokemon 0 SPECIES_GROUDON 0 0
	Message 26
	SetVar 0x4005 1
	CheckPokemonIsSeen 384 0x4004
	CompareVarValue 0x4004 1
	JumpIf DIFFERENT Function#91
	TextPokemon 0 SPECIES_RAYQUAZA 0 0
	Message 26
	SetVar 0x4005 1
	CheckPokemonIsSeen 483 0x4004
	CompareVarValue 0x4004 1
	JumpIf DIFFERENT Function#92
	TextPokemon 0 SPECIES_DIALGA 0 0
	Message 26
	SetVar 0x4005 1
	CheckPokemonIsSeen 484 0x4004
	CompareVarValue 0x4004 1
	JumpIf DIFFERENT Function#93
	TextPokemon 0 SPECIES_PALKIA 0 0
	Message 26
	SetVar 0x4005 1
	CheckPokemonIsSeen 487 0x4004
	CompareVarValue 0x4004 1
	JumpIf DIFFERENT Function#94
	TextPokemon 0 SPECIES_GIRATINA 0 0
	Message 26
	SetVar 0x4005 1
	CompareVarValue 0x4005 1
	JumpIf DIFFERENT Function#95
	Message 27
Jump Function#96

Function 90:
	CheckPokemonIsSeen 384 0x4004
	CompareVarValue 0x4004 1
	JumpIf DIFFERENT Function#91
	TextPokemon 0 SPECIES_RAYQUAZA 0 0
	Message 26
	SetVar 0x4005 1
	CheckPokemonIsSeen 483 0x4004
	CompareVarValue 0x4004 1
	JumpIf DIFFERENT Function#92
	TextPokemon 0 SPECIES_DIALGA 0 0
	Message 26
	SetVar 0x4005 1
	CheckPokemonIsSeen 484 0x4004
	CompareVarValue 0x4004 1
	JumpIf DIFFERENT Function#93
	TextPokemon 0 SPECIES_PALKIA 0 0
	Message 26
	SetVar 0x4005 1
	CheckPokemonIsSeen 487 0x4004
	CompareVarValue 0x4004 1
	JumpIf DIFFERENT Function#94
	TextPokemon 0 SPECIES_GIRATINA 0 0
	Message 26
	SetVar 0x4005 1
	CompareVarValue 0x4005 1
	JumpIf DIFFERENT Function#95
	Message 27
Jump Function#96

Function 91:
	CheckPokemonIsSeen 483 0x4004
	CompareVarValue 0x4004 1
	JumpIf DIFFERENT Function#92
	TextPokemon 0 SPECIES_DIALGA 0 0
	Message 26
	SetVar 0x4005 1
	CheckPokemonIsSeen 484 0x4004
	CompareVarValue 0x4004 1
	JumpIf DIFFERENT Function#93
	TextPokemon 0 SPECIES_PALKIA 0 0
	Message 26
	SetVar 0x4005 1
	CheckPokemonIsSeen 487 0x4004
	CompareVarValue 0x4004 1
	JumpIf DIFFERENT Function#94
	TextPokemon 0 SPECIES_GIRATINA 0 0
	Message 26
	SetVar 0x4005 1
	CompareVarValue 0x4005 1
	JumpIf DIFFERENT Function#95
	Message 27
Jump Function#96

Function 92:
	CheckPokemonIsSeen 484 0x4004
	CompareVarValue 0x4004 1
	JumpIf DIFFERENT Function#93
	TextPokemon 0 SPECIES_PALKIA 0 0
	Message 26
	SetVar 0x4005 1
	CheckPokemonIsSeen 487 0x4004
	CompareVarValue 0x4004 1
	JumpIf DIFFERENT Function#94
	TextPokemon 0 SPECIES_GIRATINA 0 0
	Message 26
	SetVar 0x4005 1
	CompareVarValue 0x4005 1
	JumpIf DIFFERENT Function#95
	Message 27
Jump Function#96

Function 93:
	CheckPokemonIsSeen 487 0x4004
	CompareVarValue 0x4004 1
	JumpIf DIFFERENT Function#94
	TextPokemon 0 SPECIES_GIRATINA 0 0
	Message 26
	SetVar 0x4005 1
	CompareVarValue 0x4005 1
	JumpIf DIFFERENT Function#95
	Message 27
Jump Function#96

Function 94:
	CompareVarValue 0x4005 1
	JumpIf DIFFERENT Function#95
	Message 27
Jump Function#96

Function 95:
	Message 28
	OpenTouchScreen
Jump Function#62

Function 96:
	OpenTouchScreen
Jump Function#62

Function 97:
	Movement Player Action#3
	WaitMovement
	SetVar 0x4000 12
	SetVar 0x4001 2
	SetVar 0x4002 5
Jump Function#98

Function 98:
	DoorAnimation 0 0 0x4000 0x4002 77
	Call Function#60
	Movement Player Action#5
	WaitMovement
	Call Function#61
	Movement Player Action#6
	WaitMovement
	DoorAnimation 0 0 0x4000 0x4001 77
	Call Function#60
	Movement Player Action#7
	WaitMovement
	Call Function#61
	CompareVarValue 0x8004 4
	JumpIf EQUAL Function#99
	CMD_451 0x800C
	IncrementVar 0x800C 7
	BattleRoomWarp 4 0 0x800C 11 0
	ReleaseAll
End

Function 99:
	CMD_451 0x800C
	IncrementVar 0x800C 6
	BattleRoomWarp 5 0 0x800C 11 0
	ReleaseAll
End

//===== ACTIONS =====//
Action 1:
	FaceSouth 0x1
	SetVisible 0x1
	WalkSouth8 0x2
End

Action 2:
	WalkSouth8 0x2
End

Action 3:
	WalkEast8 0x1
	WalkOnSpotNorth8 0x1
End

Action 4:
	WalkWest8 0x1
	WalkOnSpotNorth8 0x1
End

Action 5:
	WalkNorth8 0x2
End

Action 6:
	WalkNorth8 0x1
End

Action 7:
	WalkNorth8 0x1
	SetInvisible 0x1
End

