/*
 * DSPRE Script File
 * Rom ID: spawn - Copy
 * Game: HGSS
 * File: 0018
 * Generated: 2/25/2026 10:00:56 PM
 */

//===== SCRIPTS =====//
Script 1:
	ClearFlag 419
	CheckFlag 120
	JumpIf EQUAL Function#1
End

Script 2:
	MecScript
	LockAll
	SetVar 0x40A4 1
	Movement Player Action#1
	WaitMovement
	GetPlayerPosition 0x8004 0x8005
	LockCamera 0x8004 0x8005
	Movement Camera Action#2
	WaitMovement
	Movement Overworld.3 Action#3
	WaitMovement
	Message 0
	CloseMessage
	WaitTime 15 0x800C
	CommonScript 2070
	TextRivalName 0
	Movement Overworld.6 Action#4
	WaitMovement
	Message 1
	CloseMessage
	WaitTime 15 0x800C
	TextRivalName 0
	Message 2
	WaitAB
	CloseMessage
	PlayFanfare SEQ_SE_DP_KAIDAN2
	Movement Overworld.6 Action#5
	WaitMovement
	RemoveOW Overworld.6
	SetFlag 120
	CommonScript 2071
	Movement Camera Action#6
	WaitMovement
	ReleaseCamera
	ReleaseAll
End

Script 3:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckFlag 118
	JumpIf EQUAL Function#2
	Message 3
	CloseMessage
	TrainerBattle TRAINER_LI_290 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#3
	Message 4
	SetVar 0x8004 397
	SetVar 0x8005 1
	CommonScript 2033
	SetFlag 118
	SetFlag 739
	ClearFlag 740
	Message 5
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== FUNCTIONS =====//
Function 1:
	SetFlag 419
End

Function 2:
	Message 6
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 3:
	LostBattle
	ReleaseAll
End

//===== ACTIONS =====//
Action 1:
	EmoteExclamation 0x1
	Delay8 0x1
End

Action 2:
	WalkNorth8 0x5
End

Action 3:
	WalkOnSpotSouth8 0x2
End

Action 4:
	WalkSouth8 0x1
End

Action 5:
	FaceWest 0x4
	FaceNorth 0x4
	FaceEast 0x4
	FaceSouth 0x4
	FaceWest 0x2
	FaceNorth 0x2
	FaceEast 0x2
	FaceSouth 0x2
	FaceWest 0x2
	FaceNorth 0x2
	FaceEast 0x2
	FaceSouth 0x2
	FaceWest 0x1
	FaceNorth 0x1
	FaceEast 0x1
	FaceSouth 0x1
	FaceWest 0x1
	FaceNorth 0x1
	FaceEast 0x1
	FaceSouth 0x1
	FaceWest 0x1
	FaceNorth 0x1
End

Action 6:
	WalkSouth8 0x5
End

