/*
 * DSPRE Script File
 * Rom ID: spawn - Copy
 * Game: HGSS
 * File: 0037
 * Generated: 2/25/2026 10:00:56 PM
 */

//===== SCRIPTS =====//
Script 1:
	SetTextBoard 2 0
	ShowBoard 3
	WaitBoard
	BoardMessage 10 0x800C
	CommonScript 2000
End

Script 2:
	SetTextBoard 2 0
	ShowBoard 3
	WaitBoard
	BoardMessage 9 0x800C
	CommonScript 2000
End

Script 3:
	SetTextBoard 2 0
	ShowBoard 3
	WaitBoard
	BoardMessage 7 0x800C
	CommonScript 2000
End

Script 4:
	SetTextBoard 2 0
	ShowBoard 3
	WaitBoard
	BoardMessage 8 0x800C
	CommonScript 2000
End

Script 5:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 0
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#1
	CheckAlbumPhoto 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#2
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 1
	CloseMessage
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	GetPlayerDirection 0x800C
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#3
	Movement Player Action#1
	Movement Overworld.8 Action#2
Jump Function#4

Script 6:
	CheckFlag 393
	JumpIf LESS Function#5
	ClearFlag 393
End

Script 7:
	CompareVarValue 0x403E 7
	JumpIf GREATER/EQUAL Function#6
	CompareVarValue 0x403E 6
	JumpIf EQUAL Function#7
	SetWarpPosition 11 418 284
	SetWarpPosition 12 419 284
	SetWarpPosition 13 418 284
	SetWarpPosition 14 419 284
End

Script 8:
	MecScript
	LockAll
	GetFirstAlivePokemonSlot 0x4005
	FollowingPokemonIsEventTrigger 2 0x4005 0x4006
	CompareVarValue 0x4006 0
	JumpIf EQUAL Function#8
Jump Function#9

//===== FUNCTIONS =====//
Function 1:
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 5
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 2:
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 3
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 3:
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#10
	Movement Player Action#3
Jump Function#4

Function 4:
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	CheckPokemonAlive 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#11
	Movement Following Action#4
	WaitMovement
	SetFlag 393
	FadeScreen 6 1 0 0
	WaitFadeScreen
	TakePhoto 3
	LockAll
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ClearFlag 393
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 5:
	CompareVarValue 0x40FB 9
	JumpIf GREATER/EQUAL Function#12
	SetVar 0x40FB 1
	CheckBadge 2 0x4000
	CompareVarValue 0x4000 0
	JumpIf EQUAL Function#13
	GetDayOfWeek 0x4000
	CompareVarValue 0x4000 5
	JumpIf EQUAL Function#14
	CompareVarValue 0x4000 6
	JumpIf EQUAL Function#14
	CompareVarValue 0x4000 0
	JumpIf EQUAL Function#14
	SetFlag 638
Jump Function#15

Function 6:
	SetWarpPosition 8 418 284
	SetWarpPosition 9 419 284
	SetWarpPosition 11 418 284
	SetWarpPosition 12 419 284
End

Function 7:
	SetWarpPosition 8 418 284
	SetWarpPosition 9 419 284
	SetWarpPosition 13 418 284
	SetWarpPosition 14 419 284
End

Function 8:
	FollowingPokemonIsEventTrigger 1 0x4005 0x4007
	CompareVarValue 0x4007 0
	JumpIf EQUAL Function#16
	CheckBike 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#16
	DoorAnimation 13 8 25 29 77
	OpenDoor 77
	WaitDoor 77
	ClearFlag 742
	AddOW Overworld.9
	CloseDoor 77
	WaitDoor 77
	FreeDoor 77
	Movement Overworld.9 Action#5
	Movement Player Action#6
	GetPlayerDirection 0x4001
	CompareVarValue 0x4001 3
	JumpIf DIFFERENT Function#17
	Movement Following Action#7
Jump Function#18

Function 9:
	CheckBike 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#16
	DoorAnimation 13 8 25 29 77
	OpenDoor 77
	WaitDoor 77
	ClearFlag 742
	AddOW Overworld.9
	CloseDoor 77
	WaitDoor 77
	FreeDoor 77
	Movement Overworld.9 Action#5
	Movement Player Action#6
	GetPlayerDirection 0x4001
	CompareVarValue 0x4001 3
	JumpIf DIFFERENT Function#17
	Movement Following Action#7
Jump Function#18

Function 10:
	Movement Player Action#8
	Movement Overworld.8 Action#2
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	CheckPokemonAlive 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#11
	Movement Following Action#4
	WaitMovement
	SetFlag 393
	FadeScreen 6 1 0 0
	WaitFadeScreen
	TakePhoto 3
	LockAll
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ClearFlag 393
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 11:
	SetFlag 393
	FadeScreen 6 1 0 0
	WaitFadeScreen
	TakePhoto 3
	LockAll
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ClearFlag 393
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 12:
	CheckBadge 2 0x4000
	CompareVarValue 0x4000 0
	JumpIf EQUAL Function#13
	GetDayOfWeek 0x4000
	CompareVarValue 0x4000 5
	JumpIf EQUAL Function#14
	CompareVarValue 0x4000 6
	JumpIf EQUAL Function#14
	CompareVarValue 0x4000 0
	JumpIf EQUAL Function#14
	SetFlag 638
Jump Function#15

Function 13:
	SetFlag 638
Jump Function#15

Function 14:
	ClearFlag 638
	CompareVarValue 0x403E 7
	JumpIf GREATER/EQUAL Function#6
	CompareVarValue 0x403E 6
	JumpIf EQUAL Function#7
Jump Function#19

Function 15:
	CompareVarValue 0x403E 7
	JumpIf GREATER/EQUAL Function#6
	CompareVarValue 0x403E 6
	JumpIf EQUAL Function#7
Jump Function#19

Function 16:
	ReleaseAll
End

Function 17:
	CompareVarValue 0x4001 2
	JumpIf DIFFERENT Function#20
	Movement Following Action#9
Jump Function#18

Function 18:
	WaitMovement
	Message 1
	CloseMessage
	Movement Overworld.9 Action#10
	CompareVarValue 0x4001 3
	JumpIf DIFFERENT Function#21
	Movement Following Action#11
Jump Function#22

Function 19:
	SetWarpPosition 11 418 284
	SetWarpPosition 12 419 284
	SetWarpPosition 13 418 284
	SetWarpPosition 14 419 284
End

Function 20:
	Movement Following Action#12
	WaitMovement
	Message 1
	CloseMessage
	Movement Overworld.9 Action#10
	CompareVarValue 0x4001 3
	JumpIf DIFFERENT Function#21
	Movement Following Action#11
Jump Function#22

Function 21:
	CompareVarValue 0x4001 2
	JumpIf DIFFERENT Function#23
	Movement Following Action#13
Jump Function#22

Function 22:
	WaitMovement
	Message 2
	CloseMessage
	CompareVarValue 0x4001 3
	JumpIf DIFFERENT Function#24
	Movement Overworld.9 Action#14
Jump Function#25

Function 23:
	Movement Following Action#15
	WaitMovement
	Message 2
	CloseMessage
	CompareVarValue 0x4001 3
	JumpIf DIFFERENT Function#24
	Movement Overworld.9 Action#14
Jump Function#25

Function 24:
	Movement Overworld.9 Action#16
	WaitMovement
	Message 3
	CloseMessage
	Movement Overworld.9 Action#17
	WaitMovement
	Message 4
	CloseMessage
	Movement Overworld.9 Action#18
	WaitMovement
	Message 5
	CloseMessage
	Movement Overworld.9 Action#19
	WaitMovement
	Message 6
	CloseMessage
	SetVar 0x40FB 2
	SetFlag 742
	ClearFlag 743
	PlayFanfare SEQ_SE_DP_KAIDAN2
	CompareVarValue 0x403E 6
	JumpIf DIFFERENT Function#26
	FadeScreen 6 1 0 0
	WaitFadeScreen
	Warp 490 0 15 24 Left
	FadeScreen 6 1 1 0
	WaitFadeScreen
Jump Function#16

Function 25:
	WaitMovement
	Message 3
	CloseMessage
	Movement Overworld.9 Action#17
	WaitMovement
	Message 4
	CloseMessage
	Movement Overworld.9 Action#18
	WaitMovement
	Message 5
	CloseMessage
	Movement Overworld.9 Action#19
	WaitMovement
	Message 6
	CloseMessage
	SetVar 0x40FB 2
	SetFlag 742
	ClearFlag 743
	PlayFanfare SEQ_SE_DP_KAIDAN2
	CompareVarValue 0x403E 6
	JumpIf DIFFERENT Function#26
	FadeScreen 6 1 0 0
	WaitFadeScreen
	Warp 490 0 15 24 Left
	FadeScreen 6 1 1 0
	WaitFadeScreen
Jump Function#16

Function 26:
	CompareVarValue 0x403E 7
	JumpIf DIFFERENT Function#27
	FadeScreen 6 1 0 0
	WaitFadeScreen
	Warp 492 0 15 24 Left
	FadeScreen 6 1 1 0
	WaitFadeScreen
Jump Function#16

Function 27:
	CompareVarValue 0x403E 8
	JumpIf DIFFERENT Function#28
	FadeScreen 6 1 0 0
	WaitFadeScreen
	Warp 492 0 15 24 Left
	FadeScreen 6 1 1 0
	WaitFadeScreen
Jump Function#16

Function 28:
	CompareVarValue 0x403E 9
	JumpIf DIFFERENT Function#29
	FadeScreen 6 1 0 0
	WaitFadeScreen
	Warp 492 0 15 24 Left
	FadeScreen 6 1 1 0
	WaitFadeScreen
Jump Function#16

Function 29:
	FadeScreen 6 1 0 0
	WaitFadeScreen
	Warp 315 0 15 24 Left
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

//===== ACTIONS =====//
Action 1:
	WalkEast8 0x1
	WalkNorth8 0x2
	WalkWest8 0x1
	WalkNorth8 0x3
	WalkOnSpotSouth8 0x1
End

Action 2:
	Delay8 0x1
	WalkOnSpotNorth8 0x1
End

Action 3:
	WalkNorth8 0x3
	WalkOnSpotSouth8 0x1
End

Action 4:
	WalkEast8 0x1
	WalkNorth8 0x1
	FaceSouth 0x1
End

Action 5:
	Delay4 0x1
	WalkSouth4 0x3
	LockDir 0x1
	WalkNorth2 0x1
	ReleaseDir 0x1
End

Action 6:
	LockDir 0x1
	JumpFarSouth 0x1
	WalkSouth4 0x2
	ReleaseDir 0x1
	WalkOnSpotNorth8 0x1
End

Action 7:
	LockDir 0x1
	WalkWest4 0x1
	ReleaseDir 0x1
	Delay8 0x2
	WalkOnSpotSouth8 0x1
End

Action 8:
	WalkNorth8 0x1
	WalkWest8 0x1
	WalkNorth8 0x3
	WalkOnSpotSouth8 0x1
End

Action 9:
	JumpOnSpotWest8 0x1
	Delay8 0x3
	WalkOnSpotSouth8 0x1
End

Action 10:
	WalkSouth4 0x1
End

Action 11:
	WalkSouth8 0x3
	WalkEast8 0x1
	WalkOnSpotNorth8 0x1
End

Action 12:
	LockDir 0x1
	WalkSouth4 0x5
	ReleaseDir 0x1
End

Action 13:
	WalkSouth8 0x4
	WalkOnSpotNorth8 0x1
End

Action 14:
	WalkOnSpotWest4 0x1
	EmoteExclamation 0x1
	Delay8 0x1
	LockDir 0x1
	WalkEast8 0x1
	ReleaseDir 0x1
End

Action 15:
	Delay8 0x2
	WalkNorth8 0x1
	WalkEast8 0x1
	WalkNorth8 0x1
End

Action 16:
	EmoteExclamation 0x1
	Delay8 0x1
	WalkEast8 0x1
	WalkOnSpotSouth4 0x1
End

Action 17:
	WalkEast8 0x1
	WalkWest8 0x2
	Delay8 0x1
	WalkEast8 0x2
	WalkOnSpotEast4 0x1
	WalkWest8 0x1
	WalkOnSpotSouth4 0x1
End

Action 18:
	EmoteExclamation 0x1
	Delay8 0x1
	WalkOnSpotSouth4 0x1
End

Action 19:
	WalkWest8 0x1
	WalkSouth8 0x1
	WalkOnSpotSouth4 0x1
End

