/*
 * DSPRE Script File
 * Rom ID: spawn - Copy
 * Game: HGSS
 * File: 0042
 * Generated: 2/25/2026 10:00:56 PM
 */

//===== SCRIPTS =====//
Script 1:
	MecScript
	LockAll
	PlayFanfare SEQ_SE_GS_RAKKA01
	Movement Player Action#1
	UnvanishOverworld Player
	WaitMovement
	ShakeCamera 0 1 1 8
	PlayFanfare SEQ_SE_DP_SUTYA2
	CheckFlag 273
	JumpIf EQUAL Function#1
	CheckFlag 272
	JumpIf EQUAL Function#1
	WaitTime 5 0x800C
	Movement Overworld.3 Action#2
	Movement Overworld.4 Action#2
	Movement Overworld.5 Action#3
	Movement Overworld.6 Action#3
	WaitMovement
	Message 0
	SetVar 0x8004 469
	SetVar 0x8005 1
	CommonScript 2033
	CloseMessage
	Movement Overworld.3 Action#4
	Movement Overworld.4 Action#5
	Movement Overworld.5 Action#6
	Movement Overworld.6 Action#6
	WaitMovement
	RemoveOW Overworld.3
	RemoveOW Overworld.4
	RemoveOW Overworld.5
	RemoveOW Overworld.6
	RemoveOW Overworld.1
	RemoveOW Overworld.0
	RemoveOW Overworld.2
	SetFlag 565
	SetFlag 566
	SetFlag 272
	Message 1
	WaitButton
	CloseMessage
	SetVar 0x40CE 0
	ReleaseAll
End

Script 2:
	CompareVarValue 0x40CE 1
	JumpIf DIFFERENT Function#2
	VanishOverworld Player
End

Script 3:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Message 5
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 4:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 5:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 3
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 6:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 4
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 7:
	MecScript
	LockAll
	Movement Overworld.7 Action#7
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	Movement Player Action#8
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	Message 6
	CloseMessage
	Movement Overworld.7 Action#9
	WaitMovement
	Message 7
	CloseMessage
	FadeOutMusic 0 30
	PlayFanfare SEQ_SE_GS_ZENIGAME_JOURO
	FadeScreen 6 6 0 0
	WaitFadeScreen
	WaitTime 1 0x800C
	FadeScreen 6 6 1 0
	WaitFadeScreen
	StopFanfare SEQ_SE_GS_ZENIGAME_JOURO
	Movement Overworld.7 Action#10
	WaitMovement
	Message 8
	CloseMessage
	PlayFanfare SEQ_SE_GS_ZENIGAME_JOURO
	FadeScreen 6 6 0 0
	WaitFadeScreen
	WaitTime 1 0x800C
	FadeScreen 6 6 1 0
	WaitFadeScreen
	StopFanfare SEQ_SE_GS_ZENIGAME_JOURO
	SetVar 0x40FB 3
	SetFlag 742
	SetFlag 743
	PlayFanfare SEQ_SE_DP_KAIDAN2
	FadeScreen 6 1 0 0
	WaitFadeScreen
	Warp 522 0 16 24 Down
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Script 8:
	MecScript
	LockAll
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	Movement Overworld.7 Action#11
	Movement Player Action#12
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	Movement Player Action#13
	WaitMovement
	Message 9
	CloseMessage
	Movement Overworld.7 Action#14
	WaitMovement
	Message 10
	CloseMessage
	Movement Overworld.7 Action#15
	WaitMovement
	RemoveOW Overworld.7
	SetFlag 743
	SetVar 0x40FB 10
	ReleaseAll
End

Script 9:
	CompareVarValue 0x40FB 10
	JumpIf EQUAL Function#3
Jump Function#4

Script 10:
	MecScript
	LockAll
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	Movement Player Action#16
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	PlayFanfare SEQ_SE_GS_ZENIGAME_JOURO
	FadeScreen 6 6 0 0
	WaitFadeScreen
	WaitTime 1 0x800C
	FadeScreen 6 6 1 0
	WaitFadeScreen
	StopFanfare SEQ_SE_GS_ZENIGAME_JOURO
	Movement Player Action#17
	WaitMovement
	PlayFanfare SEQ_SE_GS_ZENIGAME_JOURO
	FadeScreen 6 6 0 0
	WaitFadeScreen
	WaitTime 1 0x800C
	FadeScreen 6 6 1 0
	WaitFadeScreen
	StopFanfare SEQ_SE_GS_ZENIGAME_JOURO
	SetVar 0x40FB 12
	SetVar 0x4104 1
	SetFlag 732
	SetFlag 733
	SetFlag 731
	PlayFanfare SEQ_SE_DP_KAIDAN2
	FadeScreen 6 1 0 0
	WaitFadeScreen
	Warp 522 0 16 24 Down
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

//===== FUNCTIONS =====//
Function 1:
	SetVar 0x40CE 0
	ReleaseAll
End

Function 2:
End

Function 3:
	GetFirstAlivePokemonSlot 0x4005
	CompareVarValue 0x4102 1
	JumpIf EQUAL Function#5
	CompareVarValue 0x4102 2
	JumpIf EQUAL Function#6
Jump Function#4

Function 4:
End

Function 5:
	FollowingPokemonIsEventTrigger 1 0x4005 0x4007
	CompareVarValue 0x4007 1
	CallIf EQUAL Function#7
	CMD_490 0x4005
	CMD_490 0x4007
End

Function 6:
	FollowingPokemonIsEventTrigger 2 0x4005 0x4006
	CompareVarValue 0x4006 1
	CallIf EQUAL Function#7
	CMD_490 0x4005
	CMD_490 0x4006
End

Function 7:
	SetVar 0x40FB 11
Return

//===== ACTIONS =====//
Action 1:
	TeleportDown 0x1
End

Action 2:
	FaceEast 0x1
	EmoteExclamation 0x1
	WalkEast8 0x5
	WalkSouth8 0x1
End

Action 3:
	FaceWest 0x1
	EmoteExclamation 0x1
	WalkWest8 0x5
	WalkSouth8 0x1
End

Action 4:
	WalkWest8 0xA
End

Action 5:
	WalkNorth8 0xA
End

Action 6:
	WalkEast8 0xA
End

Action 7:
	WalkWest8 0x4
	WalkOnSpotEast8 0x1
End

Action 8:
	WalkWest8 0x4
End

Action 9:
	EmoteExclamation 0x1
	Delay8 0x1
	WalkNorth4 0x3
	WalkOnSpotNorth8 0x1
	WalkWest4 0x2
	WalkOnSpotNorth8 0x1
	LockDir 0x1
	WalkWest16 0x1
	ReleaseDir 0x1
End

Action 10:
	WalkOnSpotEast8 0x1
	Delay8 0x1
	WalkOnSpotWest8 0x1
	Delay8 0x1
	WalkOnSpotSouth8 0x1
End

Action 11:
	Delay8 0x1
	WalkOnSpotWest8 0x1
	EmoteExclamation 0x1
	Delay8 0x1
	WalkWest4 0x3
End

Action 12:
	WalkEast8 0x1
End

Action 13:
	WalkOnSpotEast8 0x1
End

Action 14:
	WalkOnSpotWest8 0x1
End

Action 15:
	WalkEast8 0xA
End

Action 16:
	WalkWest8 0x1
	WalkSouth8 0x1
End

Action 17:
	WalkOnSpotEast8 0x1
	Delay8 0x1
	WalkOnSpotWest8 0x1
	Delay8 0x1
	WalkOnSpotSouth8 0x1
End

