/*
 * DSPRE Script File
 * Rom ID: spawn - Copy
 * Game: HGSS
 * File: 0049
 * Generated: 2/25/2026 10:00:56 PM
 */

//===== SCRIPTS =====//
Script 1:
	MecScript
	LockAll
	SetVar 0x40CD 1
	CheckPokemonAlive 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#1
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#2
End

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Message 0
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== FUNCTIONS =====//
Function 1:
	GetPlayerDirection 0x800C
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#3
	Movement Player Action#1
Jump Function#4

Function 2:
	GetPlayerDirection 0x800C
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#5
	Movement Player Action#1
	Movement Following Action#2
Jump Function#6

Function 3:
	CompareVarValue 0x800C 3
	JumpIf DIFFERENT Function#7
	Movement Player Action#3
Jump Function#4

Function 4:
	WaitMovement
Jump Function#8

Function 5:
	CompareVarValue 0x800C 3
	JumpIf DIFFERENT Function#9
	Movement Player Action#3
	Movement Following Action#4
Jump Function#6

Function 6:
	WaitMovement
	PlayFanfare SEQ_SE_GS_RAKKA01
	FadeScreen 6 1 0 0
	WaitFadeScreen
	Warp 313 0 11 7 0x800C
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Function 7:
	Movement Player Action#5
	WaitMovement
Jump Function#8

Function 8:
	PlayFanfare SEQ_SE_GS_RAKKA01
	FadeScreen 6 1 0 0
	WaitFadeScreen
	Warp 313 0 11 7 0x800C
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Function 9:
	Movement Player Action#5
	Movement Following Action#6
	WaitMovement
	PlayFanfare SEQ_SE_GS_RAKKA01
	FadeScreen 6 1 0 0
	WaitFadeScreen
	Warp 313 0 11 7 0x800C
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

//===== ACTIONS =====//
Action 1:
	WalkOnSpotNorth2 0x4
	SetInvisible 0x1
End

Action 2:
	Delay4 0x3
	WalkNorth2 0x1
	SetInvisible 0x1
End

Action 3:
	WalkOnSpotEast2 0x4
	SetInvisible 0x1
End

Action 4:
	Delay4 0x3
	WalkEast2 0x1
	SetInvisible 0x1
End

Action 5:
	WalkOnSpotWest2 0x4
	SetInvisible 0x1
End

Action 6:
	Delay4 0x3
	WalkWest2 0x1
	SetInvisible 0x1
End

