/*
 * DSPRE Script File
 * Rom ID: spawn - Copy
 * Game: HGSS
 * File: 0081
 * Generated: 2/25/2026 10:00:56 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CompareVarValue 0x40E5 2
	JumpIf EQUAL Function#1
	Message 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 2:
	MecScript
	LockAll
	Message 0
	CloseMessage
	SetOWPosition Overworld.0 14 1 36 Up
	GetPlayerPosition 0x8004 0x8005
	CompareVarValue 0x8004 12
	JumpIf DIFFERENT Function#2
	Movement Overworld.0 Action#1
	Movement Player Action#2
Jump Function#3

Script 3:
	CompareVarValue 0x40E5 2
	JumpIf EQUAL Function#4
End

Script 4:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 0
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#5
	CheckAlbumPhoto 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#6
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 1
	CloseMessage
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	GetPlayerDirection 0x800C
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#7
	Movement Player Action#3
	Movement Overworld.1 Action#4
Jump Function#8

Script 5:
	CheckFlag 393
	JumpIf LESS Function#9
	ClearFlag 393
End

Script 6:
	CheckFlag 336
	JumpIf EQUAL Function#10
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Message 4
	Movement Overworld.2 Action#5
	WaitMovement
	Message 5
	CloseMessage
	SetFlag 336
Jump Function#11

Script 7:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 7
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 8:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 8
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 9:
	SetTextBoard 2 0
	ShowBoard 3
	WaitBoard
	BoardMessage 9 0x800C
	CommonScript 2000
End

//===== FUNCTIONS =====//
Function 1:
	Message 3
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 2:
	CompareVarValue 0x8004 13
	JumpIf DIFFERENT Function#12
	Movement Overworld.0 Action#6
	Movement Player Action#2
Jump Function#3

Function 3:
	WaitMovement
	Message 1
	WaitButton
	CloseMessage
	ReleaseAll
	SetVar 0x40E5 1
	SetFlag 603
End

Function 4:
	SetOWPosition Overworld.0 17 1 25 Left
End

Function 5:
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 5
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 6:
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 3
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 7:
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#13
	Movement Player Action#7
Jump Function#8

Function 8:
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	CheckPokemonAlive 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#14
	Movement Following Action#8
	WaitMovement
	SetFlag 393
	FadeScreen 6 1 0 0
	WaitFadeScreen
	TakePhoto 29
	LockAll
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ClearFlag 393
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 9:
	GetDayOfWeek 0x4000
	CompareVarValue 0x4000 2
	JumpIf EQUAL Function#15
	CompareVarValue 0x4000 6
	JumpIf EQUAL Function#15
	SetFlag 638
End

Function 10:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 6
	CloseMessage
	Movement Overworld.2 Action#9
	WaitMovement
	ReleaseAll
End

Function 11:
	Movement Overworld.2 Action#9
	WaitMovement
	ReleaseAll
End

Function 12:
	CompareVarValue 0x8004 14
	JumpIf DIFFERENT Function#16
	Movement Overworld.0 Action#10
	Movement Player Action#2
Jump Function#3

Function 13:
	CompareVarValue 0x800C 3
	JumpIf DIFFERENT Function#17
	Movement Player Action#11
	Movement Overworld.1 Action#4
Jump Function#8

Function 14:
	SetFlag 393
	FadeScreen 6 1 0 0
	WaitFadeScreen
	TakePhoto 29
	LockAll
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ClearFlag 393
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 15:
	ClearFlag 638
End

Function 16:
	CompareVarValue 0x8004 15
	JumpIf DIFFERENT Function#18
	Movement Overworld.0 Action#12
	Movement Player Action#13
Jump Function#3

Function 17:
	Movement Player Action#14
	Movement Overworld.1 Action#4
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	CheckPokemonAlive 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#14
	Movement Following Action#8
	WaitMovement
	SetFlag 393
	FadeScreen 6 1 0 0
	WaitFadeScreen
	TakePhoto 29
	LockAll
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ClearFlag 393
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 18:
	CompareVarValue 0x8004 16
	JumpIf DIFFERENT Function#19
	Movement Overworld.0 Action#15
	Movement Player Action#13
Jump Function#3

Function 19:
	Movement Overworld.0 Action#16
	Movement Player Action#13
	WaitMovement
	Message 1
	WaitButton
	CloseMessage
	ReleaseAll
	SetVar 0x40E5 1
	SetFlag 603
End

//===== ACTIONS =====//
Action 1:
	WalkWest4 0x1
	WalkNorth4 0x5
	WalkNorth6 0x2
	WalkNorth8 0x1
	WalkOnSpotWest8 0x1
End

Action 2:
	Delay8 0x5
	WalkOnSpotEast8 0x1
End

Action 3:
	WalkEast8 0x1
	WalkNorth8 0x2
	WalkWest8 0x1
	WalkNorth8 0x3
	WalkOnSpotSouth8 0x1
End

Action 4:
	Delay8 0x1
	WalkOnSpotNorth8 0x1
End

Action 5:
	FaceSouth 0x1
End

Action 6:
	WalkNorth4 0x5
	WalkNorth6 0x2
	WalkNorth8 0x1
	WalkOnSpotWest8 0x1
End

Action 7:
	WalkNorth8 0x3
	WalkOnSpotSouth8 0x1
End

Action 8:
	WalkEast8 0x1
	WalkNorth8 0x1
	FaceSouth 0x1
End

Action 9:
	FaceNorth 0x1
End

Action 10:
	WalkEast8 0x1
	WalkNorth4 0x5
	WalkNorth6 0x2
	WalkNorth8 0x1
	WalkOnSpotWest8 0x1
End

Action 11:
	WalkNorth8 0x1
	WalkEast8 0x1
	WalkNorth8 0x3
	WalkOnSpotSouth8 0x1
End

Action 12:
	WalkNorth4 0x5
	WalkNorth6 0x2
	WalkNorth8 0x1
	WalkOnSpotEast8 0x1
End

Action 13:
	Delay8 0x5
	WalkOnSpotWest8 0x1
End

Action 14:
	WalkNorth8 0x1
	WalkWest8 0x1
	WalkNorth8 0x3
	WalkOnSpotSouth8 0x1
End

Action 15:
	WalkEast8 0x1
	WalkNorth4 0x5
	WalkNorth6 0x2
	WalkNorth8 0x1
	WalkOnSpotEast8 0x1
End

Action 16:
	WalkEast4 0x2
	WalkNorth4 0x5
	WalkNorth6 0x2
	WalkNorth8 0x1
	WalkOnSpotEast8 0x1
End

