/*
 * DSPRE Script File
 * Rom ID: spawn - Copy
 * Game: HGSS
 * File: 0104
 * Generated: 2/25/2026 10:00:56 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	SetVar 0x400A 249
	PlayCry 0x400A 0
	Message 4
	WaitCry
	CloseMessage
	CheckVersion 0x800C
	CompareVarValue 0x800C 7
	JumpIf DIFFERENT Function#1
	SetVar 0x8004 70
Jump Function#2

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckFlag 265
	JumpIf EQUAL Function#3
	Message 1
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 3:
	SetFlag 2458
	CheckFlag 164
	JumpIf EQUAL Function#4
End

Script 4:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckFlag 265
	JumpIf EQUAL Function#5
	Message 1
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 5:
	CheckFlag 579
	JumpIf EQUAL Function#6
	VanishOverworld Overworld.6
	VanishOverworld Overworld.7
	VanishOverworld Overworld.8
	VanishOverworld Overworld.9
	VanishOverworld Overworld.10
	CompareVarValue 0x400B 123
	JumpIf DIFFERENT Function#7
	StopFanfare SEQ_SE_GS_N_TAKI
	SetVar 0x400B 0
	CheckFlag 265
	JumpIf EQUAL Function#8
	CheckFlag 267
	JumpIf LESS Function#8
	CompareVarValue 0x4003 111
	JumpIf DIFFERENT Function#8
	SetOWPosition Overworld.4 16 1 32 Up
	SetOWPosition Overworld.2 13 1 33 Up
	SetOWPosition Overworld.3 13 1 27 Up
	SetOWPosition Overworld.0 19 1 33 Up
	SetOWPosition Overworld.1 19 1 27 Up
	SetVar 0x4003 0
End

Script 6:
	MecScript
	LockAll
	Movement Player Action#1
	WaitMovement
	CMD_805
	Movement Overworld.4 Action#2
	WaitMovement
	Message 0
	CloseMessage
	StopFanfare SEQ_SE_GS_N_TAKI
	FadeScreen 4 4 0 0x7FFF
	WaitFadeScreen
	CMD_755
	CMD_757
	PlayFanfare SEQ_SE_GS_SUZUSYUTUGEN_RU
	FadeScreen 4 4 1 0x7FFF
	WaitFadeScreen
	WaitFanfare SEQ_SE_GS_SUZUSYUTUGEN_RU
	Movement Overworld.4 Action#3
	Movement Overworld.2 Action#4
	Movement Overworld.3 Action#5
	Movement Overworld.0 Action#6
	Movement Overworld.1 Action#7
	WaitMovement
	WaitTime 16 0x800C
	Movement Overworld.4 Action#2
	Movement Overworld.2 Action#2
	Movement Overworld.3 Action#2
	Movement Overworld.0 Action#2
	Movement Overworld.1 Action#2
	WaitMovement
	WaitTime 16 0x800C
	StopMusic 0
	TempMusic SEQ_GS_E_MAIKO_MAI
	WaitTime 18 0x800C
	Movement Overworld.4 Action#8
	Movement Overworld.2 Action#8
	Movement Overworld.3 Action#8
	Movement Overworld.0 Action#8
	Movement Overworld.1 Action#8
	WaitTime 12 0x800C
	CMD_758 1
	PlayFanfare SEQ_SE_GS_SUZUNOONPA_RU
	WaitMovement
	WaitTime 67 0x800C
	Movement Overworld.4 Action#8
	Movement Overworld.2 Action#8
	Movement Overworld.3 Action#8
	Movement Overworld.0 Action#8
	Movement Overworld.1 Action#8
	WaitTime 12 0x800C
	CMD_758 1
	PlayFanfare SEQ_SE_GS_SUZUNOONPA_RU
	WaitMovement
	FadeScreen 4 6 1 0x7FFF
	CMD_765
	WaitFadeScreen
	WaitTime 6 0x800C
	Movement Overworld.4 Action#9
	Movement Overworld.2 Action#9
	Movement Overworld.3 Action#10
	Movement Overworld.0 Action#11
	Movement Overworld.1 Action#12
	WaitMovement
	Movement Overworld.4 Action#13
	Movement Overworld.2 Action#13
	Movement Overworld.3 Action#14
	Movement Overworld.0 Action#15
	Movement Overworld.1 Action#16
	WaitTime 12 0x800C
	CMD_758 1
	PlayFanfare SEQ_SE_GS_SUZUNOONPA_RU
	WaitMovement
	WaitTime 32 0x800C
	Movement Overworld.4 Action#11
	Movement Overworld.2 Action#9
	Movement Overworld.3 Action#10
	Movement Overworld.0 Action#11
	Movement Overworld.1 Action#12
	WaitMovement
	Movement Overworld.4 Action#15
	Movement Overworld.2 Action#13
	Movement Overworld.3 Action#14
	Movement Overworld.0 Action#15
	Movement Overworld.1 Action#16
	WaitTime 12 0x800C
	CMD_758 1
	PlayFanfare SEQ_SE_GS_SUZUNOONPA_RU
	WaitMovement
	WaitTime 33 0x800C
	Movement Overworld.4 Action#11
	Movement Overworld.2 Action#9
	Movement Overworld.3 Action#10
	Movement Overworld.0 Action#11
	Movement Overworld.1 Action#12
	WaitMovement
	Movement Overworld.4 Action#15
	Movement Overworld.2 Action#17
	Movement Overworld.3 Action#18
	Movement Overworld.0 Action#19
	Movement Overworld.1 Action#20
	WaitTime 15 0x800C
	CMD_758 1
	PlayFanfare SEQ_SE_GS_SUZUNOONPA_RU
	WaitMovement
	WaitTime 32 0x800C
	Movement Overworld.4 Action#12
	Movement Overworld.2 Action#11
	Movement Overworld.3 Action#9
	Movement Overworld.0 Action#12
	Movement Overworld.1 Action#10
	WaitMovement
	Movement Overworld.4 Action#16
	Movement Overworld.2 Action#15
	Movement Overworld.3 Action#13
	Movement Overworld.0 Action#16
	Movement Overworld.1 Action#14
	WaitTime 12 0x800C
	CMD_758 1
	PlayFanfare SEQ_SE_GS_SUZUNOONPA_RU
	WaitMovement
	CMD_766
	CMD_762 0
	WaitTime 32 0x800C
	Movement Overworld.4 Action#12
	Movement Overworld.2 Action#11
	Movement Overworld.3 Action#9
	Movement Overworld.0 Action#12
	Movement Overworld.1 Action#10
	WaitMovement
	Movement Overworld.4 Action#16
	Movement Overworld.2 Action#15
	Movement Overworld.3 Action#13
	Movement Overworld.0 Action#16
	Movement Overworld.1 Action#14
	WaitTime 12 0x800C
	CMD_758 0
	PlayFanfare SEQ_SE_GS_SUZUNOONPA2
	WaitMovement
	WaitTime 29 0x800C
	Movement Overworld.4 Action#10
	Movement Overworld.2 Action#11
	Movement Overworld.3 Action#9
	Movement Overworld.0 Action#12
	Movement Overworld.1 Action#10
	WaitMovement
	Movement Overworld.4 Action#14
	Movement Overworld.2 Action#19
	Movement Overworld.3 Action#17
	Movement Overworld.0 Action#20
	Movement Overworld.1 Action#18
	WaitTime 15 0x800C
	CMD_758 0
	PlayFanfare SEQ_SE_GS_SUZUNOONPA2
	WaitMovement
	WaitTime 41 0x800C
	CMD_763
	WaitTime 16 0x800C
	FadeScreen 6 1 0 0
	WaitFadeScreen
	CMD_761 1
	FadeScreen 6 1 1 0
	WaitFadeScreen
	Movement Overworld.4 Action#14
	Movement Overworld.2 Action#16
	Movement Overworld.3 Action#15
	Movement Overworld.0 Action#14
	Movement Overworld.1 Action#13
	WaitTime 12 0x800C
	CMD_758 0
	PlayFanfare SEQ_SE_GS_SUZUNOONPA2
	WaitMovement
	WaitTime 32 0x800C
	Movement Overworld.4 Action#10
	Movement Overworld.2 Action#12
	Movement Overworld.3 Action#11
	Movement Overworld.0 Action#10
	Movement Overworld.1 Action#9
	WaitMovement
	Movement Overworld.4 Action#14
	Movement Overworld.2 Action#16
	Movement Overworld.3 Action#15
	Movement Overworld.0 Action#14
	Movement Overworld.1 Action#13
	WaitTime 12 0x800C
	CMD_758 0
	PlayFanfare SEQ_SE_GS_SUZUNOONPA2
	WaitMovement
	WaitTime 29 0x800C
	Movement Overworld.4 Action#9
	Movement Overworld.2 Action#12
	Movement Overworld.3 Action#11
	Movement Overworld.0 Action#10
	Movement Overworld.1 Action#9
	FadeScreen 6 1 0 0
	WaitFadeScreen
	CMD_761 2
	FadeScreen 6 1 1 0
	WaitFadeScreen
	WaitMovement
	Movement Overworld.4 Action#13
	Movement Overworld.2 Action#16
	Movement Overworld.3 Action#15
	Movement Overworld.0 Action#14
	Movement Overworld.1 Action#13
	WaitTime 12 0x800C
	CMD_758 0
	PlayFanfare SEQ_SE_GS_SUZUNOONPA2
	WaitMovement
	WaitTime 32 0x800C
	Movement Overworld.4 Action#9
	Movement Overworld.2 Action#12
	Movement Overworld.3 Action#11
	Movement Overworld.0 Action#10
	Movement Overworld.1 Action#9
	WaitMovement
	Movement Overworld.4 Action#13
	Movement Overworld.2 Action#16
	Movement Overworld.3 Action#15
	Movement Overworld.0 Action#14
	Movement Overworld.1 Action#13
	WaitTime 12 0x800C
	CMD_758 0
	PlayFanfare SEQ_SE_GS_SUZUNOONPA2
	WaitMovement
	WaitTime 38 0x800C
	Movement Overworld.4 Action#11
	Movement Overworld.2 Action#10
	Movement Overworld.3 Action#12
	Movement Overworld.0 Action#9
	Movement Overworld.1 Action#11
	WaitMovement
	Movement Overworld.4 Action#15
	Movement Overworld.2 Action#14
	Movement Overworld.3 Action#16
	Movement Overworld.0 Action#13
	Movement Overworld.1 Action#15
	WaitTime 12 0x800C
	CMD_758 0
	PlayFanfare SEQ_SE_GS_SUZUNOONPA2
	WaitMovement
	CMD_762 1
	WaitTime 32 0x800C
	Movement Overworld.4 Action#11
	Movement Overworld.2 Action#10
	Movement Overworld.3 Action#12
	Movement Overworld.0 Action#9
	Movement Overworld.1 Action#11
	WaitMovement
	Movement Overworld.4 Action#15
	Movement Overworld.2 Action#14
	Movement Overworld.3 Action#16
	Movement Overworld.0 Action#13
	Movement Overworld.1 Action#15
	WaitTime 12 0x800C
	CMD_758 0
	PlayFanfare SEQ_SE_GS_SUZUNOONPA2
	WaitMovement
	FadeOutMusic 0 100
	StopMusic 0
	WaitTime 32 0x800C
	Movement Overworld.4 Action#12
	Movement Overworld.2 Action#10
	Movement Overworld.3 Action#12
	Movement Overworld.0 Action#9
	Movement Overworld.1 Action#11
	WaitMovement
	Movement Overworld.4 Action#16
	Movement Overworld.2 Action#14
	Movement Overworld.3 Action#16
	Movement Overworld.0 Action#13
	Movement Overworld.1 Action#15
	WaitTime 12 0x800C
	WaitMovement
	CMD_763
	WaitTime 32 0x800C
	TempMusic SEQ_GS_E_LUGIA
	WaitTime 48 0x800C
	ShakeCamera 3 3 15 5
	WaitTime 10 0x800C
	WaitTime 70 0x800C
	CMD_759
	WaitTime 26 0x800C
	CMD_756
	SetVar 0x400B 123
	FadeScreen 6 1 0 0
	WaitFadeScreen
	ClearFlag 579
	AddOW Overworld.5
	VanishOverworld Overworld.5
	AddOW Overworld.6
	AddOW Overworld.7
	AddOW Overworld.8
	AddOW Overworld.9
	AddOW Overworld.10
	Release Overworld.4
	Release Overworld.2
	Release Overworld.3
	Release Overworld.0
	Release Overworld.1
	SetOWPosition Overworld.4 16 1 33 Up
	SetOWPosition Overworld.2 13 1 33 Up
	SetOWPosition Overworld.3 13 1 27 Up
	SetOWPosition Overworld.0 19 1 33 Up
	SetOWPosition Overworld.1 19 1 27 Up
	RenderCutscene 1
	CMD_767
	FadeScreen 6 1 1 0
	WaitFadeScreen
	WaitTime 59 0x800C
	CMD_764
	StopMusic 15
	CMD_769
	CMD_768
	WaitTime 16 0x800C
	CMD_726
	Movement Overworld.4 Action#21
	WaitMovement
	TextPlayerName 0
	Message 2
	CloseMessage
	Movement Overworld.4 Action#2
	WaitMovement
	TextPlayerName 0
	Message 3
	WaitButton
	CloseMessage
	ReleaseAll
	SetFlag 267
	SetVar 0x40FA 2
End

Script 7:
	SetVar 0x4003 111
	SetFlag 261
End

//===== FUNCTIONS =====//
Function 1:
	SetVar 0x8004 45
	SetFlag 164
	WildBattleSp 0x400A 0x8004 0
	ClearFlag 164
	GetBattleOutcome 0x4005
	CompareVarValue 0x4005 2
	JumpIf EQUAL Function#9
	CompareVarValue 0x4005 3
	JumpIf EQUAL Function#9
	CompareVarValue 0x4005 4
	CallIf EQUAL Function#10
	ReleaseAll
	SetFlag 265
	SetVar 0x4081 3
	SetFlag 418
	SetFlag 417
	SetFlag 744
	ClearFlag 741
	SetFlag 581
	ClearFlag 572
	ClearFlag 577
End

Function 2:
	SetFlag 164
	WildBattleSp 0x400A 0x8004 0
	ClearFlag 164
	GetBattleOutcome 0x4005
	CompareVarValue 0x4005 2
	JumpIf EQUAL Function#9
	CompareVarValue 0x4005 3
	JumpIf EQUAL Function#9
	CompareVarValue 0x4005 4
	CallIf EQUAL Function#10
	ReleaseAll
	SetFlag 265
	SetVar 0x4081 3
	SetFlag 418
	SetFlag 417
	SetFlag 744
	ClearFlag 741
	SetFlag 581
	ClearFlag 572
	ClearFlag 577
End

Function 3:
	CompareVarValue 0x4005 5
	JumpIf DIFFERENT Function#11
	Message 8
Jump Function#12

Function 4:
	SetFlag 579
	RemoveOW Overworld.5
	RemoveOW Overworld.6
	RemoveOW Overworld.7
	RemoveOW Overworld.8
	RemoveOW Overworld.9
	RemoveOW Overworld.10
	ClearFlag 164
End

Function 5:
	Message 5
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 6:
	CompareVarValue 0x400B 123
	JumpIf DIFFERENT Function#7
	StopFanfare SEQ_SE_GS_N_TAKI
	SetVar 0x400B 0
	CheckFlag 265
	JumpIf EQUAL Function#8
	CheckFlag 267
	JumpIf LESS Function#8
	CompareVarValue 0x4003 111
	JumpIf DIFFERENT Function#8
	SetOWPosition Overworld.4 16 1 32 Up
	SetOWPosition Overworld.2 13 1 33 Up
	SetOWPosition Overworld.3 13 1 27 Up
	SetOWPosition Overworld.0 19 1 33 Up
	SetOWPosition Overworld.1 19 1 27 Up
	SetVar 0x4003 0
End

Function 7:
	CheckFlag 265
	JumpIf EQUAL Function#8
	CheckFlag 267
	JumpIf LESS Function#8
	CompareVarValue 0x4003 111
	JumpIf DIFFERENT Function#8
	SetOWPosition Overworld.4 16 1 32 Up
	SetOWPosition Overworld.2 13 1 33 Up
	SetOWPosition Overworld.3 13 1 27 Up
	SetOWPosition Overworld.0 19 1 33 Up
	SetOWPosition Overworld.1 19 1 27 Up
	SetVar 0x4003 0
End

Function 8:
End

Function 9:
	ClearFlag 579
	LostBattle
	ReleaseAll
End

Function 10:
	SetFlag 279
Return

Function 11:
	CompareVarValue 0x4005 6
	JumpIf DIFFERENT Function#13
	Message 8
Jump Function#12

Function 12:
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 13:
	CompareVarValue 0x4005 4
	JumpIf DIFFERENT Function#14
	Message 6
Jump Function#12

Function 14:
	Message 7
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== ACTIONS =====//
Action 1:
	WalkNorth16 0x2
End

Action 2:
	WalkOnSpotSouth8 0x1
End

Action 3:
	Delay8 0x6
	WalkNorth8 0x1
End

Action 4:
	Delay8 0x5
	WalkWest8 0x2
End

Action 5:
	WalkWest8 0x1
	WalkNorth8 0x6
End

Action 6:
	Delay8 0x5
	WalkEast8 0x2
End

Action 7:
	WalkEast8 0x1
	WalkNorth8 0x6
End

Action 8:
	FaceEast 0x1
	Delay2 0x1
	FaceNorth 0x1
	Delay2 0x1
	FaceWest 0x1
	Delay2 0x1
	FaceSouth 0x1
	Delay2 0x1
End

Action 9:
	WalkEast16 0x2
End

Action 10:
	WalkSouth16 0x2
End

Action 11:
	WalkNorth16 0x2
End

Action 12:
	WalkWest16 0x2
End

Action 13:
	FaceNorth 0x1
	Delay2 0x1
	FaceWest 0x1
	Delay2 0x1
	FaceSouth 0x1
	Delay2 0x1
	FaceEast 0x1
	Delay2 0x1
End

Action 14:
	FaceEast 0x1
	Delay2 0x1
	FaceNorth 0x1
	Delay2 0x1
	FaceWest 0x1
	Delay2 0x1
	FaceSouth 0x1
	Delay2 0x1
End

Action 15:
	FaceWest 0x1
	Delay2 0x1
	FaceSouth 0x1
	Delay2 0x1
	FaceEast 0x1
	Delay2 0x1
	FaceNorth 0x1
	Delay2 0x1
End

Action 16:
	FaceSouth 0x1
	Delay2 0x1
	FaceEast 0x1
	Delay2 0x1
	FaceNorth 0x1
	Delay2 0x1
	FaceWest 0x1
	Delay2 0x1
End

Action 17:
	FaceNorth 0x1
	Delay2 0x1
	FaceWest 0x1
	Delay2 0x1
	FaceSouth 0x1
	Delay2 0x1
	FaceEast 0x1
	Delay2 0x1
	FaceNorth 0x1
	Delay2 0x1
End

Action 18:
	FaceEast 0x1
	Delay2 0x1
	FaceNorth 0x1
	Delay2 0x1
	FaceWest 0x1
	Delay2 0x1
	FaceSouth 0x1
	Delay2 0x1
	FaceEast 0x1
	Delay2 0x1
End

Action 19:
	FaceWest 0x1
	Delay2 0x1
	FaceSouth 0x1
	Delay2 0x1
	FaceEast 0x1
	Delay2 0x1
	FaceNorth 0x1
	Delay2 0x1
	FaceWest 0x1
	Delay2 0x1
End

Action 20:
	FaceSouth 0x1
	Delay2 0x1
	FaceEast 0x1
	Delay2 0x1
	FaceNorth 0x1
	Delay2 0x1
	FaceWest 0x1
	Delay2 0x1
	FaceSouth 0x1
	Delay2 0x1
End

Action 21:
	WalkNorth16 0x1
End

