/*
 * DSPRE Script File
 * Rom ID: spawn - Copy
 * Game: HGSS
 * File: 0109
 * Generated: 2/25/2026 10:00:56 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_GS_RAKKA01
	Movement Player Action#1
	UnvanishOverworld Player
	WaitMovement
	ShakeCamera 0 1 1 8
	PlayFanfare SEQ_SE_DP_SUTYA2
	SetVar 0x40CA 0
End

Script 2:
	CompareVarValue 0x40CA 1
	JumpIf DIFFERENT Function#1
	VanishOverworld Player
End

//===== FUNCTIONS =====//
Function 1:
End

//===== ACTIONS =====//
Action 1:
	TeleportDown 0x1
End

