/*
 * DSPRE Script File
 * Rom ID: spawn - Copy
 * Game: HGSS
 * File: 0126
 * Generated: 2/25/2026 10:00:56 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 0
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckFlag 240
	JumpIf EQUAL Function#1
	Message 1
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 3:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 3
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 4:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 4
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 5:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 5
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 6:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Message 14
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 7:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	PlayCry SPECIES_DRATINI 0
	Message 15
	WaitCry
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 8:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	TextPlayerName 0
	Message 6
	CloseMessage
	FadeScreen 6 1 0 0
	WaitFadeScreen
	CMD_712 1
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Script 9:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckFlag 726
	JumpIf LESS Function#2
	Message 7
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 10:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckFlag 725
	JumpIf LESS Function#3
	Message 9
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 11:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckFlag 727
	JumpIf LESS Function#4
	Message 11
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 12:
	CompareVarValue 0x400C 1
	JumpIf DIFFERENT Function#5
	SetOWPosition Overworld.1 2 1 3 Right
	SetVar 0x400C 0
End

Script 13:
	CheckFlag 240
	JumpIf EQUAL Function#6
	SetVar 0x400C 0
End

Script 14:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 13
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== FUNCTIONS =====//
Function 1:
	Message 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 2:
	Message 8
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 3:
	Message 10
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 4:
	Message 12
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 5:
End

Function 6:
	SetVar 0x400C 1
End

//===== ACTIONS =====//
