/*
 * DSPRE Script File
 * Rom ID: spawn - Copy
 * Game: HGSS
 * File: 0129
 * Generated: 2/25/2026 10:00:56 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 0
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 2:
	NationalDex 2 0x4000
	CompareVarValue 0x4000 1
	JumpIf EQUAL Function#1
	SetOWPosition Overworld.1 30 1 30 Up
	SetOWPosition Overworld.2 30 1 30 Up
	SetOWPosition Overworld.3 30 1 30 Up
	SetOWPosition Overworld.4 30 1 30 Up
	SetOWPosition Overworld.5 30 1 30 Up
	SetOWPosition Overworld.6 30 1 30 Up
End

//===== FUNCTIONS =====//
Function 1:
End

//===== ACTIONS =====//
