/*
 * DSPRE Script File
 * Rom ID: spawn - Copy
 * Game: HGSS
 * File: 0147
 * Generated: 2/25/2026 10:00:57 PM
 */

//===== SCRIPTS =====//
Script 1:
	MecScript
	LockAll
	GetRandom 0x8000 5
	SetVarFromVariable 0x8008 0x8000
	CompareVarValue 0x8008 0
	JumpIf EQUAL Function#1
	CompareVarValue 0x8008 1
	JumpIf EQUAL Function#2
	CompareVarValue 0x8008 2
	JumpIf EQUAL Function#3
	CompareVarValue 0x8008 3
	JumpIf EQUAL Function#4
	CompareVarValue 0x8008 4
	JumpIf EQUAL Function#5
End

//===== FUNCTIONS =====//
Function 1:
	Movement Player Action#1
	Movement Overworld.0 Action#2
	WaitMovement
Jump Function#6

Function 2:
	Movement Player Action#3
	Movement Overworld.0 Action#4
	WaitMovement
Jump Function#6

Function 3:
	Movement Player Action#5
	Movement Overworld.0 Action#6
	WaitMovement
Jump Function#6

Function 4:
	Movement Player Action#7
	Movement Overworld.0 Action#8
	WaitMovement
Jump Function#6

Function 5:
	Movement Player Action#9
	Movement Overworld.0 Action#10
	WaitMovement
Jump Function#6

Function 6:
	Message 0
	WaitAB
	CloseMessage
	Movement Player Action#11
	Movement Overworld.0 Action#12
	WaitMovement
	PlayFanfare SEQ_SE_DP_TELE2
	Movement Player Action#13
	WaitMovement
	FadeScreen 6 1 0 0
	WaitFadeScreen
	SetVar 0x4003 1
	Warp 0x4056 0 5 2 Down
	FinishOverworldScreen
	InitWFC 0x800C
	SetVarFromVariable 0x8004 0x800C
	CMD_663 0x8004
	ReturnScreen
	SetVar 0x4137 1
	VanishOverworld Player
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

//===== ACTIONS =====//
Action 1:
	WalkNorth8 0x7
	WalkWest8 0xB
End

Action 2:
	WalkNorth8 0x6
	WalkWest8 0xC
	WalkOnSpotEast8 0x1
End

Action 3:
	WalkNorth8 0x7
	WalkWest8 0x9
End

Action 4:
	WalkNorth8 0x6
	WalkWest8 0xA
	WalkOnSpotEast8 0x1
End

Action 5:
	WalkNorth8 0x7
	WalkWest8 0x7
End

Action 6:
	WalkNorth8 0x6
	WalkWest8 0x8
	WalkOnSpotEast8 0x1
End

Action 7:
	WalkNorth8 0x7
	WalkWest8 0x5
End

Action 8:
	WalkNorth8 0x6
	WalkWest8 0x6
	WalkOnSpotEast8 0x1
End

Action 9:
	WalkNorth8 0x7
	WalkWest8 0x3
End

Action 10:
	WalkNorth8 0x6
	WalkWest8 0x4
	WalkOnSpotEast8 0x1
End

Action 11:
	WalkNorth8 0x1
	FaceWest 0x1
	Delay2 0x1
	FaceSouth 0x1
	Delay2 0x1
	FaceEast 0x1
	Delay2 0x1
	FaceNorth 0x1
	Delay2 0x1
	FaceWest 0x1
	Delay2 0x1
	FaceSouth 0x1
	Delay2 0x1
	FaceEast 0x1
	Delay2 0x1
	FaceNorth 0x1
	Delay2 0x1
	FaceWest 0x1
	Delay2 0x1
	FaceSouth 0x1
	Delay2 0x1
	FaceEast 0x1
	Delay2 0x1
	FaceNorth 0x1
End

Action 12:
	WalkOnSpotNorth8 0x1
End

Action 13:
	TeleportUp 0x1
End

