/*
 * DSPRE Script File
 * Rom ID: spawn - Copy
 * Game: HGSS
 * File: 0151
 * Generated: 2/25/2026 10:00:57 PM
 */

//===== SCRIPTS =====//
Script 1:
	MecScript
	LockAll
	PlayFanfare SEQ_SE_DP_PINPON
	Message 0
	CloseMessage
	Call Function#1
	ReleaseAll
End

Script 2:
	MecScript
	LockAll
	PlayFanfare SEQ_SE_DP_PINPON
	Message 1
	CloseMessage
	Call Function#1
	ReleaseAll
End

Script 3:
End

Script 4:
End

Script 5:
	MecScript
	LockAll
	TextBugContestRemainingTime 0
	Message 3
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CloseMessage
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#2
	Call Function#1
	ReleaseAll
End

Script 6:
	CompareVarValue 0x4058 0
	JumpIf EQUAL Function#3
	Call Function#4
	LocalScript
End

Script 7:
	TextBugContestRemainingTime 0
	Message 23
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#5
	Message 26
	CloseMessage
	LocalScript
End

Script 8:
	MecScript
	LockAll
	SetVar 0x4118 0
	SetVar 0x40F7 0
	OverlayManager 1 0
	BugContestResults 0x4000 0x4001 0x4002
	GetPlayerPosition 0x8004 0x8005
	LockCamera 0x8004 0x8005
	Movement Camera Action#1
	WaitMovement
	Message 29
	TextBugContestPlacement 2
	CompareVarValue 0x4000 2
	JumpIf DIFFERENT Function#6
	Message 30
Jump Function#7

Script 9:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 48
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 10:
	CheckFlag 321
	JumpIf EQUAL Function#8
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 49
	WaitButton
	CloseMessage
	ReleaseAll
Jump Function#9

Script 11:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 51
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 12:
	CheckFlag 321
	JumpIf EQUAL Function#10
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 52
	WaitButton
	CloseMessage
	ReleaseAll
Jump Function#11

Script 13:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 54
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 14:
	CheckFlag 321
	JumpIf EQUAL Function#12
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 55
	WaitButton
	CloseMessage
	ReleaseAll
Jump Function#13

Script 15:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 57
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 16:
	CheckFlag 321
	JumpIf EQUAL Function#14
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 58
	WaitButton
	CloseMessage
	ReleaseAll
Jump Function#15

Script 17:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 60
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 18:
	CheckFlag 321
	JumpIf EQUAL Function#16
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 61
	WaitButton
	CloseMessage
	ReleaseAll
Jump Function#17

Script 19:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 63
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 20:
	CheckFlag 321
	JumpIf EQUAL Function#18
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 64
	WaitButton
	CloseMessage
	ReleaseAll
Jump Function#19

Script 21:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 66
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 22:
	CheckFlag 321
	JumpIf EQUAL Function#20
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 67
	WaitButton
	CloseMessage
	ReleaseAll
Jump Function#21

Script 23:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 69
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 24:
	CheckFlag 321
	JumpIf EQUAL Function#22
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 70
	WaitButton
	CloseMessage
	ReleaseAll
Jump Function#23

Script 25:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 72
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 26:
	CheckFlag 321
	JumpIf EQUAL Function#24
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 73
	WaitButton
	CloseMessage
	ReleaseAll
Jump Function#25

Script 27:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 75
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 28:
	CheckFlag 321
	JumpIf EQUAL Function#26
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 76
	WaitButton
	CloseMessage
	ReleaseAll
Jump Function#27

Script 29:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CompareVarValue 0x4058 0
	JumpIf EQUAL Function#28
	Call Function#4
Jump Function#29

//===== FUNCTIONS =====//
Function 1:
	FadeScreen 6 1 0 0
	WaitFadeScreen
	Warp 96 0 46 50 Up
	FadeScreen 6 1 1 0
	WaitFadeScreen
Return

Function 2:
	ReleaseAll
End

Function 3:
	CheckFlag 2727
	JumpIf EQUAL Function#30
	GetDayOfWeek 0x4000
	CompareVarValue 0x4000 2
	JumpIf DIFFERENT Function#31
	Message 4
Jump Function#32

Function 4:
	TextPlayerName 0
	Message 20
	CheckItemSpace 0x4058 1 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#33
	SetVarFromVariable 0x8004 0x4058
	SetVar 0x8005 1
	CommonScript 2008
	SetVar 0x4058 0
Jump Function#34

Function 5:
	Message 27
	CloseMessage
	SetVar 0x4118 2
	Call Function#1
	LocalScript
End

Function 6:
	Message 31
	PlaySound SEQ_ME_MUSHITORI3
	WaitSound
	Message 32
	TextBugContestPlacement 1
	CompareVarValue 0x4000 1
	JumpIf DIFFERENT Function#35
	Message 33
Jump Function#36

Function 7:
	PlaySound SEQ_ME_MUSHITORI3
	WaitSound
	Message 32
	TextBugContestPlacement 1
	CompareVarValue 0x4000 1
	JumpIf DIFFERENT Function#35
	Message 33
Jump Function#36

Function 8:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 50
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 9:
End

Function 10:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 53
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 11:
End

Function 12:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 56
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 13:
End

Function 14:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 59
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 15:
End

Function 16:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 62
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 17:
End

Function 18:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 65
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 19:
End

Function 20:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 68
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 21:
End

Function 22:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 71
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 23:
End

Function 24:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 74
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 25:
End

Function 26:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 77
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 27:
End

Function 28:
	Message 22
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 29:
	ReleaseAll
End

Function 30:
	Message 18
Jump Function#37

Function 31:
	CompareVarValue 0x4000 4
	JumpIf DIFFERENT Function#38
	Message 5
Jump Function#32

Function 32:
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#39
	Message 17
Jump Function#37

Function 33:
	Message 21
	WaitButton
	CloseMessage
Return

Function 34:
	CloseMessage
Return

Function 35:
	Message 34
	PlaySound SEQ_ME_MUSHITORI2
	WaitSound
	Message 32
	TextBugContestPlacement 0
	CompareVarValue 0x4000 0
	JumpIf DIFFERENT Function#40
	SetFlag 321
	Message 35
Jump Function#41

Function 36:
	PlaySound SEQ_ME_MUSHITORI2
	WaitSound
	Message 32
	TextBugContestPlacement 0
	CompareVarValue 0x4000 0
	JumpIf DIFFERENT Function#40
	SetFlag 321
	Message 35
Jump Function#41

Function 37:
	WaitButton
	CloseMessage
	LocalScript
End

Function 38:
	CompareVarValue 0x4000 6
	JumpIf DIFFERENT Function#42
	Message 6
Jump Function#32

Function 39:
	CountPCFreeSpace 0x800C
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#43
	GetPartyCount 0x8004
	CompareVarValue 0x8004 6
	JumpIf EQUAL Function#44
	CountAlivePokemonExceptFirst 0x8005 6
	CompareVarValue 0x8005 1
	JumpIf DIFFERENT Function#45
	GetPartyCount 0x8004
	CompareVarValue 0x8004 1
	JumpIf EQUAL Function#46
	GetFirstAlivePokemonSlot 0x800C
	TextPokeNickname 0 0x800C
	Message 10
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#47
	Message 28
Jump Function#37

Function 40:
	ClearFlag 321
	Message 36
	PlaySound SEQ_ME_MUSHITORI1
	WaitSound
	Message 32
	TextPlayerName 0
	TextItem 3 0x4001
	SetVar 0x8004 37
	IncrementVar 0x8004 0x4000
	MessageFlex 0x8004
	SetVarFromVariable 0x8004 0x4001
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#48
	CommonScript 2033
Jump Function#49

Function 41:
	PlaySound SEQ_ME_MUSHITORI1
	WaitSound
	Message 32
	TextPlayerName 0
	TextItem 3 0x4001
	SetVar 0x8004 37
	IncrementVar 0x8004 0x4000
	MessageFlex 0x8004
	SetVarFromVariable 0x8004 0x4001
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#48
	CommonScript 2033
Jump Function#49

Function 42:
	Message 7
Jump Function#37

Function 43:
	CountAlivePokemonExceptFirst 0x8005 6
	CompareVarValue 0x8005 1
	JumpIf DIFFERENT Function#45
	GetPartyCount 0x8004
	CompareVarValue 0x8004 1
	JumpIf EQUAL Function#46
	GetFirstAlivePokemonSlot 0x800C
	TextPokeNickname 0 0x800C
	Message 10
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#47
	Message 28
Jump Function#37

Function 44:
	Message 16
Jump Function#37

Function 45:
	GetFirstAlivePokemonSlot 0x800C
	TextPokeNickname 0 0x800C
	Message 10
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#47
	Message 28
Jump Function#37

Function 46:
	FadeOutMusic 0 10
	PlayMusic SEQ_GS_TAIKAIMAE
	TextPlayerName 0
	Message 14
	Message 15
	SetFlag 2451
	SetFlag 590
	SetVar 0x4118 1
	SetVar 0x40F7 1
	OverlayManager 1 0
	BugContestControl 0 0x4000
	Call Function#50
	OverlayManager 1 1
	SetFlag 2454
Jump Function#51

Function 47:
	FadeOutMusic 0 10
	PlayMusic SEQ_GS_TAIKAIMAE
	TextPlayerName 0
	Message 13
	SetFlag 351
Jump Function#52

Function 48:
	TextPlayerName 0
	Message 45
	SetVarFromVariable 0x4058 0x4001
	CheckFlag 351
	CallIf EQUAL Function#53
	Message 42
	CompareVarValue 0x4002 0
	JumpIf DIFFERENT Function#54
	CloseMessage
Jump Function#55

Function 49:
	CheckFlag 351
	CallIf EQUAL Function#53
	Message 42
	CompareVarValue 0x4002 0
	JumpIf DIFFERENT Function#54
	CloseMessage
Jump Function#55

Function 50:
	SetVar 0x8004 0
	SetVar 0x8005 627
	CheckBugContestParticipant 0x8004 0x800C
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#56
	SetFlagFromVar 0x8005
	IncrementVar 0x8004 1
	IncrementVar 0x8005 1
	CompareVarValue 0x8004 10
	JumpIf LESS Function#57
Return

Function 51:
	CloseMessage
	LocalScript
End

Function 52:
	TextPlayerName 0
	Message 14
	Message 15
	SetFlag 2451
	SetFlag 590
	SetVar 0x4118 1
	SetVar 0x40F7 1
	OverlayManager 1 0
	BugContestControl 0 0x4000
	Call Function#50
	OverlayManager 1 1
	SetFlag 2454
Jump Function#51

Function 53:
	Message 47
	CloseMessage
Return

Function 54:
	TextPokemon 1 0x4002 2 1
	Message 43
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CloseMessage
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#58
	FadeScreen 6 1 0 0
	WaitFadeScreen
	ChoosePokemonNickname 255 0x800C
	FadeScreen 6 1 1 0
	WaitFadeScreen
	TextBugContestPokeNickname 5 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#55
	Message 46
	CloseMessage
	Movement Camera Action#2
	WaitMovement
	FadeOutMusic 0 10
	PlayMusic SEQ_GS_D_KOUEN
	ReleaseCamera
	Call Function#59
	SetFlag 2727
	ClearFlag 2451
	ClearFlag 590
	ClearFlag 351
	BugContestControl 1 0
	OverlayManager 1 1
	FadeOutMusic 0 30
	PlayDefaultMusic
	ReleaseAll
End

Function 55:
	Movement Camera Action#2
	WaitMovement
	FadeOutMusic 0 10
	PlayMusic SEQ_GS_D_KOUEN
	ReleaseCamera
	Call Function#59
	SetFlag 2727
	ClearFlag 2451
	ClearFlag 590
	ClearFlag 351
	BugContestControl 1 0
	OverlayManager 1 1
	FadeOutMusic 0 30
	PlayDefaultMusic
	ReleaseAll
End

Function 56:
	IncrementVar 0x8004 1
	IncrementVar 0x8005 1
	CompareVarValue 0x8004 10
	JumpIf LESS Function#57
Return

Function 57:
	CheckBugContestParticipant 0x8004 0x800C
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#56
	SetFlagFromVar 0x8005
	IncrementVar 0x8004 1
	IncrementVar 0x8005 1
	CompareVarValue 0x8004 10
	JumpIf LESS Function#57
Return

Function 58:
	TextBugContestPokeNickname 5 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#55
	Message 46
	CloseMessage
	Movement Camera Action#2
	WaitMovement
	FadeOutMusic 0 10
	PlayMusic SEQ_GS_D_KOUEN
	ReleaseCamera
	Call Function#59
	SetFlag 2727
	ClearFlag 2451
	ClearFlag 590
	ClearFlag 351
	BugContestControl 1 0
	OverlayManager 1 1
	FadeOutMusic 0 30
	PlayDefaultMusic
	ReleaseAll
End

Function 59:
	SetVar 0x8004 0
	SetVar 0x8005 10
	SetVar 0x8006 627
	SetOWMovement 0x8005 Move.2
	ClearFlagFromVar 0x8006
	IncrementVar 0x8004 1
	IncrementVar 0x8005 1
	IncrementVar 0x8006 1
	CompareVarValue 0x8004 10
	JumpIf LESS Function#60
Return

Function 60:
	SetOWMovement 0x8005 Move.2
	ClearFlagFromVar 0x8006
	IncrementVar 0x8004 1
	IncrementVar 0x8005 1
	IncrementVar 0x8006 1
	CompareVarValue 0x8004 10
	JumpIf LESS Function#60
Return

//===== ACTIONS =====//
Action 1:
	WalkEast8 0x5
End

Action 2:
	WalkWest8 0x5
End

