/*
 * DSPRE Script File
 * Rom ID: spawn - Copy
 * Game: HGSS
 * File: 0175
 * Generated: 2/25/2026 10:00:57 PM
 */

//===== SCRIPTS =====//
Script 1:
	SetTextBoard 2 0
	ShowBoard 3
	WaitBoard
	BoardMessage 0 0x800C
	CommonScript 2000
End

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	CheckPokemonInParty SPECIES_DEOXYS 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#1
	GetFirstAlivePokemonSlot 0x4000
	GetPartyPokemonID 0x4000 0x4001
	CompareVarValue 0x4001 386
	JumpIf EQUAL Function#2
	SetDeoxysForm 3
Jump Function#3

Script 3:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	CheckPokemonInParty SPECIES_DEOXYS 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#1
	GetFirstAlivePokemonSlot 0x4000
	GetPartyPokemonID 0x4000 0x4001
	CompareVarValue 0x4001 386
	JumpIf EQUAL Function#4
	SetDeoxysForm 2
Jump Function#5

Script 4:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	CheckPokemonInParty SPECIES_DEOXYS 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#1
	GetFirstAlivePokemonSlot 0x4000
	GetPartyPokemonID 0x4000 0x4001
	CompareVarValue 0x4001 386
	JumpIf EQUAL Function#6
	SetDeoxysForm 1
Jump Function#7

Script 5:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	CheckPokemonInParty SPECIES_DEOXYS 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#1
	GetFirstAlivePokemonSlot 0x4000
	GetPartyPokemonID 0x4000 0x4001
	CompareVarValue 0x4001 386
	JumpIf EQUAL Function#8
	SetDeoxysForm 0
Jump Function#9

//===== FUNCTIONS =====//
Function 1:
	Message 1
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 2:
	SetDeoxysForm 3
	FadeScreen 6 1 0 0
	WaitFadeScreen
	GetPlayerPosition 0x8006 0x8007
	GetPlayerDirection 0x800C
	Warp 11 0 0x8006 0x8007 0x800C
	CheckBike 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#10
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#11
	SetFollowingPokePosition 0 Down
Jump Function#12

Function 3:
	PlayCry SPECIES_DEOXYS 0
	Message 2
Jump Function#13

Function 4:
	SetDeoxysForm 2
	FadeScreen 6 1 0 0
	WaitFadeScreen
	GetPlayerPosition 0x8006 0x8007
	GetPlayerDirection 0x800C
	Warp 11 0 0x8006 0x8007 0x800C
	CheckBike 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#14
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#15
	SetFollowingPokePosition 0 Down
Jump Function#16

Function 5:
	PlayCry SPECIES_DEOXYS 0
	Message 3
Jump Function#13

Function 6:
	SetDeoxysForm 1
	FadeScreen 6 1 0 0
	WaitFadeScreen
	GetPlayerPosition 0x8006 0x8007
	GetPlayerDirection 0x800C
	Warp 11 0 0x8006 0x8007 0x800C
	CheckBike 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#17
	SetFollowingPokePosition 2 Right
	LockFollowingPoke 0
	SendOutFollowingPoke
	WaitTime 10 0x800C
	LockFollowingPoke 1
	FadeScreen 6 1 1 0
	WaitFadeScreen
	PlayCry SPECIES_DEOXYS 0
	Message 4
Jump Function#13

Function 7:
	PlayCry SPECIES_DEOXYS 0
	Message 4
Jump Function#13

Function 8:
	SetDeoxysForm 0
	FadeScreen 6 1 0 0
	WaitFadeScreen
	GetPlayerPosition 0x8006 0x8007
	GetPlayerDirection 0x800C
	Warp 11 0 0x8006 0x8007 0x800C
	CheckBike 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#18
	SetFollowingPokePosition 3 Left
	LockFollowingPoke 0
	SendOutFollowingPoke
	WaitTime 10 0x800C
	LockFollowingPoke 1
	FadeScreen 6 1 1 0
	WaitFadeScreen
	PlayCry SPECIES_DEOXYS 0
	Message 5
	WaitButton
	WaitCry
	CloseMessage
	ReleaseAll
End

Function 9:
	PlayCry SPECIES_DEOXYS 0
	Message 5
	WaitButton
	WaitCry
	CloseMessage
	ReleaseAll
End

Function 10:
	FadeScreen 6 1 1 0
	WaitFadeScreen
	PlayCry SPECIES_DEOXYS 0
	Message 2
Jump Function#13

Function 11:
	SetFollowingPokePosition 3 Left
	LockFollowingPoke 0
	SendOutFollowingPoke
	WaitTime 10 0x800C
	LockFollowingPoke 1
	FadeScreen 6 1 1 0
	WaitFadeScreen
	PlayCry SPECIES_DEOXYS 0
	Message 2
Jump Function#13

Function 12:
	LockFollowingPoke 0
	SendOutFollowingPoke
	WaitTime 10 0x800C
	LockFollowingPoke 1
	FadeScreen 6 1 1 0
	WaitFadeScreen
	PlayCry SPECIES_DEOXYS 0
	Message 2
Jump Function#13

Function 13:
	WaitButton
	WaitCry
	CloseMessage
	ReleaseAll
End

Function 14:
	FadeScreen 6 1 1 0
	WaitFadeScreen
	PlayCry SPECIES_DEOXYS 0
	Message 3
Jump Function#13

Function 15:
	CompareVarValue 0x800C 3
	JumpIf DIFFERENT Function#19
	SetFollowingPokePosition 0 Down
Jump Function#16

Function 16:
	LockFollowingPoke 0
	SendOutFollowingPoke
	WaitTime 10 0x800C
	LockFollowingPoke 1
	FadeScreen 6 1 1 0
	WaitFadeScreen
	PlayCry SPECIES_DEOXYS 0
	Message 3
Jump Function#13

Function 17:
	FadeScreen 6 1 1 0
	WaitFadeScreen
	PlayCry SPECIES_DEOXYS 0
	Message 4
Jump Function#13

Function 18:
	FadeScreen 6 1 1 0
	WaitFadeScreen
	PlayCry SPECIES_DEOXYS 0
	Message 5
	WaitButton
	WaitCry
	CloseMessage
	ReleaseAll
End

Function 19:
	SetFollowingPokePosition 3 Left
	LockFollowingPoke 0
	SendOutFollowingPoke
	WaitTime 10 0x800C
	LockFollowingPoke 1
	FadeScreen 6 1 1 0
	WaitFadeScreen
	PlayCry SPECIES_DEOXYS 0
	Message 3
Jump Function#13

//===== ACTIONS =====//
