/*
 * DSPRE Script File
 * Rom ID: spawn - Copy
 * Game: HGSS
 * File: 0179
 * Generated: 2/25/2026 10:00:57 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 0
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 2:
	SetTextBoard 2 0
	ShowBoard 3
	WaitBoard
	BoardMessage 1 0x800C
	CommonScript 2000
End

//===== FUNCTIONS =====//
//===== ACTIONS =====//
