/*
 * DSPRE Script File
 * Rom ID: spawn - Copy
 * Game: HGSS
 * File: 0211
 * Generated: 2/25/2026 10:00:57 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 0
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 2:
	CheckFlag 329
	JumpIf EQUAL Function#1
End

Script 3:
	MecScript
	LockAll
	CheckBike 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#2
	Movement Player Action#1
	WaitMovement
	Message 1
	CloseMessage
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	Movement Player Action#2
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	ReleaseAll
End

Script 4:
	CyclingRoad 0
	SetVar 0x4129 0
	SetVar 0x412A 0
	ClearFlag 329
End

//===== FUNCTIONS =====//
Function 1:
	CyclingRoad 1
End

Function 2:
	CyclingRoad 1
	SetVar 0x4129 1
	SetVar 0x412A 1
	SetFlag 329
	ReleaseAll
End

//===== ACTIONS =====//
Action 1:
	WalkOnSpotNorth8 0x1
End

Action 2:
	WalkEast8 0x1
End

