/*
 * DSPRE Script File
 * Rom ID: spawn - Copy
 * Game: HGSS
 * File: 0220
 * Generated: 2/25/2026 10:00:57 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 0
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CloseMessage
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#1
	Message 1
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CloseMessage
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#1
	Message 2
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== FUNCTIONS =====//
Function 1:
	ReleaseAll
End

//===== ACTIONS =====//
