/*
 * DSPRE Script File
 * Rom ID: spawn - Copy
 * Game: HGSS
 * File: 0241
 * Generated: 2/25/2026 10:00:57 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CompareVarValue 0x4114 1
	JumpIf EQUAL Function#1
	CompareVarValue 0x4114 2
	JumpIf GREATER/EQUAL Function#2
	Message 0
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#3
	GetPartyCount 0x800C
	CompareVarValue 0x800C 6
	JumpIf EQUAL Function#4
	Message 3
	GiveLoanPokemon SPECIES_SQUIRTLE 20 101
	SetVar 0x4114 1
	TextPlayerName 0
	Message 4
	PlaySound SEQ_ME_PT_SPECIAL
	WaitSound
	KenyaCheckPartyOrMailbox 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#5
	CheckFlag 181
	JumpIf EQUAL Function#6
	Message 6
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckFlag 138
	JumpIf EQUAL Function#7
	Message 13
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== FUNCTIONS =====//
Function 1:
	KenyaCheckPartyOrMailbox 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#5
	CheckFlag 181
	JumpIf EQUAL Function#6
	Message 6
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 2:
	CompareVarValue 0x4114 4
	JumpIf GREATER/EQUAL Function#8
	Message 7
	SetVar 0x8004 45
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#9
	CommonScript 2033
	CompareVarValue 0x4114 3
	JumpIf DIFFERENT Function#10
	SetVar 0x4114 5
Jump Function#11

Function 3:
	Message 1
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 4:
	Message 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 5:
	SetVar 0x4114 6
	Message 9
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 6:
	Message 5
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 7:
	Message 14
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#12
	Message 15
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 8:
	Message 10
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 9:
	CommonScript 2009
	CloseMessage
	ReleaseAll
End

Function 10:
	SetVar 0x4114 4
	Message 8
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 11:
	Message 8
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 12:
	Message 16
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== ACTIONS =====//
