/*
 * DSPRE Script File
 * Rom ID: spawn - Copy
 * Game: HGSS
 * File: 0260
 * Generated: 2/25/2026 10:00:57 PM
 */

//===== SCRIPTS =====//
Script 1:
	SetVar 0x40EB 1
	SetFlag 2505
	CheckVersion 0x4000
	CompareVarValue 0x4000 7
	JumpIf DIFFERENT Function#1
	SetWarpPosition 4 87 385
	SetWarpPosition 5 87 389
	SetWarpPosition 6 87 385
Jump Function#2

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckFlag 337
	JumpIf EQUAL Function#3
	Message 0
	WaitButton
	CloseMessage
	SetFlag 337
	ReleaseAll
End

Script 3:
	CompareVarValue 0x40F9 5
	JumpIf GREATER/EQUAL Function#4
	CheckVersion 0x4000
	CompareVarValue 0x4000 7
	JumpIf DIFFERENT Function#5
	SetWarpPosition 4 87 385
	SetWarpPosition 5 87 389
	SetWarpPosition 6 87 385
Jump Function#6

Script 4:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckFlag 343
	JumpIf EQUAL Function#7
	Message 2
	Movement Overworld.5 Action#1
	WaitMovement
	Message 3
	GetPlayerDirection 0x800C
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#8
	Movement Overworld.5 Action#2
Jump Function#9

Script 5:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 5
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#10
	CheckAlbumPhoto 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#11
	Message 6
	CloseMessage
	SetFlag 393
	FadeScreen 6 1 0 0
	WaitFadeScreen
	TakePhoto 91
	FacePlayer
	LockAll
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ClearFlag 393
	Message 7
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== FUNCTIONS =====//
Function 1:
	SetWarpPosition 4 87 389
	SetWarpPosition 5 87 385
	SetWarpPosition 6 87 385
	CompareVarValue 0x40F9 2
	JumpIf EQUAL Function#12
	CompareVarValue 0x40F9 3
	JumpIf EQUAL Function#12
	CompareVarValue 0x40F9 5
	JumpIf GREATER/EQUAL Function#13
	CheckFlag 393
	JumpIf LESS Function#14
	ClearFlag 393
End

Function 2:
	CompareVarValue 0x40F9 2
	JumpIf EQUAL Function#12
	CompareVarValue 0x40F9 3
	JumpIf EQUAL Function#12
	CompareVarValue 0x40F9 5
	JumpIf GREATER/EQUAL Function#13
	CheckFlag 393
	JumpIf LESS Function#14
	ClearFlag 393
End

Function 3:
	Message 1
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 4:
	SetWarpPosition 4 87 385
	SetWarpPosition 5 87 385
	SetWarpPosition 6 87 389
End

Function 5:
	SetWarpPosition 4 87 389
	SetWarpPosition 5 87 385
	SetWarpPosition 6 87 385
End

Function 6:
End

Function 7:
	TextPlayerName 0
	Message 4
	CloseMessage
	Movement Overworld.5 Action#1
	WaitMovement
	SetFlag 343
	ReleaseAll
End

Function 8:
	CompareVarValue 0x800C 3
	JumpIf DIFFERENT Function#15
	Movement Overworld.5 Action#3
Jump Function#9

Function 9:
	WaitMovement
	TextPlayerName 0
	Message 4
	CloseMessage
	Movement Overworld.5 Action#1
	WaitMovement
	SetFlag 343
	ReleaseAll
End

Function 10:
	Message 8
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 11:
	Message 9
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 12:
	SetFlag 772
End

Function 13:
	SetWarpPosition 4 87 385
	SetWarpPosition 5 87 385
	SetWarpPosition 6 87 389
Jump Function#12

Function 14:
	CheckFlag 2404
	JumpIf EQUAL Function#16
Jump Function#12

Function 15:
	Movement Overworld.5 Action#4
	WaitMovement
	TextPlayerName 0
	Message 4
	CloseMessage
	Movement Overworld.5 Action#1
	WaitMovement
	SetFlag 343
	ReleaseAll
End

Function 16:
	CheckPokeGearRematch 32 0x4001
	CompareVarValue 0x4001 0
	JumpIf DIFFERENT Function#12
	GetDayOfWeek 0x4002
	CompareVarValue 0x4002 0
	JumpIf DIFFERENT Function#17
	ClearFlag 772
Jump Function#18

Function 17:
	SetFlag 772
End

Function 18:
End

//===== ACTIONS =====//
Action 1:
	WalkOnSpotNorth8 0x1
End

Action 2:
	WalkOnSpotSouth8 0x1
End

Action 3:
	WalkOnSpotWest8 0x1
End

Action 4:
	WalkOnSpotEast8 0x1
End

