/*
 * DSPRE Script File
 * Rom ID: spawn - Copy
 * Game: HGSS
 * File: 0748
 * Generated: 2/25/2026 10:00:59 PM
 */

//===== SCRIPTS =====//
Script 1:
	MecScript
	LockAll
	Movement Player Action#1
	WaitMovement
	Message 0
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#1
	SetFollowingPokeStatus 1
	SetVar 0x412E 5
	CommonScript 2006
	SetVarFromVariable 0x800C 0x4000
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#1
	CloseTouchScreen
	SendBackFollowingPoke
	HealPokemon
	Message 2
	CloseMessage
	Movement Player Action#2
	WaitMovement
	NoBallResetFollowingPoke
	SetOWMovement Following Move.56
	SetVar 0x412E 4
	ReleaseAll
End

Script 2:
	MecScript
	LockAll
	Message 4
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#2
	Message 5
	CloseMessage
	Movement Player Action#3
	WaitMovement
	SetFollowingPokeStatus 0
	BallResetFollowingPoke
	SetOWMovement Following Move.48
	SetVar 0x412E 3
	ReleaseAll
End

Script 3:
	MecScript
	LockAll
	SetVar 0x412E 2
	Message 7
	CloseMessage
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	Movement Player Action#4
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	Message 8
	CheckFlag 374
	JumpIf EQUAL Function#3
	Message 9
	SetFlag 603
	DummyGetPokemonFootprint
	SetVar 0x40E5 2
	Message 11
	SetFlag 374
	Message 12
Jump Function#4

Script 4:
	UseScript_#1

//===== FUNCTIONS =====//
Function 1:
	SetFollowingPokeStatus 0
	Message 3
	CloseMessage
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	Movement Player Action#3
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	SetVar 0x412E 3
	ReleaseAll
End

Function 2:
	Message 6
	CloseMessage
	Movement Player Action#2
	WaitMovement
	ReleaseAll
End

Function 3:
	Message 12
Jump Function#4

Function 4:
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#1
	SetFollowingPokeStatus 1
	SetVar 0x412E 5
	CommonScript 2006
	SetVarFromVariable 0x800C 0x4000
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#1
	CloseTouchScreen
	SendBackFollowingPoke
	HealPokemon
	Message 2
	CloseMessage
	Movement Player Action#2
	WaitMovement
	NoBallResetFollowingPoke
	SetOWMovement Following Move.56
	SetVar 0x412E 4
	ReleaseAll
End

//===== ACTIONS =====//
Action 1:
	WalkOnSpotWest8 0x1
End

Action 2:
	WalkSouth8 0x3
End

Action 3:
	WalkEast8 0x1
End

Action 4:
	WalkWest8 0x2
	WalkSouth8 0x1
	WalkWest8 0x2
End

