/*
 * DSPRE Script File
 * Rom ID: spawn - Copy
 * Game: HGSS
 * File: 0776
 * Generated: 2/25/2026 10:00:59 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CMD_491 247
	CheckFlag 247
	JumpIf EQUAL Function#1
	CompareVarValue 0x4135 8
	JumpIf GREATER/EQUAL Function#2
	CompareVarValue 0x4135 5
	JumpIf GREATER/EQUAL Function#3
	CompareVarValue 0x4135 1
	JumpIf GREATER/EQUAL Function#4
	Message 4
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 0
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 3:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 3
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 4:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 1
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 5:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	PlayCry SPECIES_MACHOP 0
	Message 2
	WaitCry
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 6:
	SetIconBoard 10 0 6 0x800C
	ShowBoard 3
	WaitBoard
	CloseBoard 0x800C
	CommonScript 2000
End

Script 7:
	SetTextBoard 2 0
	ShowBoard 3
	WaitBoard
	BoardMessage 11 0x800C
	CommonScript 2000
End

Script 8:
	SetTextBoard 2 0
	ShowBoard 3
	WaitBoard
	BoardMessage 12 0x800C
	CommonScript 2000
End

Script 9:
	SetTextBoard 2 0
	ShowBoard 3
	WaitBoard
	BoardMessage 13 0x800C
	CommonScript 2000
End

Script 10:
	CheckFlag 393
	JumpIf LESS Function#5
	ClearFlag 393
End

Script 11:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 0
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#6
	CheckAlbumPhoto 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#7
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 1
	CloseMessage
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	GetPlayerDirection 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#8
	Movement Player Action#1
Jump Function#9

Script 12:
	MecScript
	LockAll
	ClearFlag 676
	AddOW Overworld.16
	GetPlayerPosition 0x4000 0x4001
	CompareVarValue 0x4000 1334
	JumpIf DIFFERENT Function#10
Jump Function#11

Script 13:
	MecScript
	LockAll
	ClearFlag 692
	AddOW Overworld.17
	Movement Player Action#2
	WaitMovement
	PlayCry SPECIES_SUICUNE 0
	Release Overworld.15
	ShakeOverworld Overworld.15 2 90 2 0
	Lock Overworld.15
	WaitCry
	CommonScript 2042
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	GetPlayerPosition 0x4000 0x4001
	CompareVarValue 0x4000 1324
	JumpIf DIFFERENT Function#12
	Movement Overworld.17 Action#3
	Movement Player Action#4
	Movement Overworld.15 Action#5
Jump Function#13

Script 14:
	MecScript
	LockAll
	Movement Overworld.18 Action#6
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	Movement Player Action#7
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	Message 16
	CloseMessage
	Movement Overworld.18 Action#8
	WaitMovement
	CheckVersion 0x4004
	CompareVarValue 0x4004 8
	JumpIf EQUAL Function#14
	ShowPokemonPic SPECIES_LATIAS 1
	Message 17
	CloseMessage
	AddRoamingPokemon 2
	HidePokemonPic
	Movement Overworld.18 Action#8
	WaitMovement
	Message 19
	CloseMessage
	Movement Overworld.18 Action#8
	WaitMovement
	Message 21
	CloseMessage
Jump Function#15

//===== FUNCTIONS =====//
Function 1:
	Message 9
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 2:
	Message 7
	SetVar 0x8004 53
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#16
	CommonScript 2033
	SetFlag 247
	Message 8
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 3:
	Message 6
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 4:
	Message 5
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 5:
	GetDayOfWeek 0x4000
	CompareVarValue 0x4000 4
	JumpIf DIFFERENT Function#17
	ClearFlag 638
Jump Function#18

Function 6:
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 5
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 7:
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 3
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 8:
	CompareVarValue 0x800C 3
	JumpIf DIFFERENT Function#19
	Movement Player Action#9
	Movement Overworld.14 Action#10
Jump Function#9

Function 9:
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	CheckPokemonAlive 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#20
	Movement Following Action#11
	WaitMovement
	SetFlag 393
	FadeScreen 6 1 0 0
	WaitFadeScreen
	TakePhoto 50
	LockAll
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ClearFlag 393
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 10:
	Movement Player Action#2
	WaitMovement
	PlayCry SPECIES_SUICUNE 0
	Release Overworld.15
	ShakeOverworld Overworld.15 2 90 2 0
	Lock Overworld.15
	WaitCry
	CommonScript 2042
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	GetPlayerPosition 0x4000 0x4001
	CompareVarValue 0x4001 331
	JumpIf DIFFERENT Function#21
	Movement Player Action#12
	Movement Overworld.16 Action#13
	Movement Overworld.15 Action#5
Jump Function#22

Function 11:
	Movement Player Action#2
	Movement Overworld.15 Action#14
	WaitMovement
	PlayCry SPECIES_SUICUNE 0
	Release Overworld.15
	ShakeOverworld Overworld.15 2 90 2 0
	Lock Overworld.15
	WaitCry
	CommonScript 2042
	Movement Overworld.15 Action#15
	Movement Overworld.16 Action#16
	Movement Player Action#17
	WaitMovement
	Movement Overworld.16 Action#18
	Movement Player Action#19
	WaitMovement
	Message 14
	CloseMessage
	Movement Overworld.16 Action#20
	WaitMovement
	Message 15
	CloseMessage
	Movement Overworld.16 Action#21
	Movement Player Action#22
	WaitMovement
Jump Function#23

Function 12:
	CompareVarValue 0x4000 1325
	JumpIf DIFFERENT Function#24
	Movement Overworld.17 Action#23
	Movement Player Action#24
	Movement Overworld.15 Action#25
Jump Function#13

Function 13:
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	Message 14
	CloseMessage
	Movement Overworld.17 Action#26
	Movement Player Action#27
	WaitMovement
	TextPlayerName 0
	Message 15
	CloseMessage
	Movement Overworld.17 Action#28
	Movement Player Action#29
	WaitMovement
	CommonScript 2043
	RemoveOW Overworld.17
	RemoveOW Overworld.15
	SetFlag 676
	SetFlag 692
	SetFlag 671
	SetVar 0x4070 0
	SetVar 0x4071 0
	ClearFlag 672
	SetVar 0x4086 1
	ReleaseAll
End

Function 14:
	ShowPokemonPic SPECIES_LATIOS 0
	Message 18
	CloseMessage
	AddRoamingPokemon 3
	HidePokemonPic
	Movement Overworld.18 Action#8
	WaitMovement
	Message 20
	CloseMessage
	Movement Overworld.18 Action#8
	WaitMovement
	Message 22
	CloseMessage
Jump Function#15

Function 15:
	Movement Overworld.18 Action#8
	WaitMovement
	Message 23
	CloseMessage
	Movement Overworld.18 Action#30
	WaitMovement
	SetVar 0x4130 2
	RemoveOW Overworld.18
	SetFlag 765
	ReleaseAll
End

Function 16:
	CommonScript 2009
	CloseMessage
	ReleaseAll
End

Function 17:
	CompareVarValue 0x4000 0
	JumpIf DIFFERENT Function#25
	ClearFlag 638
Jump Function#18

Function 18:
	SetVar 0x4085 0
End

Function 19:
	Movement Player Action#31
	Movement Overworld.14 Action#10
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	CheckPokemonAlive 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#20
	Movement Following Action#11
	WaitMovement
	SetFlag 393
	FadeScreen 6 1 0 0
	WaitFadeScreen
	TakePhoto 50
	LockAll
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ClearFlag 393
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 20:
	SetFlag 393
	FadeScreen 6 1 0 0
	WaitFadeScreen
	TakePhoto 50
	LockAll
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ClearFlag 393
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 21:
	CompareVarValue 0x4001 332
	JumpIf DIFFERENT Function#26
	Movement Player Action#32
	Movement Overworld.16 Action#33
	Movement Overworld.15 Action#25
Jump Function#22

Function 22:
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	Message 14
	CloseMessage
	Movement Overworld.16 Action#34
	WaitMovement
	TextPlayerName 0
	Message 15
	CloseMessage
	Movement Overworld.16 Action#21
	Movement Player Action#22
	WaitMovement
	CommonScript 2043
	RemoveOW Overworld.16
	RemoveOW Overworld.15
	SetFlag 676
	SetFlag 692
	SetFlag 671
	SetVar 0x4070 0
	SetVar 0x4071 0
	ClearFlag 672
	SetVar 0x4086 1
	ReleaseAll
End

Function 23:
	CommonScript 2043
	RemoveOW Overworld.16
	RemoveOW Overworld.15
	SetFlag 676
	SetFlag 692
	SetFlag 671
	SetVar 0x4070 0
	SetVar 0x4071 0
	ClearFlag 672
	SetVar 0x4086 1
	ReleaseAll
End

Function 24:
	Movement Overworld.17 Action#35
	Movement Player Action#36
	Movement Overworld.15 Action#37
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	Message 14
	CloseMessage
	Movement Overworld.17 Action#26
	Movement Player Action#27
	WaitMovement
	TextPlayerName 0
	Message 15
	CloseMessage
	Movement Overworld.17 Action#28
	Movement Player Action#29
	WaitMovement
	CommonScript 2043
	RemoveOW Overworld.17
	RemoveOW Overworld.15
	SetFlag 676
	SetFlag 692
	SetFlag 671
	SetVar 0x4070 0
	SetVar 0x4071 0
	ClearFlag 672
	SetVar 0x4086 1
	ReleaseAll
End

Function 25:
	SetFlag 638
	SetVar 0x4085 0
End

Function 26:
	Movement Player Action#38
	Movement Overworld.16 Action#39
	Movement Overworld.15 Action#37
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	Message 14
	CloseMessage
	Movement Overworld.16 Action#34
	WaitMovement
	TextPlayerName 0
	Message 15
	CloseMessage
	Movement Overworld.16 Action#21
	Movement Player Action#22
	WaitMovement
	CommonScript 2043
	RemoveOW Overworld.16
	RemoveOW Overworld.15
	SetFlag 676
	SetFlag 692
	SetFlag 671
	SetVar 0x4070 0
	SetVar 0x4071 0
	ClearFlag 672
	SetVar 0x4086 1
	ReleaseAll
End

//===== ACTIONS =====//
Action 1:
	WalkNorth8 0x3
	WalkOnSpotSouth8 0x1
End

Action 2:
	EmoteExclamation 0x1
End

Action 3:
	Delay8 0x1
	WalkEast4 0x7
	WalkNorth4 0x3
	WalkEast4 0x1
End

Action 4:
	WalkSouth8 0x4
	WalkEast8 0x2
End

Action 5:
	Delay4 0x9
	0070 0x1
End

Action 6:
	EmoteExclamation 0x1
	Delay8 0x1
	WalkWest8 0x4
	WalkOnSpotWest8 0x1
End

Action 7:
	Delay16 0x4
	WalkSouth8 0x1
	WalkOnSpotEast8 0x1
End

Action 8:
	WalkOnSpotWest8 0x1
End

Action 9:
	WalkNorth8 0x1
	WalkEast8 0x1
	WalkNorth8 0x3
	WalkOnSpotSouth8 0x1
End

Action 10:
	Delay8 0x1
	WalkOnSpotNorth8 0x1
End

Action 11:
	WalkEast8 0x1
	WalkNorth8 0x1
	FaceSouth 0x1
End

Action 12:
	WalkEast8 0x2
	WalkNorth8 0x2
	WalkEast8 0x1
End

Action 13:
	Delay8 0x1
	WalkSouth4 0x6
	WalkEast4 0x1
End

Action 14:
	WalkOnSpotEast8 0x1
End

Action 15:
	Delay4 0x4
	WalkSouth2 0x2
	JumpSouth8 0x1
	JumpFarSouth 0x1
	WalkSouth2 0x2
	JumpSouth8 0x1
	JumpFarSouth 0x2
End

Action 16:
	Delay4 0x2
	WalkEast4 0x1
	WalkSouth4 0x2
End

Action 17:
	Delay4 0x4
	FaceSouth 0x1
End

Action 18:
	JumpOnSpotSouth8 0x3
End

Action 19:
	FaceWest 0x1
End

Action 20:
	FaceEast 0x1
End

Action 21:
	WalkNorth8 0x8
End

Action 22:
	FaceNorth 0x1
End

Action 23:
	Delay8 0x2
	WalkEast4 0x7
	WalkNorth4 0x3
	WalkEast4 0x1
End

Action 24:
	WalkSouth8 0x4
	WalkEast8 0x1
End

Action 25:
	Delay4 0xB
	0070 0x1
End

Action 26:
	FaceNorth 0x1
End

Action 27:
	FaceSouth 0x1
End

Action 28:
	WalkWest8 0x2
	WalkNorth8 0xD
End

Action 29:
	Delay8 0x2
	FaceWest 0x1
	Delay8 0x1
	FaceNorth 0x1
End

Action 30:
	WalkEast8 0xA
End

Action 31:
	WalkNorth8 0x1
	WalkWest8 0x1
	WalkNorth8 0x3
	WalkOnSpotSouth8 0x1
End

Action 32:
	WalkEast8 0x2
	WalkNorth8 0x3
	WalkEast8 0x1
End

Action 33:
	Delay4 0x3
	WalkSouth4 0x6
	WalkEast4 0x1
End

Action 34:
	FaceSouth 0x1
End

Action 35:
	Delay8 0x3
	WalkEast4 0x7
	WalkNorth4 0x3
	WalkEast4 0x1
End

Action 36:
	WalkSouth8 0x4
	FaceEast 0x1
End

Action 37:
	Delay4 0xD
	0070 0x1
End

Action 38:
	WalkEast8 0x2
	WalkNorth8 0x4
	WalkEast8 0x1
End

Action 39:
	Delay4 0x5
	WalkSouth4 0x6
	WalkEast4 0x1
End

