/*
 * DSPRE Script File
 * Rom ID: spawn - Copy
 * Game: HGSS
 * File: 0797
 * Generated: 2/25/2026 10:00:59 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Message 0
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 2:
	SetVar 0x4125 0
End

Script 3:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Message 1
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== FUNCTIONS =====//
//===== ACTIONS =====//
