/*
 * DSPRE Script File
 * Rom ID: spawn - Copy
 * Game: HGSS
 * File: 0798
 * Generated: 2/25/2026 10:00:59 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckCompleteJohtoDex 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#1
	CheckFlag 323
	JumpIf EQUAL Function#2
	Message 1
	PlaySound SEQ_ME_HYOUKA2
	WaitSound
	CloseMessage
	FadeScreen 6 1 0 0
	WaitFadeScreen
	OpenPokedexScreen 0
	ReturnScreen
	SetFlag 323
	AddTrainerScore 25
	FadeScreen 6 1 1 0
	WaitFadeScreen
	CheckCompleteNationalDex 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#1
	CheckFlag 324
	JumpIf EQUAL Function#3
	Message 2
	PlaySound SEQ_ME_HYOUKA2
	WaitSound
	CloseMessage
	FadeScreen 6 1 0 0
	WaitFadeScreen
	OpenPokedexScreen 1
	ReturnScreen
	SetFlag 324
	AddTrainerScore 26
	FadeScreen 6 1 1 0
	WaitFadeScreen
	Message 3
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 4
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 3:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 5
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 4:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 6
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 5:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Message 16
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 6:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Message 18
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 7:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Message 19
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 8:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Message 20
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 9:
	GetCounterpartSprite 0x4020
	SetVar 0x4125 0
End

Script 10:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckBadge 15 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#4
	Message 7
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 11:
	MecScript
	LockAll
	CommonScript 2029
	Movement Overworld.5 Action#1
	Movement Overworld.6 Action#2
	WaitMovement
	TextPlayerName 0
	GenderMessage 12 13
	CloseMessage
	Movement Overworld.5 Action#3
	Movement Overworld.6 Action#4
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	Movement Player Action#5
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	TextPlayerName 0
	GenderMessage 14 15
	CloseMessage
	Movement Overworld.5 Action#6
	Movement Overworld.6 Action#7
	WaitMovement
	DoorAnimation 0 0 3 2 77
	OpenDoor 77
	WaitDoor 77
	Movement Overworld.5 Action#8
	Movement Overworld.6 Action#9
	WaitMovement
	CloseDoor 77
	WaitDoor 77
	FreeDoor 77
	CommonScript 2030
	SetVar 0x412C 1
	SetOWPosition Overworld.5 29 0 29 Left
	SetOWPosition Overworld.6 29 0 29 Left
	ReleaseAll
End

Script 12:
	CompareVarValue 0x412C 0
	JumpIf DIFFERENT Function#5
	SetOWPosition Overworld.5 12 0 6 Left
	SetOWPosition Overworld.6 13 0 6 Left
End

Script 13:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 21
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 14:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Message 17
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== FUNCTIONS =====//
Function 1:
	Message 0
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 2:
	CheckCompleteNationalDex 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#1
	CheckFlag 324
	JumpIf EQUAL Function#3
	Message 2
	PlaySound SEQ_ME_HYOUKA2
	WaitSound
	CloseMessage
	FadeScreen 6 1 0 0
	WaitFadeScreen
	OpenPokedexScreen 1
	ReturnScreen
	SetFlag 324
	AddTrainerScore 26
	FadeScreen 6 1 1 0
	WaitFadeScreen
	Message 3
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 3:
	Message 3
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 4:
	GetItemQuantity ITEM_GB_SOUNDS 0x800C
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#6
	Message 8
	SetVar 0x8004 502
	SetVar 0x8005 1
	CommonScript 2033
	Message 10
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 5:
End

Function 6:
	Message 11
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== ACTIONS =====//
Action 1:
	WalkWest8 0x4
	EmoteExclamation 0x1
End

Action 2:
	WalkWest8 0x4
End

Action 3:
	WalkWest8 0x4
End

Action 4:
	WalkWest8 0x4
End

Action 5:
	WalkSouth8 0x3
	WalkOnSpotEast8 0x1
End

Action 6:
	WalkNorth8 0x2
	WalkWest8 0x1
	WalkNorth8 0x1
End

Action 7:
	WalkWest8 0x1
	WalkNorth8 0x2
	WalkWest8 0x1
	WalkOnSpotNorth8 0x1
End

Action 8:
	WalkNorth8 0x1
	SetInvisible 0x1
End

Action 9:
	WalkNorth8 0x2
	SetInvisible 0x1
End

