/*
 * DSPRE Script File
 * Rom ID: spawn - Copy
 * Game: HGSS
 * File: 0803
 * Generated: 2/25/2026 10:00:59 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 0
	CheckItem ITEM_COIN_CASE 1 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#1
	Message 1
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 7
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 3:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 8
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 4:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 9
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 5:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 10
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 6:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	OverlayManager 3 0
	CheckFlag 380
	JumpIf EQUAL Function#2
	Message 11
	CheckItem ITEM_COIN_CASE 1 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#3
	CanGiveCoins 0x800C 18
	Nop
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#4
	GiveCoins 18
	TextPlayerName 0
	Message 12
	PlaySound SEQ_ME_ITEM
	WaitSound
	SetFlag 380
	Message 13
	WaitButton
	CloseMessage
	ReleaseAll
	OverlayManager 3 1
End

Script 7:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 16
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 8:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 17
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 9:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Message 18
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 10:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Message 19
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 11:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Call Function#5
	CompareVarValue 0x4001 1
	JumpIf EQUAL Function#6
	FadeScreen 6 1 0 0
	WaitFadeScreen
	OpenVoltorbFlip 0 1
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Script 12:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Call Function#5
	CompareVarValue 0x4001 1
	JumpIf EQUAL Function#7
	FadeScreen 6 1 0 0
	WaitFadeScreen
	OpenVoltorbFlip 1 1
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Script 13:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Call Function#5
	CompareVarValue 0x4001 1
	JumpIf EQUAL Function#8
	FadeScreen 6 1 0 0
	WaitFadeScreen
	OpenVoltorbFlip 2 1
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Script 14:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Call Function#5
	CompareVarValue 0x4001 1
	JumpIf EQUAL Function#9
	FadeScreen 6 1 0 0
	WaitFadeScreen
	OpenVoltorbFlip 3 1
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Script 15:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Call Function#5
	CompareVarValue 0x4001 1
	JumpIf EQUAL Function#10
	FadeScreen 6 1 0 0
	WaitFadeScreen
	OpenVoltorbFlip 4 1
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Script 16:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Call Function#5
	CompareVarValue 0x4001 1
	JumpIf EQUAL Function#11
	FadeScreen 6 1 0 0
	WaitFadeScreen
	OpenVoltorbFlip 5 1
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Script 17:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Call Function#5
	CompareVarValue 0x4001 1
	JumpIf EQUAL Function#12
	FadeScreen 6 1 0 0
	WaitFadeScreen
	OpenVoltorbFlip 6 1
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Script 18:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Call Function#5
	CompareVarValue 0x4001 1
	JumpIf EQUAL Function#13
	FadeScreen 6 1 0 0
	WaitFadeScreen
	OpenVoltorbFlip 7 1
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Script 19:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Call Function#5
	CompareVarValue 0x4001 1
	JumpIf EQUAL Function#14
	FadeScreen 6 1 0 0
	WaitFadeScreen
	OpenVoltorbFlip 8 1
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Script 20:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Call Function#5
	CompareVarValue 0x4001 1
	JumpIf EQUAL Function#15
	FadeScreen 6 1 0 0
	WaitFadeScreen
	OpenVoltorbFlip 9 1
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Script 21:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Call Function#5
	CompareVarValue 0x4001 1
	JumpIf EQUAL Function#16
	FadeScreen 6 1 0 0
	WaitFadeScreen
	OpenVoltorbFlip 10 1
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Script 22:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Call Function#5
	CompareVarValue 0x4001 1
	JumpIf EQUAL Function#17
	FadeScreen 6 1 0 0
	WaitFadeScreen
	OpenVoltorbFlip 11 1
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Script 23:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Call Function#5
	CompareVarValue 0x4001 1
	JumpIf EQUAL Function#18
	Message 20
	CloseMessage
	FadeScreen 6 1 0 0
	WaitFadeScreen
	OpenVoltorbFlip 12 1
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Script 24:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Call Function#5
	CompareVarValue 0x4001 1
	JumpIf EQUAL Function#19
	FadeScreen 6 1 0 0
	WaitFadeScreen
	OpenVoltorbFlip 13 1
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

//===== FUNCTIONS =====//
Function 1:
	OverlayManager 3 0
	Message 2
	OpenTouchScreen
	ShowSpecialCurrency 0 20 2
	ShowMoney 20 7
	MultiTouchStandardText 1 1 0 1 0x800C
	CreateMultiTouchBox 127 255 0
	CreateMultiTouchBox 128 255 1
	CreateMultiTouchBox 129 255 2
	CloseMultiTouch
	SetVarFromVariable 0x8008 0x800C
	CompareVarValue 0x8008 0
	JumpIf EQUAL Function#20
	CompareVarValue 0x8008 1
	JumpIf EQUAL Function#21
	Message 6
Jump Function#22

Function 2:
	Message 13
	WaitButton
	CloseMessage
	ReleaseAll
	OverlayManager 3 1
End

Function 3:
	Message 14
	WaitButton
	CloseMessage
	ReleaseAll
	OverlayManager 3 1
End

Function 4:
	Message 15
	WaitButton
	CloseMessage
	ReleaseAll
	OverlayManager 3 1
End

Function 5:
	CheckItem ITEM_COIN_CASE 1 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#23
	OverlayManager 3 0
	HasCoinsImmediate 0x800C 3
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#24
	OverlayManager 3 1
	SetVar 0x4001 0
Return

Function 6:
	ReleaseAll
End

Function 7:
	ReleaseAll
End

Function 8:
	ReleaseAll
End

Function 9:
	ReleaseAll
End

Function 10:
	ReleaseAll
End

Function 11:
	ReleaseAll
End

Function 12:
	ReleaseAll
End

Function 13:
	ReleaseAll
End

Function 14:
	ReleaseAll
End

Function 15:
	ReleaseAll
End

Function 16:
	ReleaseAll
End

Function 17:
	ReleaseAll
End

Function 18:
	ReleaseAll
End

Function 19:
	ReleaseAll
End

Function 20:
	CompareMoney 0x800C 1000
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#25
	CanGiveCoins 0x800C 50
	Nop
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#26
	TakeMoney 1000
	GiveCoins 50
	UpdateSpecialCurrency 0
	UpdateMoney
	PlayFanfare SEQ_SE_DP_REGI
	WaitFanfare SEQ_SE_DP_REGI
	Message 3
Jump Function#27

Function 21:
	CompareMoney 0x800C 0x2710
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#25
	CanGiveCoins 0x800C 500
	Nop
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#26
	TakeMoney 0x2710
	GiveCoins 500
	UpdateSpecialCurrency 0
	UpdateMoney
	PlayFanfare SEQ_SE_DP_REGI
	WaitFanfare SEQ_SE_DP_REGI
	Message 3
Jump Function#27

Function 22:
	WaitButton
	CloseMessage
	CloseTouchScreen
	HideSpecialCurrency
	HideMoney
	OverlayManager 3 1
	ReleaseAll
End

Function 23:
	Message 21
	WaitButton
	CloseMessage
	SetVar 0x4001 1
Return

Function 24:
	Message 22
	WaitButton
	CloseMessage
	OverlayManager 3 1
	SetVar 0x4001 1
Return

Function 25:
	Message 4
	WaitButton
	CloseMessage
	CloseTouchScreen
	HideSpecialCurrency
	HideMoney
	OverlayManager 3 1
	ReleaseAll
End

Function 26:
	Message 5
Jump Function#22

Function 27:
	MultiTouchStandardText 1 1 0 1 0x800C
	CreateMultiTouchBox 127 255 0
	CreateMultiTouchBox 128 255 1
	CreateMultiTouchBox 129 255 2
	CloseMultiTouch
	SetVarFromVariable 0x8008 0x800C
	CompareVarValue 0x8008 0
	JumpIf EQUAL Function#20
	CompareVarValue 0x8008 1
	JumpIf EQUAL Function#21
	Message 6
Jump Function#22

//===== ACTIONS =====//
