/*
 * DSPRE Script File
 * Rom ID: spawn - Copy
 * Game: HGSS
 * File: 0806
 * Generated: 2/25/2026 10:00:59 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckItem ITEM_COIN_CASE 1 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#1
	Movement Overworld.0 Action#1
	WaitMovement
	Message 12
	CloseMessage
	FadeScreen 6 1 0 0
	WaitFadeScreen
	OpenVoltorbFlip 0 0
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	SetVar 0x4001 2
	ReleaseAll
End

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 14
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 3:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	GetPlayerDirection 0x4002
	CompareVarValue 0x4002 1
	JumpIf DIFFERENT Function#2
	Call Function#3
Jump Function#4

Script 4:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckItem ITEM_COIN_CASE 1 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#5
	CompareVarValue 0x4001 0
	JumpIf DIFFERENT Function#6
	Message 6
	SetVar 0x4001 1
Jump Function#7

//===== FUNCTIONS =====//
Function 1:
	Message 10
	Movement Overworld.0 Action#1
	WaitMovement
	Message 11
Jump Function#8

Function 2:
	Movement Overworld.0 Action#1
	WaitMovement
	CheckItem ITEM_COIN_CASE 1 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#9
	Message 13
Jump Function#8

Function 3:
	GetPlayerPosition 0x4002 0x4003
	GetPlayerPosition 0x4002 0x4003
	CompareVarValue 0x4002 6
	JumpIf DIFFERENT Function#10
	Movement Overworld.0 Action#2
Jump Function#11

Function 4:
	WaitMovement
	CheckItem ITEM_COIN_CASE 1 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#9
	Message 13
Jump Function#8

Function 5:
	CompareVarValue 0x4001 0
	JumpIf DIFFERENT Function#12
	Message 0
Jump Function#13

Function 6:
	CompareVarValue 0x4001 1
	JumpIf DIFFERENT Function#14
	Message 7
Jump Function#7

Function 7:
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 8:
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 9:
	Message 11
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 10:
	CompareVarValue 0x4002 8
	JumpIf DIFFERENT Function#11
	Movement Overworld.0 Action#3
Return

Function 11:
Return

Function 12:
	Message 9
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#15
	Message 3
	SetVar 0x4001 1
	SetVar 0x8004 444
	SetVar 0x8005 1
	CommonScript 2033
	Message 4
Jump Function#8

Function 13:
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#15
	Message 3
	SetVar 0x4001 1
	SetVar 0x8004 444
	SetVar 0x8005 1
	CommonScript 2033
	Message 4
Jump Function#8

Function 14:
	Message 8
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 15:
	SetVar 0x4001 1
	Message 5
Jump Function#8

//===== ACTIONS =====//
Action 1:
	FaceSouth 0x1
End

Action 2:
	FaceWest 0x1
End

Action 3:
	FaceEast 0x1
End

