/*
 * DSPRE Script File
 * Rom ID: spawn - Copy
 * Game: HGSS
 * File: 0824
 * Generated: 2/25/2026 10:00:59 PM
 */

//===== SCRIPTS =====//
Script 1:
	MecScript
	LockAll
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	GetPlayerPosition 0x4000 0x4001
	CompareVarValue 0x4000 5
	JumpIf DIFFERENT Function#1
	Movement Player Action#1
Jump Function#2

Script 2:
	MecScript
	LockAll
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	Movement Player Action#2
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	PlayFanfare SEQ_SE_DP_KI_GASYAN
	ClearFlag 528
	AddOW Overworld.3
	SetVar 0x40C8 1
	ReleaseAll
End

Script 3:
	SetFlag 528
	SetVar 0x40C8 0
End

//===== FUNCTIONS =====//
Function 1:
	CompareVarValue 0x4000 6
	JumpIf DIFFERENT Function#3
	Movement Player Action#3
Jump Function#2

Function 2:
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	Movement Overworld.0 Action#4
	WaitMovement
	TextPlayerName 0
	GenderMessage 0 1
	CloseMessage
	CompareVarValue 0x4135 8
	JumpIf LESS Function#4
	TrainerBattle TRAINER_LANCE_701 TRAINER_NONE 0 0
Jump Function#5

Function 3:
	Movement Player Action#5
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	Movement Overworld.0 Action#4
	WaitMovement
	TextPlayerName 0
	GenderMessage 0 1
	CloseMessage
	CompareVarValue 0x4135 8
	JumpIf LESS Function#4
	TrainerBattle TRAINER_LANCE_701 TRAINER_NONE 0 0
Jump Function#5

Function 4:
	TrainerBattle TRAINER_LANCE_244 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#6
	TextPlayerName 0
	GenderMessage 2 3
	CloseMessage
	WaitTime 10 0x8004
	PlayFanfare SEQ_SE_DP_KI_GASYAN
	RemoveOW Overworld.4
	SetOWPosition Overworld.2 6 0 20 Up
	SetOWPosition Overworld.1 6 0 17 Up
	WaitTime 30 0x8004
	StopMusic 0
	PlayMusic SEQ_GS_EYE_J_SHOUJO
	Movement Overworld.0 Action#6
	Movement Player Action#7
	WaitMovement
	CheckPokemonAlive 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#7
	CompareVarValue 0x4000 5
	JumpIf DIFFERENT Function#8
	Movement Following Action#8
Jump Function#9

Function 5:
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#6
	TextPlayerName 0
	GenderMessage 2 3
	CloseMessage
	WaitTime 10 0x8004
	PlayFanfare SEQ_SE_DP_KI_GASYAN
	RemoveOW Overworld.4
	SetOWPosition Overworld.2 6 0 20 Up
	SetOWPosition Overworld.1 6 0 17 Up
	WaitTime 30 0x8004
	StopMusic 0
	PlayMusic SEQ_GS_EYE_J_SHOUJO
	Movement Overworld.0 Action#6
	Movement Player Action#7
	WaitMovement
	CheckPokemonAlive 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#7
	CompareVarValue 0x4000 5
	JumpIf DIFFERENT Function#8
	Movement Following Action#8
Jump Function#9

Function 6:
	LostBattle
	ReleaseAll
End

Function 7:
	Movement Overworld.2 Action#9
	WaitMovement
	Message 5
	CloseMessage
	Movement Overworld.1 Action#10
	Movement Overworld.2 Action#11
	WaitMovement
	TextPlayerName 0
	GenderMessage 6 7
	CloseMessage
	Movement Overworld.2 Action#12
	WaitMovement
	Message 8
	Movement Overworld.0 Action#13
	Movement Player Action#14
	WaitMovement
	TextPlayerName 0
	GenderMessage 9 10
	CloseMessage
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	Movement Overworld.0 Action#15
	Movement Player Action#16
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	CheckPokemonAlive 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#10
	Movement Following Action#17
	WaitMovement
	PlayFanfare SEQ_SE_DP_KAIDAN2
	Movement Overworld.2 Action#18
	WaitMovement
	Message 11
	Movement Overworld.2 Action#19
	WaitMovement
	WaitAB
	CloseMessage
	CheckFlag 2404
	JumpIf EQUAL Function#11
	ClearFlag 593
	SetVar 0x411A 1
	FadeScreen 6 1 0 0
	WaitFadeScreen
	Warp 306 0 6 22 Up
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Function 8:
	CompareVarValue 0x4000 6
	JumpIf DIFFERENT Function#12
	Movement Following Action#20
Jump Function#9

Function 9:
	WaitMovement
	Movement Overworld.2 Action#9
	WaitMovement
	Message 5
	CloseMessage
	Movement Overworld.1 Action#10
	Movement Overworld.2 Action#11
	WaitMovement
	TextPlayerName 0
	GenderMessage 6 7
	CloseMessage
	Movement Overworld.2 Action#12
	WaitMovement
	Message 8
	Movement Overworld.0 Action#13
	Movement Player Action#14
	WaitMovement
	TextPlayerName 0
	GenderMessage 9 10
	CloseMessage
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	Movement Overworld.0 Action#15
	Movement Player Action#16
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	CheckPokemonAlive 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#10
	Movement Following Action#17
	WaitMovement
	PlayFanfare SEQ_SE_DP_KAIDAN2
	Movement Overworld.2 Action#18
	WaitMovement
	Message 11
	Movement Overworld.2 Action#19
	WaitMovement
	WaitAB
	CloseMessage
	CheckFlag 2404
	JumpIf EQUAL Function#11
	ClearFlag 593
	SetVar 0x411A 1
	FadeScreen 6 1 0 0
	WaitFadeScreen
	Warp 306 0 6 22 Up
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Function 10:
	PlayFanfare SEQ_SE_DP_KAIDAN2
	Movement Overworld.2 Action#18
	WaitMovement
	Message 11
	Movement Overworld.2 Action#19
	WaitMovement
	WaitAB
	CloseMessage
	CheckFlag 2404
	JumpIf EQUAL Function#11
	ClearFlag 593
	SetVar 0x411A 1
	FadeScreen 6 1 0 0
	WaitFadeScreen
	Warp 306 0 6 22 Up
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Function 11:
	FadeScreen 6 1 0 0
	WaitFadeScreen
	Warp 306 0 6 22 Up
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Function 12:
	Movement Following Action#21
	WaitMovement
	Movement Overworld.2 Action#9
	WaitMovement
	Message 5
	CloseMessage
	Movement Overworld.1 Action#10
	Movement Overworld.2 Action#11
	WaitMovement
	TextPlayerName 0
	GenderMessage 6 7
	CloseMessage
	Movement Overworld.2 Action#12
	WaitMovement
	Message 8
	Movement Overworld.0 Action#13
	Movement Player Action#14
	WaitMovement
	TextPlayerName 0
	GenderMessage 9 10
	CloseMessage
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	Movement Overworld.0 Action#15
	Movement Player Action#16
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	CheckPokemonAlive 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#10
	Movement Following Action#17
	WaitMovement
	PlayFanfare SEQ_SE_DP_KAIDAN2
	Movement Overworld.2 Action#18
	WaitMovement
	Message 11
	Movement Overworld.2 Action#19
	WaitMovement
	WaitAB
	CloseMessage
	CheckFlag 2404
	JumpIf EQUAL Function#11
	ClearFlag 593
	SetVar 0x411A 1
	FadeScreen 6 1 0 0
	WaitFadeScreen
	Warp 306 0 6 22 Up
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

//===== ACTIONS =====//
Action 1:
	WalkNorth8 0x2
	WalkEast8 0x1
	WalkOnSpotNorth8 0x1
End

Action 2:
	WalkNorth8 0x6
End

Action 3:
	WalkNorth8 0x2
End

Action 4:
	WalkOnSpotSouth8 0x1
End

Action 5:
	WalkNorth8 0x2
	WalkWest8 0x1
	WalkOnSpotNorth8 0x1
End

Action 6:
	FaceSouth 0x1
	EmoteExclamation 0x0
	LockDir 0x1
	WalkEast8 0x1
	ReleaseDir 0x1
End

Action 7:
	FaceSouth 0x1
	Delay8 0x4
	LockDir 0x1
	WalkNorth8 0x2
	ReleaseDir 0x1
End

Action 8:
	WalkNorth4 0x3
	WalkEast4 0x1
	WalkOnSpotSouth8 0x1
End

Action 9:
	WalkNorth4 0xC
	FaceSouth 0x1
	WalkOnSpotSouth4 0x3
End

Action 10:
	WalkNorth8 0x8
End

Action 11:
	Delay8 0x6
	WalkWest8 0x1
	FaceNorth 0x1
End

Action 12:
	WalkOnSpotNorth4 0x4
End

Action 13:
	WalkNorth8 0x2
	WalkWest8 0x1
	FaceSouth 0x1
End

Action 14:
	Delay8 0x3
	FaceNorth 0x1
End

Action 15:
	Delay4 0x1
	WalkNorth8 0x2
	SetInvisible 0x1
End

Action 16:
	WalkNorth8 0x2
	WalkNorth8 0x2
	SetInvisible 0x1
End

Action 17:
	SetInvisible 0x1
End

Action 18:
	WalkNorth4 0x4
	EmoteExclamation 0x0
	Delay8 0x2
End

Action 19:
	WalkEast4 0x1
	WalkWest4 0x2
	WalkEast4 0x2
	WalkWest4 0x1
	FaceNorth 0x1
End

Action 20:
	WalkNorth4 0x2
	WalkWest4 0x1
	WalkNorth4 0x2
	WalkEast4 0x1
	WalkOnSpotSouth8 0x1
End

Action 21:
	WalkNorth4 0x1
	WalkEast4 0x1
	WalkNorth4 0x2
	WalkWest4 0x2
	WalkOnSpotSouth8 0x1
End

