/*
 * DSPRE Script File
 * Rom ID: spawn - Copy
 * Game: HGSS
 * File: 0832
 * Generated: 2/25/2026 10:01:00 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckFlag 269
	JumpIf EQUAL Function#1
	Message 0
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 3:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 3
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 4:
	CheckPokeGearRematch 17 0x4000
	CheckPokeGearRematch 26 0x4001
	CheckPokeGearRematch 27 0x4002
	CheckPokeGearRematch 28 0x4003
	CheckPokeGearRematch 29 0x4004
	CheckPokeGearRematch 30 0x4005
	CheckPokeGearRematch 31 0x4006
	CheckPokeGearRematch 32 0x4007
	CheckPokeGearRematch 33 0x4008
	CheckPokeGearRematch 34 0x4009
	CheckPokeGearRematch 35 0x400A
	CheckPokeGearRematch 18 0x400B
	CheckPokeGearRematch 36 0x400C
	CheckPokeGearRematch 37 0x400D
	CheckPokeGearRematch 38 0x400E
	CheckPokeGearRematch 39 0x400F
	CompareVarValue 0x4003 0
	JumpIf DIFFERENT Function#2
	SetFlag 696
Jump Function#3

Script 5:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 8
	CloseMessage
	TrainerBattle TRAINER_WHITNEY_714 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#4
	Message 9
	WaitButton
	CloseMessage
	FadeScreen 6 1 0 0
	WaitFadeScreen
	DisablePokegearRematch 17
	SetFlag 693
	RemoveOW Overworld.1
	PlayFanfare SEQ_SE_DP_KAIDAN2
	WaitFanfare SEQ_SE_DP_KAIDAN2
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Script 6:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 30
	CloseMessage
	TrainerBattle TRAINER_JANINE_724 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#5
	Message 31
	WaitButton
	CloseMessage
	FadeScreen 6 1 0 0
	WaitFadeScreen
	DisablePokegearRematch 26
	SetFlag 694
	RemoveOW Overworld.2
	PlayFanfare SEQ_SE_DP_KAIDAN2
	WaitFanfare SEQ_SE_DP_KAIDAN2
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Script 7:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 18
	CloseMessage
	TrainerBattle TRAINER_CLAIR_719 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#6
	Message 19
	WaitButton
	CloseMessage
	FadeScreen 6 1 0 0
	WaitFadeScreen
	DisablePokegearRematch 27
	SetFlag 695
	RemoveOW Overworld.3
	PlayFanfare SEQ_SE_DP_KAIDAN2
	WaitFanfare SEQ_SE_DP_KAIDAN2
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Script 8:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 24
	CloseMessage
	TrainerBattle TRAINER_ERIKA_723 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#7
	Message 25
	WaitButton
	CloseMessage
	FadeScreen 6 1 0 0
	WaitFadeScreen
	DisablePokegearRematch 28
	SetFlag 696
	RemoveOW Overworld.4
	PlayFanfare SEQ_SE_DP_KAIDAN2
	WaitFanfare SEQ_SE_DP_KAIDAN2
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Script 9:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 26
	CloseMessage
	TrainerBattle TRAINER_MISTY_721 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#8
	Message 27
	WaitButton
	CloseMessage
	FadeScreen 6 1 0 0
	WaitFadeScreen
	DisablePokegearRematch 29
	SetFlag 697
	RemoveOW Overworld.5
	PlayFanfare SEQ_SE_DP_KAIDAN2
	WaitFanfare SEQ_SE_DP_KAIDAN2
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Script 10:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 32
	CloseMessage
	TrainerBattle TRAINER_BLAINE_726 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#9
	Message 33
	WaitButton
	CloseMessage
	FadeScreen 6 1 0 0
	WaitFadeScreen
	DisablePokegearRematch 30
	SetFlag 698
	RemoveOW Overworld.16
	PlayFanfare SEQ_SE_DP_KAIDAN2
	WaitFanfare SEQ_SE_DP_KAIDAN2
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Script 11:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 34
	CloseMessage
	TrainerBattle TRAINER_BLUE_727 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#10
	Message 35
	WaitButton
	CloseMessage
	FadeScreen 6 1 0 0
	WaitFadeScreen
	DisablePokegearRematch 31
	SetFlag 699
	RemoveOW Overworld.6
	PlayFanfare SEQ_SE_DP_KAIDAN2
	WaitFanfare SEQ_SE_DP_KAIDAN2
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Script 12:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 10
	CloseMessage
	TrainerBattle TRAINER_CHUCK_718 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#11
	Message 11
	WaitButton
	CloseMessage
	FadeScreen 6 1 0 0
	WaitFadeScreen
	DisablePokegearRematch 32
	SetFlag 700
	RemoveOW Overworld.7
	PlayFanfare SEQ_SE_DP_KAIDAN2
	WaitFanfare SEQ_SE_DP_KAIDAN2
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Script 13:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 28
	CloseMessage
	TrainerBattle TRAINER_BROCK_720 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#12
	Message 29
	WaitButton
	CloseMessage
	FadeScreen 6 1 0 0
	WaitFadeScreen
	DisablePokegearRematch 33
	SetFlag 701
	RemoveOW Overworld.8
	PlayFanfare SEQ_SE_DP_KAIDAN2
	WaitFanfare SEQ_SE_DP_KAIDAN2
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Script 14:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 6
	CloseMessage
	TrainerBattle TRAINER_BUGSY_713 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#13
	Message 7
	WaitButton
	CloseMessage
	FadeScreen 6 1 0 0
	WaitFadeScreen
	DisablePokegearRematch 34
	SetFlag 702
	RemoveOW Overworld.9
	PlayFanfare SEQ_SE_DP_KAIDAN2
	WaitFanfare SEQ_SE_DP_KAIDAN2
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Script 15:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 22
	CloseMessage
	TrainerBattle TRAINER_SABRINA_725 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#14
	Message 23
	WaitButton
	CloseMessage
	FadeScreen 6 1 0 0
	WaitFadeScreen
	DisablePokegearRematch 35
	SetFlag 703
	RemoveOW Overworld.10
	PlayFanfare SEQ_SE_DP_KAIDAN2
	WaitFanfare SEQ_SE_DP_KAIDAN2
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Script 16:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 4
	CloseMessage
	TrainerBattle TRAINER_FALKNER_712 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#15
	Message 5
	WaitButton
	CloseMessage
	FadeScreen 6 1 0 0
	WaitFadeScreen
	DisablePokegearRematch 18
	SetFlag 704
	RemoveOW Overworld.11
	PlayFanfare SEQ_SE_DP_KAIDAN2
	WaitFanfare SEQ_SE_DP_KAIDAN2
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Script 17:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 20
	CloseMessage
	TrainerBattle TRAINER_LT_SURGE_722 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#16
	Message 21
	WaitButton
	CloseMessage
	FadeScreen 6 1 0 0
	WaitFadeScreen
	DisablePokegearRematch 36
	SetFlag 705
	RemoveOW Overworld.12
	PlayFanfare SEQ_SE_DP_KAIDAN2
	WaitFanfare SEQ_SE_DP_KAIDAN2
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Script 18:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 14
	CloseMessage
	TrainerBattle TRAINER_MORTY_715 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#17
	Message 15
	WaitButton
	CloseMessage
	FadeScreen 6 1 0 0
	WaitFadeScreen
	DisablePokegearRematch 37
	SetFlag 706
	RemoveOW Overworld.13
	PlayFanfare SEQ_SE_DP_KAIDAN2
	WaitFanfare SEQ_SE_DP_KAIDAN2
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Script 19:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 12
	CloseMessage
	TrainerBattle TRAINER_JASMINE_717 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#18
	Message 13
	WaitButton
	CloseMessage
	FadeScreen 6 1 0 0
	WaitFadeScreen
	DisablePokegearRematch 38
	SetFlag 707
	RemoveOW Overworld.14
	PlayFanfare SEQ_SE_DP_KAIDAN2
	WaitFanfare SEQ_SE_DP_KAIDAN2
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Script 20:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 16
	CloseMessage
	TrainerBattle TRAINER_PRYCE_716 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#19
	Message 17
	WaitButton
	CloseMessage
	FadeScreen 6 1 0 0
	WaitFadeScreen
	DisablePokegearRematch 39
	SetFlag 708
	RemoveOW Overworld.15
	PlayFanfare SEQ_SE_DP_KAIDAN2
	WaitFanfare SEQ_SE_DP_KAIDAN2
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

//===== FUNCTIONS =====//
Function 1:
	Message 1
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 2:
	ClearFlag 696
	CompareVarValue 0x4000 0
	JumpIf DIFFERENT Function#20
	SetFlag 693
Jump Function#21

Function 3:
	CompareVarValue 0x4000 0
	JumpIf DIFFERENT Function#20
	SetFlag 693
Jump Function#21

Function 4:
	LostBattle
	ReleaseAll
End

Function 5:
	LostBattle
	ReleaseAll
End

Function 6:
	LostBattle
	ReleaseAll
End

Function 7:
	LostBattle
	ReleaseAll
End

Function 8:
	LostBattle
	ReleaseAll
End

Function 9:
	LostBattle
	ReleaseAll
End

Function 10:
	LostBattle
	ReleaseAll
End

Function 11:
	LostBattle
	ReleaseAll
End

Function 12:
	LostBattle
	ReleaseAll
End

Function 13:
	LostBattle
	ReleaseAll
End

Function 14:
	LostBattle
	ReleaseAll
End

Function 15:
	LostBattle
	ReleaseAll
End

Function 16:
	LostBattle
	ReleaseAll
End

Function 17:
	LostBattle
	ReleaseAll
End

Function 18:
	LostBattle
	ReleaseAll
End

Function 19:
	LostBattle
	ReleaseAll
End

Function 20:
	ClearFlag 693
	CompareVarValue 0x4001 0
	JumpIf DIFFERENT Function#22
	SetFlag 694
Jump Function#23

Function 21:
	CompareVarValue 0x4001 0
	JumpIf DIFFERENT Function#22
	SetFlag 694
Jump Function#23

Function 22:
	ClearFlag 694
	CompareVarValue 0x4002 0
	JumpIf DIFFERENT Function#24
	SetFlag 695
Jump Function#25

Function 23:
	CompareVarValue 0x4002 0
	JumpIf DIFFERENT Function#24
	SetFlag 695
Jump Function#25

Function 24:
	ClearFlag 695
	CompareVarValue 0x4004 0
	JumpIf DIFFERENT Function#26
	SetFlag 697
Jump Function#27

Function 25:
	CompareVarValue 0x4004 0
	JumpIf DIFFERENT Function#26
	SetFlag 697
Jump Function#27

Function 26:
	ClearFlag 697
	CompareVarValue 0x4005 0
	JumpIf DIFFERENT Function#28
	SetFlag 698
Jump Function#29

Function 27:
	CompareVarValue 0x4005 0
	JumpIf DIFFERENT Function#28
	SetFlag 698
Jump Function#29

Function 28:
	ClearFlag 698
	CompareVarValue 0x4006 0
	JumpIf DIFFERENT Function#30
	SetFlag 699
Jump Function#31

Function 29:
	CompareVarValue 0x4006 0
	JumpIf DIFFERENT Function#30
	SetFlag 699
Jump Function#31

Function 30:
	ClearFlag 699
	CompareVarValue 0x4007 0
	JumpIf DIFFERENT Function#32
	SetFlag 700
Jump Function#33

Function 31:
	CompareVarValue 0x4007 0
	JumpIf DIFFERENT Function#32
	SetFlag 700
Jump Function#33

Function 32:
	ClearFlag 700
	CompareVarValue 0x4008 0
	JumpIf DIFFERENT Function#34
	SetFlag 701
Jump Function#35

Function 33:
	CompareVarValue 0x4008 0
	JumpIf DIFFERENT Function#34
	SetFlag 701
Jump Function#35

Function 34:
	ClearFlag 701
	CompareVarValue 0x4009 0
	JumpIf DIFFERENT Function#36
	SetFlag 702
Jump Function#37

Function 35:
	CompareVarValue 0x4009 0
	JumpIf DIFFERENT Function#36
	SetFlag 702
Jump Function#37

Function 36:
	ClearFlag 702
	CompareVarValue 0x400A 0
	JumpIf DIFFERENT Function#38
	SetFlag 703
Jump Function#39

Function 37:
	CompareVarValue 0x400A 0
	JumpIf DIFFERENT Function#38
	SetFlag 703
Jump Function#39

Function 38:
	ClearFlag 703
	CompareVarValue 0x400B 0
	JumpIf DIFFERENT Function#40
	SetFlag 704
Jump Function#41

Function 39:
	CompareVarValue 0x400B 0
	JumpIf DIFFERENT Function#40
	SetFlag 704
Jump Function#41

Function 40:
	ClearFlag 704
	CompareVarValue 0x400C 0
	JumpIf DIFFERENT Function#42
	SetFlag 705
Jump Function#43

Function 41:
	CompareVarValue 0x400C 0
	JumpIf DIFFERENT Function#42
	SetFlag 705
Jump Function#43

Function 42:
	ClearFlag 705
	CompareVarValue 0x400D 0
	JumpIf DIFFERENT Function#44
	SetFlag 706
Jump Function#45

Function 43:
	CompareVarValue 0x400D 0
	JumpIf DIFFERENT Function#44
	SetFlag 706
Jump Function#45

Function 44:
	ClearFlag 706
	CompareVarValue 0x400E 0
	JumpIf DIFFERENT Function#46
	SetFlag 707
Jump Function#47

Function 45:
	CompareVarValue 0x400E 0
	JumpIf DIFFERENT Function#46
	SetFlag 707
Jump Function#47

Function 46:
	ClearFlag 707
	CompareVarValue 0x400F 0
	JumpIf DIFFERENT Function#48
	SetFlag 708
Jump Function#49

Function 47:
	CompareVarValue 0x400F 0
	JumpIf DIFFERENT Function#48
	SetFlag 708
Jump Function#49

Function 48:
	ClearFlag 708
End

Function 49:
End

//===== ACTIONS =====//
