/*
 * DSPRE Script File
 * Rom ID: spawn - Copy
 * Game: HGSS
 * File: 0839
 * Generated: 2/25/2026 10:01:00 PM
 */

//===== SCRIPTS =====//
Script 1:
	MecScript
	LockAll
	GetFirstAlivePokemonSlot 0x4000
	GetPartyPokemonID 0x4000 0x4001
	CompareVarValue 0x4001 479
	JumpIf DIFFERENT Function#1
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	Movement Player Action#1
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	Movement Following Action#2
	WaitMovement
	PlayCry SPECIES_ROTOM 0
	WaitCry
	Message 0
	CloseMessage
Jump Function#2

//===== FUNCTIONS =====//
Function 1:
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	Movement Player Action#1
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	CheckPokemonAlive 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#3
	Movement Following Action#3
	WaitMovement
	Message 1
	CloseMessage
	GetElevatorFloor 0x4113
	SetVarFromVariable 0x8008 0x4113
	CompareVarValue 0x8008 1
	JumpIf EQUAL Function#4
	CompareVarValue 0x8008 0
	JumpIf EQUAL Function#5
End

Function 2:
	GetElevatorFloor 0x4113
	SetVarFromVariable 0x8008 0x4113
	CompareVarValue 0x8008 1
	JumpIf EQUAL Function#6
	CompareVarValue 0x8008 0
	JumpIf EQUAL Function#7
End

Function 3:
	Message 1
	CloseMessage
	GetElevatorFloor 0x4113
	SetVarFromVariable 0x8008 0x4113
	CompareVarValue 0x8008 1
	JumpIf EQUAL Function#4
	CompareVarValue 0x8008 0
	JumpIf EQUAL Function#5
End

Function 4:
	SetVar 0x8004 0
	Call Function#8
	FadeScreen 6 1 0 0
	WaitFadeScreen
	Warp 403 0 7 3 Down
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Function 5:
	SetVar 0x8004 1
	Call Function#8
	FadeScreen 6 1 0 0
	WaitFadeScreen
	Warp 402 0 3 3 Down
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Function 6:
	SetVar 0x8004 0
	Call Function#9
	FadeScreen 6 1 0 0
	WaitFadeScreen
	Warp 402 0 3 3 Down
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Function 7:
	SetVar 0x8004 1
	Call Function#9
	FadeScreen 6 1 0 0
	WaitFadeScreen
	Warp 403 0 7 3 Down
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Function 8:
	CheckPokemonAlive 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#10
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#11
End

Function 9:
	WaitFanfare SEQ_SE_CONFIRM
	ElevatorAnimation 0x8004 1
	CheckPokemonAlive 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#10
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#11
End

Function 10:
	Movement Player Action#4
	WaitMovement
	PlayFanfare SEQ_SE_DP_KAIDAN2
Return

Function 11:
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	Movement Player Action#4
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
Jump Function#12

Function 12:
	PlayFanfare SEQ_SE_DP_KAIDAN2
Return

//===== ACTIONS =====//
Action 1:
	WalkNorth8 0x2
	WalkOnSpotSouth8 0x1
End

Action 2:
	FaceSouth 0x1
	WalkSouth8 0x1
	JumpOnSpotSouth16 0x3
End

Action 3:
	WalkEast8 0x1
	WalkNorth8 0x1
	FaceSouth 0x1
End

Action 4:
	WalkSouth8 0x2
	WalkOnSpotSouth8 0x1
End

