/*
 * DSPRE Script File
 * Rom ID: spawn - Copy
 * Game: HGSS
 * File: 0842
 * Generated: 2/25/2026 10:01:00 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Message 13
	CloseMessage
	GetPlayerDirection 0x800C
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#1
	Movement Overworld.0 Action#1
Jump Function#2

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CompareVarValue 0x4072 0
	JumpIf DIFFERENT Function#3
	Message 9
Jump Function#4

Script 3:
	MecScript
	LockAll
	CheckFlag 156
	JumpIf EQUAL Function#5
	Movement Overworld.1 Action#2
	WaitMovement
	TextPlayerName 0
	GenderMessage 1 2
	WaitTime 20 0x800C
	CloseMessage
	Movement Player Action#3
	WaitMovement
	CompareVarValue 0x4072 2
	JumpIf EQUAL Function#6
	GetPlayerPosition 0x4000 0x4001
	CompareVarValue 0x4001 396
	JumpIf DIFFERENT Function#7
	Movement Overworld.1 Action#4
Jump Function#8

Script 4:
	MecScript
	LockAll
	Release Overworld.3
	Movement Overworld.3 Action#5
	WaitMovement
	PlayFanfare SEQ_SE_DP_KAIDAN2
	ClearFlag 418
	AddOW Overworld.4
	WaitFanfare SEQ_SE_DP_KAIDAN2
	CommonScript 2029
	Movement Overworld.4 Action#6
	WaitMovement
	Movement Overworld.3 Action#7
	WaitMovement
	Movement Player Action#8
	Movement Overworld.4 Action#9
	WaitMovement
	Movement Overworld.3 Action#10
	WaitMovement
	Movement Overworld.4 Action#11
	Movement Overworld.3 Action#12
	WaitMovement
	CommonScript 2030
	SetVar 0x4106 2
	RemoveOW Overworld.3
	RemoveOW Overworld.4
	SetFlag 417
	SetFlag 418
	ReleaseAll
End

Script 5:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	GenderMessage 25 26
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 6:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	PlayCry SPECIES_MARILL 0
	Message 33
	WaitCry
	CloseMessage
	Movement Overworld.9 Action#13
	WaitMovement
	Movement Overworld.8 Action#14
	WaitMovement
	GenderMessage 31 32
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 7:
	GetCounterpartSprite 0x4020
	CheckFlag 393
	JumpIf LESS Function#9
	ClearFlag 393
End

Script 8:
	TextPlayerName 0
	SetTextBoard 2 0
	ShowBoard 3
	WaitBoard
	BoardMessage 35 0x800C
	CommonScript 2000
End

Script 9:
	MecScript
	LockAll
	CommonScript 2029
	Movement Overworld.4 Action#15
	Movement Overworld.3 Action#16
	WaitMovement
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	Movement Player Action#17
	Movement Overworld.4 Action#18
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	TextPlayerName 0
	TextPartyPokemonDefault 1 0
	GenderMessage 15 16
	CloseMessage
	Movement Overworld.4 Action#19
	Movement Overworld.3 Action#20
	Movement Player Action#21
	WaitMovement
	Movement Overworld.4 Action#22
	Movement Overworld.3 Action#23
	WaitMovement
	RemoveOW Overworld.3
	RemoveOW Overworld.4
	SetFlag 417
	SetFlag 418
	CommonScript 2030
	SetVar 0x4072 2
	ReleaseAll
End

Script 10:
	CompareVarValue 0x4072 1
	JumpIf EQUAL Function#10
End

Script 11:
	CheckPokemonAlive 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#11
	GetFollowingPokeSize 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#11
	SendBackFollowingPoke
	PlayFanfare SEQ_SE_DP_KAIDAN2
	FadeScreen 6 1 0 0
	WaitFadeScreen
	Warp 62 0 12 6 Left
	FadeScreen 6 1 1 0
	WaitFadeScreen
	WaitFanfare SEQ_SE_DP_KAIDAN2
	CMD_582 60 688 393
	SetVar 0x407C 1
End

Script 12:
	MecScript
	LockAll
	CompareVarValue 0x4007 2
	JumpIf EQUAL Function#12
	DoorAnimation 21 12 23 12 77
	OpenDoor 77
	WaitDoor 77
	PlayFanfare SEQ_SE_DP_KAIDAN2
	ClearFlag 678
	AddOW Overworld.7
	WaitFanfare SEQ_SE_DP_KAIDAN2
	Movement Overworld.7 Action#24
	WaitMovement
	CompareVarValue 0x4007 0
	JumpIf DIFFERENT Function#13
	TextPlayerName 0
	Message 21
	CloseMessage
	CloseDoor 77
	WaitDoor 77
	FreeDoor 77
	GetPlayerPosition 0x8004 0x8005
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	CompareVarValue 0x8005 398
	JumpIf DIFFERENT Function#14
	Movement Overworld.7 Action#25
	Movement Player Action#26
Jump Function#15

Script 13:
	MecScript
	LockAll
	Movement Overworld.8 Action#27
	WaitMovement
	TextPlayerName 0
	GenderMessage 27 28
	CloseMessage
	GetPlayerPosition 0x8004 0x8005
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	CompareVarValue 0x8005 398
	JumpIf DIFFERENT Function#16
	Movement Overworld.8 Action#28
Jump Function#17

Script 14:
	SetTextBoard 2 0
	ShowBoard 3
	WaitBoard
	BoardMessage 36 0x800C
	CommonScript 2000
End

Script 15:
	SetIconBoard 34 0 11 0x800C
	ShowBoard 3
	WaitBoard
	CloseBoard 0x800C
	CommonScript 2000
End

Script 16:
	TextPlayerName 0
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 12
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 17:
	TextCounterpart 0
	SetTextBoard 2 0
	ShowBoard 3
	WaitBoard
	BoardMessage 35 0x800C
	CommonScript 2000
End

Script 18:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 0
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#18
	CheckAlbumPhoto 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#19
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 1
	CloseMessage
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	GetPlayerDirection 0x800C
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#20
	Movement Player Action#29
	Movement Overworld.6 Action#30
Jump Function#21

//===== FUNCTIONS =====//
Function 1:
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#22
	Movement Overworld.0 Action#31
Jump Function#2

Function 2:
	WaitMovement
	Message 14
	CloseMessage
	CheckFlag 106
	JumpIf LESS Function#23
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#24
Jump Function#25

Function 3:
	CompareVarValue 0x4072 1
	JumpIf DIFFERENT Function#26
	Message 5
Jump Function#4

Function 4:
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 5:
	DoorAnimation 21 12 12 9 77
	OpenDoor 77
	WaitDoor 77
	AddOW Overworld.5
	SetOWPosition Overworld.5 684 0 393 Down
	Movement Overworld.5 Action#32
	WaitMovement
	CloseDoor 77
	WaitDoor 77
	FreeDoor 77
	Message 17
	CloseMessage
	Movement Player Action#33
	WaitMovement
	GetPlayerPosition 0x4000 0x4001
	CompareVarValue 0x4001 396
	JumpIf DIFFERENT Function#27
	Movement Overworld.5 Action#34
	Movement Player Action#35
Jump Function#28

Function 6:
	GetPlayerPosition 0x4000 0x4001
	CompareVarValue 0x4001 396
	JumpIf DIFFERENT Function#29
	Movement Player Action#36
	Movement Overworld.1 Action#37
Jump Function#30

Function 7:
	CompareVarValue 0x4001 397
	JumpIf DIFFERENT Function#31
	Movement Overworld.1 Action#38
Jump Function#8

Function 8:
	WaitMovement
	Message 3
	CloseMessage
	CompareVarValue 0x4001 396
	JumpIf DIFFERENT Function#32
	Movement Overworld.1 Action#39
	Movement Player Action#40
Jump Function#33

Function 9:
	SetVar 0x4007 0
	CheckBadge 2 0x4002
	CompareVarValue 0x4002 0
	JumpIf EQUAL Function#34
	GetDayOfWeek 0x4000
	CompareVarValue 0x4000 2
	JumpIf EQUAL Function#35
	SetFlag 638
End

Function 10:
	ClearFlag 418
	AddOW Overworld.4
	ClearFlag 417
	AddOW Overworld.3
	SetOWPosition Overworld.4 686 0 396 Left
	SetOWPosition Overworld.3 685 0 396 Down
End

Function 11:
	PlayFanfare SEQ_SE_DP_KAIDAN2
	FadeScreen 6 1 0 0
	WaitFadeScreen
	Warp 62 0 12 6 Left
	FadeScreen 6 1 1 0
	WaitFadeScreen
	WaitFanfare SEQ_SE_DP_KAIDAN2
	CMD_582 60 688 393
	SetVar 0x407C 1
End

Function 12:
	Message 24
	CloseMessage
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	Movement Player Action#41
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	ReleaseAll
End

Function 13:
	CloseDoor 77
	WaitDoor 77
	FreeDoor 77
	GetPlayerPosition 0x8004 0x8005
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	CompareVarValue 0x8005 398
	JumpIf DIFFERENT Function#14
	Movement Overworld.7 Action#25
	Movement Player Action#26
Jump Function#15

Function 14:
	CompareVarValue 0x8005 399
	JumpIf DIFFERENT Function#36
	Movement Overworld.7 Action#42
	Movement Player Action#43
Jump Function#15

Function 15:
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	CompareVarValue 0x4007 0
	JumpIf DIFFERENT Function#37
	Message 22
Jump Function#38

Function 16:
	CompareVarValue 0x8005 399
	JumpIf DIFFERENT Function#39
	Movement Overworld.8 Action#44
Jump Function#17

Function 17:
	Movement Player Action#45
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	TextPlayerName 0
	GenderMessage 29 30
	CloseMessage
	CompareVarValue 0x8005 398
	JumpIf DIFFERENT Function#40
	Movement Overworld.8 Action#46
Jump Function#41

Function 18:
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 5
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 19:
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 3
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 20:
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#42
	Movement Player Action#47
Jump Function#21

Function 21:
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	CheckPokemonAlive 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#43
	Movement Following Action#48
	WaitMovement
	SetFlag 393
	FadeScreen 6 1 0 0
	WaitFadeScreen
	TakePhoto 0
	LockAll
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ClearFlag 393
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 22:
	CompareVarValue 0x800C 3
	JumpIf DIFFERENT Function#2
	Movement Overworld.0 Action#49
	WaitMovement
	Message 14
	CloseMessage
	CheckFlag 106
	JumpIf LESS Function#23
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#24
Jump Function#25

Function 23:
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#44
Jump Function#45

Function 24:
	CompareVarValue 0x800C 3
	JumpIf DIFFERENT Function#23
Jump Function#46

Function 25:
	Movement Overworld.0 Action#50
	Movement Following Action#51
	Movement Player Action#52
	WaitMovement
	Movement Overworld.0 Action#53
	WaitMovement
	ReleaseAll
End

Function 26:
	CompareVarValue 0x4072 2
	JumpIf DIFFERENT Function#47
	Message 5
Jump Function#4

Function 27:
	CompareVarValue 0x4001 397
	JumpIf DIFFERENT Function#48
	Movement Overworld.5 Action#54
	Movement Player Action#55
Jump Function#28

Function 28:
	WaitMovement
	Message 18
	RecordPokegearNumber 1
	TextPlayerName 0
	Message 19
	PlaySound SEQ_ME_POKEGEAR_REGIST
	WaitSound
	Message 20
	CloseMessage
	GetPlayerPosition 0x4000 0x4001
	CompareVarValue 0x4001 396
	JumpIf DIFFERENT Function#49
	Movement Player Action#3
	Movement Overworld.5 Action#56
Jump Function#50

Function 29:
	CompareVarValue 0x4001 397
	JumpIf DIFFERENT Function#51
	Movement Player Action#36
	Movement Overworld.1 Action#57
Jump Function#30

Function 30:
	WaitMovement
	Message 10
	CloseMessage
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	CompareVarValue 0x4001 396
	JumpIf DIFFERENT Function#52
	Movement Overworld.1 Action#58
	Movement Player Action#59
Jump Function#53

Function 31:
	CompareVarValue 0x4001 398
	JumpIf DIFFERENT Function#54
	Movement Overworld.1 Action#60
Jump Function#8

Function 32:
	CompareVarValue 0x4001 397
	JumpIf DIFFERENT Function#55
	Movement Overworld.1 Action#61
	Movement Player Action#62
Jump Function#33

Function 33:
	WaitMovement
	Message 4
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 34:
	SetFlag 638
End

Function 35:
	ClearFlag 638
End

Function 36:
	CompareVarValue 0x8005 400
	JumpIf DIFFERENT Function#56
	Movement Overworld.7 Action#63
	Movement Player Action#64
Jump Function#15

Function 37:
	Message 23
	CloseMessage
	CompareVarValue 0x8005 398
	JumpIf DIFFERENT Function#57
	Movement Overworld.7 Action#65
	WaitMovement
Jump Function#58

Function 38:
	CloseMessage
	CompareVarValue 0x8005 398
	JumpIf DIFFERENT Function#57
	Movement Overworld.7 Action#65
	WaitMovement
Jump Function#58

Function 39:
	CompareVarValue 0x8005 399
	JumpIf DIFFERENT Function#59
	Movement Overworld.8 Action#66
Jump Function#17

Function 40:
	CompareVarValue 0x8005 399
	JumpIf DIFFERENT Function#60
	Movement Overworld.8 Action#67
Jump Function#41

Function 41:
	WaitMovement
	ReleaseAll
End

Function 42:
	CompareVarValue 0x800C 3
	JumpIf DIFFERENT Function#61
	Movement Player Action#68
	Movement Overworld.6 Action#30
Jump Function#21

Function 43:
	SetFlag 393
	FadeScreen 6 1 0 0
	WaitFadeScreen
	TakePhoto 0
	LockAll
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ClearFlag 393
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 44:
	CompareVarValue 0x800C 3
	JumpIf DIFFERENT Function#46
Jump Function#62

Function 45:
	Movement Overworld.0 Action#50
	Movement Player Action#52
	WaitMovement
	Movement Overworld.0 Action#53
	WaitMovement
	ReleaseAll
End

Function 46:
	Movement Overworld.0 Action#69
	Movement Following Action#70
	Movement Player Action#71
	WaitMovement
	Movement Overworld.0 Action#53
	WaitMovement
	ReleaseAll
End

Function 47:
	CompareVarValue 0x407E 1
	JumpIf DIFFERENT Function#63
	Message 0
Jump Function#4

Function 48:
	CompareVarValue 0x4001 398
	JumpIf DIFFERENT Function#64
	Movement Overworld.5 Action#72
	Movement Player Action#55
Jump Function#28

Function 49:
	CompareVarValue 0x4001 397
	JumpIf DIFFERENT Function#65
	Movement Player Action#3
	Movement Overworld.5 Action#73
Jump Function#50

Function 50:
	WaitMovement
	DoorAnimation 21 12 12 9 77
	OpenDoor 77
	WaitDoor 77
	Movement Overworld.5 Action#74
	WaitMovement
	RemoveOW Overworld.5
	CloseDoor 77
	WaitDoor 77
	FreeDoor 77
	SetVar 0x407E 1
	ReleaseAll
End

Function 51:
	CompareVarValue 0x4001 398
	JumpIf DIFFERENT Function#66
	Movement Player Action#36
	Movement Overworld.1 Action#75
Jump Function#30

Function 52:
	CompareVarValue 0x4001 397
	JumpIf DIFFERENT Function#67
	Movement Overworld.1 Action#76
	Movement Player Action#77
Jump Function#53

Function 53:
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	Message 11
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 54:
	CompareVarValue 0x4001 399
	JumpIf DIFFERENT Function#68
	Movement Overworld.1 Action#78
Jump Function#8

Function 55:
	CompareVarValue 0x4001 398
	JumpIf DIFFERENT Function#69
	Movement Overworld.1 Action#79
	Movement Player Action#80
Jump Function#33

Function 56:
	CompareVarValue 0x8005 401
	JumpIf DIFFERENT Function#70
	Movement Overworld.7 Action#63
	Movement Player Action#81
Jump Function#15

Function 57:
	CompareVarValue 0x8005 399
	JumpIf DIFFERENT Function#71
	Movement Overworld.7 Action#82
	WaitMovement
Jump Function#58

Function 58:
	DoorAnimation 21 12 23 12 77
	OpenDoor 77
	WaitDoor 77
	Movement Overworld.7 Action#83
	WaitMovement
	SetFlag 678
	PlayFanfare SEQ_SE_DP_KAIDAN2
	RemoveOW Overworld.7
	WaitFanfare SEQ_SE_DP_KAIDAN2
	CloseDoor 77
	WaitDoor 77
	FreeDoor 77
	IncrementVar 0x4007 1
	ReleaseAll
End

Function 59:
	CompareVarValue 0x8005 399
	JumpIf DIFFERENT Function#72
	Movement Overworld.8 Action#84
Jump Function#17

Function 60:
	CompareVarValue 0x8005 399
	JumpIf DIFFERENT Function#73
	Movement Overworld.8 Action#85
Jump Function#41

Function 61:
	Movement Player Action#86
	Movement Overworld.6 Action#30
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	CheckPokemonAlive 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#43
	Movement Following Action#48
	WaitMovement
	SetFlag 393
	FadeScreen 6 1 0 0
	WaitFadeScreen
	TakePhoto 0
	LockAll
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ClearFlag 393
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 62:
	Movement Overworld.0 Action#69
	Movement Player Action#71
	WaitMovement
	Movement Overworld.0 Action#53
	WaitMovement
	ReleaseAll
End

Function 63:
	TextPlayerName 0
	GenderMessage 6 7
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 64:
	CompareVarValue 0x4001 399
	JumpIf DIFFERENT Function#74
	Movement Overworld.5 Action#87
	Movement Player Action#55
Jump Function#28

Function 65:
	CompareVarValue 0x4001 398
	JumpIf DIFFERENT Function#75
	Movement Player Action#88
	Movement Overworld.5 Action#89
Jump Function#50

Function 66:
	CompareVarValue 0x4001 399
	JumpIf DIFFERENT Function#76
	Movement Player Action#90
	Movement Overworld.1 Action#91
Jump Function#30

Function 67:
	CompareVarValue 0x4001 398
	JumpIf DIFFERENT Function#77
	Movement Overworld.1 Action#92
	Movement Player Action#93
Jump Function#53

Function 68:
	CompareVarValue 0x4001 400
	JumpIf DIFFERENT Function#78
	Movement Overworld.1 Action#94
Jump Function#8

Function 69:
	CompareVarValue 0x4001 399
	JumpIf DIFFERENT Function#79
	Movement Overworld.1 Action#95
	Movement Player Action#96
Jump Function#33

Function 70:
	Movement Overworld.7 Action#63
	Movement Player Action#97
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	CompareVarValue 0x4007 0
	JumpIf DIFFERENT Function#37
	Message 22
Jump Function#38

Function 71:
	Movement Overworld.7 Action#98
	WaitMovement
	DoorAnimation 21 12 23 12 77
	OpenDoor 77
	WaitDoor 77
	Movement Overworld.7 Action#83
	WaitMovement
	SetFlag 678
	PlayFanfare SEQ_SE_DP_KAIDAN2
	RemoveOW Overworld.7
	WaitFanfare SEQ_SE_DP_KAIDAN2
	CloseDoor 77
	WaitDoor 77
	FreeDoor 77
	IncrementVar 0x4007 1
	ReleaseAll
End

Function 72:
	Movement Overworld.8 Action#99
	Movement Player Action#45
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	TextPlayerName 0
	GenderMessage 29 30
	CloseMessage
	CompareVarValue 0x8005 398
	JumpIf DIFFERENT Function#40
	Movement Overworld.8 Action#46
Jump Function#41

Function 73:
	CompareVarValue 0x8005 399
	JumpIf DIFFERENT Function#80
	Movement Overworld.8 Action#100
Jump Function#41

Function 74:
	CompareVarValue 0x4001 400
	JumpIf DIFFERENT Function#81
	Movement Overworld.5 Action#101
	Movement Player Action#55
Jump Function#28

Function 75:
	CompareVarValue 0x4001 399
	JumpIf DIFFERENT Function#82
	Movement Overworld.5 Action#102
Jump Function#50

Function 76:
	CompareVarValue 0x4001 400
	JumpIf DIFFERENT Function#83
	Movement Player Action#90
	Movement Overworld.1 Action#103
Jump Function#30

Function 77:
	CompareVarValue 0x4001 399
	JumpIf DIFFERENT Function#84
	Movement Overworld.1 Action#104
	Movement Player Action#105
Jump Function#53

Function 78:
	CompareVarValue 0x4001 401
	JumpIf DIFFERENT Function#85
	Movement Overworld.1 Action#106
Jump Function#8

Function 79:
	CompareVarValue 0x4001 400
	JumpIf DIFFERENT Function#86
	Movement Overworld.1 Action#107
	Movement Player Action#108
Jump Function#33

Function 80:
	Movement Overworld.8 Action#109
	WaitMovement
	ReleaseAll
End

Function 81:
	CompareVarValue 0x4001 401
	JumpIf DIFFERENT Function#87
	Movement Overworld.5 Action#110
	Movement Player Action#88
Jump Function#28

Function 82:
	CompareVarValue 0x4001 400
	JumpIf DIFFERENT Function#88
	Movement Overworld.5 Action#111
Jump Function#50

Function 83:
	CompareVarValue 0x4001 401
	JumpIf DIFFERENT Function#89
	Movement Player Action#90
	Movement Overworld.1 Action#112
Jump Function#30

Function 84:
	CompareVarValue 0x4001 400
	JumpIf DIFFERENT Function#90
	Movement Overworld.1 Action#113
	Movement Player Action#114
Jump Function#53

Function 85:
	CompareVarValue 0x4001 402
	JumpIf DIFFERENT Function#8
	Movement Overworld.1 Action#115
	WaitMovement
	Message 3
	CloseMessage
	CompareVarValue 0x4001 396
	JumpIf DIFFERENT Function#32
	Movement Overworld.1 Action#39
	Movement Player Action#40
Jump Function#33

Function 86:
	CompareVarValue 0x4001 401
	JumpIf DIFFERENT Function#91
	Movement Overworld.1 Action#116
	Movement Player Action#117
Jump Function#33

Function 87:
	CompareVarValue 0x4001 402
	JumpIf DIFFERENT Function#28
	Movement Overworld.5 Action#118
	Movement Player Action#88
	WaitMovement
	Message 18
	RecordPokegearNumber 1
	TextPlayerName 0
	Message 19
	PlaySound SEQ_ME_POKEGEAR_REGIST
	WaitSound
	Message 20
	CloseMessage
	GetPlayerPosition 0x4000 0x4001
	CompareVarValue 0x4001 396
	JumpIf DIFFERENT Function#49
	Movement Player Action#3
	Movement Overworld.5 Action#56
Jump Function#50

Function 88:
	CompareVarValue 0x4001 401
	JumpIf DIFFERENT Function#92
	Movement Overworld.5 Action#119
Jump Function#50

Function 89:
	CompareVarValue 0x4001 402
	JumpIf DIFFERENT Function#30
	Movement Player Action#90
	Movement Overworld.1 Action#120
	WaitMovement
	Message 10
	CloseMessage
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	CompareVarValue 0x4001 396
	JumpIf DIFFERENT Function#52
	Movement Overworld.1 Action#58
	Movement Player Action#59
Jump Function#53

Function 90:
	CompareVarValue 0x4001 401
	JumpIf DIFFERENT Function#93
	Movement Overworld.1 Action#121
	Movement Player Action#122
Jump Function#53

Function 91:
	CompareVarValue 0x4001 402
	JumpIf DIFFERENT Function#33
	Movement Overworld.1 Action#123
	Movement Player Action#124
	WaitMovement
	Message 4
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 92:
	CompareVarValue 0x4001 402
	JumpIf DIFFERENT Function#50
	Movement Overworld.5 Action#125
	WaitMovement
	DoorAnimation 21 12 12 9 77
	OpenDoor 77
	WaitDoor 77
	Movement Overworld.5 Action#74
	WaitMovement
	RemoveOW Overworld.5
	CloseDoor 77
	WaitDoor 77
	FreeDoor 77
	SetVar 0x407E 1
	ReleaseAll
End

Function 93:
	CompareVarValue 0x4001 402
	JumpIf DIFFERENT Function#53
	Movement Overworld.1 Action#126
	Movement Player Action#127
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	Message 11
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== ACTIONS =====//
Action 1:
	WalkOnSpotSouth8 0x1
End

Action 2:
	WalkOnSpotWest8 0x1
	EmoteExclamation 0x1
	Delay8 0x1
End

Action 3:
	FaceEast 0x1
End

Action 4:
	WalkWest8 0x3
	WalkNorth8 0x3
	WalkWest8 0x3
End

Action 5:
	Delay32 0x1
	WalkNorth4 0x8
	LockDir 0x1
	JumpSouth8 0x1
	ReleaseDir 0x1
	FaceEast 0x5
	FaceNorth 0x5
	FaceWest 0x5
	FaceNorth 0x5
	WalkNorth8 0x1
	Delay32 0x1
End

Action 6:
	Delay16 0x1
	WalkSouth8 0x6
	FaceEast 0x1
	EmoteExclamation 0x1
End

Action 7:
	FaceWest 0x1
	EmoteExclamation 0x1
	WalkOnSpotNorth4 0x4
	FaceSouth 0x2
	FaceEast 0x2
	FaceNorth 0x2
	FaceWest 0x2
	WalkOnSpotWest4 0x4
	WalkWest4 0x6
End

Action 8:
	FaceWest 0x4
End

Action 9:
	WalkOnSpotEast4 0x4
End

Action 10:
	JumpOnSpotWest8 0x4
End

Action 11:
	FaceSouth 0x1
	WalkSouth8 0x4
	FaceWest 0x1
	WalkWest8 0x2
End

Action 12:
	FaceWest 0x1
	WalkWest8 0x1
	FaceSouth 0x1
	WalkSouth8 0x4
	FaceWest 0x1
	WalkWest8 0x2
End

Action 13:
	JumpOnSpotEast16 0x1
	JumpOnSpotEast16 0x1
End

Action 14:
	WalkOnSpotWest8 0x1
End

Action 15:
	Delay4 0x4
	Delay4 0x2
	WalkOnSpotSouth4 0x1
	Delay4 0x2
	WalkOnSpotEast4 0x1
	Delay4 0x1
	WalkOnSpotNorth4 0x1
	Delay4 0x1
	WalkOnSpotSouth4 0x1
	Delay4 0x1
	WalkOnSpotNorth4 0x1
	Delay4 0x1
	EmoteExclamation 0x1
End

Action 16:
	JumpOnSpotEast8 0x3
	WalkSouth4 0x1
	WalkEast4 0x2
	WalkNorth4 0x2
	WalkWest4 0x2
	WalkSouth4 0x2
	WalkNorth4 0x2
	WalkEast4 0x2
	WalkSouth4 0x1
	WalkOnSpotWest8 0x1
End

Action 17:
	WalkSouth8 0x2
	WalkEast8 0x1
End

Action 18:
	Delay8 0x1
	WalkOnSpotWest8 0x1
End

Action 19:
	WalkSouth8 0x1
	WalkWest8 0x2
	WalkSouth8 0x5
	WalkOnSpotNorth8 0x1
End

Action 20:
	WalkWest8 0x1
	WalkSouth8 0x1
	WalkWest8 0x2
	WalkOnSpotNorth8 0x1
	Delay8 0x3
	WalkOnSpotSouth8 0x1
	WalkSouth4 0x4
	JumpOnSpotSouth8 0x2
End

Action 21:
	Delay8 0x2
	WalkOnSpotSouth8 0x1
End

Action 22:
	WalkSouth8 0x3
End

Action 23:
	WalkSouth8 0x4
End

Action 24:
	WalkSouth8 0x1
End

Action 25:
	WalkSouth8 0x1
	WalkOnSpotEast8 0x1
End

Action 26:
	WalkOnSpotWest8 0x1
	WalkWest8 0x4
End

Action 27:
	FaceEast 0x1
	EmoteExclamation 0x1
End

Action 28:
	WalkOnSpotEast8 0x1
End

Action 29:
	WalkEast8 0x1
	WalkNorth8 0x2
	WalkWest8 0x1
	WalkNorth8 0x3
	WalkOnSpotSouth8 0x1
End

Action 30:
	Delay8 0x1
	WalkOnSpotNorth8 0x1
End

Action 31:
	WalkOnSpotNorth8 0x1
End

Action 32:
	WalkSouth8 0x1
End

Action 33:
	EmoteExclamation 0x1
	Delay8 0x1
End

Action 34:
	WalkSouth8 0x3
	WalkWest8 0x8
	WalkOnSpotNorth8 0x1
End

Action 35:
	FaceEast 0x1
	Delay32 0x2
	FaceSouth 0x1
End

Action 36:
	Delay32 0x2
	WalkOnSpotSouth8 0x1
End

Action 37:
	WalkWest8 0x7
	WalkNorth8 0x2
End

Action 38:
	WalkWest8 0x3
	WalkNorth8 0x2
	WalkWest8 0x3
End

Action 39:
	WalkEast8 0x3
	WalkSouth8 0x3
	WalkEast8 0x3
	WalkOnSpotWest8 0x1
End

Action 40:
	WalkEast8 0x4
	WalkSouth8 0x3
	WalkEast8 0x2
End

Action 41:
	WalkWest8 0x1
End

Action 42:
	WalkSouth8 0x2
	WalkOnSpotEast8 0x1
End

Action 43:
	WalkOnSpotWest8 0x1
	WalkWest8 0x4
End

Action 44:
	WalkOnSpotEast8 0x1
End

Action 45:
	WalkWest8 0x2
End

Action 46:
	WalkOnSpotWest8 0x1
End

Action 47:
	WalkNorth8 0x3
	WalkOnSpotSouth8 0x1
End

Action 48:
	WalkEast8 0x1
	WalkNorth8 0x1
	FaceSouth 0x1
End

Action 49:
	WalkOnSpotWest8 0x1
End

Action 50:
	WalkNorth6 0x1
	FaceWest 0x1
	WalkWest6 0x1
	FaceSouth 0x1
	WalkSouth6 0x3
End

Action 51:
	LockDir 0x1
	WalkSouth6 0x6
	ReleaseDir 0x1
End

Action 52:
	FaceEast 0x1
	LockDir 0x1
	WalkWest6 0x1
	ReleaseDir 0x1
	FaceNorth 0x1
	LockDir 0x1
	WalkSouth6 0x3
	JumpFarSouth 0x1
	ReleaseDir 0x1
End

Action 53:
	FaceNorth 0x1
	WalkNorth8 0x2
	FaceEast 0x1
	WalkEast8 0x1
End

Action 54:
	WalkSouth8 0x2
	WalkWest8 0x8
	WalkOnSpotSouth8 0x1
End

Action 55:
	FaceEast 0x1
	Delay32 0x2
	FaceNorth 0x1
End

Action 56:
	WalkEast8 0x8
	WalkNorth8 0x3
End

Action 57:
	WalkWest8 0x7
	WalkNorth8 0x1
End

Action 58:
	WalkSouth8 0x2
	WalkEast8 0x7
	WalkOnSpotWest8 0x1
End

Action 59:
	WalkSouth8 0x3
	WalkEast8 0x6
End

Action 60:
	WalkWest8 0x3
	WalkNorth8 0x1
	WalkWest8 0x3
End

Action 61:
	WalkEast8 0x3
	WalkSouth8 0x2
	WalkEast8 0x3
	WalkOnSpotWest8 0x1
End

Action 62:
	WalkEast8 0x4
	WalkSouth8 0x2
	WalkEast8 0x2
End

Action 63:
	WalkSouth8 0x3
	WalkOnSpotEast8 0x1
End

Action 64:
	WalkOnSpotWest8 0x1
	WalkWest8 0x4
End

Action 65:
	WalkNorth8 0x1
End

Action 66:
	WalkEast8 0x1
End

Action 67:
	WalkOnSpotWest8 0x1
End

Action 68:
	WalkNorth8 0x1
	WalkEast8 0x1
	WalkNorth8 0x3
	WalkOnSpotSouth8 0x1
End

Action 69:
	WalkWest6 0x1
	FaceSouth 0x1
	WalkSouth6 0x2
End

Action 70:
	LockDir 0x1
	WalkSouth6 0x4
	ReleaseDir 0x1
End

Action 71:
	FaceNorth 0x1
	LockDir 0x1
	WalkSouth6 0x2
	JumpFarSouth 0x1
	ReleaseDir 0x1
End

Action 72:
	WalkSouth8 0x2
	WalkWest8 0x8
	WalkSouth8 0x1
End

Action 73:
	WalkEast8 0x8
	WalkNorth8 0x2
End

Action 74:
	WalkNorth8 0x1
End

Action 75:
	WalkWest8 0x7
	WalkOnSpotNorth8 0x1
End

Action 76:
	WalkSouth8 0x1
	WalkEast8 0x7
	WalkOnSpotWest8 0x1
End

Action 77:
	WalkSouth8 0x2
	WalkEast8 0x6
End

Action 78:
	WalkWest8 0x6
End

Action 79:
	WalkEast8 0x3
	WalkSouth8 0x1
	WalkEast8 0x3
	WalkOnSpotWest8 0x1
End

Action 80:
	WalkEast8 0x4
	WalkSouth8 0x1
	WalkEast8 0x2
End

Action 81:
	WalkWest8 0x2
	WalkNorth8 0x1
	WalkWest8 0x2
End

Action 82:
	WalkNorth8 0x2
End

Action 83:
	WalkNorth8 0x1
End

Action 84:
	WalkOnSpotEast8 0x1
End

Action 85:
	WalkOnSpotWest8 0x1
End

Action 86:
	WalkNorth8 0x1
	WalkWest8 0x1
	WalkNorth8 0x3
	WalkOnSpotSouth8 0x1
End

Action 87:
	WalkSouth8 0x2
	WalkWest8 0x8
	WalkSouth8 0x2
End

Action 88:
	FaceNorth 0x1
End

Action 89:
	WalkNorth8 0x1
	WalkEast8 0x8
	WalkNorth8 0x2
End

Action 90:
	Delay32 0x2
	WalkOnSpotNorth8 0x1
End

Action 91:
	WalkWest8 0x3
	WalkNorth8 0x1
	WalkWest8 0x4
	WalkOnSpotSouth8 0x1
End

Action 92:
	WalkEast8 0x7
	WalkOnSpotWest8 0x1
End

Action 93:
	WalkSouth8 0x1
	WalkEast8 0x6
End

Action 94:
	WalkWest8 0x3
	WalkSouth8 0x1
	WalkWest8 0x3
End

Action 95:
	WalkEast8 0x6
	WalkOnSpotWest8 0x1
End

Action 96:
	WalkEast8 0x6
End

Action 97:
	WalkWest8 0x2
	WalkNorth8 0x2
	WalkWest8 0x2
End

Action 98:
	WalkNorth8 0x3
End

Action 99:
	WalkOnSpotEast8 0x1
End

Action 100:
	WalkOnSpotWest8 0x1
End

Action 101:
	WalkSouth8 0x2
	WalkWest8 0x8
	WalkSouth8 0x3
End

Action 102:
	WalkNorth8 0x2
	WalkEast8 0x8
	WalkNorth8 0x2
End

Action 103:
	WalkWest8 0x7
	WalkOnSpotSouth8 0x1
End

Action 104:
	WalkEast8 0x3
	WalkSouth8 0x1
	WalkEast8 0x4
	WalkOnSpotWest8 0x1
End

Action 105:
	WalkNorth8 0x1
	WalkEast8 0x3
	WalkSouth8 0x1
	WalkEast8 0x3
End

Action 106:
	WalkWest8 0x6
	WalkSouth8 0x2
	FaceWest 0x1
End

Action 107:
	WalkEast8 0x3
	WalkNorth8 0x1
	WalkEast8 0x3
	WalkOnSpotWest8 0x1
End

Action 108:
	WalkEast8 0x4
	WalkNorth8 0x1
	WalkEast8 0x2
End

Action 109:
	WalkOnSpotWest8 0x1
End

Action 110:
	WalkSouth8 0x2
	WalkWest8 0x8
	WalkSouth8 0x4
End

Action 111:
	WalkNorth8 0x2
	WalkEast8 0x8
	WalkNorth8 0x3
End

Action 112:
	WalkWest8 0x7
	WalkSouth8 0x1
End

Action 113:
	WalkEast8 0x7
	WalkOnSpotWest8 0x1
End

Action 114:
	WalkNorth8 0x1
	WalkEast8 0x6
End

Action 115:
	WalkWest8 0x6
	WalkSouth8 0x3
	FaceWest 0x1
End

Action 116:
	WalkNorth8 0x2
	WalkEast8 0x6
	WalkOnSpotWest8 0x1
End

Action 117:
	WalkEast8 0x1
	WalkNorth8 0x2
	WalkEast8 0x5
End

Action 118:
	WalkSouth8 0x2
	WalkWest8 0x8
	WalkSouth8 0x5
End

Action 119:
	WalkNorth8 0x2
	WalkEast8 0x8
	WalkNorth8 0x4
End

Action 120:
	WalkWest8 0x7
	WalkSouth8 0x2
End

Action 121:
	WalkNorth8 0x1
	WalkEast8 0x7
	WalkOnSpotWest8 0x1
End

Action 122:
	WalkNorth8 0x2
	WalkEast8 0x6
End

Action 123:
	WalkNorth8 0x3
	WalkEast8 0x6
	WalkOnSpotWest8 0x1
End

Action 124:
	WalkEast8 0x1
	WalkNorth8 0x3
	WalkEast8 0x5
End

Action 125:
	WalkNorth8 0x5
	WalkEast8 0x8
	WalkNorth8 0x2
End

Action 126:
	WalkNorth8 0x2
	WalkEast8 0x7
	WalkOnSpotWest8 0x1
End

Action 127:
	WalkNorth8 0x3
	WalkEast8 0x6
End

