/*
 * DSPRE Script File
 * Rom ID: spawn - Copy
 * Game: HGSS
 * File: 0850
 * Generated: 2/25/2026 10:01:00 PM
 */

//===== SCRIPTS =====//
Script 1:
End

Script 2:
	Lock Overworld.0
	Movement Overworld.0 Action#1
	WaitMovement
	CommonScript 2037
	GetPlayerPosition 0x4000 0x4001
	CompareVarValue 0x4001 397
	JumpIf DIFFERENT Function#1
	Movement Overworld.0 Action#2
Jump Function#2

Script 3:
	MecScript
	LockAll
	Movement Player Action#3
	WaitMovement
	CommonScript 2037
	ClearFlag 408
	AddOW Overworld.0
	Lock Overworld.0
	GetPlayerPosition 0x4000 0x4001
	SetOWPosition Overworld.0 0x4000 1 394 Up
	CompareVarValue 0x4000 549
	JumpIf DIFFERENT Function#3
	Movement Overworld.0 Action#4
Jump Function#4

Script 4:
	MecScript
	LockAll
	FadeOutMusic 0 3
	Movement Player Action#1
	WaitMovement
	CommonScript 2031
	GetPlayerPosition 0x4000 0x4001
	SetOWPosition Overworld.4 583 0 0x4001 Left
	Movement Overworld.4 Action#5
	WaitMovement
	Message 13
	CloseMessage
	CheckStarter 0x800C
	CompareVarValue 0x800C 152
	JumpIf DIFFERENT Function#5
	TrainerBattle TRAINER_BOY_496 TRAINER_NONE 1 0
Jump Function#6

Script 5:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckFlag 243
	JumpIf EQUAL Function#7
	Message 20
	SetVar 0x8004 243
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#8
	CommonScript 2033
	SetFlag 243
	Message 21
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 6:
	SetTextBoard 2 0
	ShowBoard 3
	WaitBoard
	BoardMessage 24 0x800C
	CommonScript 2000
End

Script 7:
	SetIconBoard 23 0 12 0x800C
	ShowBoard 3
	WaitBoard
	CloseBoard 0x800C
	CommonScript 2000
End

Script 8:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 19
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 9:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 17
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 10:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 0
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#9
	CheckAlbumPhoto 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#10
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 1
	CloseMessage
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	GetPlayerDirection 0x800C
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#11
	Movement Player Action#6
	Movement Overworld.5 Action#7
Jump Function#12

Script 11:
	CheckFlag 393
	JumpIf LESS Function#13
	ClearFlag 393
End

//===== FUNCTIONS =====//
Function 1:
	CompareVarValue 0x4001 398
	JumpIf DIFFERENT Function#14
	Movement Overworld.0 Action#8
Jump Function#2

Function 2:
	Movement Player Action#9
	WaitMovement
	Message 0
	CloseMessage
	TextPlayerName 0
	GetPlayerPosition 0x4000 0x4001
	CompareVarValue 0x4001 397
	JumpIf DIFFERENT Function#15
	Movement Overworld.0 Action#10
Jump Function#16

Function 3:
	CompareVarValue 0x4000 550
	JumpIf DIFFERENT Function#17
	Movement Overworld.0 Action#4
Jump Function#4

Function 4:
	WaitMovement
	CompareVarValue 0x4000 549
	JumpIf DIFFERENT Function#18
	Movement Player Action#11
Jump Function#19

Function 5:
	CompareVarValue 0x800C 155
	JumpIf DIFFERENT Function#20
	TrainerBattle TRAINER_BOY_497 TRAINER_NONE 1 0
Jump Function#6

Function 6:
	CheckBattleIsLost 0x800C
	CommonScript 2070
	Message 14
	CloseMessage
	PlayFanfare SEQ_SE_DP_WALL_HIT2
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 56
	GetPlayerPosition 0x8004 0x8005
	CompareVarValue 0x8005 398
	JumpIf DIFFERENT Function#21
	Movement Player Action#12
Jump Function#22

Function 7:
	Message 21
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 8:
	Message 22
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 9:
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 5
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 10:
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 3
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 11:
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#23
	Movement Player Action#13
Jump Function#12

Function 12:
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	CheckPokemonAlive 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#24
	Movement Following Action#14
	WaitMovement
	SetFlag 393
	FadeScreen 6 1 0 0
	WaitFadeScreen
	TakePhoto 1
	LockAll
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ClearFlag 393
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 13:
	CheckBadge 2 0x4000
	CompareVarValue 0x4000 0
	JumpIf EQUAL Function#25
	GetDayOfWeek 0x4000
	CompareVarValue 0x4000 1
	JumpIf EQUAL Function#26
	CompareVarValue 0x4000 3
	JumpIf EQUAL Function#26
	CompareVarValue 0x4000 5
	JumpIf EQUAL Function#26
	SetFlag 638
End

Function 14:
	CompareVarValue 0x4001 399
	JumpIf DIFFERENT Function#27
	Movement Overworld.0 Action#15
Jump Function#2

Function 15:
	CompareVarValue 0x4001 398
	JumpIf DIFFERENT Function#28
	Movement Overworld.0 Action#16
Jump Function#16

Function 16:
	WaitMovement
	Movement Player Action#11
	WaitMovement
	Message 1
	CloseMessage
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	CompareVarValue 0x4001 397
	JumpIf DIFFERENT Function#29
	Movement Overworld.0 Action#17
	Movement Player Action#18
Jump Function#30

Function 17:
	Movement Overworld.0 Action#19
	WaitMovement
	CompareVarValue 0x4000 549
	JumpIf DIFFERENT Function#18
	Movement Player Action#11
Jump Function#19

Function 18:
	CompareVarValue 0x4000 550
	JumpIf DIFFERENT Function#31
	Movement Player Action#11
Jump Function#19

Function 19:
	WaitMovement
	Message 9
	TextPlayerName 0
	Message 10
	PlaySound SEQ_ME_KEYITEM
	WaitSound
	Message 11
	Message 12
	CloseMessage
	Movement Overworld.0 Action#20
	WaitMovement
	CommonScript 2038
	Release Overworld.0
	RemoveOW Overworld.0
	SetFlag 408
	UpgradePokegear 1
	ReleaseAll
	SetVar 0x4073 2
End

Function 20:
	TrainerBattle TRAINER_BOY_495 TRAINER_NONE 1 0
	CheckBattleIsLost 0x800C
	CommonScript 2070
	Message 14
	CloseMessage
	PlayFanfare SEQ_SE_DP_WALL_HIT2
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 56
	GetPlayerPosition 0x8004 0x8005
	CompareVarValue 0x8005 398
	JumpIf DIFFERENT Function#21
	Movement Player Action#12
Jump Function#22

Function 21:
	Movement Player Action#21
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	CompareVarValue 0x8005 398
	JumpIf DIFFERENT Function#32
	Movement Overworld.4 Action#22
Jump Function#33

Function 22:
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	CompareVarValue 0x8005 398
	JumpIf DIFFERENT Function#32
	Movement Overworld.4 Action#22
Jump Function#33

Function 23:
	CompareVarValue 0x800C 3
	JumpIf DIFFERENT Function#34
	Movement Player Action#23
	Movement Overworld.5 Action#7
Jump Function#12

Function 24:
	SetFlag 393
	FadeScreen 6 1 0 0
	WaitFadeScreen
	TakePhoto 1
	LockAll
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ClearFlag 393
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 25:
	SetFlag 638
End

Function 26:
	ClearFlag 638
End

Function 27:
	CompareVarValue 0x4001 400
	JumpIf DIFFERENT Function#2
	Movement Overworld.0 Action#24
	Movement Player Action#9
	WaitMovement
	Message 0
	CloseMessage
	TextPlayerName 0
	GetPlayerPosition 0x4000 0x4001
	CompareVarValue 0x4001 397
	JumpIf DIFFERENT Function#15
	Movement Overworld.0 Action#10
Jump Function#16

Function 28:
	CompareVarValue 0x4001 399
	JumpIf DIFFERENT Function#35
	Movement Overworld.0 Action#25
Jump Function#16

Function 29:
	CompareVarValue 0x4001 398
	JumpIf DIFFERENT Function#36
	Movement Overworld.0 Action#26
	Movement Player Action#27
Jump Function#30

Function 30:
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	Message 2
	CloseMessage
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	Movement Overworld.0 Action#28
	Movement Player Action#29
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	Message 3
	CloseMessage
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	Movement Overworld.0 Action#30
	Movement Player Action#31
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	Message 4
	CloseMessage
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	Movement Overworld.0 Action#32
	Movement Player Action#33
	WaitMovement
	PlayFanfare SEQ_SE_GS_N_UMIBE
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	Message 5
	CloseMessage
	StopFanfare SEQ_SE_GS_N_UMIBE
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	Movement Overworld.0 Action#34
	Movement Player Action#35
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	Message 6
	GiveShoes
	TextPlayerName 0
	Message 7
	PlaySound SEQ_ME_ITEM
	WaitSound
	Message 8
	CloseMessage
	Movement Overworld.0 Action#36
	WaitMovement
	DoorAnimation 17 12 14 17 77
	OpenDoor 77
	WaitDoor 77
	Movement Overworld.0 Action#36
	WaitMovement
	Release Overworld.0
	Release Following
	PlayFanfare SEQ_SE_DP_KAIDAN2
	RemoveOW Overworld.0
	WaitFanfare SEQ_SE_DP_KAIDAN2
	SetFlag 408
	CloseDoor 77
	WaitDoor 77
	FreeDoor 77
	CommonScript 2038
	SetVar 0x4073 1
End

Function 31:
	Movement Player Action#37
	WaitMovement
	Message 9
	TextPlayerName 0
	Message 10
	PlaySound SEQ_ME_KEYITEM
	WaitSound
	Message 11
	Message 12
	CloseMessage
	Movement Overworld.0 Action#20
	WaitMovement
	CommonScript 2038
	Release Overworld.0
	RemoveOW Overworld.0
	SetFlag 408
	UpgradePokegear 1
	ReleaseAll
	SetVar 0x4073 2
End

Function 32:
	Movement Overworld.4 Action#38
	WaitMovement
	Message 15
	CloseMessage
	GetOWPosition Overworld.4 0x8004 0x8005
	CompareVarValue 0x8005 401
	JumpIf DIFFERENT Function#37
	Movement Overworld.4 Action#39
	Movement Player Action#40
Jump Function#38

Function 33:
	WaitMovement
	Message 15
	CloseMessage
	GetOWPosition Overworld.4 0x8004 0x8005
	CompareVarValue 0x8005 401
	JumpIf DIFFERENT Function#37
	Movement Overworld.4 Action#39
	Movement Player Action#40
Jump Function#38

Function 34:
	Movement Player Action#41
	Movement Overworld.5 Action#7
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	CheckPokemonAlive 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#24
	Movement Following Action#14
	WaitMovement
	SetFlag 393
	FadeScreen 6 1 0 0
	WaitFadeScreen
	TakePhoto 1
	LockAll
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ClearFlag 393
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 35:
	CompareVarValue 0x4001 400
	JumpIf DIFFERENT Function#16
	Movement Overworld.0 Action#42
	WaitMovement
	Movement Player Action#11
	WaitMovement
	Message 1
	CloseMessage
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	CompareVarValue 0x4001 397
	JumpIf DIFFERENT Function#29
	Movement Overworld.0 Action#17
	Movement Player Action#18
Jump Function#30

Function 36:
	CompareVarValue 0x4001 399
	JumpIf DIFFERENT Function#39
	Movement Overworld.0 Action#43
	Movement Player Action#44
Jump Function#30

Function 37:
	Movement Overworld.4 Action#45
	Movement Player Action#40
	WaitMovement
	RemoveOW Overworld.4
	SetFlag 412
	CommonScript 2071
	ReleaseAll
	SetVar 0x4073 4
	SetFlag 153
End

Function 38:
	WaitMovement
	RemoveOW Overworld.4
	SetFlag 412
	CommonScript 2071
	ReleaseAll
	SetVar 0x4073 4
	SetFlag 153
End

Function 39:
	CompareVarValue 0x4001 400
	JumpIf DIFFERENT Function#30
	Movement Overworld.0 Action#46
	Movement Player Action#47
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	Message 2
	CloseMessage
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	Movement Overworld.0 Action#28
	Movement Player Action#29
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	Message 3
	CloseMessage
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	Movement Overworld.0 Action#30
	Movement Player Action#31
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	Message 4
	CloseMessage
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	Movement Overworld.0 Action#32
	Movement Player Action#33
	WaitMovement
	PlayFanfare SEQ_SE_GS_N_UMIBE
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	Message 5
	CloseMessage
	StopFanfare SEQ_SE_GS_N_UMIBE
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	Movement Overworld.0 Action#34
	Movement Player Action#35
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	Message 6
	GiveShoes
	TextPlayerName 0
	Message 7
	PlaySound SEQ_ME_ITEM
	WaitSound
	Message 8
	CloseMessage
	Movement Overworld.0 Action#36
	WaitMovement
	DoorAnimation 17 12 14 17 77
	OpenDoor 77
	WaitDoor 77
	Movement Overworld.0 Action#36
	WaitMovement
	Release Overworld.0
	Release Following
	PlayFanfare SEQ_SE_DP_KAIDAN2
	RemoveOW Overworld.0
	WaitFanfare SEQ_SE_DP_KAIDAN2
	SetFlag 408
	CloseDoor 77
	WaitDoor 77
	FreeDoor 77
	CommonScript 2038
	SetVar 0x4073 1
End

//===== ACTIONS =====//
Action 1:
	EmoteExclamation 0x1
End

Action 2:
	Delay4 0x1
End

Action 3:
	EmoteExclamation 0x1
	WalkOnSpotSouth4 0x1
End

Action 4:
	WalkWest4 0x1
	WalkNorth4 0x9
	WalkOnSpotEast8 0x1
End

Action 5:
	WalkWest8 0x7
End

Action 6:
	WalkEast8 0x1
	WalkNorth8 0x2
	WalkWest8 0x1
	WalkNorth8 0x3
	WalkOnSpotSouth8 0x1
End

Action 7:
	Delay8 0x1
	WalkOnSpotNorth8 0x1
End

Action 8:
	WalkSouth8 0x1
End

Action 9:
	WalkOnSpotNorth8 0x1
End

Action 10:
	WalkWest4 0x2
	WalkNorth4 0x2
	EmoteExclamation 0x1
	WalkOnSpotSouth4 0x1
	WalkSouth4 0x3
	WalkEast4 0x1
End

Action 11:
	WalkOnSpotWest8 0x1
End

Action 12:
	FaceNorth 0x1
	LockDir 0x1
	WalkSouth4 0x1
	ReleaseDir 0x1
End

Action 13:
	WalkNorth8 0x3
	WalkOnSpotSouth8 0x1
End

Action 14:
	WalkEast8 0x1
	WalkNorth8 0x1
	FaceSouth 0x1
End

Action 15:
	WalkSouth8 0x2
End

Action 16:
	WalkWest4 0x2
	WalkNorth4 0x3
	Delay8 0x1
	WalkOnSpotSouth4 0x1
	Delay32 0x1
	EmoteExclamation 0x1
	WalkSouth4 0x4
	WalkEast4 0x1
End

Action 17:
	WalkWest4 0x1
	WalkNorth4 0x3
	WalkOnSpotSouth4 0x1
	Delay4 0x4
	WalkOnSpotNorth4 0x1
End

Action 18:
	WalkWest8 0x2
	WalkNorth8 0x2
	Delay8 0x1
End

Action 19:
	WalkEast4 0x1
	WalkNorth4 0x9
	WalkOnSpotWest8 0x1
End

Action 20:
	WalkSouth4 0x9
End

Action 21:
	FaceSouth 0x1
	LockDir 0x1
	WalkNorth4 0x1
	ReleaseDir 0x1
End

Action 22:
	WalkWest8 0x6
	EmoteExclamation 0x1
	WalkOnSpotSouth4 0x1
	Delay8 0x1
	WalkOnSpotNorth4 0x1
	Delay8 0x1
	WalkOnSpotSouth4 0x1
	Delay8 0x1
	WalkOnSpotEast8 0x1
	Delay8 0x1
	WalkEast8 0x5
	WalkOnSpotSouth8 0x1
End

Action 23:
	WalkSouth8 0x1
	WalkEast8 0x2
	WalkNorth8 0x2
	WalkWest8 0x1
	WalkNorth8 0x3
	WalkOnSpotSouth8 0x1
End

Action 24:
	WalkSouth8 0x3
End

Action 25:
	WalkWest4 0x2
	WalkNorth4 0x4
	Delay8 0x1
	WalkOnSpotSouth4 0x1
	Delay32 0x1
	EmoteExclamation 0x1
	WalkSouth4 0x5
	WalkEast4 0x1
End

Action 26:
	WalkWest4 0x1
	WalkNorth4 0x4
	WalkOnSpotSouth4 0x1
	Delay4 0x5
	WalkOnSpotNorth4 0x1
End

Action 27:
	WalkWest8 0x2
	WalkNorth8 0x3
	Delay8 0x1
End

Action 28:
	WalkWest4 0x9
	WalkOnSpotEast4 0x1
	Delay4 0x7
	WalkOnSpotNorth4 0x1
End

Action 29:
	WalkNorth8 0x1
	WalkWest8 0x8
	Delay8 0x2
	WalkOnSpotNorth8 0x1
End

Action 30:
	WalkWest4 0x6
	WalkNorth4 0x2
	WalkWest4 0x1
	WalkOnSpotEast4 0x1
	Delay4 0x7
	WalkOnSpotNorth4 0x1
End

Action 31:
	WalkWest8 0x7
	WalkNorth8 0x2
	Delay8 0x1
End

Action 32:
	WalkSouth4 0x2
	WalkWest4 0x6
	WalkSouth4 0x8
	WalkWest8 0x6
	WalkOnSpotNorth4 0x1
	Delay4 0x11
	WalkOnSpotWest4 0x1
End

Action 33:
	WalkWest8 0x1
	WalkSouth8 0x2
	WalkWest8 0x6
	WalkSouth8 0x7
	WalkWest8 0x6
	Delay8 0x2
	WalkOnSpotWest8 0x1
End

Action 34:
	WalkEast4 0x10
	WalkOnSpotWest4 0x1
	Delay4 0x6
	WalkSouth4 0x2
	WalkEast4 0x6
	WalkOnSpotWest4 0x1
End

Action 35:
	Delay4 0x1
	WalkSouth8 0x1
	WalkEast8 0x10
	WalkSouth8 0x2
	WalkEast8 0x5
End

Action 36:
	WalkNorth8 0x2
End

Action 37:
	WalkOnSpotEast8 0x1
End

Action 38:
	WalkWest8 0x6
	EmoteExclamation 0x1
	WalkOnSpotSouth4 0x1
	Delay8 0x1
	WalkOnSpotNorth4 0x1
	Delay8 0x1
	WalkOnSpotSouth4 0x1
	Delay8 0x1
	WalkOnSpotEast8 0x1
	Delay8 0x1
	WalkEast8 0x5
	WalkOnSpotNorth8 0x1
End

Action 39:
	WalkWest8 0x5
	WalkNorth8 0x1
	WalkWest8 0x6
End

Action 40:
	Delay8 0x2
	WalkOnSpotWest8 0x1
End

Action 41:
	WalkNorth8 0x1
	WalkWest8 0x1
	WalkNorth8 0x3
	WalkOnSpotSouth8 0x1
End

Action 42:
	WalkWest4 0x2
	WalkNorth4 0x4
	Delay8 0x1
	WalkOnSpotSouth4 0x1
	Delay32 0x1
	EmoteExclamation 0x1
	WalkSouth4 0x5
	WalkEast4 0x1
End

Action 43:
	WalkWest4 0x1
	WalkNorth4 0x5
	WalkOnSpotSouth4 0x1
	Delay4 0x6
	WalkOnSpotNorth4 0x1
End

Action 44:
	WalkWest8 0x2
	WalkNorth8 0x4
	Delay8 0x1
End

Action 45:
	WalkWest8 0xB
End

Action 46:
	WalkWest4 0x1
	WalkNorth4 0x6
	WalkOnSpotSouth4 0x1
	Delay4 0x9
	WalkOnSpotNorth4 0x1
End

Action 47:
	WalkWest8 0x2
	WalkNorth8 0x5
	Delay8 0x1
End

