/*
 * DSPRE Script File
 * Rom ID: spawn - Copy
 * Game: HGSS
 * File: 0908
 * Generated: 2/25/2026 10:01:00 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 0
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 1
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 3:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 4:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 3
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 5:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 4
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 6:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 5
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 7:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 6
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 8:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 7
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 9:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 8
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 10:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Message 9
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 11:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Message 10
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 12:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	SetVar 0x8005 6
Jump Function#1

Script 13:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	SetVar 0x8005 5
Jump Function#2

//===== FUNCTIONS =====//
Function 1:
	Message 13
	OpenTouchScreen
	MultiTouchLocalText 21 11 0 1 0x800C
	CreateMultiTouchBox 15 255 0
	CreateMultiTouchBox 16 255 1
	CreateMultiTouchBox 17 255 2
	CloseMultiTouch
	SetVarFromVariable 0x8008 0x800C
	CompareVarValue 0x8008 0
	JumpIf EQUAL Function#3
	CompareVarValue 0x8008 1
	JumpIf EQUAL Function#4
Jump Function#5

Function 2:
	Message 11
	OpenTouchScreen
	MultiTouchLocalText 21 11 0 1 0x800C
	CreateMultiTouchBox 15 255 0
	CreateMultiTouchBox 16 255 1
	CreateMultiTouchBox 17 255 2
	CloseMultiTouch
	SetVarFromVariable 0x8008 0x800C
	CompareVarValue 0x8008 0
	JumpIf EQUAL Function#6
	CompareVarValue 0x8008 1
	JumpIf EQUAL Function#7
Jump Function#8

Function 3:
	CommonScript 2006
	SetVarFromVariable 0x800C 0x4000
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#9
	CloseMessage
	CMD_815 0
	CommonScript 2046
	ReleaseAll
End

Function 4:
	Message 14
Jump Function#1

Function 5:
	CloseTouchScreen
	CloseMessage
	ReleaseAll
End

Function 6:
	CommonScript 2006
	SetVarFromVariable 0x800C 0x4000
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#10
	CloseMessage
	CMD_815 0
	CommonScript 2046
	ReleaseAll
End

Function 7:
	Message 12
Jump Function#2

Function 8:
	CloseTouchScreen
	CloseMessage
	ReleaseAll
End

Function 9:
	CloseMessage
	ReleaseAll
End

Function 10:
	CloseMessage
	ReleaseAll
End

//===== ACTIONS =====//
