/*
 * DSPRE Script File
 * Rom ID: spawn - Copy
 * Game: HGSS
 * File: 0918
 * Generated: 2/25/2026 10:01:00 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckFlag 189
	JumpIf EQUAL Function#1
	Message 0
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#2
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#3
End

//===== FUNCTIONS =====//
Function 1:
	Message 5
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 2:
	SetVar 0x8004 446
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#4
	Message 1
	WaitButton
	CommonScript 2033
	SetFlag 189
	Message 3
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 3:
	Message 4
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 4:
	CommonScript 2009
	CloseMessage
	ReleaseAll
End

//===== ACTIONS =====//
