/*
 * DSPRE Script File
 * Rom ID: spawn - Copy
 * Game: HGSS
 * File: 0919
 * Generated: 2/25/2026 10:01:00 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Message 1
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 3:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 3
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 4:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 0
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#1
	CheckAlbumPhoto 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#2
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 1
	CloseMessage
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	GetPlayerDirection 0x800C
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#3
	Movement Player Action#1
	Movement Overworld.3 Action#2
Jump Function#4

Script 5:
	CheckFlag 393
	JumpIf LESS Function#5
	ClearFlag 393
End

Script 6:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckPokegearNumberRegistered 38 0x4001
	CompareVarValue 0x4001 1
	JumpIf EQUAL Function#6
	CompareVarValue 0x4004 1
	JumpIf GREATER/EQUAL Function#7
	Message 4
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#8
	CompareVarValue 0x800C 1
	JumpIf GREATER/EQUAL Function#9
End

Script 7:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 0
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== FUNCTIONS =====//
Function 1:
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 5
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 2:
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 3
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 3:
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#10
	Movement Player Action#3
Jump Function#4

Function 4:
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	CheckPokemonAlive 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#11
	Movement Following Action#4
	WaitMovement
	SetFlag 393
	FadeScreen 6 1 0 0
	WaitFadeScreen
	TakePhoto 25
	LockAll
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ClearFlag 393
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 5:
	GetDayOfWeek 0x4000
	CompareVarValue 0x4000 5
	JumpIf DIFFERENT Function#12
	SetFlag 638
Jump Function#13

Function 6:
	Message 9
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#14
	CheckAlbumPhoto 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#15
	Message 10
	CloseMessage
	SetFlag 393
	FadeScreen 6 1 0 0
	WaitFadeScreen
	TakePhoto 89
	FacePlayer
	LockAll
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ClearFlag 393
	Message 11
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 7:
	Message 8
Jump Function#16

Function 8:
	TextPlayerName 0
	Message 5
	PlaySound SEQ_ME_POKEGEAR_REGIST
	WaitSound
	RecordPokegearNumber 38
	Message 6
	WaitButton
	CloseMessage
	FadeScreen 6 1 0 0
	WaitFadeScreen
	SetFlag 715
	RemoveOW Overworld.4
	PlayFanfare SEQ_SE_DP_KAIDAN2
	WaitFanfare SEQ_SE_DP_KAIDAN2
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Function 9:
	SetVar 0x4004 1
	Message 7
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 10:
	Movement Player Action#5
	Movement Overworld.3 Action#2
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	CheckPokemonAlive 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#11
	Movement Following Action#4
	WaitMovement
	SetFlag 393
	FadeScreen 6 1 0 0
	WaitFadeScreen
	TakePhoto 25
	LockAll
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ClearFlag 393
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 11:
	SetFlag 393
	FadeScreen 6 1 0 0
	WaitFadeScreen
	TakePhoto 25
	LockAll
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ClearFlag 393
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 12:
	SetFlag 638
	CheckFlag 2404
	JumpIf LESS Function#17
	CheckPokegearNumberRegistered 38 0x4001
	CompareVarValue 0x4001 1
	JumpIf EQUAL Function#18
	GetHour 0x4000
	CompareVarValue 0x4000 13
	JumpIf DIFFERENT Function#19
	ClearFlag 715
Jump Function#20

Function 13:
	CheckFlag 2404
	JumpIf LESS Function#17
	CheckPokegearNumberRegistered 38 0x4001
	CompareVarValue 0x4001 1
	JumpIf EQUAL Function#18
	GetHour 0x4000
	CompareVarValue 0x4000 13
	JumpIf DIFFERENT Function#19
	ClearFlag 715
Jump Function#20

Function 14:
	Message 12
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 15:
	Message 13
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 16:
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#8
	CompareVarValue 0x800C 1
	JumpIf GREATER/EQUAL Function#9
End

Function 17:
	SetFlag 715
End

Function 18:
	CheckPokeGearRematch 38 0x4001
	CompareVarValue 0x4001 0
	JumpIf DIFFERENT Function#17
	GetHour 0x4000
	CompareVarValue 0x4000 12
	JumpIf DIFFERENT Function#21
	ClearFlag 715
Jump Function#22

Function 19:
Jump Function#17

Function 20:
End

Function 21:
	SetFlag 715
End

Function 22:
End

//===== ACTIONS =====//
Action 1:
	WalkEast8 0x1
	WalkNorth8 0x2
	WalkWest8 0x1
	WalkNorth8 0x3
	WalkOnSpotSouth8 0x1
End

Action 2:
	Delay8 0x1
	WalkOnSpotNorth8 0x1
End

Action 3:
	WalkNorth8 0x3
	WalkOnSpotSouth8 0x1
End

Action 4:
	WalkEast8 0x1
	WalkNorth8 0x1
	FaceSouth 0x1
End

Action 5:
	WalkNorth8 0x1
	WalkWest8 0x1
	WalkNorth8 0x3
	WalkOnSpotSouth8 0x1
End

