/*
 * DSPRE Script File
 * Rom ID: spawn - Copy
 * Game: HGSS
 * File: 0926
 * Generated: 2/25/2026 10:01:00 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckFlag 264
	JumpIf EQUAL Function#1
	CompareVarValue 0x4002 1
	JumpIf GREATER/EQUAL Function#2
	GetPlayerDirection 0x4001
	CompareVarValue 0x4001 1
	JumpIf EQUAL Function#3
	CheckBadge 3 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#4
	CheckVersion 0x800C
	CompareVarValue 0x800C 7
	JumpIf DIFFERENT Function#5
	Message 0
Jump Function#6

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckFlag 264
	JumpIf EQUAL Function#7
	CheckFlag 259
	JumpIf EQUAL Function#8
	CheckVersion 0x800C
	CompareVarValue 0x800C 7
	JumpIf DIFFERENT Function#9
	Message 6
Jump Function#10

Script 3:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 10
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 4:
	CheckFlag 264
	JumpIf EQUAL Function#11
End

//===== FUNCTIONS =====//
Function 1:
	Message 5
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 2:
	Message 4
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 3:
	Movement Overworld.0 Action#1
	WaitMovement
	SetVar 0x4002 1
	ReleaseAll
End

Function 4:
	CheckVersion 0x800C
	CompareVarValue 0x800C 7
	JumpIf DIFFERENT Function#12
	Message 2
Jump Function#13

Function 5:
	Message 1
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 6:
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 7:
	Message 9
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 8:
	Message 8
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 9:
	Message 7
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 10:
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 11:
	SetOWPosition Overworld.0 16 0 8 Left
End

Function 12:
	Message 3
	CloseMessage
	Movement Overworld.0 Action#2
	WaitMovement
	SetVar 0x4002 1
	ReleaseAll
End

Function 13:
	CloseMessage
	Movement Overworld.0 Action#2
	WaitMovement
	SetVar 0x4002 1
	ReleaseAll
End

//===== ACTIONS =====//
Action 1:
	WalkSouth8 0x1
	WalkEast8 0x1
	FaceWest 0x1
End

Action 2:
	WalkNorth8 0x1
	WalkEast8 0x1
	FaceWest 0x1
End

