/*
 * DSPRE Script File
 * Rom ID: spawn - Copy
 * Game: HGSS
 * File: 0930
 * Generated: 2/25/2026 10:01:00 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CompareVarValue 0x4077 5
	JumpIf EQUAL Function#1
	CheckFlag 355
	JumpIf EQUAL Function#2
	Message 0
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#3
	CompareMoney 0x800C 200
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#4
	SetVar 0x8004 504
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#5
	CommonScript 2033
	TakeMoney 200
	Message 5
	WaitButton
	SetFlag 355
Jump Function#6

Script 2:
	MecScript
	LockAll
	Movement Overworld.0 Action#1
	WaitMovement
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 56
	GetPlayerPosition 0x4000 0x4001
	CompareVarValue 0x4001 176
	JumpIf DIFFERENT Function#7
	Movement Overworld.0 Action#2
	Movement Player Action#3
Jump Function#8

Script 3:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckFlag 201
	JumpIf EQUAL Function#9
	Message 14
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 4:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 16
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 5:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 13
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 6:
	SetVar 0x4077 2
	SetFlag 197
	SetFlag 2459
	CompareVarValue 0x40F8 0
	JumpIf DIFFERENT Function#10
	SetVar 0x40F8 2
	SetVar 0x8004 1
	SetVar 0x8005 2
	SetVar 0x8006 2
	CommonScript 2039
	SetVar 0x4134 5
End

Script 7:
	SetIconBoard 17 0 19 0x800C
	ShowBoard 3
	WaitBoard
	CloseBoard 0x800C
	CommonScript 2000
End

Script 8:
	SetTextBoard 2 0
	ShowBoard 3
	WaitBoard
	BoardMessage 18 0x800C
	CommonScript 2000
End

Script 9:
	SetTextBoard 2 0
	ShowBoard 3
	WaitBoard
	BoardMessage 19 0x800C
	CommonScript 2000
End

//===== FUNCTIONS =====//
Function 1:
	CheckFlag 355
	JumpIf EQUAL Function#11
	Message 3
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#12
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#3
	Message 4
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 2:
	Message 1
	WaitButton
Jump Function#6

Function 3:
	Message 9
	WaitButton
Jump Function#6

Function 4:
	Message 7
	WaitButton
Jump Function#6

Function 5:
	CommonScript 2009
Jump Function#6

Function 6:
	CloseMessage
	ReleaseAll
End

Function 7:
	Movement Overworld.0 Action#4
	Movement Player Action#5
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	CheckFlag 355
	JumpIf EQUAL Function#13
	Message 0
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#14
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#15
	CompareMoney 0x800C 300
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#16
	SetVar 0x8004 504
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#5
	CommonScript 2033
	TakeMoney 300
	Message 6
	CloseMessage
	SetFlag 355
	GetPlayerPosition 0x4000 0x4001
	CompareVarValue 0x4001 176
	JumpIf DIFFERENT Function#17
	Movement Overworld.0 Action#6
Jump Function#18

Function 8:
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	CheckFlag 355
	JumpIf EQUAL Function#13
	Message 0
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#14
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#15
	CompareMoney 0x800C 300
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#16
	SetVar 0x8004 504
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#5
	CommonScript 2033
	TakeMoney 300
	Message 6
	CloseMessage
	SetFlag 355
	GetPlayerPosition 0x4000 0x4001
	CompareVarValue 0x4001 176
	JumpIf DIFFERENT Function#17
	Movement Overworld.0 Action#6
Jump Function#18

Function 9:
	Message 15
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 10:
	SetVar 0x8004 1
	SetVar 0x8005 2
	SetVar 0x8006 2
	CommonScript 2039
	SetVar 0x4134 5
End

Function 11:
	Message 4
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 12:
	CompareMoney 0x800C 200
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#4
	SetVar 0x8004 504
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#5
	CommonScript 2033
	TakeMoney 200
	Message 5
	WaitButton
	SetFlag 355
Jump Function#6

Function 13:
	Message 2
	CloseMessage
Jump Function#19

Function 14:
	CompareMoney 0x800C 300
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#16
	SetVar 0x8004 504
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#5
	CommonScript 2033
	TakeMoney 300
	Message 6
	CloseMessage
	SetFlag 355
	GetPlayerPosition 0x4000 0x4001
	CompareVarValue 0x4001 176
	JumpIf DIFFERENT Function#17
	Movement Overworld.0 Action#6
Jump Function#18

Function 15:
	Message 10
	CloseMessage
Jump Function#19

Function 16:
	Message 8
	CloseMessage
Jump Function#19

Function 17:
	Movement Overworld.0 Action#7
	WaitMovement
	ReleaseAll
End

Function 18:
	WaitMovement
	ReleaseAll
End

Function 19:
	GetPlayerPosition 0x4000 0x4001
	CompareVarValue 0x4001 176
	JumpIf DIFFERENT Function#17
	Movement Overworld.0 Action#6
Jump Function#18

//===== ACTIONS =====//
Action 1:
	FaceSouth 0x1
	EmoteExclamation 0x1
End

Action 2:
	WalkEast4 0x1
	WalkSouth4 0x1
	WalkWest4 0x1
End

Action 3:
	Delay4 0x2
	WalkWest4 0x1
	FaceEast 0x1
End

Action 4:
	WalkEast4 0x1
	WalkSouth4 0x2
	WalkWest4 0x1
End

Action 5:
	Delay4 0x3
	WalkWest4 0x1
	FaceEast 0x1
End

Action 6:
	WalkNorth8 0x1
	FaceSouth 0x1
End

Action 7:
	WalkNorth8 0x2
	FaceSouth 0x1
End

