/*
 * DSPRE Script File
 * Rom ID: spawn - Copy
 * Game: HGSS
 * File: 0943
 * Generated: 2/25/2026 10:01:00 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckFlag 234
	JumpIf EQUAL Function#1
	CheckFlag 209
	JumpIf EQUAL Function#2
	Message 3
	CloseMessage
	TrainerBattle TRAINER_CLAIR_035 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#3
	SetTrainerFlag TRAINER_PAULO_110
	SetTrainerFlag TRAINER_CODY_112
	SetTrainerFlag TRAINER_MIKE_111
	SetTrainerFlag TRAINER_FRAN_119
	SetTrainerFlag TRAINER_LOLA_117
	AddTrainerScore 22
	SetFlag 209
	SetFlag 514
	ClearFlag 515
	Message 4
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 2:
	BlackthornGymInit
	SetVar 0x4120 0
	CheckPokeGearRematch 27 0x4001
	CompareVarValue 0x4001 0
	JumpIf DIFFERENT Function#4
	CompareVarValue 0x40FC 2
	JumpIf GREATER/EQUAL Function#5
End

Script 3:
	MecScript
	LockAll
	PlayFanfare SEQ_SE_DP_GYURU
	Movement Player Action#1
	WaitMovement
	FadeScreen 6 1 0 0
	WaitFadeScreen
	Warp 141 0 8 83 Up
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Script 4:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckFlag 209
	JumpIf EQUAL Function#6
	Message 0
	SendBackFollowingPoke
	SetFollowingPokeStatus 1
	NoBallResetFollowingPoke
	SetOWMovement Following Move.56
	SetVar 0x4120 1
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 5:
	MecScript
	LockAll
	CheckFlag 312
	JumpIf EQUAL Function#7
	GetPlayerPosition 0x4000 0x4001
	CompareVarValue 0x4000 12
	JumpIf DIFFERENT Function#8
	Movement Overworld.6 Action#2
	Movement Player Action#3
Jump Function#9

Script 6:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckBadge 7 0x800C
	TextPlayerName 0
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#10
	Message 10
Jump Function#11

//===== FUNCTIONS =====//
Function 1:
	CheckFlag 218
	JumpIf EQUAL Function#12
	Message 6
	SetVar 0x8004 386
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#13
	CommonScript 2033
	SetFlag 218
	Message 7
	Message 9
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 2:
	Message 5
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 3:
	LostBattle
	ReleaseAll
End

Function 4:
	SetFlag 751
End

Function 5:
	CheckPokegearNumberRegistered 27 0x4001
	CompareVarValue 0x4001 1
	JumpIf EQUAL Function#14
	GetHour 0x4000
	CompareVarValue 0x4000 6
	JumpIf DIFFERENT Function#15
	SetFlag 751
Jump Function#16

Function 6:
	Message 1
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 7:
	SendBackFollowingPoke
	SetFollowingPokeStatus 1
	NoBallResetFollowingPoke
	SetOWMovement Following Move.56
	SetVar 0x4120 1
	SetVar 0x4120 1
	ReleaseAll
End

Function 8:
	CompareVarValue 0x4000 13
	JumpIf DIFFERENT Function#17
	Movement Overworld.6 Action#4
	Movement Player Action#5
Jump Function#9

Function 9:
	WaitMovement
	Message 2
	CloseMessage
	SetFlag 312
	CompareVarValue 0x4000 12
	JumpIf DIFFERENT Function#18
	Movement Overworld.6 Action#6
Jump Function#19

Function 10:
	Message 11
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 11:
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 12:
	Message 9
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 13:
	Message 8
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 14:
	GetHour 0x4000
	CompareVarValue 0x4000 16
	JumpIf DIFFERENT Function#20
	SetFlag 751
Jump Function#21

Function 15:
	CompareVarValue 0x4000 7
	JumpIf DIFFERENT Function#22
	SetFlag 751
Jump Function#16

Function 16:
End

Function 17:
	Movement Overworld.6 Action#7
	Movement Player Action#8
	WaitMovement
	Message 2
	CloseMessage
	SetFlag 312
	CompareVarValue 0x4000 12
	JumpIf DIFFERENT Function#18
	Movement Overworld.6 Action#6
Jump Function#19

Function 18:
	CompareVarValue 0x4000 13
	JumpIf DIFFERENT Function#23
	Movement Overworld.6 Action#9
Jump Function#19

Function 19:
	WaitMovement
	SendBackFollowingPoke
	SetFollowingPokeStatus 1
	NoBallResetFollowingPoke
	SetOWMovement Following Move.56
	SetVar 0x4120 1
	SetVar 0x4120 1
	ReleaseAll
End

Function 20:
	CompareVarValue 0x4000 17
	JumpIf DIFFERENT Function#24
	SetFlag 751
Jump Function#21

Function 21:
End

Function 22:
	CompareVarValue 0x4000 8
	JumpIf DIFFERENT Function#25
	SetFlag 751
Jump Function#16

Function 23:
	Movement Overworld.6 Action#10
	WaitMovement
	SendBackFollowingPoke
	SetFollowingPokeStatus 1
	NoBallResetFollowingPoke
	SetOWMovement Following Move.56
	SetVar 0x4120 1
	SetVar 0x4120 1
	ReleaseAll
End

Function 24:
	CompareVarValue 0x4000 18
	JumpIf DIFFERENT Function#26
	SetFlag 751
Jump Function#21

Function 25:
	CompareVarValue 0x4000 9
	JumpIf DIFFERENT Function#27
	SetFlag 751
Jump Function#16

Function 26:
	ClearFlag 751
End

Function 27:
	ClearFlag 751
End

//===== ACTIONS =====//
Action 1:
	FaceSouth 0x2
	FaceWest 0x2
	FaceNorth 0x2
	FaceEast 0x2
	FaceSouth 0x2
	FaceWest 0x2
	FaceNorth 0x2
	FaceEast 0x2
	FaceSouth 0x2
	FaceWest 0x2
	FaceNorth 0x2
	FaceEast 0x2
	FaceSouth 0x2
	FaceWest 0x2
	FaceNorth 0x2
	FaceEast 0x1
	SetInvisible 0x0
End

Action 2:
	FaceWest 0x1
	EmoteExclamation 0x1
	WalkWest8 0x2
End

Action 3:
	Delay8 0x5
	FaceEast 0x1
End

Action 4:
	FaceWest 0x1
	EmoteExclamation 0x1
	WalkWest8 0x1
End

Action 5:
	Delay8 0x4
	FaceEast 0x1
End

Action 6:
	WalkEast8 0x2
	FaceSouth 0x1
End

Action 7:
	FaceWest 0x1
	EmoteExclamation 0x1
End

Action 8:
	Delay8 0x2
	FaceEast 0x1
End

Action 9:
	WalkEast8 0x1
	FaceSouth 0x1
End

Action 10:
	FaceSouth 0x1
End

