/*
 * DSPRE Script File
 * Rom ID: spawn - Copy
 * Game: HGSS
 * File: 0963
 * Generated: 2/25/2026 10:01:00 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	CheckFlag 251
	JumpIf EQUAL Function#1
	CheckFlag 2404
	JumpIf EQUAL Function#2
	GetPlayerDirection 0x4000
	CompareVarValue 0x4000 3
	JumpIf DIFFERENT Function#3
	Movement Overworld.0 Action#1
Jump Function#4

Script 2:
	CompareVarValue 0x40E5 1
	JumpIf GREATER/EQUAL Function#5
	CheckFlag 2404
	JumpIf EQUAL Function#6
End

Script 3:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckFlag 2404
	JumpIf EQUAL Function#7
	Message 3
Jump Function#8

//===== FUNCTIONS =====//
Function 1:
	Message 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 2:
	Message 1
	CloseMessage
	ReleaseAll
	SetFlag 251
End

Function 3:
	CompareVarValue 0x4000 2
	JumpIf DIFFERENT Function#9
	Movement Overworld.0 Action#2
Jump Function#4

Function 4:
	WaitMovement
	Message 0
	CloseMessage
	Movement Overworld.0 Action#3
	WaitMovement
	ReleaseAll
End

Function 5:
	SetVar 0x40E5 2
End

Function 6:
	SetOWPosition Overworld.0 3 0 3 Up
End

Function 7:
	Message 4
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 8:
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 9:
	Movement Overworld.0 Action#4
	WaitMovement
	Message 0
	CloseMessage
	Movement Overworld.0 Action#3
	WaitMovement
	ReleaseAll
End

//===== ACTIONS =====//
Action 1:
	WalkOnSpotWest8 0x1
End

Action 2:
	WalkOnSpotEast8 0x1
End

Action 3:
	WalkOnSpotNorth8 0x1
End

Action 4:
	WalkOnSpotSouth8 0x1
End

