/*
 * DSPRE Script File
 * Rom ID: spawn - Copy
 * Game: HGSS
 * File: 0968
 * Generated: 2/25/2026 10:01:00 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 0
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 2:
	MecScript
	LockAll
	Message 9
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#1
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#2
End

Script 3:
	MecScript
	LockAll
	CMD_151
	Message 12
	CMD_257 94
	CloseMessage
	CMD_587
	ExitBattleRoom
	ReleaseAll
End

//===== FUNCTIONS =====//
Function 1:
	CMD_151
	Message 12
	CMD_257 94
	CloseMessage
	CMD_587
	ExitBattleRoom
	ReleaseAll
End

Function 2:
	CloseMessage
	ReleaseAll
End

//===== ACTIONS =====//
